from soulstruct.emevd.shared.tests import *
from soulstruct.enums.darksouls3 import *
import soulstruct.game_types as gt


# Boolean constants.
HOST = ...
CLIENT = ...
IN_OWN_WORLD = ...

def ActionButtonInRegion(action_button_id: int, region: gt.RegionInt): ...
def IsAttackedWithDamageType(attacked_entity: gt.CharacterInt, attacking_character: gt.CharacterInt,
                             damage_type: DamageType): ...
def CharacterDrawGroupActive(character: gt.CharacterInt): ...
def CharacterDrawGroupInactive(character: gt.CharacterInt): ...
