PROJECT_VERSION = """<version>4</version>
<eventgroup_nextid>0</eventgroup_nextid>
<soundbank_nextid>0</soundbank_nextid>
<sounddef_nextid>0</sounddef_nextid>
<build_project>1</build_project>
<build_headerfile>0</build_headerfile>
<build_banklists>0</build_banklists>
<build_programmerreport>0</build_programmerreport>
<build_applytemplate>0</build_applytemplate>"""
PROJECT_LANGUAGE = """<currentlanguage>default</currentlanguage>
<primarylanguage>default</primarylanguage>
<language>default</language>
<templatefilename></templatefilename>
<templatefileopen>1</templatefileopen>"""
EVENT_CAR = """<car_rpm>0</car_rpm>
<car_rpmsmooth>0.075</car_rpmsmooth>
<car_loadsmooth>0.05</car_loadsmooth>
<car_loadscale>6</car_loadscale>
<car_dialog>0</car_dialog>"""
EVENT_TEMPLATE = """<TEMPLATE_PROP_LAYERS>1</TEMPLATE_PROP_LAYERS>
<TEMPLATE_PROP_KEEP_EFFECTS_PARAMS>1</TEMPLATE_PROP_KEEP_EFFECTS_PARAMS>
<TEMPLATE_PROP_VOLUME>0</TEMPLATE_PROP_VOLUME>
<TEMPLATE_PROP_PITCH>1</TEMPLATE_PROP_PITCH>
<TEMPLATE_PROP_PITCH_RANDOMIZATION>1</TEMPLATE_PROP_PITCH_RANDOMIZATION>
<TEMPLATE_PROP_VOLUME_RANDOMIZATION>1</TEMPLATE_PROP_VOLUME_RANDOMIZATION>
<TEMPLATE_PROP_PRIORITY>1</TEMPLATE_PROP_PRIORITY>
<TEMPLATE_PROP_MAX_PLAYBACKS>1</TEMPLATE_PROP_MAX_PLAYBACKS>
<TEMPLATE_PROP_MAX_PLAYBACKS_BEHAVIOR>1</TEMPLATE_PROP_MAX_PLAYBACKS_BEHAVIOR>
<TEMPLATE_PROP_STEAL_PRIORITY>1</TEMPLATE_PROP_STEAL_PRIORITY>
<TEMPLATE_PROP_MODE>1</TEMPLATE_PROP_MODE>
<TEMPLATE_PROP_IGNORE_GEOMETRY>1</TEMPLATE_PROP_IGNORE_GEOMETRY>
<TEMPLATE_PROP_X_3D_ROLLOFF>1</TEMPLATE_PROP_X_3D_ROLLOFF>
<TEMPLATE_PROP_X_3D_MIN_DISTANCE>1</TEMPLATE_PROP_X_3D_MIN_DISTANCE>
<TEMPLATE_PROP_X_3D_MAX_DISTANCE>1</TEMPLATE_PROP_X_3D_MAX_DISTANCE>
<TEMPLATE_PROP_X_3D_POSITION>1</TEMPLATE_PROP_X_3D_POSITION>
<TEMPLATE_PROP_X_3D_POSITION_RANDOMIZATION>1</TEMPLATE_PROP_X_3D_POSITION_RANDOMIZATION>
<TEMPLATE_PROP_X_3D_CONE_INSIDE_ANGLE>1</TEMPLATE_PROP_X_3D_CONE_INSIDE_ANGLE>
<TEMPLATE_PROP_X_3D_CONE_OUTSIDE_ANGLE>1</TEMPLATE_PROP_X_3D_CONE_OUTSIDE_ANGLE>
<TEMPLATE_PROP_X_3D_CONE_OUTSIDE_VOLUME>1</TEMPLATE_PROP_X_3D_CONE_OUTSIDE_VOLUME>
<TEMPLATE_PROP_X_3D_DOPPLER_FACTOR>1</TEMPLATE_PROP_X_3D_DOPPLER_FACTOR>
<TEMPLATE_PROP_REVERB_WET_LEVEL>1</TEMPLATE_PROP_REVERB_WET_LEVEL>
<TEMPLATE_PROP_REVERB_DRY_LEVEL>1</TEMPLATE_PROP_REVERB_DRY_LEVEL>
<TEMPLATE_PROP_X_3D_SPEAKER_SPREAD>1</TEMPLATE_PROP_X_3D_SPEAKER_SPREAD>
<TEMPLATE_PROP_X_3D_PAN_LEVEL>1</TEMPLATE_PROP_X_3D_PAN_LEVEL>
<TEMPLATE_PROP_X_2D_SPEAKER_L>1</TEMPLATE_PROP_X_2D_SPEAKER_L>
<TEMPLATE_PROP_X_2D_SPEAKER_C>1</TEMPLATE_PROP_X_2D_SPEAKER_C>
<TEMPLATE_PROP_X_2D_SPEAKER_R>1</TEMPLATE_PROP_X_2D_SPEAKER_R>
<TEMPLATE_PROP_X_2D_SPEAKER_LS>1</TEMPLATE_PROP_X_2D_SPEAKER_LS>
<TEMPLATE_PROP_X_2D_SPEAKER_RS>1</TEMPLATE_PROP_X_2D_SPEAKER_RS>
<TEMPLATE_PROP_X_2D_SPEAKER_LR>1</TEMPLATE_PROP_X_2D_SPEAKER_LR>
<TEMPLATE_PROP_X_2D_SPEAKER_RR>1</TEMPLATE_PROP_X_2D_SPEAKER_RR>
<TEMPLATE_PROP_X_SPEAKER_LFE>1</TEMPLATE_PROP_X_SPEAKER_LFE>
<TEMPLATE_PROP_ONESHOT>1</TEMPLATE_PROP_ONESHOT>
<TEMPLATE_PROP_FADEIN_TIME>1</TEMPLATE_PROP_FADEIN_TIME>
<TEMPLATE_PROP_FADEOUT_TIME>1</TEMPLATE_PROP_FADEOUT_TIME>
<TEMPLATE_PROP_NOTES>1</TEMPLATE_PROP_NOTES>
<TEMPLATE_PROP_USER_PROPERTIES>1</TEMPLATE_PROP_USER_PROPERTIES>"""
LAYER_ENABLES = """<_PC_enable>1</_PC_enable>
<_XBOX_enable>1</_XBOX_enable>
<_XBOX360_enable>1</_XBOX360_enable>
<_GC_enable>1</_GC_enable>
<_PS2_enable>1</_PS2_enable>
<_PSP_enable>1</_PSP_enable>
<_PS3_enable>1</_PS3_enable>
<_WII_enable>1</_WII_enable>"""
DEFAULT_SOUNDBANK_PROPS = """<default_soundbank_props>
<name>default_soundbank_props</name>
<guid>{c90be848-b597-46c5-9a24-883b64d25d46}</guid>
<load_into_rsx>0</load_into_rsx>
<disable_seeking>0</disable_seeking>
<enable_syncpoints>1</enable_syncpoints>
<hasbuiltwithsyncpoints>0</hasbuiltwithsyncpoints>
<_PC_banktype>DecompressedSample</_PC_banktype>
<_XBOX_banktype>DecompressedSample</_XBOX_banktype>
<_XBOX360_banktype>DecompressedSample</_XBOX360_banktype>
<_GC_banktype>DecompressedSample</_GC_banktype>
<_PS2_banktype>DecompressedSample</_PS2_banktype>
<_PSP_banktype>DecompressedSample</_PSP_banktype>
<_PS3_banktype>DecompressedSample</_PS3_banktype>
<_WII_banktype>DecompressedSample</_WII_banktype>
<notes></notes>
<rebuild>0</rebuild>
<_PC_format>PCM</_PC_format>
<_PC_quality>50</_PC_quality>
<_PC_optimisesamplerate>0</_PC_optimisesamplerate>
<_PC_forcesoftware>1</_PC_forcesoftware>
<_PC_maxstreams>10</_PC_maxstreams>
<_XBOX_format>PCM</_XBOX_format>
<_XBOX_quality>50</_XBOX_quality>
<_XBOX_optimisesamplerate>0</_XBOX_optimisesamplerate>
<_XBOX_forcesoftware>0</_XBOX_forcesoftware>
<_XBOX_maxstreams>10</_XBOX_maxstreams>
<_XBOX360_format>PCM</_XBOX360_format>
<_XBOX360_quality>50</_XBOX360_quality>
<_XBOX360_optimisesamplerate>0</_XBOX360_optimisesamplerate>
<_XBOX360_forcesoftware>1</_XBOX360_forcesoftware>
<_XBOX360_maxstreams>10</_XBOX360_maxstreams>
<_GC_format>PCM</_GC_format>
<_GC_quality>50</_GC_quality>
<_GC_optimisesamplerate>0</_GC_optimisesamplerate>
<_GC_forcesoftware>0</_GC_forcesoftware>
<_GC_maxstreams>10</_GC_maxstreams>
<_PS2_format>PCM</_PS2_format>
<_PS2_quality>50</_PS2_quality>
<_PS2_optimisesamplerate>0</_PS2_optimisesamplerate>
<_PS2_forcesoftware>0</_PS2_forcesoftware>
<_PS2_maxstreams>10</_PS2_maxstreams>
<_PSP_format>PCM</_PSP_format>
<_PSP_quality>50</_PSP_quality>
<_PSP_optimisesamplerate>0</_PSP_optimisesamplerate>
<_PSP_forcesoftware>0</_PSP_forcesoftware>
<_PSP_maxstreams>10</_PSP_maxstreams>
<_PS3_format>PCM</_PS3_format>
<_PS3_quality>50</_PS3_quality>
<_PS3_optimisesamplerate>0</_PS3_optimisesamplerate>
<_PS3_forcesoftware>1</_PS3_forcesoftware>
<_PS3_maxstreams>10</_PS3_maxstreams>
<_WII_format>PCM</_WII_format>
<_WII_quality>50</_WII_quality>
<_WII_optimisesamplerate>0</_WII_optimisesamplerate>
<_WII_forcesoftware>0</_WII_forcesoftware>
<_WII_maxstreams>10</_WII_maxstreams>
</default_soundbank_props>"""
WAVEBANK_HEADER_OPTIONS = """<load_into_rsx>0</load_into_rsx>
<disable_seeking>0</disable_seeking>
<enable_syncpoints>1</enable_syncpoints>
<hasbuiltwithsyncpoints>0</hasbuiltwithsyncpoints>"""
WAVEBANK_UNUSED_BANKTYPE = """<_XBOX_banktype>DecompressedSample</_XBOX_banktype>
<_XBOX360_banktype>DecompressedSample</_XBOX360_banktype>
<_GC_banktype>DecompressedSample</_GC_banktype>
<_PS2_banktype>DecompressedSample</_PS2_banktype>
<_PSP_banktype>DecompressedSample</_PSP_banktype>
<_PS3_banktype>DecompressedSample</_PS3_banktype>
<_WII_banktype>DecompressedSample</_WII_banktype>
<notes></notes>
<rebuild>1</rebuild>"""
WAVEBANK_UNUSED_QUALITY = """<_XBOX_format>PCM</_XBOX_format>
<_XBOX_quality>50</_XBOX_quality>
<_XBOX_optimisesamplerate>0</_XBOX_optimisesamplerate>
<_XBOX_forcesoftware>0</_XBOX_forcesoftware>
<_XBOX_maxstreams>10</_XBOX_maxstreams>
<_XBOX360_format>PCM</_XBOX360_format>
<_XBOX360_quality>50</_XBOX360_quality>
<_XBOX360_optimisesamplerate>0</_XBOX360_optimisesamplerate>
<_XBOX360_forcesoftware>1</_XBOX360_forcesoftware>
<_XBOX360_maxstreams>10</_XBOX360_maxstreams>
<_GC_format>PCM</_GC_format>
<_GC_quality>50</_GC_quality>
<_GC_optimisesamplerate>0</_GC_optimisesamplerate>
<_GC_forcesoftware>0</_GC_forcesoftware>
<_GC_maxstreams>10</_GC_maxstreams>
<_PS2_format>PCM</_PS2_format>
<_PS2_quality>50</_PS2_quality>
<_PS2_optimisesamplerate>0</_PS2_optimisesamplerate>
<_PS2_forcesoftware>0</_PS2_forcesoftware>
<_PS2_maxstreams>10</_PS2_maxstreams>
<_PSP_format>PCM</_PSP_format>
<_PSP_quality>50</_PSP_quality>
<_PSP_optimisesamplerate>0</_PSP_optimisesamplerate>
<_PSP_forcesoftware>0</_PSP_forcesoftware>
<_PSP_maxstreams>10</_PSP_maxstreams>
<_PS3_format>PCM</_PS3_format>
<_PS3_quality>50</_PS3_quality>
<_PS3_optimisesamplerate>0</_PS3_optimisesamplerate>
<_PS3_forcesoftware>1</_PS3_forcesoftware>
<_PS3_maxstreams>10</_PS3_maxstreams>
<_WII_format>PCM</_WII_format>
<_WII_quality>50</_WII_quality>
<_WII_optimisesamplerate>0</_WII_optimisesamplerate>
<_WII_forcesoftware>0</_WII_forcesoftware>
<_WII_maxstreams>10</_WII_maxstreams>"""

PROJECT_FOOTER = """<notes></notes>
<currentplatform>PC</currentplatform>
<_PC_encryptionkey></_PC_encryptionkey>
<_PC_builddirectory></_PC_builddirectory>
<_PC_audiosourcedirectory></_PC_audiosourcedirectory>
<_PC_prebuildcommands></_PC_prebuildcommands>
<_PC_postbuildcommands></_PC_postbuildcommands>
<_PC_buildinteractivemusic>Yes</_PC_buildinteractivemusic>
<_XBOX_encryptionkey></_XBOX_encryptionkey>
<_XBOX_builddirectory></_XBOX_builddirectory>
<_XBOX_audiosourcedirectory></_XBOX_audiosourcedirectory>
<_XBOX_prebuildcommands></_XBOX_prebuildcommands>
<_XBOX_postbuildcommands></_XBOX_postbuildcommands>
<_XBOX_buildinteractivemusic>Yes</_XBOX_buildinteractivemusic>
<_XBOX360_encryptionkey></_XBOX360_encryptionkey>
<_XBOX360_builddirectory></_XBOX360_builddirectory>
<_XBOX360_audiosourcedirectory></_XBOX360_audiosourcedirectory>
<_XBOX360_prebuildcommands></_XBOX360_prebuildcommands>
<_XBOX360_postbuildcommands></_XBOX360_postbuildcommands>
<_XBOX360_buildinteractivemusic>Yes</_XBOX360_buildinteractivemusic>
<_GC_encryptionkey></_GC_encryptionkey>
<_GC_builddirectory></_GC_builddirectory>
<_GC_audiosourcedirectory></_GC_audiosourcedirectory>
<_GC_prebuildcommands></_GC_prebuildcommands>
<_GC_postbuildcommands></_GC_postbuildcommands>
<_GC_buildinteractivemusic>Yes</_GC_buildinteractivemusic>
<_PS2_encryptionkey></_PS2_encryptionkey>
<_PS2_builddirectory></_PS2_builddirectory>
<_PS2_audiosourcedirectory></_PS2_audiosourcedirectory>
<_PS2_prebuildcommands></_PS2_prebuildcommands>
<_PS2_postbuildcommands></_PS2_postbuildcommands>
<_PS2_buildinteractivemusic>Yes</_PS2_buildinteractivemusic>
<_PSP_encryptionkey></_PSP_encryptionkey>
<_PSP_builddirectory></_PSP_builddirectory>
<_PSP_audiosourcedirectory></_PSP_audiosourcedirectory>
<_PSP_prebuildcommands></_PSP_prebuildcommands>
<_PSP_postbuildcommands></_PSP_postbuildcommands>
<_PSP_buildinteractivemusic>Yes</_PSP_buildinteractivemusic>
<_PS3_encryptionkey></_PS3_encryptionkey>
<_PS3_builddirectory></_PS3_builddirectory>
<_PS3_audiosourcedirectory></_PS3_audiosourcedirectory>
<_PS3_prebuildcommands></_PS3_prebuildcommands>
<_PS3_postbuildcommands></_PS3_postbuildcommands>
<_PS3_buildinteractivemusic>Yes</_PS3_buildinteractivemusic>
<_WII_encryptionkey></_WII_encryptionkey>
<_WII_builddirectory></_WII_builddirectory>
<_WII_audiosourcedirectory></_WII_audiosourcedirectory>
<_WII_prebuildcommands></_WII_prebuildcommands>
<_WII_postbuildcommands></_WII_postbuildcommands>
<_WII_buildinteractivemusic>Yes</_WII_buildinteractivemusic>
<presavecommands></presavecommands>
<postsavecommands></postsavecommands>
<neweventusetemplate>0</neweventusetemplate>
<neweventlasttemplatename></neweventlasttemplatename>

<Composition>
    <AuditionConsoleControlRepository>
        <AuditionConsoleControl Type="Utility" Xpos="18" Ypos="18">
            <SimpleRack>
                <ControlName>Reset</ControlName>
                <ControlRange>0, 1</ControlRange>
                <ControlWidget>
                    <ResetControl/>
                </ControlWidget>
                <ControlMapping Type="3" ID="0"/>
            </SimpleRack>
        </AuditionConsoleControl>
    </AuditionConsoleControlRepository>
    <CompositionUI>
        <SceneEditor>
            <SceneEditorItemRepository/>
        </SceneEditor>
        <ThemeEditor>
            <ThemeEditorItemRepository/>
        </ThemeEditor>
    </CompositionUI>
    <CueFactory>
        <UID>2</UID>
    </CueFactory>
    <CueRepository/>
    <ExtLinkFactory>
        <UID>1</UID>
    </ExtLinkFactory>
    <ExtLinkRepository/>
    <ExtSegmentFactory>
        <UID>1</UID>
    </ExtSegmentFactory>
    <MusicSettings>
        <BaseVolume>1</BaseVolume>
        <BaseReverbLevel>1</BaseReverbLevel>
    </MusicSettings>
    <ParameterFactory>
        <UID>1</UID>
    </ParameterFactory>
    <ParameterRepository/>
    <SceneRepository>
        <Scene ID="1">
            <CueSheet></CueSheet>
        </Scene>
    </SceneRepository>
    <SegmentRepository/>
    <SharedFile/>
    <ThemeFactory>
        <UID>1</UID>
    </ThemeFactory>
    <ThemeRepository/>
    <TimelineFactory>
        <UID>1</UID>
    </TimelineFactory>
    <TimelineRepository/>
</Composition>"""
