
GAME_PARAM_INFO = {

    # Structure is:
    # { ParamTableName: ( ParamTableAttributeName, {
    #       ParamEntryName: ( ParamEntryNickname, VisibleDefault, ParamTableType, Docstring )
    # } ) }

    'NpcThinkParam': ('AI', {}),
    'EquipParamProtector': ('Armor', {}),
    'ReinforceParamProtector': ('ArmorUpgrades', {}),
    'GameAreaParam': ('Bosses',
                      {
                          'bonusSoul_single': ('SingleplayerSoulReward', True, None, "DOC-TODO"),
                          'bonusSoul_multi': ('MultiplayerSoulReward', True, None, "DOC-TODO"),
                      }),
    'Bullet': ('Bullets', {}),
    'LockCamParam': ('Cameras', {}),
    'AtkParam_Pc': ('CharacterAttacks', {}),
    'BehaviorParam_PC': ('CharacterBehaviors', {}),
    'CharaInitParam': ('CharacterSheets', {}),
    'TalkParam': ('Dialogue', {}),
    'FaceGenParam': ('Faces', {}),
    'EquipParamGoods': ('Goods', {}),
    'HitMtrlParam': ('Terrains', {}),
    'ItemLotParam': ('ItemLots', {}),
    'MenuColorTableParam': ('MenuColors', {}),
    'AtkParam_Npc': ('CreatureAttacks', {}),
    'BehaviorParam': ('CreatureBehaviors', {}),
    'NpcParam': ('NPCs', {
        'behaviorVariationId': ('BehaviorVariationID', True, None, "DOC-TODO"),
        'aiThinkId': ('AiThinkID', True, '<Param:AI>', "DOC-TODO"),
        'nameId': ('NameID', True, '<Text:NPCNames>', "DOC-TODO"),
        'turnVellocity': ('TurnVelocity', True, None, "DOC-TODO"),
        'hitHeight': ('HitHeight', True, None, "DOC-TODO"),
        'hitRadius': ('HitRadius', True, None, "DOC-TODO"),
        'weight': ('Weight', True, None, "DOC-TODO"),
        'hitYOffset': ('HitYOffset', False, None, "DOC-TODO"),
        'hp': ('MaximumHP', True, None, "DOC-TODO"),
        'mp': ('MaximumMP', True, None, "DOC-TODO"),
        'getSoul': ('SoulReward', True, None, "DOC-TODO"),
        'itemLotId_1': ('ItemLotID1', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_2': ('ItemLotID2', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_3': ('ItemLotID3', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_4': ('ItemLotID4', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_5': ('ItemLotID5', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_6': ('ItemLotID6', True, '<Param:ItemLots>', "DOC-TODO"),
        'humanityLotId': ('HumanityLotID', True, None, "DOC-TODO"),
        'spEffectID0': ('SpecialEffectID0', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID1': ('SpecialEffectID1', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID2': ('SpecialEffectID2', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID3': ('SpecialEffectID3', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID4': ('SpecialEffectID4', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID5': ('SpecialEffectID5', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID6': ('SpecialEffectID6', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID7': ('SpecialEffectID7', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'GameClearSpEffectID': ('NewGamePlusSpecialEffect', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'physGuardCutRate': ('PhysicalGuardCutRate', True, None, "DOC-TODO"),
        'magGuardCutRate': ('MagicGuardCutRate', True, None, "DOC-TODO"),
        'fireGuardCutRate': ('FireGuardCutRate', True, None, "DOC-TODO"),
        'thunGuardCutRate': ('LightningGuardCutRate', True, None, "DOC-TODO"),
        'animIdOffset': ('AnimationIDOffset', True, None, "DOC-TODO"),
        'moveAnimId': ('MoveAnimationID', False, None, "DOC-TODO"),
        'spMoveAnimId1': ('SpecialMoveAnimationID1', False, None, "DOC-TODO"),
        'spMoveAnimId2': ('SpecialMoveAnimationID2', False, None, "DOC-TODO"),
        'networkWarpDist': ('NetworkWarpDistance', False, None, "DOC-TODO"),
        'dbgBehaviorR1': ('DebugBehaviorR1', False, None, "DOC-TODO"),
        'dbgBehaviorL1': ('DebugBehaviorL1', False, None, "DOC-TODO"),
        'dbgBehaviorR2': ('DebugBehaviorR2', False, None, "DOC-TODO"),
        'dbgBehaviorL2': ('DebugBehaviorL2', False, None, "DOC-TODO"),
        'dbgBehaviorRL': ('DebugBehaviorRL', False, None, "DOC-TODO"),
        'dbgBehaviorRR': ('DebugBehaviorRR', False, None, "DOC-TODO"),
        'dbgBehaviorRD': ('DebugBehaviorRD', False, None, "DOC-TODO"),
        'dbgBehaviorRU': ('DebugBehaviorRU', False, None, "DOC-TODO"),
        'dbgBehaviorLL': ('DebugBehaviorLL', False, None, "DOC-TODO"),
        'dbgBehaviorLR': ('DebugBehaviorLR', False, None, "DOC-TODO"),
        'dbgBehaviorLD': ('DebugBehaviorLD', False, None, "DOC-TODO"),
        'dbgBehaviorLU': ('DebugBehaviorLU', False, None, "DOC-TODO"),
        'animIdOffset2': ('AnimationIDOffset2', False, None, "DOC-TODO"),
        'partsDamageRate1': ('Part1DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate2': ('Part2DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate3': ('Part3DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate4': ('Part4DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate5': ('Part5DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate6': ('Part6DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate7': ('Part7DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate8': ('Part8DamageRate', True, None, "DOC-TODO"),
        'weakPartsDamageRate': ('WeakPartsDamageRate', True, None, "DOC-TODO"),
        'superArmorRecoverCorrection': ('PoiseRecoveryCorrection', True, None, "DOC-TODO"),
        'superArmorBrakeKnockbackDist': ('StaggerKnockbackDistance', True, None, "DOC-TODO"),
        'stamina': ('MaxStamina', True, None, "DOC-TODO"),
        'staminaRecoverBaseVel': ('StaminaRecoveryBaseSpeed', True, None, "DOC-TODO"),
        'def_phys': ('PhysicalDefense', True, None, "Base defense applied to all physical attacks."),
        'def_slash': ('SlashDefense', True, None, "Base defense added against slashing physical attacks."),
        'def_blow': ('StrikeDefense', True, None, "Base defense added against striking physical attacks."),
        'def_thrust': ('ThrustDefense', True, None, "Base defense added against thrusting physical attacks."),
        'def_mag': ('MagicDefense', True, None, "DOC-TODO"),
        'def_fire': ('FireDefense', True, None, "DOC-TODO"),
        'def_thunder': ('LightningDefense', True, None, "DOC-TODO"),
        'defFlickPower': ('DefenseRepelPower', False, None,
                          "Determines how badly an attacker is repelled when they fail to break this NPC's "
                          "poise. The Armored Tusk and Chained Prisoner have very high values (50-60), but most "
                          "NPCs have 0."),
        'resist_poison': ('PoisonResistance', True, None, "Base poison resistance."),
        'resist_desease': ('ToxicResistance', True, None, "Base toxic resistance."),
        'resist_blood': ('BleedResistance', True, None, "Base bleed resistance."),
        'resist_curse': ('CurseResistance', True, None, "Base curse resistance."),
        'ghostModelId': ('GhostModelID', False, None,
                         "Model to be used when this quest-related NPC appears as a ghost to other players. Defaults "
                         "to -1 for almost all standard enemies, which means they do not appear as a ghost to others."),
        'normalChangeResouceId': ('NormalChangeResourceID', False, None, "Unknown. Always -1."),
        'guardAngle': ('GuardAngle', False, None,
                       "Zero for every NPC except the Phalanx Hollow (20)."),
        'slashGuardCutRate': ('SlashGuardCutRate', False, None, "Always zero."),
        'blowGuardCutRate': ('BlowGuardCutRate', False, None, "Always zero."),
        'thrustGuardCutRate': ('ThrustGuardCutRate', False, None, "Always zero."),
        'superArmorDurability': ('MaxPoise', True, None,
                                 "DOC-TODO"),
        'normalChangeTexChrId': ('NormalChangeTextureChrID', False, None,
                                 "Unknown. Used for only some NPCs, where it is generally set to a number close to "
                                 "the NPC's character model ID."),
        'dropType': ('ItemDropAppearance', True, None,
                     "Determines appearance of dropped items. 0 means the item appears to glow faintly from inside the "
                     "NPC's body (e.g. Rat, Mushroom Child/Parent, Ent) and 1 means the item is a clear white orb "
                     "just like regular treasure on corpses (most NPCs)."),
        'knockbackRate': ('KnockbackRate', True, None,
                          "DOC-TODO"),
        'knockbackParamId': ('KnockbackID', True, None,
                             "Knockback parameters were abandoned after Demons' Souls."),
        'fallDamageDump': ('FallDamageReduction', True, None,
                           "Percentage of fall damage to ignore."),
        'staminaGuardDef': ('StaminaGuardDefense', True, None,
                            "Always set to zero in the game, but presumably, increasing it will reduce the amount of "
                            "stamina lost when this NPC blocks an attack."),
        'pcAttrB': ('PCAttrB', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrW': ('PCAttrW', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrL': ('PCAttrL', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrR': ('PCAttrR', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrB': ('AreaAttrB', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrW': ('AreaAttrW', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrL': ('AreaAttrL', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrR': ('AreaAttrR', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'mpRecoverBaseVel': ('MPRecoveryBaseSpeed', False, None,
                             "Unknown effect, likely none. Set to zero for NPC parts (tails and Hydra heads) and 10 "
                             "for everyone else."),
        'flickDamageCutRate': ('RepelDamageCutRate', False, None,
                               "Unknown effect, but it is set to zero for most enemies, 50 for very heavy enemies "
                               "like Great Stone Knights and Titanite Demons, and 100 for Mimics."),
        'defaultLodParamId': ('DefaultLightingParamID', False, '<Lighting:Lod>', "Default lighting."),
        'drawType': ('DrawType', True, None, "DOC-TODO"),
        'npcType': ('NPCType', True, None, "DOC-TODO"),
        'teamType': ('TeamType', True, None, "0: enemy, 1: boss, 2: ally, 6: unused, 7: white phantom"),
        'moveType': ('MoveType', True, None, "DOC-TODO"),
        'lockDist': ('LockOnDistance', True, None, "DOC-TODO"),
        'material': ('Material', False, None, "DOC-TODO"),
        'materialSfx': ('MaterialSFX', False, None, "DOC-TODO"),
        'material_Weak': ('MaterialWeak', False, None, "DOC-TODO"),
        'materialSfx_Weak': ('MaterialWeakSFX', False, None, "DOC-TODO"),
        'partsDamageType': ('PartsDamageType', False, None,
                            "Unknown. Seems to be set to 1 for most enemies with multiple parts (Sentinels, Quelaag, "
                            "Seath, Gaping Dragon), but not all of them (Bell Gargoyles), and 0 otherwise."),
        'maxUndurationAng': ('MaxUndurationAngle', False, None,
                             "Unknown effect, but it is generally set to 30 for all four-legged enemies, and 0 for all "
                             "others."),
        'guardLevel': ('GuardLevel', False, None, "Set to 4 for enemies who can guard (including Manus), except Giant "
                                                  "Skeletons, who have a value of 3. All other NPCs have zero."),
        'burnSfxType': ('BurnSFXType', False, None, "Set to 1 for Slimes and Undead Dragons, and 0 for everyone else."),
        'poisonGuardResist': ('PoisonGuardResistance', True, None, "Added poison resistance while guarding."),
        'diseaseGuardResist': ('ToxicGuardResistance', True, None, "Added toxic resistance while guarding."),
        'bloodGuardResist': ('BleedGuardResistance', True, None, "Added bleed resistance while guarding."),
        'curseGuardResist': ('CurseGuardResistance', True, None, "Added curse resistance while guarding."),
        'parryAttack': ('ParryAttack', False, None, "Always zero."),
        'parryDefence': ('ParryDefense', True, None, "Always zero."),
        'sfxSize': ('SFXSize', False, None, "Set to 2 for very large enemies, 1 for large enemies, and 0 otherwise."),
        'pushOutCamRegionRadius': ('PushOutCameraRegionRadius', False, None, "Always zero."),
        'hitStopType': ('HitStopType', False, None,
                        "Set to 1 or 2 for most bosses/tough enemies, and 0 otherwise. Likely related to AI triggers."),
        'ladderEndChkOffsetTop': ('LadderEndCheckOffsetTop', False, None, "Not something you want to mess with."),
        'ladderEndChkOffsetLow': ('LadderEndCheckOffsetBottom', False, None, "Not something you want to mess with."),
        'useRagdollCamHit:1': ('UseRagdollCameraHit', False, None, "DOC-TODO"),
        'disableClothRigidHit:1': ('DisableClothRigidHit', False, None, "DOC-TODO"),
        'useRagdoll:1': ('UseRagdoll', False, None, "DOC-TODO"),
        'isDemon:1': ('IsDemon', True, None, "DOC-TODO"),
        'isGhost:1': ('IsGhost', True, None, "DOC-TODO"),
        'isNoDamageMotion:1': ('IsNoDamageMotion', True, None, "DOC-TODO"),
        'isUnduration:1': ('IsUnduration', False, None, "DOC-TODO"),
        'isChangeWanderGhost:1': ('IsChangeWanderGhost', False, None, "Always false."),
        'modelDispMask0:1': ('ModelDisplayMask0', False, None, "DOC-TODO"),
        'modelDispMask1:1': ('ModelDisplayMask1', False, None, "DOC-TODO"),
        'modelDispMask2:1': ('ModelDisplayMask2', False, None, "DOC-TODO"),
        'modelDispMask3:1': ('ModelDisplayMask3', False, None, "DOC-TODO"),
        'modelDispMask4:1': ('ModelDisplayMask4', False, None, "DOC-TODO"),
        'modelDispMask5:1': ('ModelDisplayMask5', False, None, "DOC-TODO"),
        'modelDispMask6:1': ('ModelDisplayMask6', False, None, "DOC-TODO"),
        'modelDispMask7:1': ('ModelDisplayMask7', False, None, "DOC-TODO"),
        'modelDispMask8:1': ('ModelDisplayMask8', False, None, "DOC-TODO"),
        'modelDispMask9:1': ('ModelDisplayMask9', False, None, "DOC-TODO"),
        'modelDispMask10:1': ('ModelDisplayMask10', False, None, "DOC-TODO"),
        'modelDispMask11:1': ('ModelDisplayMask11', False, None, "DOC-TODO"),
        'modelDispMask12:1': ('ModelDisplayMask12', False, None, "DOC-TODO"),
        'modelDispMask13:1': ('ModelDisplayMask13', False, None, "DOC-TODO"),
        'modelDispMask14:1': ('ModelDisplayMask14', False, None, "DOC-TODO"),
        'modelDispMask15:1': ('ModelDisplayMask15', False, None, "DOC-TODO"),
        'isEnableNeckTurn:1': ('IsEnableNeckTurn', False, None, "DOC-TODO"),
        'disableRespawn:1': ('DisableRespawnOnRest', True, None,
                             "Prevents NPC from respawning when you rest at a bonfire, though they will still respawn "
                             "when you die or the map is de-loaded unless they are disabled by an event script."),
        'isMoveAnimWait:1': ('IsMoveAnimationWait', False, None, "DOC-TODO"),
        'isCrowd:1': ('IsCrowd', False, None, "Always false."),
        'isWeakSaint:1': ('IsWeakToDivine', True, None,
                          "True for skeletons and friends, but not sure how it is actually used to disable their "
                          "reanimation by Necromancers."),
        'isWeakA:1': ('IsWeakToOccult', True, None, "True for all Gods and most NPCs in Anor Londo."),
        'isWeakB:1': ('IsAbyssal', True, None,
                      "True for Darkwraiths, Primordial Serpents, and the Four Kings, but not Manus."),
        'pad1:1': ('__Pad1', False, None, "DOC-TODO"),
        'vowType:3': ('VowType', False, None,
                      "Effects unknown. Set to 1 (Way of White) for Andre and 0 for everyone else."),
        'disableInitializeDead:1': ('DisableInitializeDead', False, None,
                                    "True for bosses and non-respawning enemies that are disabled in event scripts, "
                                    "but its effects are unknown."),
        'pad3:4': ('__Pad3', False, None, "DOC-TODO"),
        'pad2[6]': ('__Pad2', False, None, "DOC-TODO"),
    }),
    # 'RagdollParam': ('Ragdolls', {}),
    'EquipParamAccessory': ('Rings', {}),
    'ObjectParam': ('Objects', {}),
    'ObjActParam': ('ObjectActivations', {}),
    'ShopLineupParam': ('Shops', {}),
    # 'SkeletonParam': ('Skeletons', {}),
    'SpEffectParam': ('SpecialEffects', {}),
    'Magic': ('Spells', {}),
    'ThrowParam': ('Throws', {}),
    'EquipMtrlSetParam': ('UpgradeMaterials', {}),
    'EquipParamWeapon': ('Weapons', {}),
    'ReinforceParamWeapon': ('WeaponUpgrades', {}),
}