GAME_PARAM_INFO = {

    # Structure is:
    # { ParamTableName: ( ParamTableAttributeName, {
    #       ParamEntryName: ( ParamEntryNickname, VisibleDefault, ParamTableType, Docstring )
    # } ) }

    'NpcThinkParam': ('AI', {
        'logicId': ('LogicID', True, '<AI:Logic>', "ID of logic (non-battle) Lua script."),
        'battleGoalID': ('BattleID', True, '<AI:Battle>', "ID of battle Lua script."),
        'nearDist': ('NearDistance', True, None, "Near distance parameter for scripts."),
        'midDist': ('MidDistance', True, None, "Middle distance parameter for scripts."),
        'farDist': ('FarDistance', True, None, "Far distance parameter for scripts."),
        'outDist': ('OutDistance', True, None, "Outer distance parameter for scripts."),
        'BackHomeLife_OnHitEneWal': ('', True, None, "DOC-TODO"),
        'goalID_ToCaution': ('CautionGoalID', True, '<Lua:Logic>',
                             "Lua script to use when NPC's AI enters the 'Caution' state (I think). Requires a "
                             "CautionGoalAction value of 4. Used only by Hawkeye Gough (411000); zero otherwise."),
        'idAttackCannotMove': ('StuckAnimationID', True, None,
                               "Animation to use if the NPC gets stuck while navigating. Usually 3000 (basic attack)."),
        'goalID_ToFind': ('SearchGoalID', True, '<Lua:Logic>',
                          "Lua script to use when NPC's AI enters the 'Search' state (I think). Requires a "
                          "SearchGoalAction value of 4. Not used by any vanilla NPC (all zero)."),
        'callHelp_ActionAnimId': ('HelpCallAnimation', True, '<Animation>',
                                  "Animation to play when calling for help (I think)."),
        'callHelp_CallActionId': ('', True, None, "DOC-TODO"),
        'eye_dist': ('SightDistance', True, None, "Distance of NPC eyesight."),
        'ear_dist': ('HearingDistance', True, None, "Distance of NPC hearing."),
        'ear_soundcut_dist': ('HearingCutDistance', False, None,
                              "Unknown. Set to 1 for Bloatheads and Bloathead Sorcerers and 0 for everyone else."),
        'nose_dist': ('SmellDistance', True, None, "Distance of NPC smell (auto-detect)."),
        'maxBackhomeDist': ('MaxRetreatDistance', True, None,
                            "Largest distance the NPC will travel from their nest before retreating. Usually set "
                            "25-50% higher than RetreatDistance. Unclear how they differ; this distance may force "
                            "the NPC to retreat more quickly (i.e. where they can be kited)."),
        'backhomeDist': ('RetreatDistance', True, None,
                         "Distance the NPC will travel from their nest before retreating."),
        'backhomeBattleDist': ('RetreatBattleStartDistance', True, None,
                               "Target distance at which battle mode is triggered while the enemy is retreating."),
        'nonBattleActLife': ('NonBattleActLife', False, None,
                             "Lifespan of Acts outside of battle. Set to 10 for Bloatheads and Bloathead Sorcerers, "
                             "0 for Priscilla's Tail and the Bed of Chaos bug, and 5 for everyone else."),
        'BackHome_LookTargetTime': ('SearchTimeBeforeRetreat', True, None,
                                    "Time that NPC will search for a lost target before retreating (I think). Set to "
                                    "20 for everyone except the Bounding Demons of Izalith, who have a value of 0."),
        'BackHome_LookTargetDist': ('SearchDistanceBeforeRetreat', True, None,
                                    "Distance that NPC will search for a lost target before retreating (I think). Set "
                                    "to 20 for everyone except the Bounding Demons of Izaltih, who have a value of 0."),
        'SightTargetForgetTime': ('SightForgetTime', True, None,
                                  "Time to forget about sighted targets. Usually set to 600."),
        'SoundTargetForgetTime': ('HearingForgetTime', True, None,
                                  "Time to forget about heard targets. Usually set to 300."),
        'BattleStartDist': ('BattleStartDistance', True, None, "Target distance at which battle mode is triggered."),
        'callHelp_MyPeerId': ('HelpID', True, None,
                              "ID that must match the HelpCallID of allies who calls for help (e.g. set to 1 for Male "
                              "Ghosts, who are called by Female Ghosts). Only 0 (no ID) and 1 are used."),
        'callHelp_CallPeerId': ('HelpCallID', True, None,
                                "ID that must match the HelpID of allies when this NPC calls for help (e.g. set to 1 "
                                "for Female Ghosts, who call Male Ghosts). Only 0 (no ID) and 1 are used."),
        'targetSys_DmgEffectRate': ('TargetSysDamageRate', False, None,
                                    "Unknown. Set to 0 for summons, phantoms, and the Parasitic Wall Hugger, and 100 "
                                    "for everyone else."),
        'TeamAttackEffectivity': ('TeamAttackEffectivity', True, None,
                                  "Has an unknown effect on damage to allies. Generally set to 100 for bosses and 25 "
                                  "for everyone else. Unclear why a value of 25 is used; effect may be pointless "
                                  "when NPCs are on the same team already."),
        'eye_angX': ('SightHorizontalAngle', True, None, "Angular width of sight box."),
        'eye_angY': ('SightVerticalAngle', True, None, "Angular height of sight box."),
        'ear_angX': ('HearingHorizontalAngle', True, None, "Angular width of hearing box."),
        'ear_angY': ('HearingVerticalAngle', True, None, "Angular height of hearing box."),
        'callHelp_CallValidMinDistTarget': ('HelpCallTargetMinDistance', False, None, "Unclear. Always set to zero."),
        'callHelp_CallValidRange': ('HelpCallRange', True, None,
                                    "Range of sending/receiving calls for help (I think). Set to 50 for both Male and "
                                    "Female Ghosts, and 0 for everyone else."),
        'callHelp_ForgetTimeByArrival': ('', True, None, "DOC-TODO"),
        'callHelp_MinWaitTime': ('', True, None, "DOC-TODO"),
        'callHelp_MaxWaitTime': ('', True, None, "DOC-TODO"),
        'goalAction_ToCaution': ('', True, None, "DOC-TODO"),
        'goalAction_ToFind': ('', True, None, "DOC-TODO"),
        'callHelp_ReplyBehaviorType': ('', True, None, "DOC-TODO"),
        'disablePathMove': ('IgnoreNavimesh', True, None,  # TODO: Seems to act like a bool.
                            "If 1, this NPC will ignore navimesh. Used by Ghosts and enemies that don't move at all."),
        'skipArrivalVisibleCheck': ('SkipArrivalVisibleCheck', False, '<bool>',
                                    "Unknown. True only for Hawkeye Gough. Possibly skips an automatic sight check "
                                    "that happens on spawn (or some other form of 'arrival')."),
        'thinkAttr_doAdmirer': ('ThinkAttributeDoAdmirer', True, None,
                                "Unclear, but likely relevant. Enabled for Soulmass and Pursuers, Rats (except the "
                                "Giant Rat), Infested Ghouls, Mushrooms, most Hollows (not archers), Male Ghosts, "
                                "normals Skeletons and Skeleton Beasts, Pisaca, Gardeners, Bloatheads (not Sorcerers), "
                                "Humanity Phantoms, and the Four Kings."),
        'enableNaviFlg_Edge:1': ('CanFallOffEdges', True, None,
                                 "If True, this NPC will pursue targets off navimesh edges (survivable falls)."),
        'enableNaviFlg_LargeSpace:1': ('CanNavigateWideSpaces', True, None,
                                       "If True, this NPC will pursue targets into navimesh regions flagged as 'large "
                                       "spaces'."),
        'enableNaviFlg_Ladder:1': ('CanNavigateLadders', True, None,
                                   "If True, this NPC will pursue targets up or down ladders."),
        'enableNaviFlg_Hole:1': ('CanNavigateHoles', True, None,
                                 "If True, this NPC will pursue targets into navimesh holes."),
        'enableNaviFlg_Door:1': ('CanNavigateDoors', True, None,
                                 "If True, this NPC will pursue targets through doors. (Unlikely this lets them open "
                                 "closed doors, though.)"),
        'enableNaviFlg_InSideWall:1': ('CanNavigateInSideWalls', True, None,
                                       "Unclear what navimesh type this refers to. "),
        'enableNaviFlg_reserve0:2': ('UnusedNavimeshFlagsX2', False, None,
                                     "Two unused bytes reserved for other navimesh checks. No effect."),
        'enableNaviFlg_reserve1[3]': ('UnusedNavimeshFlagX3', False, '<Pad:3>',
                                      "Three unused bytes reserved for other navimesh checks. Marked as padding."),
        'pad0[12]': ('Pad0', False, '<Pad:12>', "Null padding."),
    }),
    'EquipParamProtector': ('Armor', {}),
    'ReinforceParamProtector': ('ArmorUpgrades', {}),
    'GameAreaParam': ('Bosses', {
        'bonusSoul_single': ('SingleplayerSoulReward', True, None,
                             "Souls awarded (after delay) when boss is defeated with no summons."),
        'bonusSoul_multi': ('MultiplayerSoulReward', True, None,
                            "Souls awarded to each player (after delay) when boss is defeated with summons."),
        'humanityPointCountFlagIdTop': ('FirstHumanityFlag', True, None,
                                        "First flag for recording number of humanity drops awarded in boss's area."),
        'humanityDropPoint1': ('HumanityDropPoint1', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for first Humanity."),
        'humanityDropPoint2': ('HumanityDropPoint2', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for second Humanity."),
        'humanityDropPoint3': ('HumanityDropPoint3', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for third Humanity."),
        'humanityDropPoint4': ('HumanityDropPoint4', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for fourth Humanity."),
        'humanityDropPoint5': ('HumanityDropPoint5', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for fifth Humanity."),
        'humanityDropPoint6': ('HumanityDropPoint6', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for sixth Humanity."),
        'humanityDropPoint7': ('HumanityDropPoint7', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for seventh Humanity."),
        'humanityDropPoint8': ('HumanityDropPoint8', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for eighth Humanity."),
        'humanityDropPoint9': ('HumanityDropPoint9', True, None,
                               "Number of 'points' needed from killing enemies in the boss area for ninth Humanity."),
        'humanityDropPoint10': ('HumanityDropPoint10', True, None,
                                "Number of 'points' needed from killing enemies in the boss area for final Humanity."),
    }),
    'Bullet': ('Bullets', {
        'atkId_Bullet': ('BulletAttack', True, '<Attacks>',  # TODO: <Attacks>?
                         "Attack parameters for bullet impact. Could refer to either CharacterAttacks table or "
                         "CreatureAttacks table, depending on the bullet's owner. Set to 0 if bullet deals no damage."),
        'sfxId_Bullet': ('ProjectileFX', True, '<FX>', "Visual effect ID for bullet projectile."),
        'sfxId_Hit': ('ImpactFX', True, '<FX>', "Visual effect ID for bullet impact."),
        'sfxId_Flick': ('FlickFX', True, '<FX>',
                        "Visual effect ID for when bullet is blocked (I think). Used predominantly for arrows and "
                        "throwing knives."),
        'life': ('MaxTime', True, None, "Maximum time before bullet will disappear on its own."),
        'dist': ('MaxDistance', True, None,
                 "Maximum distance bullet can travel before it disappears. (Unclear if this is distance from its "
                 "owner or total distance traversed by the bullet.)"),
        'shootInterval': ('EmitInterval', True, None,
                          "Time between emitted bullets. Does nothing for bullets that only shoot once and is "
                          "generally left at zero for those bullets."),
        'gravityInRange': ('GravityInRange', True, None,
                           "Downward acceleration acting on bullet. Used rarely, and unclear how it it differs to "
                           "GravityOutRange below. (I suspect 'in range' is true only at close distance to its "
                           "owner.)"),
        'gravityOutRange': ('GravityOutRange', True, None,
                            "Downward acceleration acting on bullet. Used more than GravityInRange. (I suspect 'in "
                            "range' is true only at close distance to its owner.)"),
        'hormingStopRange': ('MaxHomingDistance', True, None,
                             "Maximum distance that the bullet will home for. It will travel straight (plus gravity) "
                             "after this distance is reached."),
        'initVellocity': ('InitialSpeed', True, None, "Initial speed of bullet."),
        'accelInRange': ('AccelerationInRange', True, None,
                         "Forward acceleration acting on bullet. Negative values will slow the bullet down. (I suspect "
                         "'in range' is true only at close distance.)"
                         "to its owner."),
        'accelOutRange': ('AccelerationOutRange', True, None,
                          "Forward acceleration acting on bullet. Negative values will slow the bullet down. (I "
                          "suspect 'in range' is true only at close distance.)"),
        'maxVellocity': ('MaxSpeed', True, None, "Maximum speed of bullet."),
        'minVellocity': ('MinSpeed', True, None, "Minimum speed of bullet."),
        'accelTime': ('AccelerationTime', True, None, "Time that acceleration is active after bullet creation."),
        'homingBeginDist': ('HomingStartDistance', True, None,
                            "Distance from owner at which the bullet starts homing in on targets."),
        'hitRadius': ('InitialHitRadius', True, None, "Initial hit radius of bullet projectile."),
        'hitRadiusMax': ('FinalHitRadius', True, None,
                         "Final hit radius of bullet projectile. Set to -1 if radius does not change, which is always "
                         "coupled with a value of 0 for RadiusIncreaseDuration."),
        'spreadTime': ('RadiusIncreaseDuration', True, None,
                       "Time taken by bullet to transition from initial to final hit radius. Value of 0 are always "
                       "coupled with values of -1 for RadiusIncreaseDuration."),
        'expDelay': ('ExpDelay', False, None, "Unknown. Always set to zero."),
        'hormingOffsetRange': ('HomingOffsetRange', True, None,
                               "Unknown. Nonzero only for Hydra blasts and Vagrant attacks."),
        'dmgHitRecordLifeTime': ('HitboxLifeTime', True, None,
                                 "Duration of bullet impact hitbox. A value of zero means it is disabled immediately "
                                 "after first impact."),
        'externalForce': ('ExternalForce', True, None,
                          "Unknown. Used only for Gargoyle fire breath and Undead Dragon poison breath."),
        'spEffectIDForShooter': ('OwnerSpecialEffect', True, '<SpecialEffect>',
                                 "Special effect applied to owner when bullet is created. (Unclear if it is applied "
                                 "repeatedly by repeating bullets.)"),
        'autoSearchNPCThinkID': ('BulletAI', True, '<AI>',
                                 "AI parameter ID for triggered floating bullets. Only used by Homing [Crystal] "
                                 "Soulmass (10000) and Pursuers (10001) in the vanilla game."),
        'HitBulletID': ('BulletOnHit', True, '<Bullet>',
                        "Bullet emitted on impact of this bullet. Used often for 'throw'/'landing' or 'parent'/'child' "
                        "combinations, like a thrown Firebomb (bullet 110) triggering a fiery explosion (bullet 111). "
                        "These can be chained together indefinitely (see White Dragon Breath, bullet 11500)."),
        'spEffectId0': ('HitSpecialEffect0', True, '<SpecialEffect>',
                        "Special effect applied to target hit by bullet. (Slot 0)"),
        'spEffectId1': ('HitSpecialEffect1', True, '<SpecialEffect>',
                        "Special effect applied to target hit by bullet. (Slot 1)"),
        'spEffectId2': ('HitSpecialEffect2', True, '<SpecialEffect>',
                        "Special effect applied to target hit by bullet. (Slot 2)"),
        'spEffectId3': ('HitSpecialEffect3', True, '<SpecialEffect>',
                        "Special effect applied to target hit by bullet. (Slot 3)"),
        'spEffectId4': ('HitSpecialEffect4', True, '<SpecialEffect>',
                        "Special effect applied to target hit by bullet. (Slot 4)"),
        'numShoot': ('BulletCount', True, None, "Number of bullets emitted at once."),
        'homingAngle': ('HomingAngle', True, None,
                        "Turning angle of homing bullet. Higher values are better for homing."),
        'shootAngle': ('FirstBulletYAngle', True, None,
                       "Angle of first bullet in degrees around the vertical axis relative to the forward direction."),
        'shootAngleInterval': ('YAngleBetweenBullets', True, None,
                               "Angle from one bullet to the next around the vertical axis, beginning at "
                               "FirstBulletYAngle."),
        'shootAngleXInterval': ('ElevationAngleBetweenBullets', True, None,
                                "Angle from one bullet to the next around the X (left-right) axis."),
        'damageDamp': ('PhysicalDamageDamp', False, None,
                       "Unknown. Set to 0 for all bullets except Throwing Knives (40) and arrows/bolts (100)."),
        'spelDamageDamp': ('MagicDamageDamp', False, None,
                           "Unknown. Set to 0 for all bullets except Throwing Knives (40) and arrows/bolts (100)."),
        'fireDamageDamp': ('FireDamageDamp', False, None,
                           "Unknown. Set to 0 for all bullets except Throwing Knives (40) and arrows/bolts (100)."),
        'thunderDamageDamp': ('LightningDamageDamp', False, None,
                              "Unknown. Set to 0 for all bullets except arrows/bolts (100). Throwing Knives lack this "
                              "value, for some reason."),
        'staminaDamp': ('StaminaDamp', False, None,
                        "Unknown. Set to 0 for all bullets except Throwing Knives (40) and arrows/bolts (100)."),
        'knockbackDamp': ('KnockbackDamp', False, None,
                          "Unknown. Set to 0 for all bullets except Throwing Knives (40) and arrows/bolts (100)."),
        'shootAngleXZ': ('FirstBulletElevationAngle', True, None,
                         "Angle of elevation of first bullet. Positive values will angle the bullets up (e.g. "
                         "Quelaag's fireballs) and negative values will angle the bullets down (e.g. most breath "
                         "attacks)."),
        'lockShootLimitAng': ('LockShootLimitAngle', True, None,
                              "Unknown, but likely important. Set to 30 for most basic projectile magic."),
        'isPenetrate': ('IsTargetPiercing', True, None, "Bullet will go through targets (I think)."),
        'prevVelocityDirRate': ('PreviousVelocityDirectionRate', False, None,
                                "Unknown. Like ExternalForce, this is used only for Gargoyle and Undead Dragon breath "
                                "(100) and is zero for everything else."),
        'atkAttribute': ('AttackAttribute', True, '<Enum:AttackAttribute>',
                         "Attack type. Almost always 4 ('other'), but sometimes 3 (knives/arrows/bolts)."),
        'spAttribute': ('ElementAttribute', True, None, "Element attached to bullet hit."),
        'Material_AttackType': ('MaterialAttackType', True, None, "DOC-TODO"),
        'Material_AttackMaterial': ('MaterialAttackMaterial', True, None, "DOC-TODO"),
        'Material_Size': ('MaterialSize', True, None, "DOC-TODO"),
        'launchConditionType': ('LaunchConditionType', True, None, "DOC-TODO"),
        'FollowType:3': ('', True, None, "DOC-TODO"),
        'EmittePosType:3': ('', True, None, "DOC-TODO"),
        'isAttackSFX:1': ('IsAttackFX', True, '<bool>',
                          "Indicates that FX ID should be taken from attack FX rather than general map FX (I think)."),
        'isEndlessHit:1': ('IsEndlessHit', True, '<bool>',
                           "Bullet hitbox is continuous. Only used for corrosion cloud in vanilla."),
        'isPenetrateMap:1': ('IsMapPiercing', True, '<bool>', "Bullet will pierce the map (e.g. Stray Demon blast)."),
        'isHitBothTeam:1': ('HitsBothTeams', True, '<bool>', "Bullet can hit any character."),
        'isUseSharedHitList:1': ('SharedHitCheck', True, '<bool>',
                                 "Repeating bullets share the amount of times they have hit a target (usually so the "
                                 "target is only hit once by any of those repeating bullets)."),
        'isUseMultiDmyPolyIfPlace:1': ('', True, None, "DOC-TODO"),
        'attachEffectType:2': ('AttachEffectType', False, None,
                               "Mostly 0, but sometimes 1 (Dragon Head breath, Grant AoE, Force miracles)."),
        'isHitForceMagic:1': ('IsHitForceMagic', True, None,
                              "Unclear effect, but True for knives/arrows/bolts and False otherwise."),
        'isIgnoreSfxIfHitWater:1': ('IgnoreFXOnWaterHit', True, None,
                                    "If True, hit FX are not produced if the bullet impacts water."),
        'isIgnoreMoveStateIfHitWater:1': ('IgnoreMoveStateOnWaterHit', True, None,
                                          "Unclear effect, but True for knives/arrows/bolts and False otherwise."),
        'isHitDarkForceMagic:1': ('DarkMagic', True, None, "True for dark sorceries and False otherwise."),
        'pad[3]': ('Pad3', False, '<Pad:3>', "Null padding."),

    }),
    'LockCamParam': ('Cameras', {}),
    'AtkParam_Pc': ('CharacterAttacks', {}),
    'BehaviorParam_PC': ('CharacterBehaviors', {}),
    'CharaInitParam': ('CharacterSheets', {}),
    'TalkParam': ('Dialogue', {
        'msgId': ('SubtitleText', True, '<Text:Conversations>', "Text ID for dialogue subtitle."),
        'voiceId': ('VoiceSound', True, '<Sound:Voice>', "Sound ID (voice) for dialogue."),
        'motionId': (),  # TODO
        'returnPos': (),  # TODO
        'reactionId': (),  # TODO
        'eventId': (),  # TODO
        'isMotionLoop': ('IsMotionLoop', True, '<bool>', "DOC-TODO"),
        'pad0[7]': ('Pad', False, '<Pad:7>', "Null padding."),
    }),
    'FaceGenParam': ('Faces', {}),
    'EquipParamGoods': ('Goods', {}),
    'HitMtrlParam': ('Terrains', {}),
    'ItemLotParam': ('ItemLots', {}),
    'MenuColorTableParam': ('MenuColors', {}),
    'AtkParam_Npc': ('CreatureAttacks', {}),
    'BehaviorParam': ('CreatureBehaviors', {}),
    'NpcParam': ('NPCs', {
        'behaviorVariationId': ('BehaviorVariationID', True, None, "DOC-TODO"),
        'aiThinkId': ('AiThinkID', True, '<Param:AI>', "DOC-TODO"),
        'nameId': ('NameID', True, '<Text:NPCNames>', "DOC-TODO"),
        'turnVellocity': ('TurnVelocity', True, None, "DOC-TODO"),
        'hitHeight': ('HitHeight', True, None, "DOC-TODO"),
        'hitRadius': ('HitRadius', True, None, "DOC-TODO"),
        'weight': ('Weight', True, None, "DOC-TODO"),
        'hitYOffset': ('HitYOffset', False, None, "DOC-TODO"),
        'hp': ('MaximumHP', True, None, "DOC-TODO"),
        'mp': ('MaximumMP', True, None, "DOC-TODO"),
        'getSoul': ('SoulReward', True, None, "DOC-TODO"),
        'itemLotId_1': ('ItemLotID1', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_2': ('ItemLotID2', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_3': ('ItemLotID3', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_4': ('ItemLotID4', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_5': ('ItemLotID5', True, '<Param:ItemLots>', "DOC-TODO"),
        'itemLotId_6': ('ItemLotID6', True, '<Param:ItemLots>', "DOC-TODO"),
        'humanityLotId': ('HumanityLotID', True, None, "DOC-TODO"),
        'spEffectID0': ('SpecialEffectID0', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID1': ('SpecialEffectID1', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID2': ('SpecialEffectID2', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID3': ('SpecialEffectID3', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID4': ('SpecialEffectID4', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID5': ('SpecialEffectID5', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID6': ('SpecialEffectID6', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'spEffectID7': ('SpecialEffectID7', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'GameClearSpEffectID': ('NewGamePlusSpecialEffect', True, '<Param:SpecialEffects>', "DOC-TODO"),
        'physGuardCutRate': ('PhysicalGuardCutRate', True, None, "DOC-TODO"),
        'magGuardCutRate': ('MagicGuardCutRate', True, None, "DOC-TODO"),
        'fireGuardCutRate': ('FireGuardCutRate', True, None, "DOC-TODO"),
        'thunGuardCutRate': ('LightningGuardCutRate', True, None, "DOC-TODO"),
        'animIdOffset': ('AnimationIDOffset', True, None, "DOC-TODO"),
        'moveAnimId': ('MoveAnimationID', False, None, "DOC-TODO"),
        'spMoveAnimId1': ('SpecialMoveAnimationID1', False, None, "DOC-TODO"),
        'spMoveAnimId2': ('SpecialMoveAnimationID2', False, None, "DOC-TODO"),
        'networkWarpDist': ('NetworkWarpDistance', False, None, "DOC-TODO"),
        'dbgBehaviorR1': ('DebugBehaviorR1', False, None, "DOC-TODO"),
        'dbgBehaviorL1': ('DebugBehaviorL1', False, None, "DOC-TODO"),
        'dbgBehaviorR2': ('DebugBehaviorR2', False, None, "DOC-TODO"),
        'dbgBehaviorL2': ('DebugBehaviorL2', False, None, "DOC-TODO"),
        'dbgBehaviorRL': ('DebugBehaviorRL', False, None, "DOC-TODO"),
        'dbgBehaviorRR': ('DebugBehaviorRR', False, None, "DOC-TODO"),
        'dbgBehaviorRD': ('DebugBehaviorRD', False, None, "DOC-TODO"),
        'dbgBehaviorRU': ('DebugBehaviorRU', False, None, "DOC-TODO"),
        'dbgBehaviorLL': ('DebugBehaviorLL', False, None, "DOC-TODO"),
        'dbgBehaviorLR': ('DebugBehaviorLR', False, None, "DOC-TODO"),
        'dbgBehaviorLD': ('DebugBehaviorLD', False, None, "DOC-TODO"),
        'dbgBehaviorLU': ('DebugBehaviorLU', False, None, "DOC-TODO"),
        'animIdOffset2': ('AnimationIDOffset2', False, None, "DOC-TODO"),
        'partsDamageRate1': ('Part1DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate2': ('Part2DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate3': ('Part3DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate4': ('Part4DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate5': ('Part5DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate6': ('Part6DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate7': ('Part7DamageRate', True, None, "DOC-TODO"),
        'partsDamageRate8': ('Part8DamageRate', True, None, "DOC-TODO"),
        'weakPartsDamageRate': ('WeakPartsDamageRate', True, None, "DOC-TODO"),
        'superArmorRecoverCorrection': ('PoiseRecoveryCorrection', True, None, "DOC-TODO"),
        'superArmorBrakeKnockbackDist': ('StaggerKnockbackDistance', True, None, "DOC-TODO"),
        'stamina': ('MaxStamina', True, None, "DOC-TODO"),
        'staminaRecoverBaseVel': ('StaminaRecoveryBaseSpeed', True, None, "DOC-TODO"),
        'def_phys': ('PhysicalDefense', True, None, "Base defense applied to all physical attacks."),
        'def_slash': ('SlashDefense', True, None, "Base defense added against slashing physical attacks."),
        'def_blow': ('StrikeDefense', True, None, "Base defense added against striking physical attacks."),
        'def_thrust': ('ThrustDefense', True, None, "Base defense added against thrusting physical attacks."),
        'def_mag': ('MagicDefense', True, None, "DOC-TODO"),
        'def_fire': ('FireDefense', True, None, "DOC-TODO"),
        'def_thunder': ('LightningDefense', True, None, "DOC-TODO"),
        'defFlickPower': ('DefenseRepelPower', False, None,
                          "Determines how badly an attacker is repelled when they fail to break this NPC's "
                          "poise. The Armored Tusk and Chained Prisoner have very high values (50-60), but most "
                          "NPCs have 0."),
        'resist_poison': ('PoisonResistance', True, None, "Base poison resistance."),
        'resist_desease': ('ToxicResistance', True, None, "Base toxic resistance."),
        'resist_blood': ('BleedResistance', True, None, "Base bleed resistance."),
        'resist_curse': ('CurseResistance', True, None, "Base curse resistance."),
        'ghostModelId': ('GhostModelID', False, None,
                         "Model to be used when this quest-related NPC appears as a ghost to other players. Defaults "
                         "to -1 for almost all standard enemies, which means they do not appear as a ghost to others."),
        'normalChangeResouceId': ('NormalChangeResourceID', False, None, "Unknown. Always -1."),
        'guardAngle': ('GuardAngle', False, None,
                       "Zero for every NPC except the Phalanx Hollow (20)."),
        'slashGuardCutRate': ('SlashGuardCutRate', False, None, "Always zero."),
        'blowGuardCutRate': ('BlowGuardCutRate', False, None, "Always zero."),
        'thrustGuardCutRate': ('ThrustGuardCutRate', False, None, "Always zero."),
        'superArmorDurability': ('MaxPoise', True, None,
                                 "DOC-TODO"),
        'normalChangeTexChrId': ('NormalChangeTextureChrID', False, None,
                                 "Unknown. Used for only some NPCs, where it is generally set to a number close to "
                                 "the NPC's character model ID."),
        'dropType': ('ItemDropAppearance', True, None,
                     "Determines appearance of dropped items. 0 means the item appears to glow faintly from inside the "
                     "NPC's body (e.g. Rat, Mushroom Child/Parent, Ent) and 1 means the item is a clear white orb "
                     "just like regular treasure on corpses (most NPCs)."),
        'knockbackRate': ('KnockbackRate', True, None,
                          "DOC-TODO"),
        'knockbackParamId': ('KnockbackID', True, None,
                             "Knockback parameters were abandoned after Demons' Souls."),
        'fallDamageDump': ('FallDamageReduction', True, None,
                           "Percentage of fall damage to ignore."),
        'staminaGuardDef': ('StaminaGuardDefense', True, None,
                            "Always set to zero in the game, but presumably, increasing it will reduce the amount of "
                            "stamina lost when this NPC blocks an attack."),
        'pcAttrB': ('PCAttrB', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrW': ('PCAttrW', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrL': ('PCAttrL', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'pcAttrR': ('PCAttrR', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrB': ('AreaAttrB', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrW': ('AreaAttrW', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrL': ('AreaAttrL', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'areaAttrR': ('AreaAttrR', False, None, "Like a remnant of World Tendency. Always set to zero."),
        'mpRecoverBaseVel': ('MPRecoveryBaseSpeed', False, None,
                             "Unknown effect, likely none. Set to zero for NPC parts (tails and Hydra heads) and 10 "
                             "for everyone else."),
        'flickDamageCutRate': ('RepelDamageCutRate', False, None,
                               "Unknown effect, but it is set to zero for most enemies, 50 for very heavy enemies "
                               "like Great Stone Knights and Titanite Demons, and 100 for Mimics."),
        'defaultLodParamId': ('DefaultLightingParamID', False, '<Lighting:Lod>', "Default lighting."),
        'drawType': ('DrawType', True, None, "DOC-TODO"),
        'npcType': ('NPCType', True, None, "DOC-TODO"),
        'teamType': ('TeamType', True, None, "0: enemy, 1: boss, 2: ally, 6: unused, 7: white phantom"),
        'moveType': ('MoveType', True, None, "DOC-TODO"),
        'lockDist': ('LockOnDistance', True, None, "DOC-TODO"),
        'material': ('Material', False, None, "DOC-TODO"),
        'materialSfx': ('MaterialSFX', False, None, "DOC-TODO"),
        'material_Weak': ('MaterialWeak', False, None, "DOC-TODO"),
        'materialSfx_Weak': ('MaterialWeakSFX', False, None, "DOC-TODO"),
        'partsDamageType': ('PartsDamageType', False, None,
                            "Unknown. Seems to be set to 1 for most enemies with multiple parts (Sentinels, Quelaag, "
                            "Seath, Gaping Dragon), but not all of them (Bell Gargoyles), and 0 otherwise."),
        'maxUndurationAng': ('MaxUndurationAngle', False, None,
                             "Unknown effect, but it is generally set to 30 for all four-legged enemies, and 0 for all "
                             "others."),
        'guardLevel': ('GuardLevel', False, None, "Set to 4 for enemies who can guard (including Manus), except Giant "
                                                  "Skeletons, who have a value of 3. All other NPCs have zero."),
        'burnSfxType': ('BurnSFXType', False, None, "Set to 1 for Slimes and Undead Dragons, and 0 for everyone else."),
        'poisonGuardResist': ('PoisonGuardResistance', True, None, "Added poison resistance while guarding."),
        'diseaseGuardResist': ('ToxicGuardResistance', True, None, "Added toxic resistance while guarding."),
        'bloodGuardResist': ('BleedGuardResistance', True, None, "Added bleed resistance while guarding."),
        'curseGuardResist': ('CurseGuardResistance', True, None, "Added curse resistance while guarding."),
        'parryAttack': ('ParryAttack', False, None, "Always zero."),
        'parryDefence': ('ParryDefense', True, None, "Always zero."),
        'sfxSize': ('SFXSize', False, None, "Set to 2 for very large enemies, 1 for large enemies, and 0 otherwise."),
        'pushOutCamRegionRadius': ('PushOutCameraRegionRadius', False, None, "Always zero."),
        'hitStopType': ('HitStopType', False, None,
                        "Set to 1 or 2 for most bosses/tough enemies, and 0 otherwise. Likely related to AI triggers."),
        'ladderEndChkOffsetTop': ('LadderEndCheckOffsetTop', False, None, "Not something you want to mess with."),
        'ladderEndChkOffsetLow': ('LadderEndCheckOffsetBottom', False, None, "Not something you want to mess with."),
        'useRagdollCamHit:1': ('UseRagdollCameraHit', False, None, "DOC-TODO"),
        'disableClothRigidHit:1': ('DisableClothRigidHit', False, None, "DOC-TODO"),
        'useRagdoll:1': ('UseRagdoll', False, None, "DOC-TODO"),
        'isDemon:1': ('IsDemon', True, None, "DOC-TODO"),
        'isGhost:1': ('IsGhost', True, None, "DOC-TODO"),
        'isNoDamageMotion:1': ('IsNoDamageMotion', True, None, "DOC-TODO"),
        'isUnduration:1': ('IsUnduration', False, None, "DOC-TODO"),
        'isChangeWanderGhost:1': ('IsChangeWanderGhost', False, None, "Always false."),
        'modelDispMask0:1': ('ModelDisplayMask0', False, None, "DOC-TODO"),
        'modelDispMask1:1': ('ModelDisplayMask1', False, None, "DOC-TODO"),
        'modelDispMask2:1': ('ModelDisplayMask2', False, None, "DOC-TODO"),
        'modelDispMask3:1': ('ModelDisplayMask3', False, None, "DOC-TODO"),
        'modelDispMask4:1': ('ModelDisplayMask4', False, None, "DOC-TODO"),
        'modelDispMask5:1': ('ModelDisplayMask5', False, None, "DOC-TODO"),
        'modelDispMask6:1': ('ModelDisplayMask6', False, None, "DOC-TODO"),
        'modelDispMask7:1': ('ModelDisplayMask7', False, None, "DOC-TODO"),
        'modelDispMask8:1': ('ModelDisplayMask8', False, None, "DOC-TODO"),
        'modelDispMask9:1': ('ModelDisplayMask9', False, None, "DOC-TODO"),
        'modelDispMask10:1': ('ModelDisplayMask10', False, None, "DOC-TODO"),
        'modelDispMask11:1': ('ModelDisplayMask11', False, None, "DOC-TODO"),
        'modelDispMask12:1': ('ModelDisplayMask12', False, None, "DOC-TODO"),
        'modelDispMask13:1': ('ModelDisplayMask13', False, None, "DOC-TODO"),
        'modelDispMask14:1': ('ModelDisplayMask14', False, None, "DOC-TODO"),
        'modelDispMask15:1': ('ModelDisplayMask15', False, None, "DOC-TODO"),
        'isEnableNeckTurn:1': ('IsEnableNeckTurn', False, None, "DOC-TODO"),
        'disableRespawn:1': ('DisableRespawnOnRest', True, None,
                             "Prevents NPC from respawning when you rest at a bonfire, though they will still respawn "
                             "when you die or the map is de-loaded unless they are disabled by an event script."),
        'isMoveAnimWait:1': ('IsMoveAnimationWait', False, None, "DOC-TODO"),
        'isCrowd:1': ('IsCrowd', False, None, "Always false."),
        'isWeakSaint:1': ('IsWeakToDivine', True, None,
                          "True for skeletons and friends, but not sure how it is actually used to disable their "
                          "reanimation by Necromancers."),
        'isWeakA:1': ('IsWeakToOccult', True, None, "True for all Gods and most NPCs in Anor Londo."),
        'isWeakB:1': ('IsAbyssal', True, None,
                      "True for Darkwraiths, Primordial Serpents, and the Four Kings, but not Manus."),
        'pad1:1': ('__Pad1', False, None, "DOC-TODO"),
        'vowType:3': ('VowType', False, None,
                      "Effects unknown. Set to 1 (Way of White) for Andre and 0 for everyone else."),
        'disableInitializeDead:1': ('DisableInitializeDead', False, None,
                                    "True for bosses and non-respawning enemies that are disabled in event scripts, "
                                    "but its effects are unknown."),
        'pad3:4': ('__Pad3', False, None, "DOC-TODO"),
        'pad2[6]': ('__Pad2', False, None, "DOC-TODO"),
    }),
    # 'RagdollParam': ('Ragdolls', {}),
    'EquipParamAccessory': ('Rings', {}),
    'ObjectParam': ('Objects', {}),
    'ObjActParam': ('ObjectActivations', {}),
    'ShopLineupParam': ('Shops', {}),
    # 'SkeletonParam': ('Skeletons', {}),
    'SpEffectParam': ('SpecialEffects', {}),
    'Magic': ('Spells', {}),
    'ThrowParam': ('Throws', {}),
    'EquipMtrlSetParam': ('UpgradeMaterials', {}),
    'EquipParamWeapon': ('Weapons', {}),
    'ReinforceParamWeapon': ('WeaponUpgrades', {}),
}
