from soulstruct.emevd import ds_types as dt
from soulstruct.emevd.pydses.event_enums import *

PLAYER = 10000

DEPTHS = dt.Map(10, 0)
UNDEAD_BURG = UNDEAD_PARISH = dt.Map(10, 1)
FIRELINK_SHRINE = dt.Map(10, 2)
PAINTED_WORLD = dt.Map(11, 0)
DARKROOT_GARDEN = DARKROOT_BASIN = dt.Map(12, 0)
OOLACILE = OOLACILE_SANCTUARY = ROYAL_WOOD = OOLACILE_TOWNSHIP = CHASM_OF_THE_ABYSS = DLC_MAP = dt.Map(12, 1)
CATACOMBS = dt.Map(13, 0)
TOMB_OF_THE_GIANTS = dt.Map(13, 1)
GREAT_HOLLOW = ASH_LAKE = dt.Map(13, 2)
BLIGHTTOWN = dt.Map(14, 0)
DEMON_RUINS = LOST_IZALITH = dt.Map(14, 1)
SENS_FORTRESS = dt.Map(15, 0)
ANOR_LONDO = dt.Map(15, 1)
NEW_LONDO_RUINS = VALLEY_OF_DRAKES = dt.Map(16, 0)
DUKES_ARCHIVES = CRYSTAL_CAVE = dt.Map(17, 0)
KILN_OF_THE_FIRST_FLAME = dt.Map(18, 0)
UNDEAD_ASYLUM = dt.Map(18, 1)
