from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


ACTIONBUTTON_PARAM_ST = {
    "param_type": "ACTIONBUTTON_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "regionType",
            "Region Type",
            True,
            int,
            'Range shape (cylinder, prism, capsule)',
        ),
        ParamFieldInfo(
            "category",
            "Category",
            True,
            int,
            'category. The number on the left side of the name is the priority when multiple action buttons overlap (the closer it is to 0, the higher the priority is displayed).',
        ),
        ParamFieldInfo(
            "padding1[2]",
            "Padding 1",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "dummyPoly1",
            "Dummy Poly [1]",
            True,
            int,
            'Specify the Damipoli ID that is the center of the bottom of the range. If there is no Damipoly or -1 is entered, the center coordinates will be the reference.',
        ),
        ParamFieldInfo(
            "dummyPoly2",
            "Dummy Poly [2]",
            True,
            int,
            'Used only when the range type is a capsule. Additional Damipoly (capsule) that creates a line segment with two Damipoly',
        ),
        ParamFieldInfo(
            "radius",
            "Radius",
            True,
            float,
            'Radius (cylinder / capsule)',
        ),
        ParamFieldInfo(
            "angle",
            "Angle",
            True,
            int,
            'Angle (cylinder)',
        ),
        ParamFieldInfo(
            "depth",
            "Depth",
            True,
            float,
            'Depth (prism)',
        ),
        ParamFieldInfo(
            "width",
            "Width",
            True,
            float,
            'Width (prism)',
        ),
        ParamFieldInfo(
            "height",
            "Height",
            True,
            float,
            'Height (cylinder / prism)',
        ),
        ParamFieldInfo(
            "baseHeightOffset",
            "Bottom Height Offset",
            True,
            float,
            'How much to raise or lower the Y coordinate of the bottom (cylinder / prism)',
        ),
        ParamFieldInfo(
            "angleCheckType",
            "Angle Difference Check Type",
            True,
            int,
            'Angle difference judgment type (cylinder / prism)',
        ),
        ParamFieldInfo(
            "padding2[3]",
            "Padding 2",
            False,
            pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "allowAngle",
            "Allowable Angle Difference",
            True,
            int,
            'Allowable angle difference (cylinder / prism)',
        ),
        ParamFieldInfo(
            "spotDummyPoly",
            "Action Spot Dummy Poly",
            True,
            int,
            'If there is no Damipoli that specifies the Damipoli ID that will be the position of the action spot, or if -1 is entered, the center coordinates will be the reference.',
        ),
        ParamFieldInfo(
            "textBoxType",
            "Textbox Type",
            True,
            int,
            'Text box type',
        ),
        ParamFieldInfo(
            "padding3[2]",
            "Padding 3",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "padding5:1",
            "Padding 5",
            False,
            bit_pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "isInvalidForRide:1",
            "Invalid for Ride",
            True,
            int,
            'If this item is YES, the action button will not appear when riding and no judgment will be made.',
        ),
        ParamFieldInfo(
            "isGrayoutForRide:1",
            "Greyout for Ride",
            True,
            int,
            'If this item is YES, the action button will be grayed out when riding and no judgment will be made.',
        ),
        ParamFieldInfo(
            "isInvalidForCrouching:1",
            "Invalid for Crouching",
            True,
            int,
            'If this item is YES, the action button will not appear when crouching, and no judgment will be made.',
        ),
        ParamFieldInfo(
            "isGrayoutForCrouching:1",
            "Greyout for Crouching",
            True,
            int,
            'If this item is YES, the action button will be grayed out when crouching and no judgment will be made.',
        ),
        ParamFieldInfo(
            "padding4:3",
            "Padding 4",
            False,
            bit_pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "textId",
            "Text ID",
            True,
            int,
            'Text ID to display',
        ),
        ParamFieldInfo(
            "invalidFlag",
            "Invalid Flag",
            True,
            int,
            'If this flag is ON, the action button will not appear and no judgment will be made.',
        ),
        ParamFieldInfo(
            "grayoutFlag",
            "Grayout Flag",
            True,
            int,
            'If this flag is ON, the action button will be grayed out and no judgment will be made.',
        ),
        ParamFieldInfo(
            "overrideActionButtonIdForRide",
            "Override Button ID for Ride",
            True,
            int,
            'Replace with this action button ID parameter while riding (-1: No replacement)',
        ),
        ParamFieldInfo(
            "execInvalidTime",
            "Execution Invalid Time",
            True,
            float,
            'Invalid time after execution (-infinite by value)',
        ),
        ParamFieldInfo(
            "padding6[28]",
            "Padding 6",
            False,
            pad_field(28),
            '',
        ),
    ],
}
