from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


AI_ATTACK_PARAM_ST = {
    "param_type": "AI_ATTACK_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "attackTableId",
            "Reference ID",
            True,
            int,
            'ID specified by NPC thinking parameters',
        ),
        ParamFieldInfo(
            "attackId",
            "Attack ID",
            True,
            int,
            'Attack number',
        ),
        ParamFieldInfo(
            "successDistance",
            "Success judgment distance",
            True,
            float,
            'For arguments of Common_Attack type subgoals',
        ),
        ParamFieldInfo(
            "turnTimeBeforeAttack",
            "Turn time before attack",
            True,
            float,
            'For arguments of Common_Attack type subgoals',
        ),
        ParamFieldInfo(
            "frontAngleRange",
            "Front judgment angle",
            True,
            int,
            'For arguments of Common_Attack type subgoals',
        ),
        ParamFieldInfo(
            "upAngleThreshold",
            "Upward execution threshold",
            True,
            int,
            'For arguments of Common_Attack type subgoals',
        ),
        ParamFieldInfo(
            "downAngleThershold",
            "Downward execution threshold",
            True,
            int,
            'For arguments of Common_Attack type subgoals',
        ),
        ParamFieldInfo(
            "isFirstAttack",
            "Is it a starting technique?",
            True,
            int,
            'Attacks from the second stage of the combo are �~',
        ),
        ParamFieldInfo(
            "doesSelectOnOutRange",
            "Whether to select outside the proper distance",
            True,
            int,
            'Whether to select when the distance is out of the proper distance',
        ),
        ParamFieldInfo(
            "minOptimalDistance",
            "Minimum proper distance",
            True,
            float,
            'Minimum value of proper attack distance',
        ),
        ParamFieldInfo(
            "maxOptimalDistance",
            "Maximum proper distance",
            True,
            float,
            'Maximum attack suitability distance',
        ),
        ParamFieldInfo(
            "baseDirectionForOptimalAngle1",
            "Appropriate angle reference direction 1",
            True,
            int,
            'Direction that serves as a reference for the proper angle of attack (XZ plane)',
        ),
        ParamFieldInfo(
            "optimalAttackAngleRange1",
            "Appropriate angle reference range 1",
            True,
            int,
            'Range of aptitude angles for attacks',
        ),
        ParamFieldInfo(
            "baseDirectionForOptimalAngle2",
            "Appropriate angle reference direction 2",
            True,
            int,
            'Direction that serves as a reference for attack aptitude accuracy (XZ plane)',
        ),
        ParamFieldInfo(
            "optimalAttackAngleRange2",
            "Appropriate angle reference range 2",
            True,
            int,
            'Range of aptitude angles for attacks',
        ),
        ParamFieldInfo(
            "intervalForExec",
            "Executable interval",
            True,
            float,
            'Time required to attack once and then use it again',
        ),
        ParamFieldInfo(
            "selectionTendency",
            "Selection rate",
            True,
            float,
            'Specify the ease of selection by magnification',
        ),
        ParamFieldInfo(
            "shortRangeTendency",
            "Short range selection rate",
            True,
            float,
            'Selection rate at close range',
        ),
        ParamFieldInfo(
            "middleRangeTendency",
            "Medium range selection rate",
            True,
            float,
            'Selection rate at medium range',
        ),
        ParamFieldInfo(
            "farRangeTendency",
            "Distance selection rate",
            True,
            float,
            'Selection rate at long distances',
        ),
        ParamFieldInfo(
            "outRangeTendency",
            "Out of range rate",
            True,
            float,
            'Selection rate out of range',
        ),
        ParamFieldInfo(
            "deriveAttackId1",
            "Derived attack 1",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId2",
            "Derived attack 2",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId3",
            "Derived attack 3",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId4",
            "Derived attack 4",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId5",
            "Derived attack 5",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId6",
            "Derived attack 6",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId7",
            "Derived attack 7",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId8",
            "Derived attack 8",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId9",
            "Derived attack 9",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId10",
            "Derived attack 10",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId11",
            "Derived attack 11",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId12",
            "Derived attack 12",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId13",
            "Derived attack 13",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId14",
            "Derived attack 14",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId15",
            "Derived attack 15",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "deriveAttackId16",
            "Derived attack 16",
            True,
            int,
            'Derivable attack number',
        ),
        ParamFieldInfo(
            "goalLifeMin",
            "Minimum life of the goal",
            True,
            float,
            'Minimum life of the goal',
        ),
        ParamFieldInfo(
            "goalLifeMax",
            "Maximum life span of the goal",
            True,
            float,
            'Maximum life span of the goal',
        ),
        ParamFieldInfo(
            "doesSelectOnInnerRange",
            "Whether to select within the appropriate distance",
            True,
            int,
            'Whether to select when within the appropriate distance',
        ),
        ParamFieldInfo(
            "enableAttackOnBattleStart",
            "Whether to use it as the first hit",
            True,
            int,
            'Whether to use it as the first hit',
        ),
        ParamFieldInfo(
            "doesSelectOnTargetDown",
            "Whether to select when the target is down",
            True,
            int,
            'Whether to select when the target is down',
        ),
        ParamFieldInfo(
            "pad1[1]",
            "pad",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "minArriveDistance",
            "Minimum reach judgment distance",
            True,
            float,
            'Minimum reach judgment distance',
        ),
        ParamFieldInfo(
            "maxArriveDistance",
            "Maximum reach judgment distance",
            True,
            float,
            'Maximum reach judgment distance',
        ),
        ParamFieldInfo(
            "comboExecDistance",
            "Continuous attack execution distance",
            True,
            float,
            'Distance used to determine the execution of attacks from the second stage onward',
        ),
        ParamFieldInfo(
            "comboExecRange",
            "Continuous attack execution angle",
            True,
            float,
            'Distance used to determine the execution of attacks from the second stage onward',
        ),
    ],
}
