from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


AI_ANIM_TBL_PARAM = {
    "param_type": "AI_ANIM_TBL_PARAM",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "atk0_EzStateId",
            "Attack 1 EzState Anime Number",
            True,
            int,
            'Attack 1 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk1_EzStateId",
            "Attack 2 EzState Anime Number",
            True,
            int,
            'Attack 2 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk2_EzStateId",
            "Attack 3 EzState Anime Number",
            True,
            int,
            'Attack 3 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk3_EzStateId",
            "Attack 4 EzState Anime Number",
            True,
            int,
            'Attack 4 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk4_EzStateId",
            "Attack 5 EzState Anime Number",
            True,
            int,
            'Attack 5 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk5_EzStateId",
            "Attack 6 EzState Anime Number",
            True,
            int,
            'Attack 6 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk6_EzStateId",
            "Attack 7 EzState Anime Number",
            True,
            int,
            'Attack 7 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk7_EzStateId",
            "Attack 8 EzState Anime Number",
            True,
            int,
            'Attack 8 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk8_EzStateId",
            "Attack 9 EzState Anime Number",
            True,
            int,
            'Attack 9 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk9_EzStateId",
            "Attack 10 EzState Anime Number",
            True,
            int,
            'Attack 10 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk10_EzStateId",
            "Attack 11 EzState Anime Number",
            True,
            int,
            'Attack 11 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk11_EzStateId",
            "Attack 12 EzState Anime Number",
            True,
            int,
            'Attack 12 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk12_EzStateId",
            "Attack 13 EzState Anime Number",
            True,
            int,
            'Attack 13 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk13_EzStateId",
            "Attack 14 EzState Anime Number",
            True,
            int,
            'Attack 14 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk14_EzStateId",
            "Attack 15 EzState Anime Number",
            True,
            int,
            'Attack 15 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk15_EzStateId",
            "Attack 16 EzState Anime Number",
            True,
            int,
            'Attack 16 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk16_EzStateId",
            "Attack 17 EzState Anime Number",
            True,
            int,
            'Attack 17 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk17_EzStateId",
            "Attack 18 EzState Anime Number",
            True,
            int,
            'Attack 18 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk18_EzStateId",
            "Attack 19 EzState Anime Number",
            True,
            int,
            'Attack 19 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk19_EzStateId",
            "Attack 20 EzState Anime Number",
            True,
            int,
            'Attack 20 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk20_EzStateId",
            "Attack 21 EzState Anime Number",
            True,
            int,
            'Attack 21 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk21_EzStateId",
            "Attack 22 EzState Anime Number",
            True,
            int,
            'Attack 22 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk22_EzStateId",
            "Attack 23 EzState Anime Number",
            True,
            int,
            'Attack 23 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk23_EzStateId",
            "Attack 24 EzState Anime Number",
            True,
            int,
            'Attack 24 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk24_EzStateId",
            "Attack 25 EzState Anime Number",
            True,
            int,
            'Attack 25 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk25_EzStateId",
            "Attack 26 EzState Anime Number",
            True,
            int,
            'Attack 26 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk26_EzStateId",
            "Attack 27 EzState Anime Number",
            True,
            int,
            'Attack 27 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk27_EzStateId",
            "Attack 28 EzState Anime Number",
            True,
            int,
            'Attack 28 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk28_EzStateId",
            "Attack 29 EzState Anime Number",
            True,
            int,
            'Attack 29 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk29_EzStateId",
            "Attack 30 EzState Anime Number",
            True,
            int,
            'Attack 30 EzState Anime Number',
        ),
        ParamFieldInfo(
            "atk0_MinDist",
            "Minimum distance of attack 1 [cm]",
            True,
            int,
            'Minimum distance of attack 1 [cm]',
        ),
        ParamFieldInfo(
            "atk1_MinDist",
            "Minimum distance of attack 2 [cm]",
            True,
            int,
            'Minimum distance of attack 2 [cm]',
        ),
        ParamFieldInfo(
            "atk2_MinDist",
            "Minimum distance of attack 3 [cm]",
            True,
            int,
            'Minimum distance of attack 3 [cm]',
        ),
        ParamFieldInfo(
            "atk3_MinDist",
            "Minimum distance of attack 4 [cm]",
            True,
            int,
            'Minimum distance of attack 4 [cm]',
        ),
        ParamFieldInfo(
            "atk4_MinDist",
            "Minimum distance of attack 5 [cm]",
            True,
            int,
            'Minimum distance of attack 5 [cm]',
        ),
        ParamFieldInfo(
            "atk5_MinDist",
            "Minimum distance of attack 6 [cm]",
            True,
            int,
            'Minimum distance of attack 6 [cm]',
        ),
        ParamFieldInfo(
            "atk6_MinDist",
            "Minimum distance of attack 7 [cm]",
            True,
            int,
            'Minimum distance of attack 7 [cm]',
        ),
        ParamFieldInfo(
            "atk7_MinDist",
            "Minimum distance of attack 8 [cm]",
            True,
            int,
            'Minimum distance of attack 8 [cm]',
        ),
        ParamFieldInfo(
            "atk8_MinDist",
            "Minimum distance of attack 9 [cm]",
            True,
            int,
            'Minimum distance of attack 9 [cm]',
        ),
        ParamFieldInfo(
            "atk9_MinDist",
            "Minimum distance of attack 10 [cm]",
            True,
            int,
            'Minimum distance of attack 10 [cm]',
        ),
        ParamFieldInfo(
            "atk10_MinDist",
            "Minimum distance of attack 11 [cm]",
            True,
            int,
            'Minimum distance of attack 11 [cm]',
        ),
        ParamFieldInfo(
            "atk11_MinDist",
            "Minimum distance of attack 12 [cm]",
            True,
            int,
            'Minimum distance of attack 12 [cm]',
        ),
        ParamFieldInfo(
            "atk12_MinDist",
            "Minimum distance of attack 13 [cm]",
            True,
            int,
            'Minimum distance of attack 13 [cm]',
        ),
        ParamFieldInfo(
            "atk13_MinDist",
            "Minimum distance of attack 14 [cm]",
            True,
            int,
            'Minimum distance of attack 14 [cm]',
        ),
        ParamFieldInfo(
            "atk14_MinDist",
            "Minimum distance of attack 15 [cm]",
            True,
            int,
            'Minimum distance of attack 15 [cm]',
        ),
        ParamFieldInfo(
            "atk15_MinDist",
            "Minimum distance of attack 16 [cm]",
            True,
            int,
            'Minimum distance of attack 16 [cm]',
        ),
        ParamFieldInfo(
            "atk16_MinDist",
            "Minimum distance of attack 17 [cm]",
            True,
            int,
            'Minimum distance of attack 17 [cm]',
        ),
        ParamFieldInfo(
            "atk17_MinDist",
            "Minimum distance of attack 18 [cm]",
            True,
            int,
            'Minimum distance of attack 18 [cm]',
        ),
        ParamFieldInfo(
            "atk18_MinDist",
            "Minimum distance of attack 19 [cm]",
            True,
            int,
            'Minimum distance of attack 19 [cm]',
        ),
        ParamFieldInfo(
            "atk19_MinDist",
            "Minimum distance of attack 20 [cm]",
            True,
            int,
            'Minimum distance of attack 20 [cm]',
        ),
        ParamFieldInfo(
            "atk20_MinDist",
            "Minimum distance of attack 21 [cm]",
            True,
            int,
            'Minimum distance of attack 21 [cm]',
        ),
        ParamFieldInfo(
            "atk21_MinDist",
            "Minimum distance of attack 22 [cm]",
            True,
            int,
            'Minimum distance of attack 22 [cm]',
        ),
        ParamFieldInfo(
            "atk22_MinDist",
            "Minimum distance of attack 23 [cm]",
            True,
            int,
            'Minimum distance of attack 23 [cm]',
        ),
        ParamFieldInfo(
            "atk23_MinDist",
            "Minimum distance of attack 24 [cm]",
            True,
            int,
            'Minimum distance of attack 24 [cm]',
        ),
        ParamFieldInfo(
            "atk24_MinDist",
            "Minimum distance of attack 25 [cm]",
            True,
            int,
            'Minimum distance of attack 25 [cm]',
        ),
        ParamFieldInfo(
            "atk25_MinDist",
            "Minimum distance of attack 26 [cm]",
            True,
            int,
            'Minimum distance of attack 26 [cm]',
        ),
        ParamFieldInfo(
            "atk26_MinDist",
            "Minimum distance of attack 27 [cm]",
            True,
            int,
            'Minimum distance of attack 27 [cm]',
        ),
        ParamFieldInfo(
            "atk27_MinDist",
            "Minimum distance of attack 28 [cm]",
            True,
            int,
            'Minimum distance of attack 28 [cm]',
        ),
        ParamFieldInfo(
            "atk28_MinDist",
            "Minimum distance of attack 29 [cm]",
            True,
            int,
            'Minimum distance of attack 29 [cm]',
        ),
        ParamFieldInfo(
            "atk29_MinDist",
            "Minimum distance of attack 30 [cm]",
            True,
            int,
            'Minimum distance of attack 30 [cm]',
        ),
        ParamFieldInfo(
            "atk0_MaxDist",
            "Maximum distance of attack 1 [cm]",
            True,
            int,
            'Maximum distance of attack 1 [cm]',
        ),
        ParamFieldInfo(
            "atk1_MaxDist",
            "Maximum distance of attack 2 [cm]",
            True,
            int,
            'Maximum distance of attack 2 [cm]',
        ),
        ParamFieldInfo(
            "atk2_MaxDist",
            "Maximum distance of attack 3 [cm]",
            True,
            int,
            'Maximum distance of attack 3 [cm]',
        ),
        ParamFieldInfo(
            "atk3_MaxDist",
            "Maximum distance of attack 4 [cm]",
            True,
            int,
            'Maximum distance of attack 4 [cm]',
        ),
        ParamFieldInfo(
            "atk4_MaxDist",
            "Maximum distance of attack 5 [cm]",
            True,
            int,
            'Maximum distance of attack 5 [cm]',
        ),
        ParamFieldInfo(
            "atk5_MaxDist",
            "Maximum distance of attack 6 [cm]",
            True,
            int,
            'Maximum distance of attack 6 [cm]',
        ),
        ParamFieldInfo(
            "atk6_MaxDist",
            "Maximum distance of attack 7 [cm]",
            True,
            int,
            'Maximum distance of attack 7 [cm]',
        ),
        ParamFieldInfo(
            "atk7_MaxDist",
            "Maximum distance of attack 8 [cm]",
            True,
            int,
            'Maximum distance of attack 8 [cm]',
        ),
        ParamFieldInfo(
            "atk8_MaxDist",
            "Maximum distance of attack 9 [cm]",
            True,
            int,
            'Maximum distance of attack 9 [cm]',
        ),
        ParamFieldInfo(
            "atk9_MaxDist",
            "Maximum distance of attack 10 [cm]",
            True,
            int,
            'Maximum distance of attack 10 [cm]',
        ),
        ParamFieldInfo(
            "atk10_MaxDist",
            "Maximum distance of attack 11 [cm]",
            True,
            int,
            'Maximum distance of attack 11 [cm]',
        ),
        ParamFieldInfo(
            "atk11_MaxDist",
            "Maximum distance of attack 12 [cm]",
            True,
            int,
            'Maximum distance of attack 12 [cm]',
        ),
        ParamFieldInfo(
            "atk12_MaxDist",
            "Maximum distance of attack 13 [cm]",
            True,
            int,
            'Maximum distance of attack 13 [cm]',
        ),
        ParamFieldInfo(
            "atk13_MaxDist",
            "Maximum distance of attack 14 [cm]",
            True,
            int,
            'Maximum distance of attack 14 [cm]',
        ),
        ParamFieldInfo(
            "atk14_MaxDist",
            "Maximum distance of attack 15 [cm]",
            True,
            int,
            'Maximum distance of attack 15 [cm]',
        ),
        ParamFieldInfo(
            "atk15_MaxDist",
            "Maximum distance of attack 16 [cm]",
            True,
            int,
            'Maximum distance of attack 16 [cm]',
        ),
        ParamFieldInfo(
            "atk16_MaxDist",
            "Maximum distance of attack 17 [cm]",
            True,
            int,
            'Maximum distance of attack 17 [cm]',
        ),
        ParamFieldInfo(
            "atk17_MaxDist",
            "Maximum distance of attack 18 [cm]",
            True,
            int,
            'Maximum distance of attack 18 [cm]',
        ),
        ParamFieldInfo(
            "atk18_MaxDist",
            "Maximum distance of attack 19 [cm]",
            True,
            int,
            'Maximum distance of attack 19 [cm]',
        ),
        ParamFieldInfo(
            "atk19_MaxDist",
            "Maximum distance of attack 20 [cm]",
            True,
            int,
            'Maximum distance of attack 20 [cm]',
        ),
        ParamFieldInfo(
            "atk20_MaxDist",
            "Maximum distance of attack 21 [cm]",
            True,
            int,
            'Maximum distance of attack 21 [cm]',
        ),
        ParamFieldInfo(
            "atk21_MaxDist",
            "Maximum distance of attack 22 [cm]",
            True,
            int,
            'Maximum distance of attack 22 [cm]',
        ),
        ParamFieldInfo(
            "atk22_MaxDist",
            "Maximum distance of attack 23 [cm]",
            True,
            int,
            'Maximum distance of attack 23 [cm]',
        ),
        ParamFieldInfo(
            "atk23_MaxDist",
            "Maximum distance of attack 24 [cm]",
            True,
            int,
            'Maximum distance of attack 24 [cm]',
        ),
        ParamFieldInfo(
            "atk24_MaxDist",
            "Maximum distance of attack 25 [cm]",
            True,
            int,
            'Maximum distance of attack 25 [cm]',
        ),
        ParamFieldInfo(
            "atk25_MaxDist",
            "Maximum distance of attack 26 [cm]",
            True,
            int,
            'Maximum distance of attack 26 [cm]',
        ),
        ParamFieldInfo(
            "atk26_MaxDist",
            "Maximum distance of attack 27 [cm]",
            True,
            int,
            'Maximum distance of attack 27 [cm]',
        ),
        ParamFieldInfo(
            "atk27_MaxDist",
            "Maximum distance of attack 28 [cm]",
            True,
            int,
            'Maximum distance of attack 28 [cm]',
        ),
        ParamFieldInfo(
            "atk28_MaxDist",
            "Maximum distance of attack 29 [cm]",
            True,
            int,
            'Maximum distance of attack 29 [cm]',
        ),
        ParamFieldInfo(
            "atk29_MaxDist",
            "Maximum distance of attack 30 [cm]",
            True,
            int,
            'Maximum distance of attack 30 [cm]',
        ),
        ParamFieldInfo(
            "atk0_AtkDistType:4",
            "Attack success distance type of attack 1",
            True,
            int,
            'Attack success distance type of attack 1',
        ),
        ParamFieldInfo(
            "atk1_AtkDistType:4",
            "Attack success distance type of attack 2",
            True,
            int,
            'Attack success distance type of attack 2',
        ),
        ParamFieldInfo(
            "atk2_AtkDistType:4",
            "Attack success distance type of attack 3",
            True,
            int,
            'Attack success distance type of attack 3',
        ),
        ParamFieldInfo(
            "atk3_AtkDistType:4",
            "Attack success distance type of attack 4",
            True,
            int,
            'Attack success distance type of attack 4',
        ),
        ParamFieldInfo(
            "atk4_AtkDistType:4",
            "Attack success distance type of attack 5",
            True,
            int,
            'Attack success distance type of attack 5',
        ),
        ParamFieldInfo(
            "atk5_AtkDistType:4",
            "Attack success distance type of attack 6",
            True,
            int,
            'Attack success distance type of attack 6',
        ),
        ParamFieldInfo(
            "atk6_AtkDistType:4",
            "Attack success distance type of attack 7",
            True,
            int,
            'Attack success distance type of attack 7',
        ),
        ParamFieldInfo(
            "atk7_AtkDistType:4",
            "Attack success distance type of attack 8",
            True,
            int,
            'Attack success distance type of attack 8',
        ),
        ParamFieldInfo(
            "atk8_AtkDistType:4",
            "Attack 9 success distance type",
            True,
            int,
            'Attack 9 success distance type',
        ),
        ParamFieldInfo(
            "atk9_AtkDistType:4",
            "Attack 10 attack success distance type",
            True,
            int,
            'Attack 10 attack success distance type',
        ),
        ParamFieldInfo(
            "atk10_AtkDistType:4",
            "Attack 11 attack success distance type",
            True,
            int,
            'Attack 11 attack success distance type',
        ),
        ParamFieldInfo(
            "atk11_AtkDistType:4",
            "Attack 12 attack success distance type",
            True,
            int,
            'Attack 12 attack success distance type',
        ),
        ParamFieldInfo(
            "atk12_AtkDistType:4",
            "Attack 13 attack success distance type",
            True,
            int,
            'Attack 13 attack success distance type',
        ),
        ParamFieldInfo(
            "atk13_AtkDistType:4",
            "Attack success distance type of attack 14",
            True,
            int,
            'Attack success distance type of attack 14',
        ),
        ParamFieldInfo(
            "atk14_AtkDistType:4",
            "Attack 15 attack success distance type",
            True,
            int,
            'Attack 15 attack success distance type',
        ),
        ParamFieldInfo(
            "atk15_AtkDistType:4",
            "Attack 16 attack success distance type",
            True,
            int,
            'Attack 16 attack success distance type',
        ),
        ParamFieldInfo(
            "atk16_AtkDistType:4",
            "Attack 17 attack success distance type",
            True,
            int,
            'Attack 17 attack success distance type',
        ),
        ParamFieldInfo(
            "atk17_AtkDistType:4",
            "Attack 18 attack success distance type",
            True,
            int,
            'Attack 18 attack success distance type',
        ),
        ParamFieldInfo(
            "atk18_AtkDistType:4",
            "Attack 19 attack success distance type",
            True,
            int,
            'Attack 19 attack success distance type',
        ),
        ParamFieldInfo(
            "atk19_AtkDistType:4",
            "Attack 20 attack success distance type",
            True,
            int,
            'Attack 20 attack success distance type',
        ),
        ParamFieldInfo(
            "atk20_AtkDistType:4",
            "Attack success distance type of attack 21",
            True,
            int,
            'Attack success distance type of attack 21',
        ),
        ParamFieldInfo(
            "atk21_AtkDistType:4",
            "Attack 22 attack success distance type",
            True,
            int,
            'Attack 22 attack success distance type',
        ),
        ParamFieldInfo(
            "atk22_AtkDistType:4",
            "Attack success distance type of attack 23",
            True,
            int,
            'Attack 23 attack success distance type',
        ),
        ParamFieldInfo(
            "atk23_AtkDistType:4",
            "Attack success distance type of attack 24",
            True,
            int,
            'Attack success distance type of attack 24',
        ),
        ParamFieldInfo(
            "atk24_AtkDistType:4",
            "Attack 25 attack success distance type",
            True,
            int,
            'Attack 25 attack success distance type',
        ),
        ParamFieldInfo(
            "atk25_AtkDistType:4",
            "Attack 26 attack success distance type",
            True,
            int,
            'Attack 26 attack success distance type',
        ),
        ParamFieldInfo(
            "atk26_AtkDistType:4",
            "Attack 27 attack success distance type",
            True,
            int,
            'Attack 27 attack success distance type',
        ),
        ParamFieldInfo(
            "atk27_AtkDistType:4",
            "Attack 28 attack success distance type",
            True,
            int,
            'Attack 28 attack success distance type',
        ),
        ParamFieldInfo(
            "atk28_AtkDistType:4",
            "Attack 29 attack success distance type",
            True,
            int,
            'Attack 29 attack success distance type',
        ),
        ParamFieldInfo(
            "atk29_AtkDistType:4",
            "Attack success distance type of attack 30",
            True,
            int,
            'Attack success distance type of attack 30',
        ),
        ParamFieldInfo(
            "pad0[13]",
            "pad",
            False,
            pad_field(13),
            'pad',
        ),
    ],
}
