from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


AI_ODDS_PARAM = {
    "param_type": "AI_ODDS_PARAM",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "act0",
            "Action 0",
            True,
            int,
            'Action 0 ratio',
        ),
        ParamFieldInfo(
            "act1",
            "Action 1",
            True,
            int,
            'Action 1 ratio',
        ),
        ParamFieldInfo(
            "act2",
            "Action 2",
            True,
            int,
            'Action 2 ratio',
        ),
        ParamFieldInfo(
            "act3",
            "Action 3",
            True,
            int,
            'Action 3 ratio',
        ),
        ParamFieldInfo(
            "act4",
            "Action 4",
            True,
            int,
            'Action 4 ratio',
        ),
        ParamFieldInfo(
            "act5",
            "Action 5",
            True,
            int,
            'Action 5 ratio',
        ),
        ParamFieldInfo(
            "act6",
            "Action 6",
            True,
            int,
            'Action 6 ratio',
        ),
        ParamFieldInfo(
            "act7",
            "Action 7",
            True,
            int,
            'Action 7 ratio',
        ),
        ParamFieldInfo(
            "act8",
            "Action 8",
            True,
            int,
            'Action 8 ratio',
        ),
        ParamFieldInfo(
            "act9",
            "Action 9",
            True,
            int,
            'Action 9 ratio',
        ),
        ParamFieldInfo(
            "act10",
            "Action 10",
            True,
            int,
            'Action 10 ratio',
        ),
        ParamFieldInfo(
            "act11",
            "Action 11",
            True,
            int,
            'Action 11 ratio',
        ),
        ParamFieldInfo(
            "act12",
            "Action 12",
            True,
            int,
            'Action 12 ratio',
        ),
        ParamFieldInfo(
            "act13",
            "Action 13",
            True,
            int,
            'Action 13 ratio',
        ),
        ParamFieldInfo(
            "act14",
            "Action 14",
            True,
            int,
            'Action 14 ratio',
        ),
        ParamFieldInfo(
            "act15",
            "Action 15",
            True,
            int,
            'Action 15 ratio',
        ),
        ParamFieldInfo(
            "act16",
            "Action 16",
            True,
            int,
            'Action 16 ratio',
        ),
        ParamFieldInfo(
            "act17",
            "Action 17",
            True,
            int,
            'Action 17 ratio',
        ),
        ParamFieldInfo(
            "act18",
            "Action 18",
            True,
            int,
            'Action 18 ratio',
        ),
        ParamFieldInfo(
            "act19",
            "Action 19",
            True,
            int,
            'Action 19 ratio',
        ),
        ParamFieldInfo(
            "act20",
            "Action 20",
            True,
            int,
            'Action 20 ratio',
        ),
        ParamFieldInfo(
            "act21",
            "Action 21",
            True,
            int,
            'Action 21 ratio',
        ),
        ParamFieldInfo(
            "act22",
            "Action 22",
            True,
            int,
            'Action 22 ratio',
        ),
        ParamFieldInfo(
            "act23",
            "Action 23",
            True,
            int,
            'Action 23 ratio',
        ),
        ParamFieldInfo(
            "act24",
            "Action 24",
            True,
            int,
            'Action 24 ratio',
        ),
        ParamFieldInfo(
            "act25",
            "Action 25",
            True,
            int,
            'Action 25 ratio',
        ),
        ParamFieldInfo(
            "act26",
            "Action 26",
            True,
            int,
            'Action 26 ratio',
        ),
        ParamFieldInfo(
            "act27",
            "Action 27",
            True,
            int,
            'Action 27 ratio',
        ),
        ParamFieldInfo(
            "act28",
            "Action 28",
            True,
            int,
            'Action 28 ratio',
        ),
        ParamFieldInfo(
            "act29",
            "Action 29",
            True,
            int,
            'Action 29 ratio',
        ),
        ParamFieldInfo(
            "act30",
            "Action 30",
            True,
            int,
            'Action 30 ratio',
        ),
        ParamFieldInfo(
            "act31",
            "Action 31",
            True,
            int,
            'Action 31 ratio',
        ),
        ParamFieldInfo(
            "act32",
            "Action 32",
            True,
            int,
            'Action 32 ratio',
        ),
        ParamFieldInfo(
            "act33",
            "Action 33",
            True,
            int,
            'Action 33 ratio',
        ),
        ParamFieldInfo(
            "act34",
            "Action 34",
            True,
            int,
            'Action 34 ratio',
        ),
        ParamFieldInfo(
            "act35",
            "Action 35",
            True,
            int,
            'Action 35 ratio',
        ),
        ParamFieldInfo(
            "act36",
            "Action 36",
            True,
            int,
            'Action 36 ratio',
        ),
        ParamFieldInfo(
            "act37",
            "Action 37",
            True,
            int,
            'Action 37 ratio',
        ),
        ParamFieldInfo(
            "act38",
            "Action 38",
            True,
            int,
            'Action 38 ratio',
        ),
        ParamFieldInfo(
            "act39",
            "Action 39",
            True,
            int,
            'Action 39 ratio',
        ),
        ParamFieldInfo(
            "act40",
            "Action 40",
            True,
            int,
            'Action 40 ratio',
        ),
        ParamFieldInfo(
            "act41",
            "Action 41",
            True,
            int,
            'Action 41 ratio',
        ),
        ParamFieldInfo(
            "act42",
            "Action 42",
            True,
            int,
            'Action 42 ratio',
        ),
        ParamFieldInfo(
            "act43",
            "Action 43",
            True,
            int,
            'Action 43 ratio',
        ),
        ParamFieldInfo(
            "act44",
            "Action 44",
            True,
            int,
            'Action 44 ratio',
        ),
        ParamFieldInfo(
            "act45",
            "Action 45",
            True,
            int,
            'Action 45 ratio',
        ),
        ParamFieldInfo(
            "act46",
            "Action 46",
            True,
            int,
            'Action 46 ratio',
        ),
        ParamFieldInfo(
            "act47",
            "Action 47",
            True,
            int,
            'Action 47 ratio',
        ),
        ParamFieldInfo(
            "act48",
            "Action 48",
            True,
            int,
            'Action 48 ratio',
        ),
        ParamFieldInfo(
            "act49",
            "Action 49",
            True,
            int,
            'Action 49 ratio',
        ),
        ParamFieldInfo(
            "act50",
            "Action 50",
            True,
            int,
            'Action 50 ratio',
        ),
        ParamFieldInfo(
            "act51",
            "Action 51",
            True,
            int,
            'Action 51 ratio',
        ),
        ParamFieldInfo(
            "act52",
            "Action 52",
            True,
            int,
            'Action 52 ratio',
        ),
        ParamFieldInfo(
            "act53",
            "Action 53",
            True,
            int,
            'Action 53 ratio',
        ),
        ParamFieldInfo(
            "act54",
            "Action 54",
            True,
            int,
            'Action 54 ratio',
        ),
        ParamFieldInfo(
            "act55",
            "Action 55",
            True,
            int,
            'Action 55 ratio',
        ),
        ParamFieldInfo(
            "act56",
            "Action 56",
            True,
            int,
            'Action 56 ratio',
        ),
        ParamFieldInfo(
            "act57",
            "Action 57",
            True,
            int,
            'Action 57 ratio',
        ),
        ParamFieldInfo(
            "act58",
            "Action 58",
            True,
            int,
            'Action 58 ratio',
        ),
        ParamFieldInfo(
            "act59",
            "Action 59",
            True,
            int,
            'Action 59 ratio',
        ),
        ParamFieldInfo(
            "act60",
            "Action 60",
            True,
            int,
            'Action 60 ratio',
        ),
        ParamFieldInfo(
            "act61",
            "Action 61",
            True,
            int,
            'Action 61 ratio',
        ),
        ParamFieldInfo(
            "act62",
            "Action 62",
            True,
            int,
            'Action 62 ratio',
        ),
        ParamFieldInfo(
            "act63",
            "Action 63",
            True,
            int,
            'Action 63 ratio',
        ),
        ParamFieldInfo(
            "act64",
            "Action 64",
            True,
            int,
            'Action 64 ratio',
        ),
        ParamFieldInfo(
            "act65",
            "Action 65",
            True,
            int,
            'Action 65 ratio',
        ),
        ParamFieldInfo(
            "act66",
            "Action 66",
            True,
            int,
            'Action 66 ratio',
        ),
        ParamFieldInfo(
            "act67",
            "Action 67",
            True,
            int,
            'Action 67 ratio',
        ),
        ParamFieldInfo(
            "act68",
            "Action 68",
            True,
            int,
            'Action 68 ratio',
        ),
        ParamFieldInfo(
            "act69",
            "Action 69",
            True,
            int,
            'Action 69 ratio',
        ),
        ParamFieldInfo(
            "act70",
            "Action 70",
            True,
            int,
            'Action 70 ratio',
        ),
        ParamFieldInfo(
            "act71",
            "Action 71",
            True,
            int,
            'Action 71 ratio',
        ),
        ParamFieldInfo(
            "act72",
            "Action 72",
            True,
            int,
            'Action 72 ratio',
        ),
        ParamFieldInfo(
            "act73",
            "Action 73",
            True,
            int,
            'Action 73 ratio',
        ),
        ParamFieldInfo(
            "act74",
            "Action 74",
            True,
            int,
            'Action 74 ratio',
        ),
        ParamFieldInfo(
            "act75",
            "Action 75",
            True,
            int,
            'Action 75 ratio',
        ),
        ParamFieldInfo(
            "act76",
            "Action 76",
            True,
            int,
            'Action 76 ratio',
        ),
        ParamFieldInfo(
            "act77",
            "Action 77",
            True,
            int,
            'Action 77 ratio',
        ),
        ParamFieldInfo(
            "act78",
            "Action 78",
            True,
            int,
            'Action 78 ratio',
        ),
        ParamFieldInfo(
            "act79",
            "Action 79",
            True,
            int,
            'Action 79 ratio',
        ),
        ParamFieldInfo(
            "act80",
            "Action 80",
            True,
            int,
            'Action 80 ratio',
        ),
        ParamFieldInfo(
            "act81",
            "Action 81",
            True,
            int,
            'Action 81 ratio',
        ),
        ParamFieldInfo(
            "act82",
            "Action 82",
            True,
            int,
            'Action 82 ratio',
        ),
        ParamFieldInfo(
            "act83",
            "Action 83",
            True,
            int,
            'Action 83 ratio',
        ),
        ParamFieldInfo(
            "act84",
            "Action 84",
            True,
            int,
            'Action 84 ratio',
        ),
        ParamFieldInfo(
            "act85",
            "Action 85",
            True,
            int,
            'Action 85 ratio',
        ),
        ParamFieldInfo(
            "act86",
            "Action 86",
            True,
            int,
            'Action 86 ratio',
        ),
        ParamFieldInfo(
            "act87",
            "Action 87",
            True,
            int,
            'Action 87 ratio',
        ),
        ParamFieldInfo(
            "act88",
            "Action 88",
            True,
            int,
            'Action 88 ratio',
        ),
        ParamFieldInfo(
            "act89",
            "Action 89",
            True,
            int,
            'Action 89 ratio',
        ),
        ParamFieldInfo(
            "act90",
            "Action 90",
            True,
            int,
            'Action 90 ratio',
        ),
        ParamFieldInfo(
            "act91",
            "Action 91",
            True,
            int,
            'Action 91 ratio',
        ),
        ParamFieldInfo(
            "act92",
            "Action 92",
            True,
            int,
            'Action 92 ratio',
        ),
        ParamFieldInfo(
            "act93",
            "Action 93",
            True,
            int,
            'Action 93 ratio',
        ),
        ParamFieldInfo(
            "act94",
            "Action 94",
            True,
            int,
            'Action 94 ratio',
        ),
        ParamFieldInfo(
            "act95",
            "Action 95",
            True,
            int,
            'Action 95 ratio',
        ),
        ParamFieldInfo(
            "act96",
            "Action 96",
            True,
            int,
            'Action 96 ratio',
        ),
        ParamFieldInfo(
            "act97",
            "Action 97",
            True,
            int,
            'Action 97 ratio',
        ),
        ParamFieldInfo(
            "act98",
            "Action 98",
            True,
            int,
            'Action 98 ratio',
        ),
        ParamFieldInfo(
            "act99",
            "Action 99",
            True,
            int,
            'Action 99 ratio',
        ),
        ParamFieldInfo(
            "pad0[12]",
            "pad",
            False,
            pad_field(12),
            'pad',
        ),
    ],
}
