from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


ASSET_MATERIAL_SFX_PARAM_ST = {
    "param_type": "ASSET_MATERIAL_SFX_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "sfxId_00",
            "SFX ID [00]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_01",
            "SFX ID [01]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_02",
            "SFX ID [02]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_03",
            "SFX ID [03]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_04",
            "SFX ID [04]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_05",
            "SFX ID [05]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_06",
            "SFX ID [06]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_07",
            "SFX ID [07]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_08",
            "SFX ID [08]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_09",
            "SFX ID [09]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_10",
            "SFX ID [10]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_11",
            "SFX ID [11]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_12",
            "SFX ID [12]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_13",
            "SFX ID [13]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_14",
            "SFX ID [14]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_15",
            "SFX ID [15]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_16",
            "SFX ID [16]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_17",
            "SFX ID [17]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_18",
            "SFX ID [18]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_19",
            "SFX ID [19]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_20",
            "SFX ID [20]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_21",
            "SFX ID [21]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_22",
            "SFX ID [22]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_23",
            "SFX ID [23]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_24",
            "SFX ID [24]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_25",
            "SFX ID [25]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_26",
            "SFX ID [26]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_27",
            "SFX ID [27]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_28",
            "SFX ID [28]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_29",
            "SFX ID [29]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_30",
            "SFX ID [30]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_31",
            "SFX ID [31]",
            True,
            int,
            'SFX identifier corresponding to the asset parameter "SFX identifier after destruction"',
        ),
    ],
}
