from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


BUDDY_PARAM_ST = {
    "param_type": "BUDDY_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "triggerSpEffectId",
            "Trigger SpEffect ID",
            True,
            int,
            'Set the special effect ID that will be the summoning condition',
        ),
        ParamFieldInfo(
            "npcParamId",
            "NPC Param ID",
            True,
            int,
            'Set the NPC parameter ID of the summoned buddy',
        ),
        ParamFieldInfo(
            "npcThinkParamId",
            "NPC Think Param ID",
            True,
            int,
            'Sets the NPC Thinking Parameter ID of the summoned buddy',
        ),
        ParamFieldInfo(
            "npcParamId_ridden",
            "NPC Param ID - Ride",
            True,
            int,
            'For buddies that you want to summon while riding, set the NPC parameter ID for the "rider"',
        ),
        ParamFieldInfo(
            "npcThinkParamId_ridden",
            "NPC Think Param ID - Ride",
            True,
            int,
            'For buddies that you want to summon while riding, set the NPC Thinking Parameter ID for the "rider"',
        ),
        ParamFieldInfo(
            "x_offset",
            "Spawn Offset: X",
            True,
            float,
            'Sets the distance in meters to offset the buddy from the summon point to the X coordinate',
        ),
        ParamFieldInfo(
            "z_offset",
            "Spawn Offset: Z",
            True,
            float,
            'Sets the distance in meters that offsets the buddy from the summon point to the Z coordinate.',
        ),
        ParamFieldInfo(
            "y_angle",
            "Spawn Angle: Y",
            True,
            float,
            'Set the angle to rotate yourself around the Y axis',
        ),
        ParamFieldInfo(
            "appearOnAroundSekihi",
            "Appear near Stone Monument",
            True,
            int,
            'Will it emerge from around the stone monument?',
        ),
        ParamFieldInfo(
            "disablePCTargetShare",
            "Disable Player Target Share",
            True,
            int,
            'Do you want to skip target sharing with your PC?',
        ),
        ParamFieldInfo(
            "pcFollowType",
            "Player Follow Type",
            True,
            int,
            'PC tracking & warp type',
        ),
        ParamFieldInfo(
            "Reserve[1]",
            "Reserve",
            False,
            pad_field(1),
            'Reserve',
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv0",
            "Reinforcement SpEffect: +0",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv1",
            "Reinforcement SpEffect: +1",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv2",
            "Reinforcement SpEffect: +2",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv3",
            "Reinforcement SpEffect: +3",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv4",
            "Reinforcement SpEffect: +4",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv5",
            "Reinforcement SpEffect: +5",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv6",
            "Reinforcement SpEffect: +6",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv7",
            "Reinforcement SpEffect: +7",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv8",
            "Reinforcement SpEffect: +8",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv9",
            "Reinforcement SpEffect: +9",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "dopingSpEffect_lv10",
            "Reinforcement SpEffect: +10",
            True,
            int,
            "+0 o'clock doping special effect",
        ),
        ParamFieldInfo(
            "npcPlayerInitParamId",
            "Character Init ID",
            True,
            int,
            'Initial parameter ID by architype',
        ),
        ParamFieldInfo(
            "generateAnimId",
            "Generate Anim ID",
            True,
            int,
            'Generate Anime ID',
        ),
        ParamFieldInfo(
            "Reserve2[4]",
            "Reserve 2",
            False,
            pad_field(4),
            'Reserve 2',
        ),
    ],
}
