from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


BUDGET_PARAM_ST = {
    "param_type": "BUDGET_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "vram_all",
            "VRAM: ALL",
            True,
            float,
            'VRAM: ALL (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_mapobj_tex",
            "VRAM: Map / Object Texture",
            True,
            float,
            'VRAM: Map / Object Texture (Unit: MB)',
        ),
        ParamFieldInfo(
            "vram_mapobj_mdl",
            "VRAM: Map / Object Model",
            True,
            float,
            'VRAM: Map / object model (in MB)',
        ),
        ParamFieldInfo(
            "vram_map",
            "VRAM: map",
            True,
            float,
            'VRAM: Map (in MB)',
        ),
        ParamFieldInfo(
            "vram_chr",
            "VRAM: Character",
            True,
            float,
            'VRAM: Character (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_parts",
            "VRAM: Parts",
            True,
            float,
            'VRAM: Parts (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_sfx",
            "VRAM: SFX",
            True,
            float,
            'VRAM: SFX (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_chr_tex",
            "VRAM: Character texture",
            True,
            float,
            'VRAM: Character texture (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_chr_mdl",
            "VRAM: Character model",
            True,
            float,
            'VRAM: Character model (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_parts_tex",
            "VRAM: Parts texture",
            True,
            float,
            'VRAM: Parts texture (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_parts_mdl",
            "VRAM: Parts model",
            True,
            float,
            'VRAM: Parts model (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_sfx_tex",
            "VRAM: SFX texture",
            True,
            float,
            'VRAM: SFX texture (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_sfx_mdl",
            "VRAM: SFX model",
            True,
            float,
            'VRAM: SFX model (in MB)',
        ),
        ParamFieldInfo(
            "vram_gi",
            "VRAM: Gi",
            True,
            float,
            'VRAM: Gi (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_menu_tex",
            "VRAM: Menu",
            True,
            float,
            'VRAM: Menu (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_decal_rt",
            "VRAM: DECAL_RT",
            True,
            float,
            'VRAM: DECAL render target (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_decal",
            "VRAM: DECAL",
            True,
            float,
            'VRAM: DECAL (unit is MB)',
        ),
        ParamFieldInfo(
            "reserve_0[4]",
            "Reserved area",
            False,
            pad_field(4),
            '',
        ),
        ParamFieldInfo(
            "vram_other_tex",
            "VRAM: Other textures",
            True,
            float,
            'VRAM: Other models (in MB)',
        ),
        ParamFieldInfo(
            "vram_other_mdl",
            "VRAM: Other models",
            True,
            float,
            'VRAM: Other textures (in MB)',
        ),
        ParamFieldInfo(
            "havok_anim",
            "HAVOK: Anime",
            True,
            float,
            'HAVOK: Animation (unit is MB)',
        ),
        ParamFieldInfo(
            "havok_ins",
            "HAVOK: Placement",
            True,
            float,
            'HAVOK: Placement (unit is MB)',
        ),
        ParamFieldInfo(
            "havok_hit",
            "HAVOK: Hit",
            True,
            float,
            'HAVOK: Hit (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_other",
            "VRAM: Other",
            True,
            float,
            'VRAM: Other (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_detail_all",
            "VRAM: Total Value",
            True,
            float,
            'VRAM: Total value (unit is MB)',
        ),
        ParamFieldInfo(
            "vram_chr_and_parts",
            "VRAM: Characters and Parts",
            True,
            float,
            'VRAM: Total value of characters and parts (unit is MB)',
        ),
        ParamFieldInfo(
            "havok_navimesh",
            "HAVOK: Navimesh",
            True,
            float,
            'HAVOK: Navimesh (unit is MB)',
        ),
        ParamFieldInfo(
            "reserve_1[24]",
            "Reserved area",
            False,
            pad_field(24),
            'Reserved area',
        ),
    ],
}
