from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


CACL_CORRECT_GRAPH_ST = {
    "param_type": "CACL_CORRECT_GRAPH_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "stageMaxVal0",
            "Threshold Point [0]",
            True,
            float,
            'Those with "nth threshold [point]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxVal1",
            "Threshold Point [1]",
            True,
            float,
            'Those with "nth threshold [point]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxVal2",
            "Threshold Point [2]",
            True,
            float,
            'Those with "nth threshold [point]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxVal3",
            "Threshold Point [3]",
            True,
            float,
            'Those with "nth threshold [point]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxVal4",
            "Threshold Point [4]",
            True,
            float,
            'Those with "nth threshold [point]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxGrowVal0",
            "Threshold Coefficient [0]",
            True,
            float,
            'Those with "nth threshold [coefficient]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxGrowVal1",
            "Threshold Coefficient [1]",
            True,
            float,
            'Those with "nth threshold [coefficient]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxGrowVal2",
            "Threshold Coefficient [2]",
            True,
            float,
            'Those with "nth threshold [coefficient]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxGrowVal3",
            "Threshold Coefficient [3]",
            True,
            float,
            'Those with "nth threshold [coefficient]" written in the specifications',
        ),
        ParamFieldInfo(
            "stageMaxGrowVal4",
            "Threshold Coefficient [4]",
            True,
            float,
            'Those with "nth threshold [coefficient]" written in the specifications',
        ),
        ParamFieldInfo(
            "adjPt_maxGrowVal0",
            "Adjustment Factor [0]",
            True,
            float,
            'Adjustment factor',
        ),
        ParamFieldInfo(
            "adjPt_maxGrowVal1",
            "Adjustment Factor [1]",
            True,
            float,
            'Adjustment factor',
        ),
        ParamFieldInfo(
            "adjPt_maxGrowVal2",
            "Adjustment Factor [2]",
            True,
            float,
            'Adjustment factor',
        ),
        ParamFieldInfo(
            "adjPt_maxGrowVal3",
            "Adjustment Factor [3]",
            True,
            float,
            'Adjustment factor',
        ),
        ParamFieldInfo(
            "adjPt_maxGrowVal4",
            "Adjustment Factor [4]",
            True,
            float,
            'Adjustment factor',
        ),
        ParamFieldInfo(
            "init_inclination_soul",
            "Leveling Cost - Initial Cost",
            True,
            float,
            'Growth Soul Slope of the early graph ��1',
        ),
        ParamFieldInfo(
            "adjustment_value",
            "Leveling Cost - Initial Offset",
            True,
            float,
            'Growth soul Early soul adjustment ��2',
        ),
        ParamFieldInfo(
            "boundry_inclination_soul",
            "Leveling Cost - Cost Increase",
            True,
            float,
            'Affects the slope of the graph after the growth soul threshold ��3',
        ),
        ParamFieldInfo(
            "boundry_value",
            "Leveling Cost - Increase Interval",
            True,
            float,
            'Growth soul threshold t',
        ),
        ParamFieldInfo(
            "pad[4]",
            "Padding",
            False,
            pad_field(4),
            '',
        ),
    ],
}
