from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


CHARACTER_INIT_PARAM = {
    "param_type": "CHARACTER_INIT_PARAM",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "baseRec_mp",
            "Base FP Recovery Time",
            True,
            float,
            'Time until MP recovers 1 point (first decimal place)',
        ),
        ParamFieldInfo(
            "baseRec_sp",
            "Base Stamina Recovery Time",
            True,
            float,
            'Time to recover 1 point of stamina (first decimal place)',
        ),
        ParamFieldInfo(
            "red_Falldam",
            "Characer Head Land - Damage Reduction",
            True,
            float,
            'Damage reduction amount (%) that can be a cushion when scolded by another character from above (first decimal place)',
        ),
        ParamFieldInfo(
            "soul",
            "Runes",
            True,
            int,
            'The amount of soul you have at the beginning',
        ),
        ParamFieldInfo(
            "equip_Wep_Right",
            "Equipped Weapon: Right Primary",
            True,
            int,
            'Weapon ID of equipment parameter (right hand slot 1)',
        ),
        ParamFieldInfo(
            "equip_Subwep_Right",
            "Equipped Weapon: Right Secondary",
            True,
            int,
            'Weapon ID of equipment parameter (right hand slot 2)',
        ),
        ParamFieldInfo(
            "equip_Wep_Left",
            "Equipped Weapon: Left Primary",
            True,
            int,
            'Weapon ID of equipment parameter (left hand slot 1)',
        ),
        ParamFieldInfo(
            "equip_Subwep_Left",
            "Equipped Weapon: Left Secondary",
            True,
            int,
            'Weapon ID of equipment parameter (left hand slot 2)',
        ),
        ParamFieldInfo(
            "equip_Helm",
            "Equipped Armor: Head",
            True,
            int,
            'Equipment parameter armor ID (head armor)',
        ),
        ParamFieldInfo(
            "equip_Armer",
            "Equipped Armor: Chest",
            True,
            int,
            'Equipment parameter armor ID (torso armor)',
        ),
        ParamFieldInfo(
            "equip_Gaunt",
            "Equipped Armor: Arms",
            True,
            int,
            'Equipment parameter armor ID (arm armor)',
        ),
        ParamFieldInfo(
            "equip_Leg",
            "Equipped Armor: Legs",
            True,
            int,
            'Equipment parameter armor ID (leg armor)',
        ),
        ParamFieldInfo(
            "equip_Arrow",
            "Equipped Ammunition: Arrow Primary",
            True,
            int,
            'Weapon ID (arrow) of equipment parameter',
        ),
        ParamFieldInfo(
            "equip_Bolt",
            "Equipped Ammunition: Bolt Primary",
            True,
            int,
            'Weapon ID (bolt) of equipment parameter',
        ),
        ParamFieldInfo(
            "equip_SubArrow",
            "Equipped Ammunition: Arrow Secondary",
            True,
            int,
            'Weapon ID of equipment parameter (arrow reserve)',
        ),
        ParamFieldInfo(
            "equip_SubBolt",
            "Equipped Ammunition: Bolt Secondary",
            True,
            int,
            'Weapon ID of equipment parameter (spare bolt)',
        ),
        ParamFieldInfo(
            "equip_Accessory01",
            "Equipped Accessory: Slot 1",
            True,
            int,
            'Equipment parameter decoration ID01',
        ),
        ParamFieldInfo(
            "equip_Accessory02",
            "Equipped Accessory: Slot 2",
            True,
            int,
            'Equipment parameter decoration ID02',
        ),
        ParamFieldInfo(
            "equip_Accessory03",
            "Equipped Accessory: Slot 3",
            True,
            int,
            'Equipment parameter decoration ID03',
        ),
        ParamFieldInfo(
            "equip_Accessory04",
            "Equipped Accessory: Slot 4",
            True,
            int,
            'Equipment parameter decoration ID04',
        ),
        ParamFieldInfo(
            "pad8[4]",
            "pad",
            False,
            pad_field(4),
            'pad',
        ),
        ParamFieldInfo(
            "elixir_material00",
            "Elixir Material 1",
            True,
            int,
            'Material ID1 for Elixir',
        ),
        ParamFieldInfo(
            "elixir_material01",
            "Elixir Material 2",
            True,
            int,
            'Material ID2 for Elixir',
        ),
        ParamFieldInfo(
            "elixir_material02",
            "Elixir Material 3",
            True,
            int,
            'Material ID3 for Elixir',
        ),
        ParamFieldInfo(
            "equip_Spell_01",
            "Equipped Spell: Slot 1",
            True,
            int,
            'Initial placement magic / miracle ID01',
        ),
        ParamFieldInfo(
            "equip_Spell_02",
            "Equipped Spell: Slot 2",
            True,
            int,
            'Initial placement magic / miracle ID02',
        ),
        ParamFieldInfo(
            "equip_Spell_03",
            "Equipped Spell: Slot 3",
            True,
            int,
            'Initial placement magic / miracle ID03',
        ),
        ParamFieldInfo(
            "equip_Spell_04",
            "Equipped Spell: Slot 4",
            True,
            int,
            'Initial placement magic / miracle ID04',
        ),
        ParamFieldInfo(
            "equip_Spell_05",
            "Equipped Spell: Slot 5",
            True,
            int,
            'Initial placement magic / miracle ID05',
        ),
        ParamFieldInfo(
            "equip_Spell_06",
            "Equipped Spell: Slot 6",
            True,
            int,
            'Initial placement magic / miracle ID06',
        ),
        ParamFieldInfo(
            "equip_Spell_07",
            "Equipped Spell: Slot 7",
            True,
            int,
            'Initial placement magic / miracle ID07',
        ),
        ParamFieldInfo(
            "item_01",
            "Equipped Item: Slot 1",
            True,
            int,
            'Initial possession item ID 01',
        ),
        ParamFieldInfo(
            "item_02",
            "Equipped Item: Slot 2",
            True,
            int,
            'Initial possession item ID 02',
        ),
        ParamFieldInfo(
            "item_03",
            "Equipped Item: Slot 3",
            True,
            int,
            'Initial possession item ID 03',
        ),
        ParamFieldInfo(
            "item_04",
            "Equipped Item: Slot 4",
            True,
            int,
            'Initial possession item ID 04',
        ),
        ParamFieldInfo(
            "item_05",
            "Equipped Item: Slot 5",
            True,
            int,
            'Initial possession item ID 05',
        ),
        ParamFieldInfo(
            "item_06",
            "Equipped Item: Slot 6",
            True,
            int,
            'Initial possession item ID 06',
        ),
        ParamFieldInfo(
            "item_07",
            "Equipped Item: Slot 7",
            True,
            int,
            'Initial possession item ID 07',
        ),
        ParamFieldInfo(
            "item_08",
            "Equipped Item: Slot 8",
            True,
            int,
            'Initial possession item ID 08',
        ),
        ParamFieldInfo(
            "item_09",
            "Equipped Item: Slot 9",
            True,
            int,
            'Initial possession item ID 09',
        ),
        ParamFieldInfo(
            "item_10",
            "Equipped Item: Slot 10",
            True,
            int,
            'Initial possession item ID 10',
        ),
        ParamFieldInfo(
            "npcPlayerFaceGenId",
            "NPC Player - Face Gen ID",
            True,
            int,
            'Facegen parameter ID used by NPC players. Not used by normal players.',
        ),
        ParamFieldInfo(
            "npcPlayerThinkId",
            "NPC Player - Think ID",
            True,
            int,
            'NPC Thinking Parameter ID used by NPC players. Not used by normal players.',
        ),
        ParamFieldInfo(
            "baseHp",
            "Base HP",
            True,
            int,
            'Basic value of HP (actually, it is corrected by the calculation formula)',
        ),
        ParamFieldInfo(
            "baseMp",
            "Base FP",
            True,
            int,
            'Basic value of MP (actually, it is corrected by the calculation formula)',
        ),
        ParamFieldInfo(
            "baseSp",
            "Base Stamina",
            True,
            int,
            'Basic value of stamina (actually, it is corrected by the formula)',
        ),
        ParamFieldInfo(
            "arrowNum",
            "Equipped Ammunition: Arrow Primary Count",
            True,
            int,
            'Initial number of arrows',
        ),
        ParamFieldInfo(
            "boltNum",
            "Equipped Ammunition: Bolt Primary Count",
            True,
            int,
            'Initial number of bolts',
        ),
        ParamFieldInfo(
            "subArrowNum",
            "Equipped Ammunition: Arrow Secondary Count",
            True,
            int,
            'Initial number of arrows',
        ),
        ParamFieldInfo(
            "subBoltNum",
            "Equipped Ammunition: Bolt Secondary Count",
            True,
            int,
            'Initial number of bolts',
        ),
        ParamFieldInfo(
            "pad4[6]",
            "pad",
            False,
            pad_field(6),
            '',
        ),
        ParamFieldInfo(
            "soulLv",
            "Level",
            True,
            int,
            'Initial Lv',
        ),
        ParamFieldInfo(
            "baseVit",
            "Vigor",
            True,
            int,
            'Basic value of physical fitness',
        ),
        ParamFieldInfo(
            "baseWil",
            "Attunement",
            True,
            int,
            'Basic value of spirit',
        ),
        ParamFieldInfo(
            "baseEnd",
            "Endurance",
            True,
            int,
            'Robust base value',
        ),
        ParamFieldInfo(
            "baseStr",
            "Strength",
            True,
            int,
            'Basic value of muscle strength',
        ),
        ParamFieldInfo(
            "baseDex",
            "Dexterity",
            True,
            int,
            'Basic value of agility',
        ),
        ParamFieldInfo(
            "baseMag",
            "Intelligence",
            True,
            int,
            'Basic value of magic power',
        ),
        ParamFieldInfo(
            "baseFai",
            "Faith",
            True,
            int,
            'Basic value of faith',
        ),
        ParamFieldInfo(
            "baseLuc",
            "Arcane",
            True,
            int,
            'Basic value of luck',
        ),
        ParamFieldInfo(
            "baseHeroPoint",
            "Humanity",
            True,
            int,
            'Basic value of human nature',
        ),
        ParamFieldInfo(
            "baseDurability",
            "Vitality",
            True,
            int,
            'Basic value of endurance',
        ),
        ParamFieldInfo(
            "itemNum_01",
            "Equipped Item: Slot 1 Amount",
            True,
            int,
            'Initial possession number of items 01',
        ),
        ParamFieldInfo(
            "itemNum_02",
            "Equipped Item: Slot 2 Amount",
            True,
            int,
            'Initial possession number of items 02',
        ),
        ParamFieldInfo(
            "itemNum_03",
            "Equipped Item: Slot 3 Amount",
            True,
            int,
            'Initial possession number of items 03',
        ),
        ParamFieldInfo(
            "itemNum_04",
            "Equipped Item: Slot 4 Amount",
            True,
            int,
            'Initial possession number of items 04',
        ),
        ParamFieldInfo(
            "itemNum_05",
            "Equipped Item: Slot 5 Amount",
            True,
            int,
            'Initial possession number of items 05',
        ),
        ParamFieldInfo(
            "itemNum_06",
            "Equipped Item: Slot 6 Amount",
            True,
            int,
            'Initial possession number of items 06',
        ),
        ParamFieldInfo(
            "itemNum_07",
            "Equipped Item: Slot 7 Amount",
            True,
            int,
            'Initial possession number of items 07',
        ),
        ParamFieldInfo(
            "itemNum_08",
            "Equipped Item: Slot 8 Amount",
            True,
            int,
            'Initial possession number of items 08',
        ),
        ParamFieldInfo(
            "itemNum_09",
            "Equipped Item: Slot 9 Amount",
            True,
            int,
            'Initial possession number of items 09',
        ),
        ParamFieldInfo(
            "itemNum_10",
            "Equipped Item: Slot 10 Amount",
            True,
            int,
            'Initial possession number of items 10',
        ),
        ParamFieldInfo(
            "pad5[5]",
            "pad",
            False,
            pad_field(5),
            '',
        ),
        ParamFieldInfo(
            "gestureId0",
            "Equipped Gesture: Slot 0",
            True,
            int,
            'Gesture 0th (0 if you want to play EzState gesture 0)',
        ),
        ParamFieldInfo(
            "gestureId1",
            "Equipped Gesture: Slot 1",
            True,
            int,
            'Gesture 1st (0 if you want to play EzState gesture 0)',
        ),
        ParamFieldInfo(
            "gestureId2",
            "Equipped Gesture: Slot 2",
            True,
            int,
            "Gesture 2nd (0 if you want to play EzState's gesture 0)",
        ),
        ParamFieldInfo(
            "gestureId3",
            "Equipped Gesture: Slot 3",
            True,
            int,
            'Gesture 3rd (0 if you want to play EzState gesture 0)',
        ),
        ParamFieldInfo(
            "gestureId4",
            "Equipped Gesture: Slot 4",
            True,
            int,
            "Gesture 4th (0 if you want to play EzState's gesture 0)",
        ),
        ParamFieldInfo(
            "gestureId5",
            "Equipped Gesture: Slot 5",
            True,
            int,
            'Gesture 5th (0 if you want to play EzState gesture 0)',
        ),
        ParamFieldInfo(
            "gestureId6",
            "Equipped Gesture: Slot 6",
            True,
            int,
            'Gesture 6th (0 if you want to play EzState gesture 0)',
        ),
        ParamFieldInfo(
            "npcPlayerType",
            "NPC Player - Type",
            True,
            int,
            'NPC type used by NPC players. Not used by normal players.',
        ),
        ParamFieldInfo(
            "npcPlayerDrawType",
            "NPC Player - Draw Type",
            True,
            int,
            'Drawing type used by NPC players. Not used by normal players.',
        ),
        ParamFieldInfo(
            "npcPlayerSex",
            "NPC Player - Sex",
            True,
            int,
            'The gender used by NPC players. It is not reflected to normal players.',
        ),
        ParamFieldInfo(
            "vowType:4",
            "Vow Type",
            True,
            int,
            'Pledge type (None: 0)',
        ),
        ParamFieldInfo(
            "isSyncTarget:1",
            "Is Sync Target",
            True,
            int,
            'Is it a send / receive target (for copy NPCs)?',
        ),
        ParamFieldInfo(
            "pad:3",
            "pad",
            False,
            bit_pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "pad6[2]",
            "pad",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "wepParamType_Right1",
            "Weapon Param Type - Right Primary",
            True,
            int,
            'Right-handed weapon slot 1 parameter reference',
        ),
        ParamFieldInfo(
            "wepParamType_Right2",
            "Weapon Param Type - Right Secondary",
            True,
            int,
            'Right-handed weapon slot 2 parameter reference',
        ),
        ParamFieldInfo(
            "wepParamType_Right3",
            "Weapon Param Type - Right Tertiary",
            True,
            int,
            'Right-handed weapon slot 3 parameter reference',
        ),
        ParamFieldInfo(
            "wepParamType_Left1",
            "Weapon Param Type - Left Primary",
            True,
            int,
            'Parameter reference for left-handed weapon slot 1',
        ),
        ParamFieldInfo(
            "wepParamType_Left2",
            "Weapon Param Type - Left Secondary",
            True,
            int,
            'Parameter reference for left-handed weapon slot 2',
        ),
        ParamFieldInfo(
            "wepParamType_Left3",
            "Weapon Param Type - Left Tertiary",
            True,
            int,
            'Parameter reference for left-handed weapon slot 3',
        ),
        ParamFieldInfo(
            "pad2[26]",
            "pad",
            False,
            pad_field(26),
            '',
        ),
        ParamFieldInfo(
            "equip_Subwep_Right3",
            "Equipped Weapon: Right Tertiary",
            True,
            int,
            'Weapon ID of equipment parameter (right hand slot 3)',
        ),
        ParamFieldInfo(
            "equip_Subwep_Left3",
            "Equipped Weapon: Left Tertiary",
            True,
            int,
            'Weapon ID of equipment parameter (left hand slot 3)',
        ),
        ParamFieldInfo(
            "pad3[4]",
            "pad",
            False,
            pad_field(4),
            '',
        ),
        ParamFieldInfo(
            "secondaryItem_01",
            "Stored Item: Slot 1",
            True,
            int,
            'Item ID 01 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItem_02",
            "Stored Item: Slot 2",
            True,
            int,
            'Item ID 02 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItem_03",
            "Stored Item: Slot 3",
            True,
            int,
            'Item ID 03 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItem_04",
            "Stored Item: Slot 4",
            True,
            int,
            'Item ID 04 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItem_05",
            "Stored Item: Slot 5",
            True,
            int,
            'Item ID 05 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItem_06",
            "Stored Item: Slot 6",
            True,
            int,
            'Item ID 06 of the second shortcut initial possession',
        ),
        ParamFieldInfo(
            "secondaryItemNum_01",
            "Stored Item: Slot 1 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 01',
        ),
        ParamFieldInfo(
            "secondaryItemNum_02",
            "Stored Item: Slot 2 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 02',
        ),
        ParamFieldInfo(
            "secondaryItemNum_03",
            "Stored Item: Slot 3 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 03',
        ),
        ParamFieldInfo(
            "secondaryItemNum_04",
            "Stored Item: Slot 4 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 04',
        ),
        ParamFieldInfo(
            "secondaryItemNum_05",
            "Stored Item: Slot 5 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 05',
        ),
        ParamFieldInfo(
            "secondaryItemNum_06",
            "Stored Item: Slot 6 Count",
            True,
            int,
            '2nd Shortcut Initial possession number of items 06',
        ),
        ParamFieldInfo(
            "HpEstMax",
            "HP Flask - Max Possession Limit",
            True,
            int,
            'HP Est Bottle Possession Limit',
        ),
        ParamFieldInfo(
            "MpEstMax",
            "FP Flask - Max Possession Limit",
            True,
            int,
            'MP Est Bottle Possession Limit',
        ),
        ParamFieldInfo(
            "pad7[5]",
            "pad",
            False,
            pad_field(5),
            '',
        ),
        ParamFieldInfo(
            "voiceType",
            "Voice Type",
            True,
            int,
            'Voice type',
        ),
        ParamFieldInfo(
            "reserve[6]",
            "Reserved area",
            False,
            pad_field(6),
            'Reserved area',
        ),
    ],
}
