from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


CHR_ACTIVATE_CONDITION_PARAM_ST = {
    "param_type": "CHR_ACTIVATE_CONDITION_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "weatherSunny:1",
            "Appear during Weather: Sunny",
            True,
            int,
            'Will it appear when the weather is "sunny"?',
        ),
        ParamFieldInfo(
            "weatherClearSky:1",
            "Appear during Weather: Clear Sky",
            True,
            int,
            'Will it appear when the weather is "clear"?',
        ),
        ParamFieldInfo(
            "weatherWeakCloudy:1",
            "Appear during Weather: Light Cloud",
            True,
            int,
            'Will it appear when the weather is "lightly cloudy"?',
        ),
        ParamFieldInfo(
            "weatherCloudy:1",
            "Appear during Weather: Cloud",
            True,
            int,
            'Will it appear when the weather is "cloudy"?',
        ),
        ParamFieldInfo(
            "weatherRain:1",
            "Appear during Weather: Rain",
            True,
            int,
            'Will it appear when the weather is "rainy"?',
        ),
        ParamFieldInfo(
            "weatherHeavyRain:1",
            "Appear during Weather: Heavy Rain",
            True,
            int,
            'Will it appear when the weather is "heavy rain"?',
        ),
        ParamFieldInfo(
            "weatherStorm:1",
            "Appear during Weather: Storm",
            True,
            int,
            'Will it appear when the weather is "stormy"?',
        ),
        ParamFieldInfo(
            "weatherStormForBattle:1",
            "Appear during Weather: Storm for Battle",
            True,
            int,
            'Will it appear when the weather is "storm (for combat with the descendants of the guardian)"?',
        ),
        ParamFieldInfo(
            "weatherSnow:1",
            "Appear during Weather: Snow",
            True,
            int,
            'Will it appear when the weather is "snow"?',
        ),
        ParamFieldInfo(
            "weatherHeavySnow:1",
            "Appear during Weather: Heavy Snow",
            True,
            int,
            'Will it appear when the weather is "heavy snow"?',
        ),
        ParamFieldInfo(
            "weatherFog:1",
            "Appear during Weather: Fog",
            True,
            int,
            'Will it appear when the weather is "fog"?',
        ),
        ParamFieldInfo(
            "weatherHeavyFog:1",
            "Appear during Weather: Heavy Fog",
            True,
            int,
            'Will it appear when the weather is "dense fog"?',
        ),
        ParamFieldInfo(
            "weatherHeavyFogRain:1",
            "Appear during Weather: Heavy Fog and Rain",
            True,
            int,
            'Does it appear when the weather is "dense fog (rain)"?',
        ),
        ParamFieldInfo(
            "weatherSandStorm:1",
            "Appear during Weather: Sandstorm",
            True,
            int,
            'Will it appear when the weather is a "sandstorm"?',
        ),
        ParamFieldInfo(
            "pad1:2",
            "pad",
            False,
            bit_pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "timeStartHour",
            "Time: Start Hour",
            True,
            int,
            'Appearance start in game time_hour',
        ),
        ParamFieldInfo(
            "timeStartMin",
            "Time: Start Minute",
            True,
            int,
            'Appearance start in-game time_minutes',
        ),
        ParamFieldInfo(
            "timeEndHour",
            "Time: End Hour",
            True,
            int,
            'Appearance end in game time_hour',
        ),
        ParamFieldInfo(
            "timeEndMin",
            "Time: End Minute",
            True,
            int,
            'End of appearance In-game time_minutes',
        ),
        ParamFieldInfo(
            "pad2[2]",
            "pad",
            False,
            pad_field(2),
            '',
        ),
    ],
}
