from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


CLEAR_COUNT_CORRECT_PARAM_ST = {
    "param_type": "CLEAR_COUNT_CORRECT_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "MaxHpRate",
            "Max HP %",
            True,
            float,
            'Maximum HP magnification [%]',
        ),
        ParamFieldInfo(
            "MaxMpRate",
            "Max FP %",
            True,
            float,
            'Maximum MP magnification [%]',
        ),
        ParamFieldInfo(
            "MaxStaminaRate",
            "Max Stamina %",
            True,
            float,
            'Maximum stamina magnification [%]',
        ),
        ParamFieldInfo(
            "PhysicsAttackRate",
            "Damage %: Physical",
            True,
            float,
            'Physical attack power multiplier',
        ),
        ParamFieldInfo(
            "SlashAttackRate",
            "Damage %: Slash",
            True,
            float,
            'Slash attack power multiplier',
        ),
        ParamFieldInfo(
            "BlowAttackRate",
            "Damage %: Strike",
            True,
            float,
            'Batter attack power multiplier',
        ),
        ParamFieldInfo(
            "ThrustAttackRate",
            "Damage %: Thrust",
            True,
            float,
            'Puncture attack power multiplier',
        ),
        ParamFieldInfo(
            "NeturalAttackRate",
            "Damage %: Standard",
            True,
            float,
            'Non-attribute attack power multiplier',
        ),
        ParamFieldInfo(
            "MagicAttackRate",
            "Damage %: Magic",
            True,
            float,
            'Magic attack power multiplier',
        ),
        ParamFieldInfo(
            "FireAttackRate",
            "Damage %: Fire",
            True,
            float,
            'Fire attack power multiplier',
        ),
        ParamFieldInfo(
            "ThunderAttackRate",
            "Damage %: Lightning",
            True,
            float,
            'Electric shock attack power multiplier',
        ),
        ParamFieldInfo(
            "DarkAttackRate",
            "Damage %: Holy",
            True,
            float,
            'Dark attack power multiplier',
        ),
        ParamFieldInfo(
            "PhysicsDefenseRate",
            "Defence %: Physical",
            True,
            float,
            'Physical defense power multiplier',
        ),
        ParamFieldInfo(
            "MagicDefenseRate",
            "Defence %: Magic",
            True,
            float,
            'Magic defense multiplier',
        ),
        ParamFieldInfo(
            "FireDefenseRate",
            "Defence %: Fire",
            True,
            float,
            'Fire defense multiplier',
        ),
        ParamFieldInfo(
            "ThunderDefenseRate",
            "Defence %: Lightning",
            True,
            float,
            'Electric shock defense power multiplier',
        ),
        ParamFieldInfo(
            "DarkDefenseRate",
            "Defence %: Holy",
            True,
            float,
            'Dark defense multiplier',
        ),
        ParamFieldInfo(
            "StaminaAttackRate",
            "Damage %: Stamina",
            True,
            float,
            'Stamina attack power multiplier',
        ),
        ParamFieldInfo(
            "SoulRate",
            "Rune Multiplier",
            True,
            float,
            'Possession soul rate',
        ),
        ParamFieldInfo(
            "PoisionResistRate",
            "Resist %: Poison",
            True,
            float,
            'Poison resistance change rate',
        ),
        ParamFieldInfo(
            "DiseaseResistRate",
            "Resist %: Scarlet Rot",
            True,
            float,
            'Epidemic resistance change rate',
        ),
        ParamFieldInfo(
            "BloodResistRate",
            "Resist %: Hemorrhage",
            True,
            float,
            'Bleeding resistance change rate',
        ),
        ParamFieldInfo(
            "CurseResistRate",
            "Resist %: Blight",
            True,
            float,
            'Curse resistance change rate',
        ),
        ParamFieldInfo(
            "FreezeResistRate",
            "Resist %: Frostbite",
            True,
            float,
            'Cold resistance change rate',
        ),
        ParamFieldInfo(
            "BloodDamageRate",
            "Damage %: Hemorrhage",
            True,
            float,
            'Bleeding damage correction factor',
        ),
        ParamFieldInfo(
            "SuperArmorDamageRate",
            "Damage %: Poise",
            True,
            float,
            'SA damage correction factor',
        ),
        ParamFieldInfo(
            "FreezeDamageRate",
            "Damage %: Frostbite",
            True,
            float,
            'Cold damage correction factor',
        ),
        ParamFieldInfo(
            "SleepResistRate",
            "Resist %: Sleep",
            True,
            float,
            'Sleep tolerance change rate',
        ),
        ParamFieldInfo(
            "MadnessResistRate",
            "Resist %: Madness",
            True,
            float,
            'Madness resistance change rate',
        ),
        ParamFieldInfo(
            "SleepDamageRate",
            "Damage %: Sleep",
            True,
            float,
            'Sleep damage correction factor',
        ),
        ParamFieldInfo(
            "MadnessDamageRate",
            "Damage %: Madness",
            True,
            float,
            'Mad damage correction factor',
        ),
        ParamFieldInfo(
            "pad1[4]",
            "pad",
            False,
            pad_field(4),
            '',
        ),
    ],
}
