from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


CUTSCENE_TEXTURE_LOAD_PARAM_ST = {
    "param_type": "CUTSCENE_TEXTURE_LOAD_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParam_Debug:1",
            "Disable Param - Debug",
            True,
            int,
            'Parameters marked with a circle are excluded from all packages (because they are for debugging).',
        ),
        ParamFieldInfo(
            "disableParamReserve1:6",
            "Reserve for package output 1",
            False,
            bit_pad_field(6),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "texName_00[16]",
            "Texture DisplayName [00]",
            True,
            str,
            'Texture DisplayName [00]',
        ),
        ParamFieldInfo(
            "texName_01[16]",
            "Texture DisplayName [01]",
            True,
            str,
            'Texture DisplayName [01]',
        ),
        ParamFieldInfo(
            "texName_02[16]",
            "Texture DisplayName [02]",
            True,
            str,
            'Texture DisplayName [02]',
        ),
        ParamFieldInfo(
            "texName_03[16]",
            "Texture DisplayName [03]",
            True,
            str,
            'Texture DisplayName [03]',
        ),
        ParamFieldInfo(
            "texName_04[16]",
            "Texture DisplayName [04]",
            True,
            str,
            'Texture DisplayName [04]',
        ),
        ParamFieldInfo(
            "texName_05[16]",
            "Texture DisplayName [05]",
            True,
            str,
            'Texture DisplayName [05]',
        ),
        ParamFieldInfo(
            "texName_06[16]",
            "Texture DisplayName [06]",
            True,
            str,
            'Texture DisplayName [06]',
        ),
        ParamFieldInfo(
            "texName_07[16]",
            "Texture DisplayName [07]",
            True,
            str,
            'Texture DisplayName [07]',
        ),
        ParamFieldInfo(
            "texName_08[16]",
            "Texture DisplayName [08]",
            True,
            str,
            'Texture DisplayName [08]',
        ),
        ParamFieldInfo(
            "texName_09[16]",
            "Texture DisplayName [09]",
            True,
            str,
            'Texture DisplayName [09]',
        ),
        ParamFieldInfo(
            "texName_10[16]",
            "Texture DisplayName [10]",
            True,
            str,
            'Texture DisplayName [10]',
        ),
        ParamFieldInfo(
            "texName_11[16]",
            "Texture DisplayName [11]",
            True,
            str,
            'Texture DisplayName [11]',
        ),
        ParamFieldInfo(
            "texName_12[16]",
            "Texture DisplayName [12]",
            True,
            str,
            'Texture DisplayName [12]',
        ),
        ParamFieldInfo(
            "texName_13[16]",
            "Texture DisplayName [13]",
            True,
            str,
            'Texture DisplayName [13]',
        ),
        ParamFieldInfo(
            "texName_14[16]",
            "Texture DisplayName [14]",
            True,
            str,
            'Texture DisplayName [14]',
        ),
        ParamFieldInfo(
            "texName_15[16]",
            "Texture DisplayName [15]",
            True,
            str,
            'Texture DisplayName [15]',
        ),
    ],
}
