from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


DEFAULT_KEY_ASSIGN = {
    "param_type": "DEFAULT_KEY_ASSIGN",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "priority0:1",
            "Pad 0",
            True,
            int,
            'Lower suppression pad 0',
        ),
        ParamFieldInfo(
            "priority1:1",
            "For GUI framework",
            True,
            int,
            'Pad for lower suppression GUI framework',
        ),
        ParamFieldInfo(
            "priority2:1",
            "Pad 2",
            True,
            int,
            'Lower suppression pad 2',
        ),
        ParamFieldInfo(
            "priority3:1",
            "Debug menu mode switching",
            True,
            int,
            'Lower suppression debug menu mode switching pad',
        ),
        ParamFieldInfo(
            "priority4:1",
            "Pad 4",
            True,
            int,
            'Lower suppression pad 4',
        ),
        ParamFieldInfo(
            "priority5:1",
            "Pad debug menu",
            True,
            int,
            'Lower suppression pad Debug menu pad',
        ),
        ParamFieldInfo(
            "priority6:1",
            "Pad 6",
            True,
            int,
            'Lower suppression pad 6',
        ),
        ParamFieldInfo(
            "priority7:1",
            "Pad 7",
            True,
            int,
            'Lower suppression pad 7',
        ),
        ParamFieldInfo(
            "priority8:1",
            "Pad 8",
            True,
            int,
            'Lower suppression pad 8',
        ),
        ParamFieldInfo(
            "priority9:1",
            "Pad 9",
            True,
            int,
            'Lower suppression pad 9',
        ),
        ParamFieldInfo(
            "priority10:1",
            "Pad 10",
            True,
            int,
            'Lower suppression pad 10',
        ),
        ParamFieldInfo(
            "priority11:1",
            "Pad 11",
            True,
            int,
            'Lower suppression pad 11',
        ),
        ParamFieldInfo(
            "priority12:1",
            "Pad 12",
            True,
            int,
            'Lower suppression pad 12',
        ),
        ParamFieldInfo(
            "priority13:1",
            "Pad 13",
            True,
            int,
            'Lower suppression pad 13',
        ),
        ParamFieldInfo(
            "priority14:1",
            "Pad 14",
            True,
            int,
            'Lower suppression pad 14',
        ),
        ParamFieldInfo(
            "priority15:1",
            "Pad 15",
            True,
            int,
            'Lower suppression pad 15',
        ),
        ParamFieldInfo(
            "priority16:1",
            "Pad 16",
            True,
            int,
            'Lower suppression pad 16',
        ),
        ParamFieldInfo(
            "priority17:1",
            "Pad 17",
            True,
            int,
            'Lower suppression pad 17',
        ),
        ParamFieldInfo(
            "priority18:1",
            "Pad 18",
            True,
            int,
            'Lower suppression pad 18',
        ),
        ParamFieldInfo(
            "priority19:1",
            "Pad 19",
            True,
            int,
            'Lower suppression pad 19',
        ),
        ParamFieldInfo(
            "priority20:1",
            "Pad 20",
            True,
            int,
            'Lower suppression pad 20',
        ),
        ParamFieldInfo(
            "priority21:1",
            "Pad 21",
            True,
            int,
            'Lower suppression pad 21',
        ),
        ParamFieldInfo(
            "priority22:1",
            "Pad 22",
            True,
            int,
            'Lower suppression pad 22',
        ),
        ParamFieldInfo(
            "priority23:1",
            "Pad 23",
            True,
            int,
            'Lower suppression pad 23',
        ),
        ParamFieldInfo(
            "priority24:1",
            "Pad 24",
            True,
            int,
            'Lower suppression pad 24',
        ),
        ParamFieldInfo(
            "priority25:1",
            "Pad 25",
            True,
            int,
            'Lower suppression pad 25',
        ),
        ParamFieldInfo(
            "priority26:1",
            "Pad 26",
            True,
            int,
            'Lower suppression pad 26',
        ),
        ParamFieldInfo(
            "priority27:1",
            "Pad 27",
            True,
            int,
            'Lower suppression pad 27',
        ),
        ParamFieldInfo(
            "priority28:1",
            "Pad 28",
            True,
            int,
            'Lower suppression pad 28',
        ),
        ParamFieldInfo(
            "priority29:1",
            "Pad 29",
            True,
            int,
            'Lower suppression pad 29',
        ),
        ParamFieldInfo(
            "priority30:1",
            "Pad 30",
            True,
            int,
            'Lower suppression pad 30',
        ),
        ParamFieldInfo(
            "priority31:1",
            "Pad 31",
            True,
            int,
            'Lower suppression pad 31',
        ),
        ParamFieldInfo(
            "dummy[12]",
            "dummy",
            False,
            pad_field(12),
            '',
        ),
        ParamFieldInfo(
            "phyisicalKey",
            "PC physical key",
            True,
            int,
            'PC physical key',
        ),
        ParamFieldInfo(
            "traitsType",
            "How to be pushed",
            True,
            int,
            'How to be pushed',
        ),
        ParamFieldInfo(
            "a2dOperator",
            "Analog-to-digital conversion method",
            True,
            int,
            'Analog-to-digital conversion method',
        ),
        ParamFieldInfo(
            "applyTarget",
            "Applicable target",
            True,
            int,
            'Reflection target',
        ),
        ParamFieldInfo(
            "isAnalog:1",
            "Digital / analog",
            True,
            int,
            'Digital or analog',
        ),
        ParamFieldInfo(
            "enableWin64:1",
            "Win64",
            True,
            int,
            'Will it be used in Win64?',
        ),
        ParamFieldInfo(
            "enablePS4:1",
            "PS4",
            True,
            int,
            'Will it be used on PS4',
        ),
        ParamFieldInfo(
            "enableXboxOne:1",
            "Xbox One",
            True,
            int,
            'Will it be used on Xbox One',
        ),
        ParamFieldInfo(
            "time1",
            "time",
            True,
            float,
            'time',
        ),
        ParamFieldInfo(
            "time2",
            "Interval time for repeat",
            True,
            float,
            'Interval time for repeat',
        ),
        ParamFieldInfo(
            "a2dThreshold",
            "Analog-to-digital conversion threshold",
            True,
            float,
            'Analog-to-digital conversion threshold',
        ),
    ],
}
