from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


EQUIP_PARAM_PROTECTOR_ST = {
    "param_type": "EQUIP_PARAM_PROTECTOR_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "sortId",
            "Sort ID",
            True,
            int,
            'Sort ID (7 digits is the limit for s32 because the enhancement level is added in the program)',
        ),
        ParamFieldInfo(
            "wanderingEquipId",
            "Wandering Equip ID",
            True,
            int,
            'Replacement equipment ID for wandering ghosts.',
        ),
        ParamFieldInfo(
            "resistSleep",
            "Resist - Sleep",
            True,
            int,
            'Difficulty in getting sleep abnormalities',
        ),
        ParamFieldInfo(
            "resistMadness",
            "Resist - Madness",
            True,
            int,
            'Difficulty in getting mad',
        ),
        ParamFieldInfo(
            "saDurability",
            "Poise Durability",
            True,
            float,
            'Super armor endurance',
        ),
        ParamFieldInfo(
            "toughnessCorrectRate",
            "Toughness Correction",
            True,
            float,
            'It is a magnification that corrects the basic value of toughness.',
        ),
        ParamFieldInfo(
            "fixPrice",
            "Repair Price",
            True,
            int,
            'Basic repair price',
        ),
        ParamFieldInfo(
            "basicPrice",
            "Basic Price",
            True,
            int,
            'Basic price',
        ),
        ParamFieldInfo(
            "sellValue",
            "Sell Value",
            True,
            int,
            'Selling price',
        ),
        ParamFieldInfo(
            "weight",
            "Weight",
            True,
            float,
            'Weight [kg].',
        ),
        ParamFieldInfo(
            "residentSpEffectId",
            "Resident SpEffect ID [1]",
            True,
            int,
            'Resident special effect ID1',
        ),
        ParamFieldInfo(
            "residentSpEffectId2",
            "Resident SpEffect ID [2]",
            True,
            int,
            'Resident special effect ID2',
        ),
        ParamFieldInfo(
            "residentSpEffectId3",
            "Resident SpEffect ID [3]",
            True,
            int,
            'Resident special effect ID3',
        ),
        ParamFieldInfo(
            "materialSetId",
            "Upgrade Material ID",
            True,
            int,
            'Material parameter ID required for weapon enhancement',
        ),
        ParamFieldInfo(
            "partsDamageRate",
            "Weak Parts Damage %",
            True,
            float,
            'Part damage rate',
        ),
        ParamFieldInfo(
            "corectSARecover",
            "Poise Recovery Correction",
            True,
            float,
            'Super Armor Recovery Time Correction Value',
        ),
        ParamFieldInfo(
            "originEquipPro",
            "Origin Armor +0",
            True,
            int,
            'Strengthening of this armor Original armor ID',
        ),
        ParamFieldInfo(
            "originEquipPro1",
            "Origin Armor +1",
            True,
            int,
            'Strengthening this armor Original armor ID1',
        ),
        ParamFieldInfo(
            "originEquipPro2",
            "Origin Armor +2",
            True,
            int,
            'Strengthening this armor Original armor ID2',
        ),
        ParamFieldInfo(
            "originEquipPro3",
            "Origin Armor +3",
            True,
            int,
            'Strengthening this armor Original armor ID3',
        ),
        ParamFieldInfo(
            "originEquipPro4",
            "Origin Armor +4",
            True,
            int,
            'Strengthening this armor Original armor ID4',
        ),
        ParamFieldInfo(
            "originEquipPro5",
            "Origin Armor +5",
            True,
            int,
            'Strengthening this armor Original armor ID5',
        ),
        ParamFieldInfo(
            "originEquipPro6",
            "Origin Armor +6",
            True,
            int,
            'Strengthening this armor Original armor ID6',
        ),
        ParamFieldInfo(
            "originEquipPro7",
            "Origin Armor +7",
            True,
            int,
            'Strengthening this armor Original armor ID7',
        ),
        ParamFieldInfo(
            "originEquipPro8",
            "Origin Armor +8",
            True,
            int,
            'Strengthening this armor Original armor ID8',
        ),
        ParamFieldInfo(
            "originEquipPro9",
            "Origin Armor +9",
            True,
            int,
            'Strengthening this armor Original armor ID9',
        ),
        ParamFieldInfo(
            "originEquipPro10",
            "Origin Armor +10",
            True,
            int,
            'Strengthening this armor Original armor ID10',
        ),
        ParamFieldInfo(
            "originEquipPro11",
            "Origin Armor +11",
            True,
            int,
            'Strengthening this armor Original armor ID11',
        ),
        ParamFieldInfo(
            "originEquipPro12",
            "Origin Armor +12",
            True,
            int,
            'Strengthening this armor Original armor ID12',
        ),
        ParamFieldInfo(
            "originEquipPro13",
            "Origin Armor +13",
            True,
            int,
            'Strengthening this armor Original armor ID13',
        ),
        ParamFieldInfo(
            "originEquipPro14",
            "Origin Armor +14",
            True,
            int,
            'Strengthening this armor Original armor ID14',
        ),
        ParamFieldInfo(
            "originEquipPro15",
            "Origin Armor +15",
            True,
            int,
            'Strengthening this armor Original armor ID15',
        ),
        ParamFieldInfo(
            "faceScaleM_ScaleX",
            "Facescale - Male - Scale X",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleM_ScaleZ",
            "Facescale - Male - Scale Z",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleM_MaxX",
            "Facescale - Male - Max X",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleM_MaxZ",
            "Facescale - Male - Max Z",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleF_ScaleX",
            "Facescale - Female - Scale X",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleF_ScaleZ",
            "Facescale - Female - Scale Z",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleF_MaxX",
            "Facescale - Female - Max X",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "faceScaleF_MaxZ",
            "Facescale - Female - Max Z",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "qwcId",
            "QWC ID",
            True,
            int,
            'QWC parameter ID',
        ),
        ParamFieldInfo(
            "equipModelId",
            "Equip Model ID",
            True,
            int,
            'Equipment model number.',
        ),
        ParamFieldInfo(
            "iconIdM",
            "Icon ID - Male",
            True,
            int,
            "Men's menu icon ID.",
        ),
        ParamFieldInfo(
            "iconIdF",
            "Icon ID - Female",
            True,
            int,
            "Women's menu icon ID.",
        ),
        ParamFieldInfo(
            "knockBack",
            "Knockback",
            True,
            int,
            'Knockback reduction value.',
        ),
        ParamFieldInfo(
            "knockbackBounceRate",
            "Knockback Bounce Rate",
            True,
            int,
            'Knockback repulsion rate.',
        ),
        ParamFieldInfo(
            "durability",
            "Durability",
            True,
            int,
            'Initial durability.',
        ),
        ParamFieldInfo(
            "durabilityMax",
            "Max Durability",
            True,
            int,
            'New durability.',
        ),
        ParamFieldInfo(
            "pad03[2]",
            "pad",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "defFlickPower",
            "Weapon Repel Power",
            True,
            int,
            'Used to determine the repulsion of enemy attacks.',
        ),
        ParamFieldInfo(
            "defensePhysics",
            "Defence - Physical",
            True,
            int,
            'Physical attack damage protection.',
        ),
        ParamFieldInfo(
            "defenseMagic",
            "Defence - Magic",
            True,
            int,
            'Magic attack damage protection.',
        ),
        ParamFieldInfo(
            "defenseFire",
            "Defence - Fire",
            True,
            int,
            'Fire attack damage protection.',
        ),
        ParamFieldInfo(
            "defenseThunder",
            "Defence - Lightning",
            True,
            int,
            'Damage protection for electric shock attacks.',
        ),
        ParamFieldInfo(
            "defenseSlash",
            "Defence - Slash",
            True,
            int,
            'Look at the attack type, and if it is a slashing attribute, reduce the defense power',
        ),
        ParamFieldInfo(
            "defenseBlow",
            "Defence - Strike",
            True,
            int,
            'Look at the attack attribute, and if it is a hit attribute, reduce the defense power.',
        ),
        ParamFieldInfo(
            "defenseThrust",
            "Defence - Thrust",
            True,
            int,
            'Look at the attack attribute, and if it is a hit attribute, reduce the defense power.',
        ),
        ParamFieldInfo(
            "resistPoison",
            "Resist - Poison",
            True,
            int,
            'Difficulty in getting poisonous',
        ),
        ParamFieldInfo(
            "resistDisease",
            "Resist - Scarlet Rot",
            True,
            int,
            'Difficulty in getting sick',
        ),
        ParamFieldInfo(
            "resistBlood",
            "Resist - Hemorrhage",
            True,
            int,
            'Difficulty in getting bleeding abnormalities',
        ),
        ParamFieldInfo(
            "resistCurse",
            "Resist - Blight",
            True,
            int,
            'Difficulty in getting a curse condition',
        ),
        ParamFieldInfo(
            "reinforceTypeId",
            "Reinforce Type ID",
            True,
            int,
            'Enhanced type ID',
        ),
        ParamFieldInfo(
            "trophySGradeId",
            "Achievement ID",
            True,
            int,
            'Is it related to the trophy system?',
        ),
        ParamFieldInfo(
            "shopLv",
            "Shop Level",
            True,
            int,
            'Level that can be sold at the store',
        ),
        ParamFieldInfo(
            "knockbackParamId",
            "Knockback Param ID",
            True,
            int,
            'ID of the parameter used for knockback',
        ),
        ParamFieldInfo(
            "flickDamageCutRate",
            "Weapon Repel Damage %",
            True,
            int,
            'Used for damage attenuation rate when repelling',
        ),
        ParamFieldInfo(
            "equipModelCategory",
            "Equip Model Category",
            True,
            int,
            'Equipment model type.',
        ),
        ParamFieldInfo(
            "equipModelGender",
            "Equip Model Gender",
            True,
            int,
            'Gender of equipment model.',
        ),
        ParamFieldInfo(
            "protectorCategory",
            "Armor Category",
            True,
            int,
            'Armor category.',
        ),
        ParamFieldInfo(
            "rarity",
            "Rarity",
            True,
            int,
            'Rarity used in item acquisition logs',
        ),
        ParamFieldInfo(
            "sortGroupId",
            "Sort Group ID",
            True,
            int,
            'Sort item type ID. In the sort "Item type order", the same ID is displayed together as the same group.',
        ),
        ParamFieldInfo(
            "partsDmgType",
            "Parts Damage Type",
            True,
            int,
            'Set the attack type to judge the part damage',
        ),
        ParamFieldInfo(
            "pad04[2]",
            "Padding",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "isDeposit:1",
            "Can Deposit",
            True,
            int,
            'Can you leave it in the warehouse?',
        ),
        ParamFieldInfo(
            "headEquip:1",
            "Is Head Equipment",
            True,
            int,
            'Is it head equipment?',
        ),
        ParamFieldInfo(
            "bodyEquip:1",
            "Is Body Equipment",
            True,
            int,
            'Is it torso equipment?',
        ),
        ParamFieldInfo(
            "armEquip:1",
            "Is Arm Equipment",
            True,
            int,
            'Is it arm equipment?',
        ),
        ParamFieldInfo(
            "legEquip:1",
            "Is Leg Equipment",
            True,
            int,
            'Is it leg equipment?',
        ),
        ParamFieldInfo(
            "useFaceScale:1",
            "Use Facescale",
            True,
            int,
            'Whether to use a face scale',
        ),
        ParamFieldInfo(
            "isSkipWeakDamageAnim:1",
            "Skip Weak Damage Anim",
            True,
            int,
            'Weakness damage Whether to skip animation playback. "Part damage rate" and "defense material" are treated as weak points just by not playing the animation.',
        ),
        ParamFieldInfo(
            "pad06:1",
            "Padding",
            False,
            bit_pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "defenseMaterialVariationValue_Weak",
            "Defence Material - Variation Value - Weak",
            True,
            int,
            'It is a value used for variation of abnormal condition, damage SFX, SE in combination with weak point defense material. SEQ16473',
        ),
        ParamFieldInfo(
            "autoFootEffectDecalBaseId2",
            "Auto Foot Effect Decal Base ID [2]",
            True,
            int,
            'Decal ID for automatic foot effects. Floor material is also considered. Only used when the "armor category" is "legs".',
        ),
        ParamFieldInfo(
            "autoFootEffectDecalBaseId3",
            "Auto Foot Effect Decal Base ID [3]",
            True,
            int,
            'Decal ID for automatic foot effects. Floor material is also considered. Only used when the "armor category" is "legs".',
        ),
        ParamFieldInfo(
            "defenseMaterialVariationValue",
            "Defence Material - Variation Value",
            True,
            int,
            'It is a value used in combination with the defense material to classify abnormal conditions, damage SFX, and SE. SEQ16473',
        ),
        ParamFieldInfo(
            "isDiscard:1",
            "Can Discard",
            True,
            int,
            'Can you throw away the item? TRUE = thrown away',
        ),
        ParamFieldInfo(
            "isDrop:1",
            "Can Drop",
            True,
            int,
            'Can I put the item on the spot? TRUE = can be placed',
        ),
        ParamFieldInfo(
            "disableMultiDropShare:1",
            "Cannot Drop in Multiplayer",
            True,
            int,
            'Is multi-drop sharing prohibited?',
        ),
        ParamFieldInfo(
            "simpleModelForDlc:1",
            "Simple Model for DLC1",
            True,
            int,
            'Is there a simple model for DLC?',
        ),
        ParamFieldInfo(
            "showLogCondType:1",
            "Item Acquisition Log Condition Type",
            True,
            int,
            'Whether to display in the item acquisition log when acquiring the item (not entered: ��)',
        ),
        ParamFieldInfo(
            "showDialogCondType:2",
            "Item Acquisition Dialog Condition Type ",
            True,
            int,
            'Whether to display it in the item acquisition dialog when acquiring an item (not entered: new only)',
        ),
        ParamFieldInfo(
            "pad:1",
            "Padding",
            False,
            bit_pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "neutralDamageCutRate",
            "Absorption - Physical",
            True,
            float,
            'Non-attribute damage multiplier',
        ),
        ParamFieldInfo(
            "slashDamageCutRate",
            "Absorption - Slash",
            True,
            float,
            'Slash damage multiplier',
        ),
        ParamFieldInfo(
            "blowDamageCutRate",
            "Absorption - Strike",
            True,
            float,
            'Batter damage multiplier',
        ),
        ParamFieldInfo(
            "thrustDamageCutRate",
            "Absorption - Thrust",
            True,
            float,
            'Puncture damage ratio',
        ),
        ParamFieldInfo(
            "magicDamageCutRate",
            "Absorption - Magic",
            True,
            float,
            'Magic damage multiplier',
        ),
        ParamFieldInfo(
            "fireDamageCutRate",
            "Absorption - Fire",
            True,
            float,
            'Flame damage multiplier',
        ),
        ParamFieldInfo(
            "thunderDamageCutRate",
            "Absorption - Lightning",
            True,
            float,
            'Electric shock damage ratio',
        ),
        ParamFieldInfo(
            "defenseMaterialSfx1",
            "Defence Material SFX [1]",
            True,
            int,
            'For SFX when moving / defending. 1',
        ),
        ParamFieldInfo(
            "defenseMaterialSfx_Weak1",
            "Defence Material SFX - Weakness [1]",
            True,
            int,
            'For SFX when weak points are damaged 1',
        ),
        ParamFieldInfo(
            "defenseMaterial1",
            "Defence Material - SE [1]",
            True,
            int,
            'For SE when moving / defending. 1',
        ),
        ParamFieldInfo(
            "defenseMaterial_Weak1",
            "Defence Material SE - Weakness [1]",
            True,
            int,
            'For SE when weak points are damaged 1',
        ),
        ParamFieldInfo(
            "defenseMaterialSfx2",
            "Defence Material SFX [2]",
            True,
            int,
            'For SFX when moving / defending. 2',
        ),
        ParamFieldInfo(
            "defenseMaterialSfx_Weak2",
            "Defence Material SFX - Weakness [2]",
            True,
            int,
            '2 for SFX when weak points are damaged',
        ),
        ParamFieldInfo(
            "footMaterialSe",
            "Foot Material SE",
            True,
            int,
            'Material for foot equipment SE. Only foot equipment is referenced. ([GR] SEQ10061) In the case of "139: None", the defense material 1 [SE] is referred to.',
        ),
        ParamFieldInfo(
            "defenseMaterial_Weak2",
            "Defence Material SE - Weakness [2]",
            True,
            int,
            '2 for SE when weak points are damaged',
        ),
        ParamFieldInfo(
            "autoFootEffectDecalBaseId1",
            "Auto Foot Effect Decal Base ID [1]",
            True,
            int,
            'Decal ID for automatic foot effects. Floor material is also considered. Only used when the "armor category" is "legs".',
        ),
        ParamFieldInfo(
            "toughnessDamageCutRate",
            "Toughness Absorption",
            True,
            float,
            'Toughness version cut rate',
        ),
        ParamFieldInfo(
            "toughnessRecoverCorrection",
            "Toughness Recovery Correction",
            True,
            float,
            'Correction value for toughness recovery time',
        ),
        ParamFieldInfo(
            "darkDamageCutRate",
            "Absorption - Holy",
            True,
            float,
            'Dark damage multiplier',
        ),
        ParamFieldInfo(
            "defenseDark",
            "Defence - Holy",
            True,
            int,
            'Dark attack damage protection.',
        ),
        ParamFieldInfo(
            "invisibleFlag48:1",
            "PAD_original_ # 48 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 48 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag49:1",
            "PAD_original_ # 49 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 49 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag50:1",
            "PAD_original_ # 50 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 50 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag51:1",
            "PAD_original_ # 51 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 51 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag52:1",
            "PAD_original_ # 52 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 52 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag53:1",
            "PAD_original_ # 53 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 53 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag54:1",
            "PAD_original_ # 54 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 54 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag55:1",
            "PAD_original_ # 55 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 55 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag56:1",
            "PAD_original_ # 56 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 56 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag57:1",
            "PAD_original_ # 57 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 57 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag58:1",
            "PAD_original_ # 58 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 58 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag59:1",
            "PAD_original_ # 59 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 59 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag60:1",
            "PAD_original_ # 60 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 60 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag61:1",
            "PAD_original_ # 61 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 61 # Hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag62:1",
            "PAD_original_ # 62 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 62 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag63:1",
            "PAD_original_ # 63 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 63 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag64:1",
            "PAD_original_ # 64 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 64 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag65:1",
            "PAD_original_ # 65 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 65 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag66:1",
            "PAD_original_ # 66 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 66 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag67:1",
            "PAD_original_ # 67 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 67 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag68:1",
            "PAD_original_ # 68 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 68 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag69:1",
            "PAD_original_ # 69 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 69 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag70:1",
            "PAD_original_ # 70 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 70 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag71:1",
            "PAD_original_ # 71 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 71 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag72:1",
            "PAD_original_ # 72 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 72 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag73:1",
            "PAD_original_ # 73 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 73 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag74:1",
            "PAD_original_ # 74 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 74 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag75:1",
            "PAD_original_ # 75 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 75 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag76:1",
            "PAD_original_ # 76 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 76 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag77:1",
            "PAD_original_ # 77 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 77 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag78:1",
            "PAD_original_ # 78 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 78 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag79:1",
            "PAD_original_ # 79 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 79 # hidden',
        ),
        ParamFieldInfo(
            "invisibleFlag80:1",
            "PAD_original_ # 80 # hidden",
            False,
            bit_pad_field(1),
            'Original _ # 80 # hidden',
        ),
        ParamFieldInfo(
            "padbit:7",
            "Padding",
            False,
            bit_pad_field(7),
            '',
        ),
        ParamFieldInfo(
            "postureControlId",
            "Posture Control ID",
            True,
            int,
            'Attitude control ID (torso)',
        ),
        ParamFieldInfo(
            "pad2[4]",
            "pad",
            False,
            pad_field(4),
            '',
        ),
        ParamFieldInfo(
            "saleValue",
            "Shop Price",
            True,
            int,
            'Selling price',
        ),
        ParamFieldInfo(
            "resistFreeze",
            "Resist - Frost",
            True,
            int,
            'Difficulty in getting cold air condition abnormal',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer00",
            "Mask 00 - Hide upper front face",
            True,
            int,
            'Bangs tip',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer01",
            "Mask 01 - Hide lower front face",
            True,
            int,
            'Bangs root',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer02",
            "Mask 02 - Hide middle front face",
            True,
            int,
            'Sideburns',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer03",
            "Mask 03 - Hide top and back of head",
            True,
            int,
            'Top of the head',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer04",
            "Mask 04 - Hide neck",
            True,
            int,
            'Top of the head',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer05",
            "Mask 05 - Hide neckline and shoulders",
            True,
            int,
            'Back hair',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer06",
            "Mask 06 - Hide upper torso area, reduce back size",
            True,
            int,
            'The tip of the back hair',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer07",
            "Mask 07 - Reduce bicep size",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer08",
            "Mask 08 - Reduce shoulder and upper bicep size",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer09",
            "Mask 09 - Hide elbows",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer10",
            "Mask 10 - Hide lower forearms",
            True,
            int,
            'collar',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer11",
            "Mask 11 - Hide right hand",
            True,
            int,
            'Around the collar',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer12",
            "Mask 12 - Hide upper leg area",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer13",
            "Mask 13 - Hide left hand",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer14",
            "Mask 14 - Hide lower leg area",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer15",
            "Mask 15 - Hide calves",
            True,
            int,
            'Hood hem',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer16",
            "Mask 16 - Hide feet",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer17",
            "Mask 17 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer18",
            "Mask 18 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer19",
            "Mask 19 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer20",
            "Mask 20 - Alter Armor Part",
            True,
            int,
            'Sleeve A',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer21",
            "Mask 21 - Alter Armor Part",
            True,
            int,
            'Sleeve B',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer22",
            "Mask 22 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer23",
            "Mask 23 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer24",
            "Mask 24 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer25",
            "Mask 25 - Alter Armor Part",
            True,
            int,
            'arm',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer26",
            "Mask 26 - Hide arms (for specific chest armor)",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer27",
            "Mask 27 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer28",
            "Mask 28 - Hide shoulders and shoulder armor",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer29",
            "Mask 29 - Hide wrist cloth",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer30",
            "Mask 30 - Alter Armor Part",
            True,
            int,
            'belt',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer31",
            "Mask 31 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer32",
            "Mask 32 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer33",
            "Mask 33 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer34",
            "Mask 34 - Alter Neck/Shoulder Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer35",
            "Mask 35 - Alter Lower Stomach Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer36",
            "Mask 36 - Alter Hood Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer37",
            "Mask 37 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer38",
            "Mask 38 - Hide Left Shoulder Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer39",
            "Mask 39 - Hide Right Shoulder Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer40",
            "Mask 40 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer41",
            "Mask 41 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer42",
            "Mask 42 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer43",
            "Mask 43 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer44",
            "Mask 44 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer45",
            "Mask 45 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer46",
            "Mask 46 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer47",
            "Mask 47 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer48",
            "Mask 48 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer49",
            "Mask 49 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer50",
            "Mask 50 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer51",
            "Mask 51 - Head: Hide Leg Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer52",
            "Mask 52 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer53",
            "Mask 53 - Head: Hide Knee Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer54",
            "Mask 54 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer55",
            "Mask 55 - Head: Hide Belt Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer56",
            "Mask 56 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer57",
            "Mask 57 - Head: Hide Skirt Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer58",
            "Mask 58 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer59",
            "Mask 59 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer60",
            "Mask 60 - Hide hair scalp",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer61",
            "Mask 61 - Hide hair low",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer62",
            "Mask 62 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer63",
            "Mask 63 - Hide hair top in",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer64",
            "Mask 64 - Hide hair top out",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer65",
            "Mask 65 - Hide hair front in",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer66",
            "Mask 66 - Hide hair front out",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer67",
            "Mask 67 - Hide hair sides",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer68",
            "Mask 68 - Hide hair back",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer69",
            "Mask 69 - Hide ponytail",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer70",
            "Mask 70 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer71",
            "Mask 71 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer72",
            "Mask 72 - Alter Prisoner Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer73",
            "Mask 73 - Alter Fia Clothing Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer74",
            "Mask 74 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer75",
            "Mask 75 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer76",
            "Mask 76 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer77",
            "Mask 77 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer78",
            "Mask 78 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer79",
            "Mask 79 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer80",
            "Mask 80 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer81",
            "Mask 81 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer82",
            "Mask 82 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer83",
            "Mask 83 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer84",
            "Mask 84 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer85",
            "Mask 85 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer86",
            "Mask 86 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer87",
            "Mask 87 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer88",
            "Mask 88 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer89",
            "Mask 89 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer90",
            "Mask 90 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer91",
            "Mask 91 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer92",
            "Mask 92 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer93",
            "Mask 93 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer94",
            "Mask 94 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "invisibleFlag_SexVer95",
            "Mask 95 - Alter Armor Part",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "pad404[14]",
            "Padding",
            False,
            pad_field(14),
            'Padding',
        ),
    ],
}
