from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


FACE_PARAM_ST = {
    "param_type": "FACE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "face_partsId",
            "Face - Parts ID",
            True,
            int,
            'Face part ID',
        ),
        ParamFieldInfo(
            "skin_color_R",
            "Skin - Color: R",
            True,
            int,
            'Skin color (R)',
        ),
        ParamFieldInfo(
            "skin_color_G",
            "Skin - Color: G",
            True,
            int,
            'Skin color (G)',
        ),
        ParamFieldInfo(
            "skin_color_B",
            "Skin - Color: B",
            True,
            int,
            'Skin color (B)',
        ),
        ParamFieldInfo(
            "skin_gloss",
            "Skin - Gloss",
            True,
            int,
            'Shiny skin',
        ),
        ParamFieldInfo(
            "skin_pores",
            "Skin - Pores",
            True,
            int,
            'pores',
        ),
        ParamFieldInfo(
            "face_beard",
            "Face - Beard",
            True,
            int,
            'Blue beard',
        ),
        ParamFieldInfo(
            "face_aroundEye",
            "Face - Around Eye",
            True,
            int,
            'Bear',
        ),
        ParamFieldInfo(
            "face_aroundEyeColor_R",
            "Face - Around Eye Color: R",
            True,
            int,
            'Bear color (R)',
        ),
        ParamFieldInfo(
            "face_aroundEyeColor_G",
            "Face - Around Eye Color: G",
            True,
            int,
            'Bear color (G)',
        ),
        ParamFieldInfo(
            "face_aroundEyeColor_B",
            "Face - Around Eye Color: B",
            True,
            int,
            'Bear color (B)',
        ),
        ParamFieldInfo(
            "face_cheek",
            "Face - Cheek",
            True,
            int,
            'cheek',
        ),
        ParamFieldInfo(
            "face_cheekColor_R",
            "Face - Cheek Color: R",
            True,
            int,
            'Teak color (R)',
        ),
        ParamFieldInfo(
            "face_cheekColor_G",
            "Face - Cheek Color: G",
            True,
            int,
            'Teak color (G)',
        ),
        ParamFieldInfo(
            "face_cheekColor_B",
            "Face - Cheek Color: B",
            True,
            int,
            'Teak color (B)',
        ),
        ParamFieldInfo(
            "face_eyeLine",
            "Face - Eyeline",
            True,
            int,
            'Eyeline',
        ),
        ParamFieldInfo(
            "face_eyeLineColor_R",
            "Face - Eyeline Color: R",
            True,
            int,
            'Eyeliner color (R)',
        ),
        ParamFieldInfo(
            "face_eyeLineColor_G",
            "Face - Eyeline Color: G",
            True,
            int,
            'Eyeliner color (G)',
        ),
        ParamFieldInfo(
            "face_eyeLineColor_B",
            "Face - Eyeline Color: B",
            True,
            int,
            'Eyeliner color (B)',
        ),
        ParamFieldInfo(
            "face_eyeShadowDown",
            "Face - Eyeshadow (Down)",
            True,
            int,
            'Eye shadow (bottom)',
        ),
        ParamFieldInfo(
            "face_eyeShadowDownColor_R",
            "Face - Eyeshadow (Down) Color: R",
            True,
            int,
            'Eyeshadow (bottom) color (R)',
        ),
        ParamFieldInfo(
            "face_eyeShadowDownColor_G",
            "Face - Eyeshadow (Down) Color: G",
            True,
            int,
            'Eyeshadow (bottom) color (G)',
        ),
        ParamFieldInfo(
            "face_eyeShadowDownColor_B",
            "Face - Eyeshadow (Down) Color: B",
            True,
            int,
            'Eyeshadow (bottom) color (B)',
        ),
        ParamFieldInfo(
            "face_eyeShadowUp",
            "Face - Eyeshadow (Up)",
            True,
            int,
            'Eye shadow (top)',
        ),
        ParamFieldInfo(
            "face_eyeShadowUpColor_R",
            "Face - Eyeshadow (Up) Color: R",
            True,
            int,
            'Eyeshadow (top) color (R)',
        ),
        ParamFieldInfo(
            "face_eyeShadowUpColor_G",
            "Face - Eyeshadow (Up) Color: G",
            True,
            int,
            'Eyeshadow (top) color (G)',
        ),
        ParamFieldInfo(
            "face_eyeShadowUpColor_B",
            "Face - Eyeshadow (Up) Color: B",
            True,
            int,
            'Eyeshadow (top) color (B)',
        ),
        ParamFieldInfo(
            "face_lip",
            "Face - Lip",
            True,
            int,
            'lipstick',
        ),
        ParamFieldInfo(
            "face_lipColor_R",
            "Face - Lip Color: R",
            True,
            int,
            'Lipstick color (R)',
        ),
        ParamFieldInfo(
            "face_lipColor_G",
            "Face - Lip Color: G",
            True,
            int,
            'Lipstick color (G)',
        ),
        ParamFieldInfo(
            "face_lipColor_B",
            "Face - Lip Color: B",
            True,
            int,
            'Lipstick color (B)',
        ),
        ParamFieldInfo(
            "body_hair",
            "Body - Hair",
            True,
            int,
            'Hair thickness',
        ),
        ParamFieldInfo(
            "body_hairColor_R",
            "Body - Hair Color: R",
            True,
            int,
            'Hair color (R)',
        ),
        ParamFieldInfo(
            "body_hairColor_G",
            "Body - Hair Color: G",
            True,
            int,
            'Hair color (G)',
        ),
        ParamFieldInfo(
            "body_hairColor_B",
            "Body - Hair Color: B",
            True,
            int,
            'Hair color (B)',
        ),
        ParamFieldInfo(
            "eye_partsId",
            "Eyes - Parts ID",
            True,
            int,
            'Eyeball part ID',
        ),
        ParamFieldInfo(
            "eyeR_irisColor_R",
            "Right Eye - Iris Color: R",
            True,
            int,
            'Right eye iris color (R)',
        ),
        ParamFieldInfo(
            "eyeR_irisColor_G",
            "Right Eye - Iris Color: G",
            True,
            int,
            'Right eye iris color (G)',
        ),
        ParamFieldInfo(
            "eyeR_irisColor_B",
            "Right Eye - Iris Color: B",
            True,
            int,
            'Right eye iris color (B)',
        ),
        ParamFieldInfo(
            "eyeR_irisScale",
            "Right Eye - Iris Scale",
            True,
            int,
            'The size of the iris of the right eye',
        ),
        ParamFieldInfo(
            "eyeR_cataract",
            "Right Eye - Cataract",
            True,
            int,
            'Cloudiness of the crystalline lens of the right eye',
        ),
        ParamFieldInfo(
            "eyeR_cataractColor_R",
            "Right Eye - Cataract Color: R",
            True,
            int,
            'The turbid color of the crystalline lens of the right eye (R)',
        ),
        ParamFieldInfo(
            "eyeR_cataractColor_G",
            "Right Eye - Cataract Color: G",
            True,
            int,
            'The turbid color of the crystalline lens of the right eye (G)',
        ),
        ParamFieldInfo(
            "eyeR_cataractColor_B",
            "Right Eye - Cataract Color: B",
            True,
            int,
            'The turbid color of the crystalline lens of the right eye (B)',
        ),
        ParamFieldInfo(
            "eyeR_scleraColor_R",
            "Right Eye - Sclera Color: R",
            True,
            int,
            'White eye color of the right eye (R)',
        ),
        ParamFieldInfo(
            "eyeR_scleraColor_G",
            "Right Eye - Sclera Color: G",
            True,
            int,
            'White eye color of the right eye (G)',
        ),
        ParamFieldInfo(
            "eyeR_scleraColor_B",
            "Right Eye - Sclera Color: B",
            True,
            int,
            'White eye color of the right eye (B)',
        ),
        ParamFieldInfo(
            "eyeR_irisDistance",
            "Right Eye - Iris Distance",
            True,
            int,
            'Position of the iris of the right eye',
        ),
        ParamFieldInfo(
            "eyeL_irisColor_R",
            "Left Eye - Iris Color: R",
            True,
            int,
            'Left eye iris color (R)',
        ),
        ParamFieldInfo(
            "eyeL_irisColor_G",
            "Left Eye - Iris Color: G",
            True,
            int,
            'Left eye iris color (G)',
        ),
        ParamFieldInfo(
            "eyeL_irisColor_B",
            "Left Eye - Iris Color: B",
            True,
            int,
            'Left eye iris color (B)',
        ),
        ParamFieldInfo(
            "eyeL_irisScale",
            "Left Eye - Iris Scale",
            True,
            int,
            'The size of the iris of the left eye',
        ),
        ParamFieldInfo(
            "eyeL_cataract",
            "Left Eye - Cataract",
            True,
            int,
            'Cloudiness of the crystalline lens of the left eye',
        ),
        ParamFieldInfo(
            "eyeL_cataractColor_R",
            "Left Eye - Cataract Color: R",
            True,
            int,
            'The turbid color of the crystalline lens of the left eye (R)',
        ),
        ParamFieldInfo(
            "eyeL_cataractColor_G",
            "Left Eye - Cataract Color: G",
            True,
            int,
            'The turbid color of the crystalline lens of the left eye (G)',
        ),
        ParamFieldInfo(
            "eyeL_cataractColor_B",
            "Left Eye - Cataract Color: B",
            True,
            int,
            'The turbid color of the crystalline lens of the left eye (B)',
        ),
        ParamFieldInfo(
            "eyeL_scleraColor_R",
            "Left Eye - Sclera Color: R",
            True,
            int,
            'White eye color of the left eye (R)',
        ),
        ParamFieldInfo(
            "eyeL_scleraColor_G",
            "Left Eye - Sclera Color: G",
            True,
            int,
            'White eye color of the left eye (G)',
        ),
        ParamFieldInfo(
            "eyeL_scleraColor_B",
            "Left Eye - Sclera Color: B",
            True,
            int,
            'White eye color of the left eye (B)',
        ),
        ParamFieldInfo(
            "eyeL_irisDistance",
            "Left Eye - Iris Distance",
            True,
            int,
            'Position of the iris of the left eye',
        ),
        ParamFieldInfo(
            "hair_partsId",
            "Hair - Parts ID",
            True,
            int,
            'Hair part ID',
        ),
        ParamFieldInfo(
            "hair_color_R",
            "Hair - Color: R",
            True,
            int,
            'Hair color (R)',
        ),
        ParamFieldInfo(
            "hair_color_G",
            "Hair - Color: G",
            True,
            int,
            'Hair color (G)',
        ),
        ParamFieldInfo(
            "hair_color_B",
            "Hair - Color: B",
            True,
            int,
            'Hair color (B)',
        ),
        ParamFieldInfo(
            "hair_shininess",
            "Hair - Shininess",
            True,
            int,
            'Hair gloss',
        ),
        ParamFieldInfo(
            "hair_rootBlack",
            "Hair - Root Black",
            True,
            int,
            'Blackness at the base of hair',
        ),
        ParamFieldInfo(
            "hair_whiteDensity",
            "Hair - White Density",
            True,
            int,
            'Amount of white hair',
        ),
        ParamFieldInfo(
            "beard_partsId",
            "Beard - Parts ID",
            True,
            int,
            'Beard part ID',
        ),
        ParamFieldInfo(
            "beard_color_R",
            "Beard - Color: R",
            True,
            int,
            'Beard color (R)',
        ),
        ParamFieldInfo(
            "beard_color_G",
            "Beard - Color: G",
            True,
            int,
            'Beard color (G)',
        ),
        ParamFieldInfo(
            "beard_color_B",
            "Beard - Color: B",
            True,
            int,
            'Beard color (B)',
        ),
        ParamFieldInfo(
            "beard_shininess",
            "Beard - Shininess",
            True,
            int,
            'Beard luster',
        ),
        ParamFieldInfo(
            "beard_rootBlack",
            "Beard - Root Black",
            True,
            int,
            'Blackness at the base of the beard',
        ),
        ParamFieldInfo(
            "beard_whiteDensity",
            "Beard - White Density",
            True,
            int,
            'Amount of white hair with a beard',
        ),
        ParamFieldInfo(
            "eyebrow_partsId",
            "Eyebrow - Parts ID",
            True,
            int,
            'Eyebrow part ID',
        ),
        ParamFieldInfo(
            "eyebrow_color_R",
            "Eyebrow - Color: R",
            True,
            int,
            'Eyebrow color (R)',
        ),
        ParamFieldInfo(
            "eyebrow_color_G",
            "Eyebrow - Color: G",
            True,
            int,
            'Eyebrow color (G)',
        ),
        ParamFieldInfo(
            "eyebrow_color_B",
            "Eyebrow - Color: B",
            True,
            int,
            'Eyebrow color (B)',
        ),
        ParamFieldInfo(
            "eyebrow_shininess",
            "Eyebrow - Shininess",
            True,
            int,
            'Glossy eyebrows',
        ),
        ParamFieldInfo(
            "eyebrow_rootBlack",
            "Eyebrow - Root Black",
            True,
            int,
            'Blackness at the base of the eyebrows',
        ),
        ParamFieldInfo(
            "eyebrow_whiteDensity",
            "Eyebrow - White Density",
            True,
            int,
            'Amount of white hair on the eyebrows',
        ),
        ParamFieldInfo(
            "eyelash_partsId",
            "Eyelash - Parts ID",
            True,
            int,
            'Eyelash parts ID',
        ),
        ParamFieldInfo(
            "eyelash_color_R",
            "Eyelash - Color: R",
            True,
            int,
            'Eyelash color (R)',
        ),
        ParamFieldInfo(
            "eyelash_color_G",
            "Eyelash - Color: G",
            True,
            int,
            'Eyelash color (G)',
        ),
        ParamFieldInfo(
            "eyelash_color_B",
            "Eyelash - Color: B",
            True,
            int,
            'Eyelash color (B)',
        ),
        ParamFieldInfo(
            "accessories_partsId",
            "Accessories - Parts ID",
            True,
            int,
            'Decorative part ID',
        ),
        ParamFieldInfo(
            "accessories_color_R",
            "Accessories - Color: R",
            True,
            int,
            'Decoration color (R)',
        ),
        ParamFieldInfo(
            "accessories_color_G",
            "Accessories - Color: G",
            True,
            int,
            'Decoration color (G)',
        ),
        ParamFieldInfo(
            "accessories_color_B",
            "Accessories - Color: B",
            True,
            int,
            'Decorative color (B)',
        ),
        ParamFieldInfo(
            "decal_partsId",
            "Decal - Parts ID",
            True,
            int,
            'Decal part ID',
        ),
        ParamFieldInfo(
            "decal_posX",
            "Decal - Position: X",
            True,
            int,
            'Decal position (x)',
        ),
        ParamFieldInfo(
            "decal_posY",
            "Decal - Position: Y",
            True,
            int,
            'Decal position (y)',
        ),
        ParamFieldInfo(
            "decal_angle",
            "Decal - Angle",
            True,
            int,
            'Decal angle',
        ),
        ParamFieldInfo(
            "decal_scale",
            "Decal - Scale",
            True,
            int,
            'Decal scale',
        ),
        ParamFieldInfo(
            "decal_color_R",
            "Decal - Color: R",
            True,
            int,
            'Decal color (R)',
        ),
        ParamFieldInfo(
            "decal_color_G",
            "Decal - Color: G",
            True,
            int,
            'Decal color (G)',
        ),
        ParamFieldInfo(
            "decal_color_B",
            "Decal - Color: B",
            True,
            int,
            'Decal color (B)',
        ),
        ParamFieldInfo(
            "decal_gloss",
            "Decal - Gloss",
            True,
            int,
            'Decal gloss',
        ),
        ParamFieldInfo(
            "decal_mirror",
            "Decal - Mirror",
            True,
            int,
            'Decal reversal',
        ),
        ParamFieldInfo(
            "chrBodyScaleHead",
            "Chr Body Scale - Head",
            True,
            int,
            'Character body head scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleBreast",
            "Chr Body Scale - Breast",
            True,
            int,
            'Character body chest scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleAbdomen",
            "Chr Body Scale - Abdomen",
            True,
            int,
            'Character body type abdominal scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleRArm",
            "Chr Body Scale - Right Arm",
            True,
            int,
            'Character body right arm scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleRLeg",
            "Chr Body Scale - Right Leg",
            True,
            int,
            'Character body right leg scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleLArm",
            "Chr Body Scale - Left Arm",
            True,
            int,
            'Character body shape left arm scale',
        ),
        ParamFieldInfo(
            "chrBodyScaleLLeg",
            "Chr Body Scale - Left Leg",
            True,
            int,
            'Character body type left leg scale',
        ),
        ParamFieldInfo(
            "burn_scar",
            "Burn Scar",
            True,
            int,
            'Burn scars',
        ),
        ParamFieldInfo(
            "override_eye_partsId:1",
            "Override - Eye - Parts ID",
            True,
            int,
            'Whether to overwrite the eyeball part ID',
        ),
        ParamFieldInfo(
            "override_eye_irisColor:1",
            "Override - Eye - Iris Color",
            True,
            int,
            'Do you want to overwrite the color of the iris?',
        ),
        ParamFieldInfo(
            "override_eye_cataract:1",
            "Override - Eye - Cataract",
            True,
            int,
            'Do you want to overwrite the turbidity of the crystalline lens?',
        ),
        ParamFieldInfo(
            "override_eye_cataractColor:1",
            "Override - Eye - Cataract Color",
            True,
            int,
            'Do you want to overwrite the muddy color of the crystalline lens?',
        ),
        ParamFieldInfo(
            "override_eye_scleraColor:1",
            "Override - Eye - Sclera Color",
            True,
            int,
            'Do you want to overwrite the white eye color?',
        ),
        ParamFieldInfo(
            "override_burn_scar:1",
            "Override - Burn Scar",
            True,
            int,
            'Do you want to overwrite the burn scars?',
        ),
        ParamFieldInfo(
            "pad2:2",
            "pad2",
            False,
            bit_pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "pad[5]",
            "pad",
            False,
            pad_field(5),
            '',
        ),
        ParamFieldInfo(
            "age",
            "Age",
            True,
            int,
            'age',
        ),
        ParamFieldInfo(
            "gender",
            "Gender",
            True,
            int,
            'sex',
        ),
        ParamFieldInfo(
            "caricatureGeometry",
            "Model Geometry",
            True,
            int,
            'Exaggeration (model)',
        ),
        ParamFieldInfo(
            "caricatureTexture",
            "Model Texture",
            True,
            int,
            'Exaggeration (texture)',
        ),
        ParamFieldInfo(
            "faceGeoData00",
            "Face - Geo Data [00]",
            True,
            int,
            'Face - Geo Data [00]',
        ),
        ParamFieldInfo(
            "faceGeoData01",
            "Face - Geo Data [01]",
            True,
            int,
            'Face - Geo Data [01]',
        ),
        ParamFieldInfo(
            "faceGeoData02",
            "Face - Geo Data [02]",
            True,
            int,
            'Face - Geo Data [02]',
        ),
        ParamFieldInfo(
            "faceGeoData03",
            "Face - Geo Data [03]",
            True,
            int,
            'Face - Geo Data [03]',
        ),
        ParamFieldInfo(
            "faceGeoData04",
            "Face - Geo Data [04]",
            True,
            int,
            'Face - Geo Data [04]',
        ),
        ParamFieldInfo(
            "faceGeoData05",
            "Face - Geo Data [05]",
            True,
            int,
            'Face - Geo Data [05]',
        ),
        ParamFieldInfo(
            "faceGeoData06",
            "Face - Geo Data [06]",
            True,
            int,
            'Face - Geo Data [06]',
        ),
        ParamFieldInfo(
            "faceGeoData07",
            "Face - Geo Data [07]",
            True,
            int,
            'Face - Geo Data [07]',
        ),
        ParamFieldInfo(
            "faceGeoData08",
            "Face - Geo Data [08]",
            True,
            int,
            'Face - Geo Data [08]',
        ),
        ParamFieldInfo(
            "faceGeoData09",
            "Face - Geo Data [09]",
            True,
            int,
            'Face - Geo Data [09]',
        ),
        ParamFieldInfo(
            "faceGeoData10",
            "Face - Geo Data [10]",
            True,
            int,
            'Face - Geo Data [10]',
        ),
        ParamFieldInfo(
            "faceGeoData11",
            "Face - Geo Data [11]",
            True,
            int,
            'Face - Geo Data [11]',
        ),
        ParamFieldInfo(
            "faceGeoData12",
            "Face - Geo Data [12]",
            True,
            int,
            'Face - Geo Data [12]',
        ),
        ParamFieldInfo(
            "faceGeoData13",
            "Face - Geo Data [13]",
            True,
            int,
            'Face - Geo Data [13]',
        ),
        ParamFieldInfo(
            "faceGeoData14",
            "Face - Geo Data [14]",
            True,
            int,
            'Face - Geo Data [14]',
        ),
        ParamFieldInfo(
            "faceGeoData15",
            "Face - Geo Data [15]",
            True,
            int,
            'Face - Geo Data [15]',
        ),
        ParamFieldInfo(
            "faceGeoData16",
            "Face - Geo Data [16]",
            True,
            int,
            'Face - Geo Data [16]',
        ),
        ParamFieldInfo(
            "faceGeoData17",
            "Face - Geo Data [17]",
            True,
            int,
            'Face - Geo Data [17]',
        ),
        ParamFieldInfo(
            "faceGeoData18",
            "Face - Geo Data [18]",
            True,
            int,
            'Face - Geo Data [18]',
        ),
        ParamFieldInfo(
            "faceGeoData19",
            "Face - Geo Data [19]",
            True,
            int,
            'Face - Geo Data [19]',
        ),
        ParamFieldInfo(
            "faceGeoData20",
            "Face - Geo Data [20]",
            True,
            int,
            'Face - Geo Data [20]',
        ),
        ParamFieldInfo(
            "faceGeoData21",
            "Face - Geo Data [21]",
            True,
            int,
            'Face - Geo Data [21]',
        ),
        ParamFieldInfo(
            "faceGeoData22",
            "Face - Geo Data [22]",
            True,
            int,
            'Face - Geo Data [22]',
        ),
        ParamFieldInfo(
            "faceGeoData23",
            "Face - Geo Data [23]",
            True,
            int,
            'Face - Geo Data [23]',
        ),
        ParamFieldInfo(
            "faceGeoData24",
            "Face - Geo Data [24]",
            True,
            int,
            'Face - Geo Data [24]',
        ),
        ParamFieldInfo(
            "faceGeoData25",
            "Face - Geo Data [25]",
            True,
            int,
            'Face - Geo Data [25]',
        ),
        ParamFieldInfo(
            "faceGeoData26",
            "Face - Geo Data [26]",
            True,
            int,
            'Face - Geo Data [26]',
        ),
        ParamFieldInfo(
            "faceGeoData27",
            "Face - Geo Data [27]",
            True,
            int,
            'Face - Geo Data [27]',
        ),
        ParamFieldInfo(
            "faceGeoData28",
            "Face - Geo Data [28]",
            True,
            int,
            'Face - Geo Data [28]',
        ),
        ParamFieldInfo(
            "faceGeoData29",
            "Face - Geo Data [29]",
            True,
            int,
            'Face - Geo Data [29]',
        ),
        ParamFieldInfo(
            "faceGeoData30",
            "Face - Geo Data [30]",
            True,
            int,
            'Face - Geo Data [30]',
        ),
        ParamFieldInfo(
            "faceGeoData31",
            "Face - Geo Data [31]",
            True,
            int,
            'Face - Geo Data [31]',
        ),
        ParamFieldInfo(
            "faceGeoData32",
            "Face - Geo Data [32]",
            True,
            int,
            'Face - Geo Data [32]',
        ),
        ParamFieldInfo(
            "faceGeoData33",
            "Face - Geo Data [33]",
            True,
            int,
            'Face - Geo Data [33]',
        ),
        ParamFieldInfo(
            "faceGeoData34",
            "Face - Geo Data [34]",
            True,
            int,
            'Face - Geo Data [34]',
        ),
        ParamFieldInfo(
            "faceGeoData35",
            "Face - Geo Data [35]",
            True,
            int,
            'Face - Geo Data [35]',
        ),
        ParamFieldInfo(
            "faceGeoData36",
            "Face - Geo Data [36]",
            True,
            int,
            'Face - Geo Data [36]',
        ),
        ParamFieldInfo(
            "faceGeoData37",
            "Face - Geo Data [37]",
            True,
            int,
            'Face - Geo Data [37]',
        ),
        ParamFieldInfo(
            "faceGeoData38",
            "Face - Geo Data [38]",
            True,
            int,
            'Face - Geo Data [38]',
        ),
        ParamFieldInfo(
            "faceGeoData39",
            "Face - Geo Data [39]",
            True,
            int,
            'Face - Geo Data [39]',
        ),
        ParamFieldInfo(
            "faceGeoData40",
            "Face - Geo Data [40]",
            True,
            int,
            'Face - Geo Data [40]',
        ),
        ParamFieldInfo(
            "faceGeoData41",
            "Face - Geo Data [41]",
            True,
            int,
            'Face - Geo Data [41]',
        ),
        ParamFieldInfo(
            "faceGeoData42",
            "Face - Geo Data [42]",
            True,
            int,
            'Face - Geo Data [42]',
        ),
        ParamFieldInfo(
            "faceGeoData43",
            "Face - Geo Data [43]",
            True,
            int,
            'Face - Geo Data [43]',
        ),
        ParamFieldInfo(
            "faceGeoData44",
            "Face - Geo Data [44]",
            True,
            int,
            'Face - Geo Data [44]',
        ),
        ParamFieldInfo(
            "faceGeoData45",
            "Face - Geo Data [45]",
            True,
            int,
            'Face - Geo Data [45]',
        ),
        ParamFieldInfo(
            "faceGeoData46",
            "Face - Geo Data [46]",
            True,
            int,
            'Face - Geo Data [46]',
        ),
        ParamFieldInfo(
            "faceGeoData47",
            "Face - Geo Data [47]",
            True,
            int,
            'Face - Geo Data [47]',
        ),
        ParamFieldInfo(
            "faceGeoData48",
            "Face - Geo Data [48]",
            True,
            int,
            'Face - Geo Data [48]',
        ),
        ParamFieldInfo(
            "faceGeoData49",
            "Face - Geo Data [49]",
            True,
            int,
            'Face - Geo Data [49]',
        ),
        ParamFieldInfo(
            "faceGeoData50",
            "Face - Geo Data [50]",
            True,
            int,
            'Face - Geo Data [50]',
        ),
        ParamFieldInfo(
            "faceGeoData51",
            "Face - Geo Data [51]",
            True,
            int,
            'Face - Geo Data [51]',
        ),
        ParamFieldInfo(
            "faceGeoData52",
            "Face - Geo Data [52]",
            True,
            int,
            'Face - Geo Data [52]',
        ),
        ParamFieldInfo(
            "faceGeoData53",
            "Face - Geo Data [53]",
            True,
            int,
            'Face - Geo Data [53]',
        ),
        ParamFieldInfo(
            "faceGeoData54",
            "Face - Geo Data [54]",
            True,
            int,
            'Face - Geo Data [54]',
        ),
        ParamFieldInfo(
            "faceGeoData55",
            "Face - Geo Data [55]",
            True,
            int,
            'Face - Geo Data [55]',
        ),
        ParamFieldInfo(
            "faceGeoData56",
            "Face - Geo Data [56]",
            True,
            int,
            'Face - Geo Data [56]',
        ),
        ParamFieldInfo(
            "faceGeoData57",
            "Face - Geo Data [57]",
            True,
            int,
            'Face - Geo Data [57]',
        ),
        ParamFieldInfo(
            "faceGeoData58",
            "Face - Geo Data [58]",
            True,
            int,
            'Face - Geo Data [58]',
        ),
        ParamFieldInfo(
            "faceGeoData59",
            "Face - Geo Data [59]",
            True,
            int,
            'Face - Geo Data [59]',
        ),
        ParamFieldInfo(
            "faceGeoData60",
            "Face - Geo Data [60]",
            True,
            int,
            'Face - Geo Data [60]',
        ),
        ParamFieldInfo(
            "faceTexData00",
            "Face - Texture Data [00]",
            True,
            int,
            'Face - Texture Data [00]',
        ),
        ParamFieldInfo(
            "faceTexData01",
            "Face - Texture Data [01]",
            True,
            int,
            'Face - Texture Data [01]',
        ),
        ParamFieldInfo(
            "faceTexData02",
            "Face - Texture Data [02]",
            True,
            int,
            'Face - Texture Data [02]',
        ),
        ParamFieldInfo(
            "faceTexData03",
            "Face - Texture Data [03]",
            True,
            int,
            'Face - Texture Data [03]',
        ),
        ParamFieldInfo(
            "faceTexData04",
            "Face - Texture Data [04]",
            True,
            int,
            'Face - Texture Data [04]',
        ),
        ParamFieldInfo(
            "faceTexData05",
            "Face - Texture Data [05]",
            True,
            int,
            'Face - Texture Data [05]',
        ),
        ParamFieldInfo(
            "faceTexData06",
            "Face - Texture Data [06]",
            True,
            int,
            'Face - Texture Data [06]',
        ),
        ParamFieldInfo(
            "faceTexData07",
            "Face - Texture Data [07]",
            True,
            int,
            'Face - Texture Data [07]',
        ),
        ParamFieldInfo(
            "faceTexData08",
            "Face - Texture Data [08]",
            True,
            int,
            'Face - Texture Data [08]',
        ),
        ParamFieldInfo(
            "faceTexData09",
            "Face - Texture Data [09]",
            True,
            int,
            'Face - Texture Data [09]',
        ),
        ParamFieldInfo(
            "faceTexData10",
            "Face - Texture Data [10]",
            True,
            int,
            'Face - Texture Data [10]',
        ),
        ParamFieldInfo(
            "faceTexData11",
            "Face - Texture Data [11]",
            True,
            int,
            'Face - Texture Data [11]',
        ),
        ParamFieldInfo(
            "faceTexData12",
            "Face - Texture Data [12]",
            True,
            int,
            'Face - Texture Data [12]',
        ),
        ParamFieldInfo(
            "faceTexData13",
            "Face - Texture Data [13]",
            True,
            int,
            'Face - Texture Data [13]',
        ),
        ParamFieldInfo(
            "faceTexData14",
            "Face - Texture Data [14]",
            True,
            int,
            'Face - Texture Data [14]',
        ),
        ParamFieldInfo(
            "faceTexData15",
            "Face - Texture Data [15]",
            True,
            int,
            'Face - Texture Data [15]',
        ),
        ParamFieldInfo(
            "faceTexData16",
            "Face - Texture Data [16]",
            True,
            int,
            'Face - Texture Data [16]',
        ),
        ParamFieldInfo(
            "faceTexData17",
            "Face - Texture Data [17]",
            True,
            int,
            'Face - Texture Data [17]',
        ),
        ParamFieldInfo(
            "faceTexData18",
            "Face - Texture Data [18]",
            True,
            int,
            'Face - Texture Data [18]',
        ),
        ParamFieldInfo(
            "faceTexData19",
            "Face - Texture Data [19]",
            True,
            int,
            'Face - Texture Data [19]',
        ),
        ParamFieldInfo(
            "faceTexData20",
            "Face - Texture Data [20]",
            True,
            int,
            'Face - Texture Data [20]',
        ),
        ParamFieldInfo(
            "faceTexData21",
            "Face - Texture Data [21]",
            True,
            int,
            'Face - Texture Data [21]',
        ),
        ParamFieldInfo(
            "faceTexData22",
            "Face - Texture Data [22]",
            True,
            int,
            'Face - Texture Data [22]',
        ),
        ParamFieldInfo(
            "faceTexData23",
            "Face - Texture Data [23]",
            True,
            int,
            'Face - Texture Data [23]',
        ),
        ParamFieldInfo(
            "faceTexData24",
            "Face - Texture Data [24]",
            True,
            int,
            'Face - Texture Data [24]',
        ),
        ParamFieldInfo(
            "faceTexData25",
            "Face - Texture Data [25]",
            True,
            int,
            'Face - Texture Data [25]',
        ),
        ParamFieldInfo(
            "faceTexData26",
            "Face - Texture Data [26]",
            True,
            int,
            'Face - Texture Data [26]',
        ),
        ParamFieldInfo(
            "faceTexData27",
            "Face - Texture Data [27]",
            True,
            int,
            'Face - Texture Data [27]',
        ),
        ParamFieldInfo(
            "faceTexData28",
            "Face - Texture Data [28]",
            True,
            int,
            'Face - Texture Data [28]',
        ),
        ParamFieldInfo(
            "faceTexData29",
            "Face - Texture Data [29]",
            True,
            int,
            'Face - Texture Data [29]',
        ),
        ParamFieldInfo(
            "faceTexData30",
            "Face - Texture Data [30]",
            True,
            int,
            'Face - Texture Data [30]',
        ),
        ParamFieldInfo(
            "faceTexData31",
            "Face - Texture Data [31]",
            True,
            int,
            'Face - Texture Data [31]',
        ),
        ParamFieldInfo(
            "faceTexData32",
            "Face - Texture Data [32]",
            True,
            int,
            'Face - Texture Data [32]',
        ),
        ParamFieldInfo(
            "faceTexData33",
            "Face - Texture Data [33]",
            True,
            int,
            'Face - Texture Data [33]',
        ),
        ParamFieldInfo(
            "faceTexData34",
            "Face - Texture Data [34]",
            True,
            int,
            'Face - Texture Data [34]',
        ),
        ParamFieldInfo(
            "faceTexData35",
            "Face - Texture Data [35]",
            True,
            int,
            'Face - Texture Data [35]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData00",
            "Face - Geo Asym Data [00]",
            True,
            int,
            'Face - Geo Asym Data [00]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData01",
            "Face - Geo Asym Data [01]",
            True,
            int,
            'Face - Geo Asym Data [01]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData02",
            "Face - Geo Asym Data [02]",
            True,
            int,
            'Face - Geo Asym Data [02]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData03",
            "Face - Geo Asym Data [03]",
            True,
            int,
            'Face - Geo Asym Data [03]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData04",
            "Face - Geo Asym Data [04]",
            True,
            int,
            'Face - Geo Asym Data [04]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData05",
            "Face - Geo Asym Data [05]",
            True,
            int,
            'Face - Geo Asym Data [05]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData06",
            "Face - Geo Asym Data [06]",
            True,
            int,
            'Face - Geo Asym Data [06]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData07",
            "Face - Geo Asym Data [07]",
            True,
            int,
            'Face - Geo Asym Data [07]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData08",
            "Face - Geo Asym Data [08]",
            True,
            int,
            'Face - Geo Asym Data [08]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData09",
            "Face - Geo Asym Data [09]",
            True,
            int,
            'Face - Geo Asym Data [09]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData10",
            "Face - Geo Asym Data [10]",
            True,
            int,
            'Face - Geo Asym Data [10]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData11",
            "Face - Geo Asym Data [11]",
            True,
            int,
            'Face - Geo Asym Data [11]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData12",
            "Face - Geo Asym Data [12]",
            True,
            int,
            'Face - Geo Asym Data [12]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData13",
            "Face - Geo Asym Data [13]",
            True,
            int,
            'Face - Geo Asym Data [13]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData14",
            "Face - Geo Asym Data [14]",
            True,
            int,
            'Face - Geo Asym Data [14]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData15",
            "Face - Geo Asym Data [15]",
            True,
            int,
            'Face - Geo Asym Data [15]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData16",
            "Face - Geo Asym Data [16]",
            True,
            int,
            'Face - Geo Asym Data [16]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData17",
            "Face - Geo Asym Data [17]",
            True,
            int,
            'Face - Geo Asym Data [17]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData18",
            "Face - Geo Asym Data [18]",
            True,
            int,
            'Face - Geo Asym Data [18]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData19",
            "Face - Geo Asym Data [19]",
            True,
            int,
            'Face - Geo Asym Data [19]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData20",
            "Face - Geo Asym Data [20]",
            True,
            int,
            'Face - Geo Asym Data [20]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData21",
            "Face - Geo Asym Data [21]",
            True,
            int,
            'Face - Geo Asym Data [21]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData22",
            "Face - Geo Asym Data [22]",
            True,
            int,
            'Face - Geo Asym Data [22]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData23",
            "Face - Geo Asym Data [23]",
            True,
            int,
            'Face - Geo Asym Data [23]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData24",
            "Face - Geo Asym Data [24]",
            True,
            int,
            'Face - Geo Asym Data [24]',
        ),
        ParamFieldInfo(
            "faceGeoAsymData25",
            "Face - Geo Asym Data [25]",
            True,
            int,
            'Face - Geo Asym Data [25]',
        ),
    ],
}
