from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


FOOT_SFX_PARAM_ST = {
    "param_type": "FOOT_SFX_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "sfxId_00",
            "SFX ID [00]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_01",
            "SFX ID [01]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_02",
            "SFX ID [02]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_03",
            "SFX ID [03]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_04",
            "SFX ID [04]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_05",
            "SFX ID [05]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_06",
            "SFX ID [06]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_07",
            "SFX ID [07]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_08",
            "SFX ID [08]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_09",
            "SFX ID [09]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_10",
            "SFX ID [10]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_11",
            "SFX ID [11]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_12",
            "SFX ID [12]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_13",
            "SFX ID [13]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_14",
            "SFX ID [14]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_15",
            "SFX ID [15]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_16",
            "SFX ID [16]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_17",
            "SFX ID [17]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_18",
            "SFX ID [18]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_19",
            "SFX ID [19]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_20",
            "SFX ID [20]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_21",
            "SFX ID [21]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_22",
            "SFX ID [22]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_23",
            "SFX ID [23]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_24",
            "SFX ID [24]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_25",
            "SFX ID [25]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_26",
            "SFX ID [26]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_27",
            "SFX ID [27]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_28",
            "SFX ID [28]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_29",
            "SFX ID [29]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_30",
            "SFX ID [30]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_31",
            "SFX ID [31]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_32",
            "SFX ID [32]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_33",
            "SFX ID [33]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_34",
            "SFX ID [34]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_35",
            "SFX ID [35]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_36",
            "SFX ID [36]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_37",
            "SFX ID [37]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_38",
            "SFX ID [38]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_39",
            "SFX ID [39]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_40",
            "SFX ID [40]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_41",
            "SFX ID [41]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_42",
            "SFX ID [42]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_43",
            "SFX ID [43]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_44",
            "SFX ID [44]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_45",
            "SFX ID [45]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_46",
            "SFX ID [46]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_47",
            "SFX ID [47]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_48",
            "SFX ID [48]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_49",
            "SFX ID [49]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_50",
            "SFX ID [50]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_51",
            "SFX ID [51]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_52",
            "SFX ID [52]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_53",
            "SFX ID [53]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_54",
            "SFX ID [54]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_55",
            "SFX ID [55]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_56",
            "SFX ID [56]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_57",
            "SFX ID [57]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_58",
            "SFX ID [58]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_59",
            "SFX ID [59]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_60",
            "SFX ID [60]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_61",
            "SFX ID [61]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_62",
            "SFX ID [62]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_63",
            "SFX ID [63]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_64",
            "SFX ID [64]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_65",
            "SFX ID [65]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_66",
            "SFX ID [66]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_67",
            "SFX ID [67]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_68",
            "SFX ID [68]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_69",
            "SFX ID [69]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_70",
            "SFX ID [70]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_71",
            "SFX ID [71]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_72",
            "SFX ID [72]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_73",
            "SFX ID [73]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_74",
            "SFX ID [74]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_75",
            "SFX ID [75]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_76",
            "SFX ID [76]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_77",
            "SFX ID [77]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_78",
            "SFX ID [78]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_79",
            "SFX ID [79]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_80",
            "SFX ID [80]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_81",
            "SFX ID [81]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_82",
            "SFX ID [82]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_83",
            "SFX ID [83]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_84",
            "SFX ID [84]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_85",
            "SFX ID [85]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_86",
            "SFX ID [86]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_87",
            "SFX ID [87]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_88",
            "SFX ID [88]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_89",
            "SFX ID [89]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_90",
            "SFX ID [90]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_91",
            "SFX ID [91]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_92",
            "SFX ID [92]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_93",
            "SFX ID [93]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_94",
            "SFX ID [94]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_95",
            "SFX ID [95]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_96",
            "SFX ID [96]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_97",
            "SFX ID [97]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_98",
            "SFX ID [98]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_99",
            "SFX ID [99]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_100",
            "SFX ID [100]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_101",
            "SFX ID [101]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_102",
            "SFX ID [102]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_103",
            "SFX ID [103]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_104",
            "SFX ID [104]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_105",
            "SFX ID [105]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_106",
            "SFX ID [106]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_107",
            "SFX ID [107]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_108",
            "SFX ID [108]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_109",
            "SFX ID [109]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_110",
            "SFX ID [110]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_111",
            "SFX ID [111]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_112",
            "SFX ID [112]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_113",
            "SFX ID [113]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_114",
            "SFX ID [114]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_115",
            "SFX ID [115]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_116",
            "SFX ID [116]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_117",
            "SFX ID [117]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_118",
            "SFX ID [118]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_119",
            "SFX ID [119]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_120",
            "SFX ID [120]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_121",
            "SFX ID [121]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_122",
            "SFX ID [122]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_123",
            "SFX ID [123]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_124",
            "SFX ID [124]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_125",
            "SFX ID [125]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_126",
            "SFX ID [126]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_127",
            "SFX ID [127]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_128",
            "SFX ID [128]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_129",
            "SFX ID [129]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_130",
            "SFX ID [130]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_131",
            "SFX ID [131]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_132",
            "SFX ID [132]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_133",
            "SFX ID [133]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_134",
            "SFX ID [134]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_135",
            "SFX ID [135]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_136",
            "SFX ID [136]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_137",
            "SFX ID [137]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_138",
            "SFX ID [138]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_139",
            "SFX ID [139]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_140",
            "SFX ID [140]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_141",
            "SFX ID [141]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_142",
            "SFX ID [142]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_143",
            "SFX ID [143]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_144",
            "SFX ID [144]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_145",
            "SFX ID [145]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_146",
            "SFX ID [146]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_147",
            "SFX ID [147]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_148",
            "SFX ID [148]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_149",
            "SFX ID [149]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_150",
            "SFX ID [150]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_151",
            "SFX ID [151]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_152",
            "SFX ID [152]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_153",
            "SFX ID [153]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_154",
            "SFX ID [154]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_155",
            "SFX ID [155]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_156",
            "SFX ID [156]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_157",
            "SFX ID [157]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_158",
            "SFX ID [158]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_159",
            "SFX ID [159]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_160",
            "SFX ID [160]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_161",
            "SFX ID [161]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_162",
            "SFX ID [162]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_163",
            "SFX ID [163]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_164",
            "SFX ID [164]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_165",
            "SFX ID [165]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_166",
            "SFX ID [166]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_167",
            "SFX ID [167]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_168",
            "SFX ID [168]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_169",
            "SFX ID [169]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_170",
            "SFX ID [170]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_171",
            "SFX ID [171]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_172",
            "SFX ID [172]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_173",
            "SFX ID [173]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_174",
            "SFX ID [174]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_175",
            "SFX ID [175]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_176",
            "SFX ID [176]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_177",
            "SFX ID [177]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_178",
            "SFX ID [178]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_179",
            "SFX ID [179]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_180",
            "SFX ID [180]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_181",
            "SFX ID [181]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_182",
            "SFX ID [182]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_183",
            "SFX ID [183]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_184",
            "SFX ID [184]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_185",
            "SFX ID [185]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_186",
            "SFX ID [186]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_187",
            "SFX ID [187]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_188",
            "SFX ID [188]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_189",
            "SFX ID [189]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_190",
            "SFX ID [190]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_191",
            "SFX ID [191]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_192",
            "SFX ID [192]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_193",
            "SFX ID [193]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_194",
            "SFX ID [194]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_195",
            "SFX ID [195]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_196",
            "SFX ID [196]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_197",
            "SFX ID [197]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_198",
            "SFX ID [198]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
        ParamFieldInfo(
            "sfxId_199",
            "SFX ID [199]",
            True,
            int,
            'Numerical value entered in the "Foot effect identifier" item of the NPC parameter, numerical value entered in the "Additional foot effect identifier" item of the special effect parameter, SFX identifier set in the TAE action "Foot effect"',
        ),
    ],
}
