from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


GAME_SYSTEM_COMMON_PARAM_ST = {
    "param_type": "GAME_SYSTEM_COMMON_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "baseToughnessRecoverTime",
            "Base Toughness Recovery Time",
            True,
            float,
            'This is the basic value of toughness recovery time. (Seconds)',
        ),
        ParamFieldInfo(
            "chrEventTrun_byLeft90",
            "Chr Event Turn - By Left 90",
            True,
            int,
            'This is a 90 �� left turn animation for the "Character Turn" event.',
        ),
        ParamFieldInfo(
            "chrEventTrun_byRight90",
            "Chr Event Turn - By Right 90",
            True,
            int,
            'This is a 90 �� right turn animation for the "Character Turn" event.',
        ),
        ParamFieldInfo(
            "chrEventTrun_byLeft180",
            "Chr Event Turn - By Left 180",
            True,
            int,
            'This is a 180 �� left turn animation for the "Character Turn" event.',
        ),
        ParamFieldInfo(
            "chrEventTrun_byRight180",
            "Chr Event Turn - By Right 180",
            True,
            int,
            'This is a 180 �� right turn animation for the "Character Turn" event.',
        ),
        ParamFieldInfo(
            "chrEventTrun_90TurnStartAngle",
            "Chr Event Turn - 90 Turn Start Angle",
            True,
            int,
            'The starting angle of the angle to which the 90 �� swivel animation for the "Character Swirl" event is applied. If the event starts at an angle smaller than this angle, a system turn will occur.',
        ),
        ParamFieldInfo(
            "chrEventTrun_180TurnStartAngle",
            "Chr Event Turn - 180 Turn Start Angle",
            True,
            int,
            'The starting angle of the angle to which the 180 �� swivel animation for the "Character Swirl" event is applied.',
        ),
        ParamFieldInfo(
            "stealthAtkDamageRate",
            "Stealth Attack Multiplier",
            True,
            float,
            'Stealth attack damage multiplier',
        ),
        ParamFieldInfo(
            "flickDamageCutRateSuccessGurad",
            "Weapon Rebel Absorption on Successful Guard",
            True,
            float,
            'Damage cut rate when the guard is successful when repelled. Multiply the final damage',
        ),
        ParamFieldInfo(
            "npcTalkAnimBeginDiffAngle",
            "NPC Talk Anim - Start Diff Angle",
            True,
            float,
            'This is the difference angle at which the animation playback of the motion during the conversation of the NPC conversation starts.',
        ),
        ParamFieldInfo(
            "npcTalkAnimEndDiffAngle",
            "NPC Talk Anim - End Diff Angle",
            True,
            float,
            'This is the difference angle at which the animation playback of the motion during the conversation of the NPC conversation is stopped.',
        ),
        ParamFieldInfo(
            "sleepCollectorItemActionButtonParamId",
            "Sleep Collector Item Action Button Param ID",
            True,
            int,
            'Nemuri Item Acquisition Range_Action Button Para ID. TAE flag Used as the default value when not overwriting with "Event> Nemuri item registration".',
        ),
        ParamFieldInfo(
            "allowUseBuddyItem_sfxInterval",
            "Spirit Summon Item - SFX Interval",
            True,
            float,
            'Buddy item permission_SFX occurrence interval [s]',
        ),
        ParamFieldInfo(
            "allowUseBuddyItem_sfxDmyPolyId",
            "Spirit Summon Item - SFX Dummy Poly ID",
            True,
            int,
            'Buddy Item Permission_SFX Occurrence PC Damipoli ID',
        ),
        ParamFieldInfo(
            "allowUseBuddyItem_sfxDmyPolyId_horse",
            "Spirit Summon Item - SFX Dummy Poly ID (Horse)",
            True,
            int,
            'Buddy item permission_SFX generated horse Damipoli ID_when riding',
        ),
        ParamFieldInfo(
            "allowUseBuddyItem_sfxId",
            "Spirit Summon Item - SFX ID",
            True,
            int,
            'Buddy Item Permission_Occurrence SFXID',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_sfxInterval",
            "Spirit Summon - Activation Range - SFX Interval",
            True,
            float,
            'Buddy Summoning_Initial Range_SFX Occurrence Interval [s]',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_sfxDmyPolyId",
            "Spirit Summon - Activation Range - SFX Dummy Poly ID",
            True,
            int,
            'Buddy Summoning_Initial Range_SFX Occurrence PC Damipoli ID',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_sfxDmyPolyId_horse",
            "Spirit Summon - Activation Range - SFX Dummy Poly ID (Horse)",
            True,
            int,
            'Buddy Summoning_Initial Range_SFX Generated Horse Damipoli ID_When Riding',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_sfxId",
            "Spirit Summon - Activation Range - SFX ID",
            True,
            int,
            'Buddy Summoning_Initial Range_Occurrence SFXID',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_spEffectId_pc",
            "Spirit Summon - Activation Range - Player SpEffect ID",
            True,
            int,
            'Buddy Summoning_Initial range Special effect ID_For PC',
        ),
        ParamFieldInfo(
            "onBuddySummon_inWarnRange_spEffectId_pc",
            "Spirit Summon - Warn Range - Player SpEffect ID",
            True,
            int,
            'Buddy Summoning_Warning Range Special Effect ID_For PC',
        ),
        ParamFieldInfo(
            "onBuddySummon_atBuddyUnsummon_spEffectId_pc",
            "Spirit Summon - Unsummoned - Player SpEffect ID",
            True,
            int,
            'Buddy Summoning_Buddy Return Special Effect ID_For PC',
        ),
        ParamFieldInfo(
            "onBuddySummon_inWarnRange_spEffectId_buddy",
            "Spirit Summon - Warn Range - Spirit SpEffect ID",
            True,
            int,
            'Buddy Summoning_Warning Range Special Effect ID_For Buddy',
        ),
        ParamFieldInfo(
            "morningIngameHour",
            "Morning - In-game Hour",
            True,
            int,
            'Morning in-game time (hours). Used in conversation.',
        ),
        ParamFieldInfo(
            "morningIngameMinute",
            "Morning - In-game Minute",
            True,
            int,
            'Morning in-game time (minutes). Used in conversation.',
        ),
        ParamFieldInfo(
            "morningIngameSecond",
            "Morning - In-game Second",
            True,
            int,
            'Morning in-game time (seconds). Used in conversation.',
        ),
        ParamFieldInfo(
            "noonIngameHour",
            "Noon - In-game Hour",
            True,
            int,
            'Daytime in-game time (hours). Used in conversation.',
        ),
        ParamFieldInfo(
            "noonIngameMinute",
            "Noon - In-game Minute",
            True,
            int,
            'Daytime in-game time (minutes). Used in conversation.',
        ),
        ParamFieldInfo(
            "noonIngameSecond",
            "Noon - In-game Second",
            True,
            int,
            'Daytime in-game time (seconds). Used in conversation.',
        ),
        ParamFieldInfo(
            "nightIngameHour",
            "Night - In-game Hour",
            True,
            int,
            'Night in-game time (hours). Used in conversation.',
        ),
        ParamFieldInfo(
            "nightIngameMinute",
            "Night - In-game Minute",
            True,
            int,
            'Night in-game time (minutes). Used in conversation.',
        ),
        ParamFieldInfo(
            "nightIngameSecond",
            "Night - In-game Second",
            True,
            int,
            'Night in-game time (seconds). Used in conversation.',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Morning_Hour",
            "AI Sight Rate Start - Morning Hour",
            True,
            int,
            'AI visibility magnification_morning_start time (hour)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Morning_Minute",
            "AI Sight Rate Start - Morning Minute",
            True,
            int,
            'AI visibility magnification_morning_start time (minutes)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Noon_Hour",
            "AI Sight Rate Start - Noon Hour",
            True,
            int,
            'AI visibility magnification_day_start time (hour)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Noon_Minute",
            "AI Sight Rate Start - Noon Minute",
            True,
            int,
            'AI visibility magnification_day_start time (minutes)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Evening_Hour",
            "AI Sight Rate Start - Evening Hour",
            True,
            int,
            'AI visibility magnification_evening_start time (hour)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Evening_Minute",
            "AI Sight Rate Start - Evening Minute",
            True,
            int,
            'AI visibility magnification_evening_start time (minutes)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Night_Hour",
            "AI Sight Rate Start - Night Hour",
            True,
            int,
            'AI visibility magnification_night_start time (hour)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Night_Minute",
            "AI Sight Rate Start - Night Minute",
            True,
            int,
            'AI visibility magnification_night_start time (minutes)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Midnight_Hour",
            "AI Sight Rate Start - Midnight Hour",
            True,
            int,
            'AI visibility magnification_midnight_start time (hour)',
        ),
        ParamFieldInfo(
            "aiSightRateStart_Midnight_Minute",
            "AI Sight Rate Start - Midnight Minute",
            True,
            int,
            'AI visibility magnification_midnight_start time (minutes)',
        ),
        ParamFieldInfo(
            "saLargeDamageHitSfx_Threshold",
            "Poise - Large Damage Hit SFX Threshold",
            True,
            int,
            'SA large damage hit production SFX_ Occurrence condition SA damage threshold ratio [%]',
        ),
        ParamFieldInfo(
            "saLargeDamageHitSfx_SfxId",
            "Poise - Large Damage Hit SFX ID",
            True,
            int,
            'SA heavy damage hit production SFX_SFXID',
        ),
        ParamFieldInfo(
            "signCreatableDistFromSafePos",
            "Sign Creatable Distance from Safe Position",
            True,
            float,
            'Distance at which you can create a sign away from the last safe position on your PC [m]',
        ),
        ParamFieldInfo(
            "guestResummonDist",
            "Guest Resummon Distance",
            True,
            float,
            'Distance between host and guest where resummoning occurs [m]',
        ),
        ParamFieldInfo(
            "guestLeavingMessageDistMax",
            "Guest Leaving Message - Max Distance",
            True,
            float,
            "Distance [m] to notify the guest that they are about to leave the host. Notify me when I'm farther than this distance.",
        ),
        ParamFieldInfo(
            "guestLeavingMessageDistMin",
            "Guest Leaving Message - Min Distance",
            True,
            float,
            'Distance [m] that allows the guest to be re-notified that they are about to leave the host. Do not re-notify until closer than this distance.',
        ),
        ParamFieldInfo(
            "guestLeaveSessionDist",
            "Guest Leave Session Distance",
            True,
            float,
            'Maximum distance [m] that a guest can leave the host. If a certain period of time elapses while the distance is longer than this distance, the session will be withdrawn.',
        ),
        ParamFieldInfo(
            "retryPointAreaRadius",
            "Marika Stake Area Radius",
            True,
            float,
            'Retry area radius_default value (m). It is used as the default value when the radius and area are not set in the event type "Retry Point" of MapStudio.',
        ),
        ParamFieldInfo(
            "sleepCollectorSpEffectId",
            "Sleep Collector SpEffect ID",
            True,
            int,
            'A special effect ID that activates when a Nemuri item can be acquired. TAE flag Used as the default value when not overwriting with "Event> Nemuri item registration".',
        ),
        ParamFieldInfo(
            "recoverBelowMaxHpCompletionNoticeSpEffectId",
            "Recovery below HP Max - Notification SpEffect ID",
            True,
            int,
            'ID of the special effect that notifies that "Recovery below HP maximum" is completed. Mainly used for multi synchronization.',
        ),
        ParamFieldInfo(
            "estusFlaskRecovery_AbsorptionProductionSfxId_byHp",
            "HP Flask - Absorption SFX ID for Intruder Flask Restoration",
            True,
            int,
            'Absorption effect SFXID when recovering the number of times the HP Est bottle has been used when defeating an intruder',
        ),
        ParamFieldInfo(
            "estusFlaskRecovery_AbsorptionProductionSfxId_byMp",
            "FP Flask - Absorption SFX ID for Intruder Flask Restoration",
            True,
            int,
            'Absorption effect SFXID when recovering the number of times the MP Est bottle has been used when defeating an intruder',
        ),
        ParamFieldInfo(
            "respawnSpecialEffectActiveCheckerSpEffectId",
            "Resurrection - Notification SpEffect ID",
            True,
            int,
            'ID of the special effect that notifies that the resurrection special effect has been activated. Mainly used for multi synchronization.',
        ),
        ParamFieldInfo(
            "onBuddySummon_inActivateRange_spEffectId_buddy",
            "Spirit Summon - Activation Range - Spirit SpEffect ID",
            True,
            int,
            'Buddy Summoning_Initial Range Special Effect ID_For Buddy',
        ),
        ParamFieldInfo(
            "estusFlaskRecovery_AddEstusTime",
            "Flask - Absorption SFX Playback Time",
            True,
            float,
            'Time from the start of est absorption SFX playback to the start of est addition processing',
        ),
        ParamFieldInfo(
            "defeatMultiModeEnemyOfSoulCorrectRate_byHost",
            "Rune Absorption Multiplier - Normal Enemy - Host",
            True,
            float,
            'Correction value of the amount of soul acquired by the host when defeating a normal enemy in multiplayer',
        ),
        ParamFieldInfo(
            "defeatMultiModeEnemyOfSoulCorrectRate_byTeamGhost",
            "Rune Absorption Multiplier - Normal Enemy - Friendly Phantom",
            True,
            float,
            'Correction value of the amount of soul acquired by cooperating spirits when defeating a normal enemy in multiplayer',
        ),
        ParamFieldInfo(
            "defeatMultiModeBossOfSoulCorrectRate_byHost",
            "Rune Absorption Multiplier - Boss - Host",
            True,
            float,
            'Correction value of the amount of soul acquired by the host when defeating the boss in multiplayer',
        ),
        ParamFieldInfo(
            "defeatMultiModeBossOfSoulCorrectRate_byTeamGhost",
            "Rune Absorption Multiplier - Boss - Friendly Phantom",
            True,
            float,
            'Correction value of the amount of soul acquired when the boss is defeated in multiplayer',
        ),
        ParamFieldInfo(
            "enemyHpGaugeScreenOffset_byUp",
            "Enemy HP Gauge - Cutoff Pixel Offset",
            True,
            int,
            "Offset value [pixel] (FullHD standard) that fits in the screen when the enemy's HP gauge is cut off on the screen",
        ),
        ParamFieldInfo(
            "playRegionCollectDist",
            "Play Region Collection Distance",
            True,
            int,
            'Collection radius of the play area around the PC',
        ),
        ParamFieldInfo(
            "enemyDetectionSpEffect_ShootBulletDummypolyId",
            "Enemy Detection - Shoot Bullet Dummy Poly ID",
            True,
            int,
            'Detect bullet firing position Damipoli ID',
        ),
        ParamFieldInfo(
            "bigRuneGreaterDemonBreakInGoodsNum",
            "Phantom Great Rune - Amount given for Invasion",
            True,
            int,
            'Large Rune: Number of tools granted when the Greater Demon invades',
        ),
        ParamFieldInfo(
            "bigRuneGreaterDemonBreakInGoodsId",
            "Phantom Great Rune - Goods ID",
            True,
            int,
            'Large Rune: Greater Demon Invasion Tool Item ID',
        ),
        ParamFieldInfo(
            "rideJumpRegionDefaultSfxId",
            "Spiritspring Jump SFX ID",
            True,
            int,
            'SFX ID in the riding large jump area',
        ),
        ParamFieldInfo(
            "saAttackRate_forVsRideAtk",
            "Poise Damage - Vs. Ride Attack",
            True,
            float,
            'Magnification to be corrected at the time of riding special attack',
        ),
        ParamFieldInfo(
            "enemySpEffectIdAfterSleepCollectorItemLot",
            "Sleep Collector Item Lot - Enemy SpEffect ID",
            True,
            int,
            'Special effects on the enemy side when drawing Nemuri items',
        ),
        ParamFieldInfo(
            "afterEndingMapUid",
            "After Ending Map UID",
            True,
            int,
            'Map UID on hold for lap, enter in 8 digits (example ... m60_42_36_00-> 60423600)',
        ),
        ParamFieldInfo(
            "afterEndingReturnPointEntityId",
            "After Ending Return Point Entity ID",
            True,
            int,
            'Entity ID of return point on hold',
        ),
        ParamFieldInfo(
            "enemyDetectionSpEffect_BulletId_byCoopRing_RedHunter",
            "Enemy Detection - Bullet ID (Co-op/Anti-Invader)",
            True,
            int,
            'Bullet ID to fly depending on enemy power / type (also used for multi-automatic firing)',
        ),
        ParamFieldInfo(
            "enemyDetectionSpEffect_BulletId_byInvadeOrb_None",
            "Enemy Detection - Bullet ID (Invader)",
            True,
            int,
            'Bullet ID to fly depending on enemy power / type (also used for multi-automatic firing)',
        ),
        ParamFieldInfo(
            "tutorialFlagOnAccessDistView",
            "Tutorial Flag: Accessing Birdseye Telescope",
            True,
            int,
            'For tutorial judgment: Event flag to turn on when accessing the distant view',
        ),
        ParamFieldInfo(
            "tutorialFlagOnAccessRetryPoint",
            "Tutorial Flag: Accessing Marika Stake",
            True,
            int,
            'For tutorial judgment: Event flag to turn on when accessing the retry point',
        ),
        ParamFieldInfo(
            "tutorialFlagOnGetGroupReward",
            "Tutorial Flag: Enemy Group Flask Restoration",
            True,
            int,
            'For tutorial judgment: Event flag to turn on when group reward is entered after defeating a group',
        ),
        ParamFieldInfo(
            "tutorialFlagOnEnterRideJumpRegion",
            "Tutorial Flag: Entering Spiritspring Jump",
            True,
            int,
            'For tutorial judgment: Event flag to turn on when entering the riding big jump point',
        ),
        ParamFieldInfo(
            "tutorialCheckRideJumpRegionExpandRange",
            "Tutorial: Check Spiritspring Jump Region Range",
            True,
            float,
            'For tutorial judgment: The riding large jump point is expanded by �� [m] to judge inside and outside. �� Set the value of [m] here.',
        ),
        ParamFieldInfo(
            "retryPointActivatedPcAnimId",
            "Activated Marika Stake: Player Animation ID",
            True,
            int,
            'PC animation ID when retry point is started. If it is -1, it will not be played.',
        ),
        ParamFieldInfo(
            "retryPointActivatedDialogDelayTime",
            "Activated Marika Stake: Dialog Display Delay",
            True,
            float,
            'Delay time of dialog display when retry point is started [seconds]',
        ),
        ParamFieldInfo(
            "retryPointActivatedDialogTextId",
            "Activated Marika Stake: Dialog Text ID",
            True,
            int,
            'The text ID of the dialog when the retry point is started. Set the text in EventText_ForMap.xlsm. If it is -1, the dialog is not displayed.',
        ),
        ParamFieldInfo(
            "signPuddleOpenPcAnimId",
            "Opened Summoning Pool: Player Animation ID",
            True,
            int,
            'PC animation ID at the time of sign accumulation startup. If it is -1, it will not be played.',
        ),
        ParamFieldInfo(
            "signPuddleOpenDialogDelayTime",
            "Opened Summoning Pool: Dialog Display Delay",
            True,
            float,
            'Delay time of dialog display at startup of sign accumulation [seconds]',
        ),
        ParamFieldInfo(
            "activityOfDeadSpEffect_BulletId",
            "Corpse Explosion - Bullet ID",
            True,
            int,
            'Bullet ID fired when the "Activity of the Dead" special effect is activated',
        ),
        ParamFieldInfo(
            "activityOfDeadSpEffect_ShootBulletDummypolyId",
            "Corpse Explosion - Bullet Dummy Poly ID",
            True,
            int,
            'Damipoli ID at the position where the bullet is generated when the "Activity of the Dead" special effect is activated',
        ),
        ParamFieldInfo(
            "activityOfDeadSpEffect_DeadFadeOutTime",
            "Corpse Explosion - Dead Fadeout Time",
            True,
            float,
            'Fade time when the corpse fades out when the "Activity of the Dead" special effect is activated',
        ),
        ParamFieldInfo(
            "ignorNetStateSyncTime_ForThrow",
            "Ignore Network State Sync Time for Throw",
            True,
            float,
            'Time to ignore transitions due to network information at the start of throwing',
        ),
        ParamFieldInfo(
            "netPenaltyPointLanDisconnect",
            "Muliplayer Disconnect: LAN Disconnect Penalty Points",
            True,
            int,
            'Multi-pre-penalty: LAN disconnection',
        ),
        ParamFieldInfo(
            "netPenaltyPointProfileSignout",
            "Muliplayer Disconnect: Profile Signout Penalty Points",
            True,
            int,
            'Multi-pre-penalty: Profile sign-out',
        ),
        ParamFieldInfo(
            "netPenaltyPointReboot",
            "Muliplayer Disconnect: Reboot Penalty Points",
            True,
            int,
            'Multi-pre-penalty: Power off',
        ),
        ParamFieldInfo(
            "netPnaltyPointSuspend",
            "Muliplayer Disconnect: Suspend Penalty Points",
            True,
            int,
            'Multi-pre-penalty: Suspend / Pause',
        ),
        ParamFieldInfo(
            "netPenaltyForgiveItemLimitTime",
            "Muliplayer Disconnect: Delay before White Ring is given",
            True,
            float,
            'Multi-pre-penalty: Waiting time (seconds) to start the generation (sale) of the bone of reason',
        ),
        ParamFieldInfo(
            "netPenaltyPointThreshold",
            "Multiplayer Disconnect: Point Threshold",
            True,
            int,
            'Multi-pre-penalty: Penalty judgment points',
        ),
        ParamFieldInfo(
            "uncontrolledMoveThresholdTime",
            "Multiplayer: Timeout due to lack of Activity",
            True,
            int,
            'It is for leaving people who have not operated for a certain period of time in multiplayer. The unit is seconds.',
        ),
        ParamFieldInfo(
            "enemyDetectionSpEffect_BulletId_byNpcEnemy",
            "Enemy Detection - Bullet ID (NPC Enemy)",
            True,
            int,
            'Bullet ID to shoot to hostile NPCs / enemy characters when hostility detection fails',
        ),
        ParamFieldInfo(
            "activityOfDeadTargetSearchSpEffect_OnHitSpEffect",
            "Corpse Explosion - On Hit SpEffect",
            True,
            int,
            'Special effects applied to the searched target',
        ),
        ParamFieldInfo(
            "activityOfDeadTargetSearchSpEffect_MaxLength",
            "Corpse Explosion - Max Length",
            True,
            float,
            'Maximum searchable distance',
        ),
        ParamFieldInfo(
            "sightRangeLowerPromiseRate",
            "Field of View - Minimum Guaranteed Distance",
            True,
            float,
            'Field of view_Minimum guaranteed distance [magnification conversion]',
        ),
        ParamFieldInfo(
            "saLargeDamageHitSfx_MinDamage",
            "Poise Large Damage Hit SFX - Minimum Damage",
            True,
            int,
            'SA large damage hit production SFX_ Occurrence condition SA damage minimum required [pt]',
        ),
        ParamFieldInfo(
            "saLargeDamageHitSfx_ForceDamage",
            "Poise Large Damage Hit SFX - Force Damage",
            True,
            int,
            'SA large damage hit production SFX_ Occurrence condition SA damage forced occurrence minimum value [pt]',
        ),
        ParamFieldInfo(
            "soloBreakInMaxPoint",
            "Maximum Solo Intrusion Point",
            True,
            int,
            'Maximum solo intrusion point. When this value is exceeded, it will be invaded solo.',
        ),
        ParamFieldInfo(
            "npcTalkTimeOutThreshold",
            "NPC Talk Timeout Threshold",
            True,
            float,
            'Voice playback timeout for NPC conversations. If voice playback does not end after this time, proceed to the next message.',
        ),
        ParamFieldInfo(
            "sendPlayLogIntervalTime",
            "Send Play Log Interval",
            True,
            float,
            'Interval to send item usage log etc. to the server',
        ),
        ParamFieldInfo(
            "item370_MaxSfxNum",
            "Rainbow Stone - Max SFX Count",
            True,
            int,
            'Maximum number of seven-colored stones installed',
        ),
        ParamFieldInfo(
            "chrActivateDist_forLeavePC",
            "Chr Activate Distance - For Leave Player",
            True,
            int,
            'Distance allowed to activate during character deactivation (valid only for open placement characters)',
        ),
        ParamFieldInfo(
            "summonDataCoopMatchingLevelUpperAbs",
            "Coop - Host Level Addition Correction",
            True,
            int,
            'Weakened stats when multiplayer. Host level addition correction',
        ),
        ParamFieldInfo(
            "summonDataCoopMatchingLevelUpperRel",
            "Coop - Host Level Magnification Correction",
            True,
            int,
            'Weakened stats when multiplayer. Host level magnification correction',
        ),
        ParamFieldInfo(
            "summonDataCoopMatchingWepLevelMul",
            "Coop - Maximum Weapon Reinforcement Correction",
            True,
            int,
            'Weakened stats when multiplayer. Maximum weapon enhancement level correction',
        ),
        ParamFieldInfo(
            "pickUpBerserkerSignSpEffectBulletId",
            "Pickup Berserker Sign - Bullet ID",
            True,
            int,
            'Bullet ID when generating a bullet for special effects at the sign position',
        ),
        ParamFieldInfo(
            "succeedBerserkerSelfKillingEffectId",
            "Berserker Success Player Kill - SpEffect ID",
            True,
            int,
            'Special effect to play a special effect when Berserker succeeds in killing the PC by himself',
        ),
        ParamFieldInfo(
            "machingLevelWhiteSignUpperRel",
            "Friendly Phantom - Level Coefficient 1",
            True,
            int,
            'Soul level coefficient of whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingLevelWhiteSignUpperAbs",
            "Friendly Phantom - Level Coefficient 2",
            True,
            int,
            'Soul level coefficient of whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingLevelRedSignUpperRel",
            "Hostile Phantom - Level Coefficient 1",
            True,
            int,
            'Soul level coefficient of whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingLevelRedSignUpperAbs",
            "Hostile Phantom - Level Coefficient 2",
            True,
            int,
            'Soul level coefficient of whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_0",
            "Friendly Phantom - Max Reinforcement Coefficient 0",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_1",
            "Friendly Phantom - Max Reinforcement Coefficient 1",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_2",
            "Friendly Phantom - Max Reinforcement Coefficient 2",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_3",
            "Friendly Phantom - Max Reinforcement Coefficient 3",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_4",
            "Friendly Phantom - Max Reinforcement Coefficient 4",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_5",
            "Friendly Phantom - Max Reinforcement Coefficient 5",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_6",
            "Friendly Phantom - Max Reinforcement Coefficient 6",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_7",
            "Friendly Phantom - Max Reinforcement Coefficient 7",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_8",
            "Friendly Phantom - Max Reinforcement Coefficient 8",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_9",
            "Friendly Phantom - Max Reinforcement Coefficient 9",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_10",
            "Friendly Phantom - Max Reinforcement Coefficient 10",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_0",
            "Hostile Phantom - Max Reinforcement Coefficient 0",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_1",
            "Hostile Phantom - Max Reinforcement Coefficient 1",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_2",
            "Hostile Phantom - Max Reinforcement Coefficient 2",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_3",
            "Hostile Phantom - Max Reinforcement Coefficient 3",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_4",
            "Hostile Phantom - Max Reinforcement Coefficient 4",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_5",
            "Hostile Phantom - Max Reinforcement Coefficient 5",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_6",
            "Hostile Phantom - Max Reinforcement Coefficient 6",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_7",
            "Hostile Phantom - Max Reinforcement Coefficient 7",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_8",
            "Hostile Phantom - Max Reinforcement Coefficient 8",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_9",
            "Hostile Phantom - Max Reinforcement Coefficient 9",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_10",
            "Hostile Phantom - Max Reinforcement Coefficient 10",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "autoInvadePoint_generateDist",
            "Automatic Invasion Point - Generation Distance",
            True,
            int,
            'Automatic placement interval of intrusion points',
        ),
        ParamFieldInfo(
            "autoInvadePoint_cancelDist",
            "Automatic Invasion Point - Cancel Distance",
            True,
            int,
            'Intrusion point automatic placement cancellation range',
        ),
        ParamFieldInfo(
            "sendGlobalEventLogIntervalTime",
            "Send Global Event Log Interval",
            True,
            float,
            'Interval to send global event log to server',
        ),
        ParamFieldInfo(
            "addSoloBreakInPoint_White",
            "Solo Intrusion Point - White Phantom",
            True,
            int,
            'Solo intrusion point addition value_white sign',
        ),
        ParamFieldInfo(
            "addSoloBreakInPoint_Black",
            "Solo Intrusion Point - Black Phantom",
            True,
            int,
            'Solo intrusion point addition value_red sign',
        ),
        ParamFieldInfo(
            "addSoloBreakInPoint_ForceJoin",
            "Solo Intrusion Point - Force Join",
            True,
            int,
            'Solo intrusion point addition value_intrusion',
        ),
        ParamFieldInfo(
            "addSoloBreakInPoint_VisitorGuardian",
            "Solo Intrusion Point - Visitor Guardian",
            True,
            int,
            'Solo intrusion point addition value_Map guardian visit',
        ),
        ParamFieldInfo(
            "addSoloBreakInPoint_VisitorRedHunter",
            "Solo Intrusion Point - Red Hunter",
            True,
            int,
            'Solo intrusion point addition value_Red Scare visit',
        ),
        ParamFieldInfo(
            "invincibleTimer_forNetPC_initSync",
            "Invincibility Timer for Initial Player Sync",
            True,
            int,
            'Invincible timer for initial sync PC',
        ),
        ParamFieldInfo(
            "invincibleTimer_forNetPC",
            "Invincibility Timer for Non-Initial Player Sync",
            True,
            int,
            'Invincible timer for non-initial sync PCs',
        ),
        ParamFieldInfo(
            "redHunter_HostBossAreaGetSoulRate",
            "Red Hunter - Host Boss Area Soul Absorption",
            True,
            float,
            'Soul that you can get red hunting when the host passes through the white door = Soul required for red hunting to change from the previous Lv to the current Lv * This magnification',
        ),
        ParamFieldInfo(
            "ghostFootprintDecalParamId",
            "Ghost Footprint Decal Param ID",
            True,
            int,
            'Decal parameter ID of the trace that the wandering illusion puts out while moving',
        ),
        ParamFieldInfo(
            "leaveAroundHostWarningTime",
            "Exceeded Multiplayer Limit Distance - Warning Time",
            True,
            float,
            'If this count time elapses while you are out of the multiplayer limit distance, the multiplayer will be disbanded.',
        ),
        ParamFieldInfo(
            "hostModeCostItemId",
            "Host Mode Cost Item ID",
            True,
            int,
            'ID of the cost item consumed when hosting is turned on',
        ),
        ParamFieldInfo(
            "aIJump_DecelerateParam",
            "AI Jump - Deceleration",
            True,
            float,
            'Deceleration parameters for AI jump (0.0: constant velocity motion, 1.0: maximum deceleration, speed 0 at target point)',
        ),
        ParamFieldInfo(
            "buddyDisappearDelaySec",
            "Spirit Summon - Disappearance Delay",
            True,
            float,
            'The time from the death flag to the actual disappearance of the instance',
        ),
        ParamFieldInfo(
            "aIJump_AnimYMoveCorrectRate_onJumpOff",
            "AI Jump - Y Movement Amount Correction",
            True,
            float,
            'AI jump jumping Y movement amount correction factor',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_NotInStealthRigid_NotSightHide_StealthMode",
            "Stealth Visibility - Crouch - No Stealth Effect",
            True,
            float,
            'Stealth visibility magnification_Crouching without stealth effect',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_NotInStealthRigid_SightHide_NotStealthMode",
            "Stealth Visibility - Stand - Stealth Ray Effect",
            True,
            float,
            'Stealth visibility magnification_Standing in stealth ray shielded area',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_NotInStealthRigid_SightHide_StealthMode",
            "Stealth Visibility - Crouch - Stealth Ray Effect",
            True,
            float,
            'Stealth visibility magnification_Crouching in stealth ray shielded area',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_InStealthRigid_NotSightHide_NotStealthMode",
            "Stealth Visibility - Stand - Stealth Hit",
            True,
            float,
            'Stealth visibility magnification_Standing within a stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_InStealthRigid_NotSightHide_StealthMode",
            "Stealth Visibility - Crouch - Stealth Hit",
            True,
            float,
            'Stealth visibility magnification_Crouching within a stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_InStealthRigid_SightHide_NotStealthMode",
            "Stealth Visibility - Stealth Ray + Stand in Stealth Hit",
            True,
            float,
            'Stealth visibility magnification_Stealth ray shielded area + standing in stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightRate_InStealthRigid_SightHide_StealthMode",
            "Stealth Visibility - Stealth Ray + Crouch in Stealth Hit",
            True,
            float,
            'Stealth visibility magnification_Stealth ray shielded area + crouching in stealth hit',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_actionButtonParamId_corpse",
            "Treasure Corpse - Default Action Button ID",
            True,
            int,
            'Default action button parameter ID when "Treasure corpse" is selected in the treasure box type of treasure box information for OBJ of MapStudio event',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_itemGetAnimId_corpse",
            "Treasure Corpse - Item Get Anim ID",
            True,
            int,
            'When "Treasure corpse" is selected in the treasure box type of the treasure box information for OBJ of the MapStudio event, the default item is acquired. Animation ID',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_actionButtonParamId_box",
            "Treasure Chest - Default Action Button ID",
            True,
            int,
            'Default action button parameter ID when "Treasure chest" is selected in the treasure chest type of treasure chest information for OBJ of MapStudio event',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_itemGetAnimId_box",
            "Treasure Chest - Item Get Anim ID",
            True,
            int,
            'When "Treasure chest" is selected in the treasure chest type of the treasure chest information for OBJ of the MapStudio event, the default item acquisition animation ID',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_actionButtonParamId_shine",
            "FFX Treasure - Default Action Button ID",
            True,
            int,
            'Default action button parameter ID when "Item light" is selected in the treasure chest type of treasure chest information for OBJ of MapStudio event',
        ),
        ParamFieldInfo(
            "msbEventGeomTreasureInfo_itemGetAnimId_shine",
            "FFX Treasure - Item Get Anim ID",
            True,
            int,
            'When "Item Hikari" is selected as the treasure chest type of the treasure chest information for OBJ of the MapStudio event, the default item acquisition animation ID',
        ),
        ParamFieldInfo(
            "signPuddleAssetId",
            "Summoning Pool - Asset ID",
            True,
            int,
            'Assets used for sign collection',
        ),
        ParamFieldInfo(
            "signPuddleAppearDmypolyId0",
            "Summoning Pool - Dummy Poly ID [0]",
            True,
            int,
            'Damipoli used to determine the display position of the sign in the sign pool',
        ),
        ParamFieldInfo(
            "signPuddleAppearDmypolyId1",
            "Summoning Pool - Dummy Poly ID [1]",
            True,
            int,
            'Damipoli used to determine the display position of the sign in the sign pool',
        ),
        ParamFieldInfo(
            "signPuddleAppearDmypolyId2",
            "Summoning Pool - Dummy Poly ID [2]",
            True,
            int,
            'Damipoli used to determine the display position of the sign in the sign pool',
        ),
        ParamFieldInfo(
            "signPuddleAppearDmypolyId3",
            "Summoning Pool - Dummy Poly ID [3]",
            True,
            int,
            'Damipoli used to determine the display position of the sign in the sign pool',
        ),
        ParamFieldInfo(
            "fallDamageRate_forRidePC",
            "Fall Damage Multiplier - Mounted Player",
            True,
            float,
            "Rider's fall damage multiplier correction_for PC",
        ),
        ParamFieldInfo(
            "fallDamageRate_forRideNPC",
            "Fall Damage Multiplier - Mounted NPC",
            True,
            float,
            "Rider's Fall Damage Multiplier Correction_for NPCs",
        ),
        ParamFieldInfo(
            "OldMonkOfYellow_CreateSignSpEffectId",
            "Old Monk of Yellow - Create Sign SpEffect ID",
            True,
            int,
            'Special effect ID when creating the old man sign of yellow robe',
        ),
        ParamFieldInfo(
            "StragglerActivateDist",
            "Straggler - Activation Distance",
            True,
            float,
            'Defeated soldier activation distance',
        ),
        ParamFieldInfo(
            "SpEffectId_EnableUseItem_StragglerActivate",
            "Straggler - Enable Item Use SpEffect ID",
            True,
            int,
            'Permission to use defeated soldier items_Special effects for PC',
        ),
        ParamFieldInfo(
            "SpEffectId_StragglerWakeUp",
            "Straggler - Wake Up SpEffect ID",
            True,
            int,
            'Activate defeated soldiers_Special effects for defeated soldier characters',
        ),
        ParamFieldInfo(
            "SpEffectId_StragglerTarget",
            "Straggler - Target SpEffect ID",
            True,
            int,
            'Defeated soldiers_Special effects for subjugation targets',
        ),
        ParamFieldInfo(
            "SpEffectId_StragglerOppose",
            "Straggler - Oppose SpEffect ID",
            True,
            int,
            'Defeated soldiers_Special effects after hostility',
        ),
        ParamFieldInfo(
            "buddyWarp_TriggerTimeRayBlocked",
            "Spirit Summon - Trigger Time for Warp when Raycast is blocked",
            True,
            float,
            'Time for a buddy to warp a player with a ray block [s]',
        ),
        ParamFieldInfo(
            "buddyWarp_TriggerDistToPlayer",
            "Spirit Summon - Trigger Warp Distance to Player",
            True,
            float,
            'Distance at which the buddy warps the player at a straight line distance [m]',
        ),
        ParamFieldInfo(
            "buddyWarp_ThresholdTimePathStacked",
            "Spirit Summon - Time Threshold for Stuck Spirit",
            True,
            float,
            'Judgment time when the buddy is stuck in the pass movement [s]',
        ),
        ParamFieldInfo(
            "buddyWarp_ThresholdRangePathStacked",
            "Spirit Summon - Distance Threshold for Stuck Spirit",
            True,
            float,
            'Distance [m] that the buddy considers to be clogged with a pass move',
        ),
        ParamFieldInfo(
            "aiSightRate_morning",
            "AI Sight Multiplier - Morning",
            True,
            float,
            '[Morning] AI visibility magnification',
        ),
        ParamFieldInfo(
            "aiSightRate_noonA",
            "AI Sight Multiplier - Noon",
            True,
            float,
            '[Day] AI visibility magnification',
        ),
        ParamFieldInfo(
            "buddyPassThroughTriggerTime",
            "Spirit Summon - Pass through Player Trigger Time",
            True,
            float,
            'Time when the buddy and the player collide and start slipping through [s]',
        ),
        ParamFieldInfo(
            "aiSightRate_evening",
            "AI Sight Multiplier - Evening",
            True,
            float,
            '[Evening] AI visibility magnification',
        ),
        ParamFieldInfo(
            "aiSightRate_night",
            "AI Sight Multiplier - Night",
            True,
            float,
            '[Night] AI visibility magnification',
        ),
        ParamFieldInfo(
            "aiSightRate_midnightA",
            "AI Sight Multiplier - Midnight",
            True,
            float,
            '[Midnight] AI visibility magnification',
        ),
        ParamFieldInfo(
            "reserve4_2[4]",
            "Reserve",
            False,
            pad_field(4),
            '(dummy8)',
        ),
        ParamFieldInfo(
            "aiSightRate_sunloss_light",
            "AI Sight Multiplier - Sunloss - Light",
            True,
            float,
            'AI visibility magnification_place where the sun cannot be seen (bright)',
        ),
        ParamFieldInfo(
            "aiSightRate_sunloss_dark",
            "AI Sight Multiplier - Sunloss - Darkness",
            True,
            float,
            'AI visibility magnification_place where the sun cannot be seen (darkness)',
        ),
        ParamFieldInfo(
            "aiSightRate_sunloss_veryDark",
            "AI Sight Multiplier - Sunloss - Total Darkness",
            True,
            float,
            'AI visibility magnification_place where the sun cannot be seen (total darkness)',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_NotInStealthRigid_NotSightHide_StealthMode",
            "Stealth View Angle Attenuation - Crouch - No Stealth Effect",
            True,
            float,
            'Stealth view angle attenuation factor_ crouching without stealth effect',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_NotInStealthRigid_SightHide_NotStealthMode",
            "Stealth View Angle Attenuation - Stand - Stealth Ray",
            True,
            float,
            'Stealth view angle attenuation rate_Standing in stealth ray shielded area',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_NotInStealthRigid_SightHide_StealthMode",
            "Stealth View Angle Attenuation - Crouch - Stealth Ray",
            True,
            float,
            'Stealth visibility angle attenuation _ crouching in stealth ray shielded area',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_InStealthRigid_NotSightHide_NotStealthMode",
            "Stealth View Angle Attenuation - Stand - Stealth Hit",
            True,
            float,
            'Stealth view angle attenuation rate_Standing within stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_InStealthRigid_NotSightHide_StealthMode",
            "Stealth View Angle Attenuation - Crouch - Stealth Hit",
            True,
            float,
            'Stealth view angle attenuation rate_ crouching within stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_InStealthRigid_SightHide_NotStealthMode",
            "Stealth View Angle Attenuation - Stand - Stealth Ray + Stealth Hit",
            True,
            float,
            'Stealth view angle attenuation rate_Stealth ray shielded area + standing in stealth hit',
        ),
        ParamFieldInfo(
            "stealthSystemSightAngleReduceRate_InStealthRigid_SightHide_StealthMode",
            "Stealth View Angle Attenuation - Crouch - Stealth Ray + Stealth Hit",
            True,
            float,
            'Stealth view angle attenuation rate_Stealth ray shielded area + crouching in stealth hit',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Morning_Hour",
            "Weather Lottery Condition - Morning: Hour",
            True,
            int,
            'Weather lottery conditions_morning_start time_hour (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Morning_Minute",
            "Weather Lottery Condition - Morning: Minute",
            True,
            int,
            'Weather lottery conditions_morning_start time_minutes (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Day_Hour",
            "Weather Lottery Condition - Day: Hour",
            True,
            int,
            'Weather lottery conditions_day_start time_hour (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Day_Minute",
            "Weather Lottery Condition - Day: Minute",
            True,
            int,
            'Weather lottery conditions_day_start time_minutes (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Evening_Hour",
            "Weather Lottery Condition - Evening: Hour",
            True,
            int,
            'Weather lottery conditions_evening_start time_hour (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Evening_Minute",
            "Weather Lottery Condition - Evening: Minute",
            True,
            int,
            'Weather lottery conditions_evening_start time_minutes (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Night_Hour",
            "Weather Lottery Condition - Night: Hour",
            True,
            int,
            'Weather lottery conditions_night_start time_hour (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_Night_Minute",
            "Weather Lottery Condition - Night: Minute",
            True,
            int,
            'Weather lottery conditions_night_start time_minutes (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_DayBreak_Hour",
            "Weather Lottery Condition - Dawn: Hour",
            True,
            int,
            'Weather lottery conditions_dawn_start time_hour (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotConditionStart_DayBreak_Minute",
            "Weather Lottery Condition - Dawn: Minute",
            True,
            int,
            'Weather lottery conditions_dawn_start time_minutes (SEQ09371)',
        ),
        ParamFieldInfo(
            "weatherLotCondition_reserved[2]",
            "Weather lottery conditions_reservation",
            False,
            pad_field(2),
            '(dummy8)',
        ),
        ParamFieldInfo(
            "pclightScaleChangeStart_Hour",
            "Player Light Intensity Scale - Start Hour",
            True,
            int,
            'Player Light Intensity Scale Change Time Zone_Start Time_Hour (SEQ16562)',
        ),
        ParamFieldInfo(
            "pclightScaleChangeStart_Minute",
            "Player Light Intensity Scale - Start Minute",
            True,
            int,
            'Player Light Intensity Scale Change Time Zone_Start Time_Minute (SEQ16562)',
        ),
        ParamFieldInfo(
            "pclightScaleChangeEnd_Hour",
            "Player Light Intensity Scale - End Hour",
            True,
            int,
            'Player Light intensity scale change time zone_end time_hour (SEQ16562)',
        ),
        ParamFieldInfo(
            "pclightScaleChangeEnd_Minute",
            "Player Light Intensity Scale - End Minute",
            True,
            int,
            'Player Light Intensity Scale Change Time Zone_End Time_Minute (SEQ16562)',
        ),
        ParamFieldInfo(
            "pclightScaleByTimezone",
            "Player Light Intensity Scale - Timezone",
            True,
            float,
            'Time zone Player light intensity scale change value (SEQ16562)',
        ),
        ParamFieldInfo(
            "bigRuneGreaterDemon_SummonBuddySpecialEffectId_Buddy",
            "Great Rune - Greater Demon Spirit Summon - Spirit SpEffect ID",
            True,
            int,
            'Large Rune: Greater Demon Buddy Summon Buddy Special Effect ID',
        ),
        ParamFieldInfo(
            "bigRuneGreaterDemon_SummonBuddySpecialEffectId_Pc",
            "Great Rune - Greater Demon Spirit Summon - Player SpEffect ID",
            True,
            int,
            'Large Rune: Special effect ID given to PC when summoning Greater Demon Buddy',
        ),
        ParamFieldInfo(
            "homeBonfireParamId",
            "Base Bonfire Warp Param ID",
            True,
            int,
            'Base bonfire bonfire warp parameter ID',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_11",
            "Friendly Phantom - Max Reinforcement Coefficient 11",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_12",
            "Friendly Phantom - Max Reinforcement Coefficient 12",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_13",
            "Friendly Phantom - Max Reinforcement Coefficient 13",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_14",
            "Friendly Phantom - Max Reinforcement Coefficient 14",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_15",
            "Friendly Phantom - Max Reinforcement Coefficient 15",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_16",
            "Friendly Phantom - Max Reinforcement Coefficient 16",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_17",
            "Friendly Phantom - Max Reinforcement Coefficient 17",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_18",
            "Friendly Phantom - Max Reinforcement Coefficient 18",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_19",
            "Friendly Phantom - Max Reinforcement Coefficient 19",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_20",
            "Friendly Phantom - Max Reinforcement Coefficient 20",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_21",
            "Friendly Phantom - Max Reinforcement Coefficient 21",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_22",
            "Friendly Phantom - Max Reinforcement Coefficient 22",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_23",
            "Friendly Phantom - Max Reinforcement Coefficient 23",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_24",
            "Friendly Phantom - Max Reinforcement Coefficient 24",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperWhiteSign_25",
            "Friendly Phantom - Max Reinforcement Coefficient 25",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_11",
            "Hostile Phantom - Max Reinforcement Coefficient 11",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_12",
            "Hostile Phantom - Max Reinforcement Coefficient 12",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_13",
            "Hostile Phantom - Max Reinforcement Coefficient 13",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_14",
            "Hostile Phantom - Max Reinforcement Coefficient 14",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_15",
            "Hostile Phantom - Max Reinforcement Coefficient 15",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_16",
            "Hostile Phantom - Max Reinforcement Coefficient 16",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_17",
            "Hostile Phantom - Max Reinforcement Coefficient 17",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_18",
            "Hostile Phantom - Max Reinforcement Coefficient 18",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_19",
            "Hostile Phantom - Max Reinforcement Coefficient 19",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_20",
            "Hostile Phantom - Max Reinforcement Coefficient 20",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_21",
            "Hostile Phantom - Max Reinforcement Coefficient 21",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_22",
            "Hostile Phantom - Max Reinforcement Coefficient 22",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_23",
            "Hostile Phantom - Max Reinforcement Coefficient 23",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_24",
            "Hostile Phantom - Max Reinforcement Coefficient 24",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "machingWeaponLevelUpperRedSign_25",
            "Hostile Phantom - Max Reinforcement Coefficient 25",
            True,
            int,
            'Maximum weapon enhancement level factor for whether to apply level sync',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Morning_Hour",
            "Menu Timezone - Morning: Hour",
            True,
            int,
            'Menu time zone display_morning_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Morning_Minute",
            "Menu Timezone - Morning: Minute",
            True,
            int,
            'Menu time zone display_morning_start time_minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Day1_Hour",
            "Menu Timezone - Day 1: Hour",
            True,
            int,
            'Menu time zone display_day 1_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Day1_Minute",
            "Menu Timezone - Day 1: Minute",
            True,
            int,
            'Menu time zone display_day 1_start time_minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Day2_Hour",
            "Menu Timezone - Day 2: Hour",
            True,
            int,
            'Menu time zone display_day 2_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Day2_Minute",
            "Menu Timezone - Day 2: Minute",
            True,
            int,
            'Time zone display for menu_Lunch 2_Start time_Minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Evening_Hour",
            "Menu Timezone - Evening: Hour",
            True,
            int,
            'Menu time zone display_evening_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Evening_Minute",
            "Menu Timezone - Evening: Minute",
            True,
            int,
            'Menu time zone display_evening_start time_minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Night_Hour",
            "Menu Timezone - Night: Hour",
            True,
            int,
            'Menu time zone display_night_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Night_Minute",
            "Menu Timezone - Night: Minute",
            True,
            int,
            'Menu time zone display_night_start time_minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Midnight_Hour",
            "Menu Timezone - Midnight: Hour",
            True,
            int,
            'Menu time zone display_midnight_start time_hour (SEQ22108)',
        ),
        ParamFieldInfo(
            "menuTimezoneStart_Midnight_Minute",
            "Menu Timezone - Midnight: Minute",
            True,
            int,
            'Menu time zone display_midnight_start time_minute (SEQ22108)',
        ),
        ParamFieldInfo(
            "remotePlayerThreatLvNotify_ThreatLv",
            "Network Player Threat Notification - Threat Level",
            True,
            int,
            'Network PC Threat Level Notification_Threat Level (SEQ21950)',
        ),
        ParamFieldInfo(
            "remotePlayerThreatLvNotify_NotifyDist",
            "Network Player Threat Notification - Notify Distance",
            True,
            float,
            'Network PC Threat Level Notification_Notification Distance [m] (SEQ21950)',
        ),
        ParamFieldInfo(
            "remotePlayerThreatLvNotify_EndNotifyDist",
            "Network Player Threat Notification - Max Notify Distance",
            True,
            float,
            'Network PC threat level notification_notification end distance [m] (SEQ21950)',
        ),
        ParamFieldInfo(
            "worldMapPointDiscoveryExpandRange",
            "World Map Point - Discovery Expand Range",
            True,
            float,
            'The default extended distance for the map point discovery area. When the "discovery area overwrite area" of the map point is invalid (-1), the discovery area is generated by expanding from its own area. Its extended distance',
        ),
        ParamFieldInfo(
            "worldMapPointReentryExpandRange",
            "World Map Point - Re-entry Expand Range",
            True,
            float,
            'The default extended distance for the map point\'s entry area. When the "participation area overwrite area" of the map point is invalid (-1), the participation area is generated by expanding from its own area. Its extended distance',
        ),
        ParamFieldInfo(
            "remotePlayerThreatLvNotify_NotifyTime",
            "Network Player Threat Notification - Notify Time",
            True,
            int,
            'Network PC Threat Level Notification_Notification Time [seconds] (SEQ21950)',
        ),
        ParamFieldInfo(
            "breakIn_A_rebreakInGoodsNum",
            "Phantom Bloody Finger - Count",
            True,
            int,
            'Number of "re-invasion items" to be given at the time of intrusion: Intrusion item_Greater system (ID102)',
        ),
        ParamFieldInfo(
            "breakIn_A_rebreakInGoodsId",
            "Phantom Bloody Finger - Goods ID",
            True,
            int,
            'Tool item ID of "re-invasion item" given at the time of intrusion: Invasion item_Greater system (ID102)',
        ),
        ParamFieldInfo(
            "rideJumpoff_SfxId",
            "Spiritspring SFX ID",
            True,
            int,
            'Big jump to get off _ sky SFXID',
        ),
        ParamFieldInfo(
            "rideJumpoff_SfxHeightOffset",
            "Spiritspring SFX Height Offset",
            True,
            float,
            'Big jump to get off_SFX base point offset in the sky',
        ),
        ParamFieldInfo(
            "rideJumpoff_SpEffectId",
            "Spiritspring SpEffect ID (Horse)",
            True,
            int,
            'In the big jump area to get off _ Special effect ID for PC horse',
        ),
        ParamFieldInfo(
            "rideJumpoff_SpEffectIdPc",
            "Spiritspring SpEffect ID (Player)",
            True,
            int,
            'Special effect ID for _PC in the big jump area to get off',
        ),
        ParamFieldInfo(
            "unlockExchangeMenuEventFlagId",
            "Unlock Exchange Menu - Event Flag ID",
            True,
            int,
            'Main menu �� Event flag to unlock the item creation menu',
        ),
        ParamFieldInfo(
            "unlockMessageMenuEventFlagId",
            "Unlock Message Menu - Event Flag ID",
            True,
            int,
            'Main menu �� Event flag to unlock the message menu',
        ),
        ParamFieldInfo(
            "breakInOnce_A_rebreakInGoodsNum",
            "Phantom Bloody Finger - Count",
            True,
            int,
            'Number of "re-invasion items" to be given at the time of intrusion: Intrusion item_Greater disposable (ID111)',
        ),
        ParamFieldInfo(
            "breakIn_B_rebreakInGoodsNum",
            "Phantom Recusant Finger - Count",
            True,
            int,
            'Number of "re-invasion items" to be given at the time of invasion: Invasion item_Volcano building system (ID112)',
        ),
        ParamFieldInfo(
            "breakInOnce_A_rebreakInGoodsId",
            "Phantom Bloody Finger - Goods ID",
            True,
            int,
            'Tool item ID of "re-invasion item" given at the time of intrusion: Invasion item_Greater disposable (ID111)',
        ),
        ParamFieldInfo(
            "breakIn_B_rebreakInGoodsId",
            "Phantom Recusant Finger - Goods ID",
            True,
            int,
            'Tool item ID of "re-invasion item" given at the time of invasion: Invasion item_Volcano building system (ID112)',
        ),
        ParamFieldInfo(
            "actionButtonInputCancelTime",
            "Action Button Input Cancel Time",
            True,
            float,
            'Time to disable action button operation by holding down the action button',
        ),
        ParamFieldInfo(
            "blockClearBonusDelayTime",
            "Boss Kill - Rune Acquisition Delay Time",
            True,
            float,
            'Clear bonus acquisition delay time after boss defeat processing',
        ),
        ParamFieldInfo(
            "bonfireCheckEnemyRange",
            "Bonfire Check Enemy Range",
            True,
            float,
            '[Unused] (Refer to SEQ25048) Distance from PC to bonfire that determines invalidation of bonfire by enemy [m] (0 or less: PC distance is not checked. Checked at all distances)',
        ),
        ParamFieldInfo(
            "reserved_124[48]",
            "reserve",
            False,
            pad_field(48),
            '(dummy8)',
        ),
    ],
}
