from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


GRASS_TYPE_PARAM_ST = {
    "param_type": "GRASS_TYPE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "lodRange",
            "LOD Distance",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "lod0ClusterType",
            "LOD 0 - Cluster Type",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "lod1ClusterType",
            "LOD 1 - Cluster Type",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "lod2ClusterType",
            "LOD 2 - Cluster Type",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "pad0[2]",
            "pad0",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "distributionType",
            "Placement Method",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "baseDensity",
            "Base Density",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "model0Name[16]",
            "Model Name [0]",
            True,
            str,
            '',
        ),
        ParamFieldInfo(
            "flatTextureName[32]",
            "Flat Texture Name",
            True,
            str,
            '',
        ),
        ParamFieldInfo(
            "billboardTextureName[32]",
            "Billboard Texture Name",
            True,
            str,
            '',
        ),
        ParamFieldInfo(
            "normalInfluence",
            "Effect of Tilt %",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "inclinationMax",
            "Maximum Tilt Angle",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "inclinationJitter",
            "Randomness of Tilt Angle",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "scaleBaseMin",
            "Width Scale - Min",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "scaleBaseMax",
            "Width Scale - Max",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "scaleHeightMin",
            "Height Scale - Min",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "scaleHeightMax",
            "Height Scale - Max",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade1_r",
            "Color Shade [1]: R",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade1_g",
            "Color Shade [1]: G",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade1_b",
            "Color Shade [1]: B",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade2_r",
            "Color Shade [2]: R",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade2_g",
            "Color Shade [1]: G",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "colorShade2_b",
            "Color Shade [1]: B",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "flatSplitType",
            "Plane Split Type",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "flatBladeCount",
            "Number of Planes",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "flatSlant",
            "Plane Angle",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "flatRadius",
            "Plane Distance",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "castShadow",
            "Cast Shadow",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "windAmplitude",
            "Wind Amplitude",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "pad1[1]",
            "pad1",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "windCycle",
            "Wind Speed",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "orientationAngle",
            "Direction",
            True,
            float,
            'Random for -1',
        ),
        ParamFieldInfo(
            "orientationRange",
            "Direction Range",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "spacing",
            "Model Spacing",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "dithering",
            "Dithering",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "pad[3]",
            "pad2",
            False,
            pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "simpleModelName[16]",
            "Simple Model Name",
            True,
            str,
            '',
        ),
        ParamFieldInfo(
            "model1Name[16]",
            "Model Name [1]",
            True,
            str,
            '',
        ),
    ],
}
