from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


HIT_MTRL_PARAM_ST = {
    "param_type": "HIT_MTRL_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "aiVolumeRate",
            "AI Volume Rate",
            True,
            float,
            'Normal when 1x. When set to 0, the radius of sound becomes 0 (SE and SFX are unrelated game-like parameters).',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0",
            "On Hit [1] - SpEffect ID",
            True,
            int,
            'When the character steps on the hit material, the set special effect 0 is exhibited.',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1",
            "On Hit [2] - SpEffect ID",
            True,
            int,
            'When the character steps on the hit material, the set special effect 1 is exhibited.',
        ),
        ParamFieldInfo(
            "footEffectHeightType:2",
            "Foot Effect Height Type",
            True,
            int,
            'Height to generate foot effect',
        ),
        ParamFieldInfo(
            "footEffectDirType:2",
            "Foot Effect Direction Type",
            True,
            int,
            'Direction of foot effect',
        ),
        ParamFieldInfo(
            "floorHeightType:2",
            "Floor Height Type",
            True,
            int,
            'For floating items such as the surface of the water',
        ),
        ParamFieldInfo(
            "disableFallDamage:1",
            "Disable Fall Damage",
            True,
            int,
            'Set to 1 for floors that are not subject to fall damage',
        ),
        ParamFieldInfo(
            "isHardnessForSoundReverb:1",
            "Is Hardness for Sound Reverb",
            True,
            int,
            'Is it a hard material for sound echo? (0: soft, 1: hard)',
        ),
        ParamFieldInfo(
            "hardnessType",
            "Hardness Type",
            True,
            int,
            'The hardness of the material. Used for soft contact processing of rigid bodies.',
        ),
        ParamFieldInfo(
            "pad2[6]",
            "pad",
            False,
            pad_field(6),
            'pad',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_2",
            "On Hit [0] - NG+1 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 2nd lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_3",
            "On Hit [0] - NG+2 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 3rd lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_4",
            "On Hit [0] - NG+3 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 4th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_5",
            "On Hit [0] - NG+4 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 5th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_6",
            "On Hit [0] - NG+5 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 6th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_7",
            "On Hit [0] - NG+6 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 7th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit0_ClearCount_8",
            "On Hit [0] - NG+7 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 0 8th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_2",
            "On Hit [1] - NG+1 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1st lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_3",
            "On Hit [1] - NG+2 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1 3rd lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_4",
            "On Hit [1] - NG+3 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1 4th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_5",
            "On Hit [1] - NG+4 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1 5th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_6",
            "On Hit [1] - NG+5 - SpEffect ID",
            True,
            int,
            'Special effect when stepping on the hit material 1 6th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_7",
            "On Hit [1] - NG+6 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1 7th lap',
        ),
        ParamFieldInfo(
            "spEffectIdOnHit1_ClearCount_8",
            "On Hit [1] - NG+7 - SpEffect ID",
            True,
            int,
            'Special effect applied when stepping on the hit material 1 8th lap',
        ),
        ParamFieldInfo(
            "replaceMateiralId_Rain",
            "Rain - Replace Material ID",
            True,
            int,
            'Hit material change destination ID due to weather (rain) (-1: No change)',
        ),
        ParamFieldInfo(
            "pad4[2]",
            "pad",
            False,
            pad_field(2),
            'pad',
        ),
        ParamFieldInfo(
            "spEffectId_forWet00",
            "Wetness [0] - SpEffect ID",
            True,
            int,
            'Special effect for wetting 00',
        ),
        ParamFieldInfo(
            "spEffectId_forWet01",
            "Wetness [1] - SpEffect ID",
            True,
            int,
            'Special effects for wetting 01',
        ),
        ParamFieldInfo(
            "spEffectId_forWet02",
            "Wetness [2] - SpEffect ID",
            True,
            int,
            'Special effects for wetting 02',
        ),
        ParamFieldInfo(
            "spEffectId_forWet03",
            "Wetness [3] - SpEffect ID",
            True,
            int,
            'Special effects for wetting 03',
        ),
        ParamFieldInfo(
            "spEffectId_forWet04",
            "Wetness [4] - SpEffect ID",
            True,
            int,
            'Special effects for wetting 04',
        ),
    ],
}
