from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


ITEMLOT_PARAM_ST = {
    "param_type": "ITEMLOT_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "lotItemId01",
            "Item ID [1]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId02",
            "Item ID [2]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId03",
            "Item ID [3]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId04",
            "Item ID [4]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId05",
            "Item ID [5]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId06",
            "Item ID [6]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId07",
            "Item ID [7]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemId08",
            "Item ID [8]",
            True,
            int,
            'Item ID that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory01",
            "Item Category [1]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory02",
            "Item Category [2]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory03",
            "Item Category [3]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory04",
            "Item Category [4]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory05",
            "Item Category [5]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory06",
            "Item Category [6]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory07",
            "Item Category [7]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemCategory08",
            "Item Category [8]",
            True,
            int,
            'Category of items that can be obtained',
        ),
        ParamFieldInfo(
            "lotItemBasePoint01",
            "Item Chance [1]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint02",
            "Item Chance [2]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint03",
            "Item Chance [3]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint04",
            "Item Chance [4]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint05",
            "Item Chance [5]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint06",
            "Item Chance [6]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint07",
            "Item Chance [7]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "lotItemBasePoint08",
            "Item Chance [8]",
            True,
            int,
            'Appearance point at normal time',
        ),
        ParamFieldInfo(
            "cumulateLotPoint01",
            "Item Accumulate Chance [1]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint02",
            "Item Accumulate Chance [2]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint03",
            "Item Accumulate Chance [3]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint04",
            "Item Accumulate Chance [4]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint05",
            "Item Accumulate Chance [5]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint06",
            "Item Accumulate Chance [6]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint07",
            "Item Accumulate Chance [7]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "cumulateLotPoint08",
            "Item Accumulate Chance [8]",
            True,
            int,
            'Appearance point at maximum cumulative',
        ),
        ParamFieldInfo(
            "getItemFlagId01",
            "Item Acquisition Flag [1]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId02",
            "Item Acquisition Flag [2]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId03",
            "Item Acquisition Flag [3]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId04",
            "Item Acquisition Flag [4]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId05",
            "Item Acquisition Flag [5]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId06",
            "Item Acquisition Flag [6]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId07",
            "Item Acquisition Flag [7]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId08",
            "Item Acquisition Flag [8]",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: common use)',
        ),
        ParamFieldInfo(
            "getItemFlagId",
            "Item Acquisition Flag",
            True,
            int,
            'Combined use of acquired flag and crunchy frame (0: flag invalid)',
        ),
        ParamFieldInfo(
            "cumulateNumFlagId",
            "Item Accumulate Flag [1]",
            True,
            int,
            'For saving the number of lottery (* 8 flag serial number used)',
        ),
        ParamFieldInfo(
            "cumulateNumMax",
            "Item Accumulate Max",
            True,
            int,
            'Maximum number of lottery cumulative (0: no cumulative)',
        ),
        ParamFieldInfo(
            "lotItem_Rarity",
            "Item Rarity",
            True,
            int,
            'Specify how valuable items are in the treasure chest. When -1, use the rarity of the equipment para without overwriting',
        ),
        ParamFieldInfo(
            "lotItemNum01",
            "Item Amount [1]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum02",
            "Item Amount [2]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum03",
            "Item Amount [3]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum04",
            "Item Amount [4]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum05",
            "Item Amount [5]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum06",
            "Item Amount [6]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum07",
            "Item Amount [7]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "lotItemNum08",
            "Item Amount [8]",
            True,
            int,
            'Number of items that can be acquired',
        ),
        ParamFieldInfo(
            "enableLuck01:1",
            "Affected by Item Discovery [1]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck02:1",
            "Affected by Item Discovery [2]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck03:1",
            "Affected by Item Discovery [3]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck04:1",
            "Affected by Item Discovery [4]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck05:1",
            "Affected by Item Discovery [5]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck06:1",
            "Affected by Item Discovery [6]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck07:1",
            "Affected by Item Discovery [7]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "enableLuck08:1",
            "Affected by Item Discovery [8]",
            True,
            int,
            "Whether the probability of lottery reflects the player's luck",
        ),
        ParamFieldInfo(
            "cumulateReset01:1",
            "Accumulate Reset [1]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset02:1",
            "Accumulate Reset [2]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset03:1",
            "Accumulate Reset [3]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset04:1",
            "Accumulate Reset [4]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset05:1",
            "Accumulate Reset [5]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset06:1",
            "Accumulate Reset [6]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset07:1",
            "Accumulate Reset [7]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "cumulateReset08:1",
            "Accumulate Reset [8]",
            True,
            int,
            'Whether to reset cumulatively',
        ),
        ParamFieldInfo(
            "GameClearOffset",
            "Game Clear Offset",
            True,
            int,
            'Offset during lap play',
        ),
        ParamFieldInfo(
            "canExecByFriendlyGhost:1",
            "Can Friendly Phantom Acquire",
            True,
            int,
            'Do you draw lots even when you are a cooperating spirit?',
        ),
        ParamFieldInfo(
            "canExecByHostileGhost:1",
            "Can Hostile Phantom Acquire",
            True,
            int,
            'Do you draw lots even when you are a hostile spirit?',
        ),
        ParamFieldInfo(
            "PAD1:6",
            "Blank",
            True,
            int,
            'PAD1',
        ),
        ParamFieldInfo(
            "PAD2",
            "Blank",
            True,
            int,
            'PAD2',
        ),
    ],
}
