from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


KNOCKBACK_PARAM_ST = {
    "param_type": "KNOCKBACK_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "damage_Min_ContTime",
            "Damage Level: Minimum - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for tiny damage animation',
        ),
        ParamFieldInfo(
            "damage_S_ContTime",
            "Damage Level: Small - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for small damage animation',
        ),
        ParamFieldInfo(
            "damage_M_ContTime",
            "Damage Level: Medium - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for medium damage animation',
        ),
        ParamFieldInfo(
            "damage_L_ContTime",
            "Damage Level: Heavy - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for heavy damage animation',
        ),
        ParamFieldInfo(
            "damage_BlowS_ContTime",
            "Damage Level: Small Blow-off - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for small blow-off damage animation',
        ),
        ParamFieldInfo(
            "damage_BlowM_ContTime",
            "Damage Level: Heavy Blow-off - Maintenance Time",
            True,
            float,
            'Set the maintenance time used during the big blow damage animation',
        ),
        ParamFieldInfo(
            "damage_Strike_ContTime",
            "Damage Level: Strike - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for slamming damage animation',
        ),
        ParamFieldInfo(
            "damage_Uppercut_ContTime",
            "Damage Level: Uppercut - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for launch damage animation',
        ),
        ParamFieldInfo(
            "damage_Push_ContTime",
            "Damage Level: Push - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for push damage animation',
        ),
        ParamFieldInfo(
            "damage_Breath_ContTime",
            "Damage Level: Breath - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for breath damage animation',
        ),
        ParamFieldInfo(
            "damage_HeadShot_ContTime",
            "Damage Level: Headshot - Maintenance Time",
            True,
            float,
            'Headshot damage Set the maintenance time used during animation',
        ),
        ParamFieldInfo(
            "guard_S_ContTime",
            "Guard Damage Level: Small - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for guard receiving small animation',
        ),
        ParamFieldInfo(
            "guard_L_ContTime",
            "Guard Damage Level: Heavy - Maintenance Time",
            True,
            float,
            'Set the maintenance time used at the time of guard receiving large animation',
        ),
        ParamFieldInfo(
            "guard_LL_ContTime",
            "Guard Damage Level: Very Heavy - Maintenance Time",
            True,
            float,
            'Set the maintenance time used for guard receiving oversized animation',
        ),
        ParamFieldInfo(
            "guardBrake_ContTime",
            "Guard Damage Level: Break - Maintenance Time",
            True,
            float,
            'Set the maintenance time specified at the time of guard scraping animation',
        ),
        ParamFieldInfo(
            "damage_Min_DecTime",
            "Damage Level: Minimum - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for minimal damage animation',
        ),
        ParamFieldInfo(
            "damage_S_DecTime",
            "Damage Level: Small - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for small damage animation',
        ),
        ParamFieldInfo(
            "damage_M_DecTime",
            "Damage Level: Medium - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for medium damage animation',
        ),
        ParamFieldInfo(
            "damage_L_DecTime",
            "Damage Level: Heavy - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for heavy damage animation',
        ),
        ParamFieldInfo(
            "damage_BlowS_DecTime",
            "Damage Level: Small Blow-off - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for small blow-off damage animation',
        ),
        ParamFieldInfo(
            "damage_BlowM_DecTime",
            "Damage Level: Heavy Blow-off - Deceleration Time",
            True,
            float,
            'Large blow-off damage Set the deceleration time used during animation',
        ),
        ParamFieldInfo(
            "damage_Strike_DecTime",
            "Damage Level: Strike - Deceleration Time",
            True,
            float,
            'Set the deceleration time used during slamming damage animation',
        ),
        ParamFieldInfo(
            "damage_Uppercut_DecTime",
            "Damage Level: Uppercut - Deceleration Time",
            True,
            float,
            'Set the deceleration time used during launch damage animation',
        ),
        ParamFieldInfo(
            "damage_Push_DecTime",
            "Damage Level: Push - Deceleration Time",
            True,
            float,
            'Set the deceleration time used during push damage animation',
        ),
        ParamFieldInfo(
            "damage_Breath_DecTime",
            "Damage Level: Breath - Deceleration Time",
            True,
            float,
            'Set the deceleration time used during breath damage animation',
        ),
        ParamFieldInfo(
            "damage_HeadShot_DecTime",
            "Damage Level: Headshot - Deceleration Time",
            True,
            float,
            'Headshot damage Set the deceleration time used during animation',
        ),
        ParamFieldInfo(
            "guard_S_DecTime",
            "Guard Damage Level: Small - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for guard receiving small animation',
        ),
        ParamFieldInfo(
            "guard_L_DecTime",
            "Guard Damage Level: Heavy - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for guard receiving large animation',
        ),
        ParamFieldInfo(
            "guard_LL_DecTime",
            "Guard Damage Level: Very Break - Deceleration Time",
            True,
            float,
            'Set the deceleration time used for guard receiving oversized animation',
        ),
        ParamFieldInfo(
            "guardBrake_DecTime",
            "Guard Damage Level: Break - Deceleration Time",
            True,
            float,
            'Set the deceleration time specified at the time of guard breaking animation',
        ),
        ParamFieldInfo(
            "pad[8]",
            "pading",
            False,
            pad_field(8),
            '',
        ),
    ],
}
