from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


LEGACY_DISTANT_VIEW_PARTS_REPLACE_PARAM = {
    "param_type": "LEGACY_DISTANT_VIEW_PARTS_REPLACE_PARAM",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "TargetMapId",
            "Target Map ID",
            True,
            int,
            'Specify the target map ID. Legacy only. (m12_34_56_78 �� 12345678). Initially it was only legacy, but it also supports open celestial sphere maps',
        ),
        ParamFieldInfo(
            "TargetEventId",
            "Target Event ID",
            True,
            int,
            'If you enter the target natural disaster event ID from "300, 310, 311 and 312", it will be [natural disaster replacement data]. If it is 0 or blank, it will be [Regional ID switching data] (SEQ16039).',
        ),
        ParamFieldInfo(
            "SrcAssetId",
            "Replacement Source Asset ID",
            True,
            int,
            'Replacement source AssetId: AEG123_456_9999 �� 123456',
        ),
        ParamFieldInfo(
            "SrcAssetPartsNo",
            "Replacement Source Asset Part ID",
            True,
            int,
            'Replacement source PartsNo: AEG123_456_9999 �� 9999',
        ),
        ParamFieldInfo(
            "DstAssetId",
            "Replacement Destination Asset ID",
            True,
            int,
            'Replacement destination AssetId: AEG123_456_9999 �� 123456',
        ),
        ParamFieldInfo(
            "DstAssetPartsNo",
            "Replacement Destination Asset Part ID",
            True,
            int,
            'Replacement destination PartsNo: AEG123_456_9999 �� 9999',
        ),
        ParamFieldInfo(
            "SrcAssetIdRangeMin",
            "Replacement Source Asset ID - Min Range",
            True,
            int,
            'Replacement source asset ID range specification Min',
        ),
        ParamFieldInfo(
            "SrcAssetIdRangeMax",
            "Replacement Source Asset ID - Max Range",
            True,
            int,
            'Replacement source asset ID range specification Max',
        ),
        ParamFieldInfo(
            "DstAssetIdRangeMin",
            "Replacement Destination Asset ID - Min Range",
            True,
            int,
            'Replacement destination asset ID range specification Min',
        ),
        ParamFieldInfo(
            "DstAssetIdRangeMax",
            "Replacement Destination Asset ID - Max Range",
            True,
            int,
            'Replacement destination asset ID range specification Max',
        ),
        ParamFieldInfo(
            "LimitedMapRegionId0",
            "Limited Map Region ID [0]",
            True,
            int,
            'MapGD Local ID restriction 0: Valid only when "Natural disaster event ID" is 0. The part is valid only with the MapGD local ID you set (SEQ16039).',
        ),
        ParamFieldInfo(
            "LimitedMapRegionId1",
            "Limited Map Region ID [1]",
            True,
            int,
            'MapGD Local ID Restriction 1: Valid only when "Natural Disaster Event ID" is 0. The part is valid only with the MapGD local ID you set (SEQ16039).',
        ),
        ParamFieldInfo(
            "LimitedMapRegionId2",
            "Limited Map Region ID [2]",
            True,
            int,
            'MapGD Local ID restriction 2: Valid only when "Natural disaster event ID" is 0. The part is valid only with the MapGD local ID you set (SEQ16039).',
        ),
        ParamFieldInfo(
            "LimitedMapRegionId3",
            "Limited Map Region ID [3]",
            True,
            int,
            'MapGD Local ID restriction 3: Valid only when "Natural disaster event ID" is 0. The part is valid only with the MapGD local ID you set (SEQ16039).',
        ),
        ParamFieldInfo(
            "reserve[4]",
            "reserve",
            False,
            pad_field(4),
            'reserve',
        ),
        ParamFieldInfo(
            "LimitedMapRegionAssetId",
            "Limited Map Region Asset ID",
            True,
            int,
            'MapGD Valid assets specified by local ID: AssetId: AEG123_456_9999 �� 123456',
        ),
        ParamFieldInfo(
            "LimitedMapRegioAssetPartsNo",
            "Limited Map Region Parts ID",
            True,
            int,
            'MapGD Valid assets specified by local ID: PartsNo: AEG123_456_9999 �� 9999',
        ),
        ParamFieldInfo(
            "LimitedMapRegioAssetIdRangeMin",
            "Limited Map Region Asset ID - Range Min",
            True,
            int,
            'MapGD Valid asset specification with local ID: Asset ID range specification Min',
        ),
        ParamFieldInfo(
            "LimitedMapRegioAssetIdRangeMax",
            "Limited Map Region Asset ID - Range Max",
            True,
            int,
            'MapGD Valid asset specification for local ID: Asset ID range specification Max',
        ),
    ],
}
