from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


LOAD_BALANCER_DRAW_DIST_SCALE_PARAM_ST = {
    "param_type": "LOAD_BALANCER_DRAW_DIST_SCALE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "Lv00",
            "Draw Distance Level 0",
            True,
            float,
            'Lv00 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv01",
            "Draw Distance Level 1",
            True,
            float,
            'Lv01 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv02",
            "Draw Distance Level 2",
            True,
            float,
            'Lv02 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv03",
            "Draw Distance Level 3",
            True,
            float,
            'Lv03 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv04",
            "Draw Distance Level 4",
            True,
            float,
            'Lv04 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv05",
            "Draw Distance Level 5",
            True,
            float,
            'Lv05 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv06",
            "Draw Distance Level 6",
            True,
            float,
            'Lv06 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv07",
            "Draw Distance Level 7",
            True,
            float,
            'Lv07 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv08",
            "Draw Distance Level 8",
            True,
            float,
            'Lv08 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv09",
            "Draw Distance Level 9",
            True,
            float,
            'Lv09 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv10",
            "Draw Distance Level 10",
            True,
            float,
            'Lv10 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv11",
            "Draw Distance Level 11",
            True,
            float,
            'Lv11 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv12",
            "Draw Distance Level 12",
            True,
            float,
            'Lv12 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv13",
            "Draw Distance Level 13",
            True,
            float,
            'Lv13 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv14",
            "Draw Distance Level 14",
            True,
            float,
            'Lv14 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv15",
            "Draw Distance Level 15",
            True,
            float,
            'Lv15 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv16",
            "Draw Distance Level 16",
            True,
            float,
            'Lv16 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv17",
            "Draw Distance Level 17",
            True,
            float,
            'Lv17 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv18",
            "Draw Distance Level 18",
            True,
            float,
            'Lv18 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv19",
            "Draw Distance Level 19",
            True,
            float,
            'Lv19 Drawing distance scale',
        ),
        ParamFieldInfo(
            "Lv20",
            "Draw Distance Level 20",
            True,
            float,
            'Lv20 Drawing distance scale',
        ),
        ParamFieldInfo(
            "reserve[44]",
            "Reserve",
            False,
            pad_field(44),
            'Reserve',
        ),
    ],
}
