from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


LOCK_CAM_PARAM_ST = {
    "param_type": "LOCK_CAM_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "camDistTarget",
            "Camera Target Distance",
            True,
            float,
            'Camera distance target',
        ),
        ParamFieldInfo(
            "rotRangeMinX",
            "Rotation Range - Min X",
            True,
            float,
            'Minimum X-axis rotation',
        ),
        ParamFieldInfo(
            "lockRotXShiftRatio",
            "Lock Rotation X - Shift Ratio",
            True,
            float,
            'Lock X rotation shift rate',
        ),
        ParamFieldInfo(
            "chrOrgOffset_Y",
            "Character Origin - Offset Z",
            True,
            float,
            'Character base point offset',
        ),
        ParamFieldInfo(
            "chrLockRangeMaxRadius",
            "Character Lock Range - Max Radius",
            True,
            float,
            'Maximum radius of character range',
        ),
        ParamFieldInfo(
            "camFovY",
            "Field of View - Vertical FOV",
            True,
            float,
            'Vertical angle of view',
        ),
        ParamFieldInfo(
            "chrLockRangeMaxRadius_forD",
            "Character Lock Range - Max Radius (Darkness)",
            True,
            float,
            'Lockable range of characters in dark places',
        ),
        ParamFieldInfo(
            "chrLockRangeMaxRadius_forPD",
            "Character Lock Range - Max Radius (Total Darkness)",
            True,
            float,
            'Character lockable range in total darkness',
        ),
        ParamFieldInfo(
            "closeMaxHeight",
            "Attack Capture - Upper Limit Height",
            True,
            float,
            'Automatic lock-on judgment height upper limit when non-lock-on is close',
        ),
        ParamFieldInfo(
            "closeMinHeight",
            "Attack Capture - Lower Limit Height",
            True,
            float,
            'Automatic lock-on judgment height lower limit when not locked on Proximity',
        ),
        ParamFieldInfo(
            "closeAngRange",
            "Attack Capture - Auto Acquisition - Angle Range Left",
            True,
            float,
            'Automatic lock-on judgment when non-lock-on Left / right angle [deg] Proximity',
        ),
        ParamFieldInfo(
            "closeMaxRadius",
            "Attack Capture - Auto Acquisition - Max Radius",
            True,
            float,
            'Automatic lock-on judgment distance when non-lock-on is close',
        ),
        ParamFieldInfo(
            "closeMaxRadius_forD",
            "Attack Capture - Auto Acquisition - Max Radius (Darkness)",
            True,
            float,
            'Automatic lock-on judgment distance at non-lock-on _ darkness proximity',
        ),
        ParamFieldInfo(
            "closeMaxRadius_forPD",
            "Attack Capture - Auto Acquisition - Max Radius (Total Darkness)",
            True,
            float,
            'Automatic lock-on when non-lock-on _ pitch black proximity',
        ),
        ParamFieldInfo(
            "bulletMaxRadius",
            "Attack Capture - Bullet - Max Radius",
            True,
            float,
            'Automatic lock-on judgment distance when non-lock-on bullet',
        ),
        ParamFieldInfo(
            "bulletMaxRadius_forD",
            "Attack Capture - Bullet - Max Radius (Dark)",
            True,
            float,
            'Automatic lock-on judgment distance at non-lock-on _ darkness bullet',
        ),
        ParamFieldInfo(
            "bulletMaxRadius_forPD",
            "Attack Capture - Bullet - Max Radius (Pitch Dark",
            True,
            float,
            'Automatic lock-on judgment distance at non-lock-on _ pitch black bullet',
        ),
        ParamFieldInfo(
            "bulletAngRange",
            "Attack Capture - Bullet - Angle Range Left/Right",
            True,
            float,
            'Automatic lock-on left / right angle when non-lock-on bullet',
        ),
        ParamFieldInfo(
            "lockTgtKeepTime",
            "Lock Target Keep Time",
            True,
            float,
            'Time to continue locking even if the lock condition is not met (disabled at 0.0)',
        ),
        ParamFieldInfo(
            "chrTransChaseRateForNormal",
            "Transition Chase Factor for Normal Character",
            True,
            float,
            'Normal character translation tracking rate (disabled at -1.0)',
        ),
        ParamFieldInfo(
            "pad[48]",
            "Padding",
            False,
            pad_field(48),
            '',
        ),
    ],
}
