from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


MENU_COMMON_PARAM_ST = {
    "param_type": "MENU_COMMON_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "soloPlayDeath_ToFadeOutTime",
            "[YOU DIED] Fade Out Duration - Host",
            True,
            float,
            'How many seconds have passed after "YOU DIED" is displayed at the time of death of solo play to start fading out?',
        ),
        ParamFieldInfo(
            "partyGhostDeath_ToFadeOutTime",
            "[YOU DIED] Fade Out Duration - Phnatom",
            True,
            float,
            'How many seconds have passed after "YOU DIED" is displayed when a white or black ghost dies to start fading out?',
        ),
        ParamFieldInfo(
            "playerMaxHpLimit",
            "HP Bar - Visual Scale",
            True,
            int,
            'It is used to calculate what percentage of the gauge length provided by the resource is used when displaying the HP gauge.',
        ),
        ParamFieldInfo(
            "playerMaxMpLimit",
            "FP Bar - Visual Scale",
            True,
            int,
            'It is used to calculate what percentage of the gauge length provided by the resource is used when displaying the MP gauge.',
        ),
        ParamFieldInfo(
            "playerMaxSpLimit",
            "Stamina Bar - Visual Scale",
            True,
            int,
            'It is used to calculate what percentage of the gauge length provided by the resource is used when displaying the SP gauge.',
        ),
        ParamFieldInfo(
            "actionPanelChangeThreshold_Vel",
            "Action Panel Change Threshold - Velocity",
            True,
            float,
            'Action panel Switchable player speed. Switchable if below this speed',
        ),
        ParamFieldInfo(
            "actionPanelChangeThreshold_PassTime",
            "Action Panel Change Threshold - Pass Time",
            True,
            float,
            'Action panel Consideration time to increase the speed of switchable players. Use the average speed of this time (systematically up to 4 seconds)',
        ),
        ParamFieldInfo(
            "kgIconVspace",
            "Vertical Position of Key Guide Icon",
            True,
            int,
            'Vertical position of key guide icon (+: top,-: bottom)',
        ),
        ParamFieldInfo(
            "worldMapCursorSelectRadius",
            "World Map - Cursor Select Radius",
            True,
            float,
            'If the cursor position is within this radius, it means that it is selected.',
        ),
        ParamFieldInfo(
            "reserved8[4]",
            "reserve",
            False,
            pad_field(4),
            '(dummy8)',
        ),
        ParamFieldInfo(
            "decalPosOffsetX",
            "Decal Position Offset: X",
            True,
            int,
            'Decal display position offset left and right',
        ),
        ParamFieldInfo(
            "decalPosOffsetY",
            "Decal Position Offset: Y",
            True,
            int,
            'Decal display position offset vertical direction',
        ),
        ParamFieldInfo(
            "targetStateSearchDurationTime",
            "FE Search Icon Fade Time",
            True,
            float,
            'The number of seconds it takes for the FE Search icon to start fading in and then fading out.',
        ),
        ParamFieldInfo(
            "targetStateBattleDurationTime",
            "FE Battle Icon Fade Time",
            True,
            float,
            'The number of seconds it takes for the FE Battle icon to start fading in and then fading out.',
        ),
        ParamFieldInfo(
            "worldMapCursorSpeed",
            "World Map - Cursor Speed",
            True,
            float,
            'Movement speed when moving smoothly [px]',
        ),
        ParamFieldInfo(
            "worldMapCursorFirstDistance",
            "World Map - Cursor First Distance",
            True,
            float,
            'Distance to move only once at the first input [px]',
        ),
        ParamFieldInfo(
            "worldMapCursorFirstDelay",
            "World Map - Cursor First Delay",
            True,
            float,
            'The time it takes to move only once at the first input [sec]',
        ),
        ParamFieldInfo(
            "worldMapCursorWaitTime",
            "World Map - Cursor Wait Time",
            True,
            float,
            'Waiting time from input to smooth movement [sec]',
        ),
        ParamFieldInfo(
            "worldMapCursorSnapRadius",
            "World Map - Cursor Snap Radius",
            True,
            float,
            'Move the cursor closer than this radius to start adsorption (for snap mode) [px]',
        ),
        ParamFieldInfo(
            "worldMapCursorSnapTime",
            "World Map - Cursor Snap Time",
            True,
            float,
            'The time it takes to start and complete adsorption [sec]',
        ),
        ParamFieldInfo(
            "itemGetLogAliveTime",
            "Item Get Log Alive Time",
            True,
            float,
            'Time to add one line of log and fade out. There is a timer for each line [sec]',
        ),
        ParamFieldInfo(
            "playerMaxSaLimit",
            "Player Max Poise Guage Length",
            True,
            int,
            'It is used to calculate what percentage of the gauge length provided by the resource is used when displaying the SA gauge.',
        ),
        ParamFieldInfo(
            "worldMap_IsChangeableLayerEventFlagId",
            "World Map - Underground Layer Event Flag ID",
            True,
            int,
            'Specify the event flag ID that manages whether it is possible to switch to the underground map. When this event flag ID is ON, it is possible to switch to the underground map.',
        ),
        ParamFieldInfo(
            "worldMap_TravelMargin",
            "World Map - Travel Margin",
            True,
            float,
            'Distance (m) that extends in four directions around the player. I decided to break through this range',
        ),
        ParamFieldInfo(
            "systemAnnounceScrollBufferTime",
            "System Announcement - Scroll Buffer Time",
            True,
            float,
            'The number of seconds to wait before and after scrolling through the long text of the operation announcement. For example, if it is 3 seconds, wait for a total of 6 seconds before and after.',
        ),
        ParamFieldInfo(
            "systemAnnounceScrollSpeed",
            "System Announcement - Scroll Speed",
            True,
            int,
            'Scrolling speed (pixels / second) when scrolling long sentences in the operation announcement. It does not depend on the screen size. Think of the entire menu as 1920x1080',
        ),
        ParamFieldInfo(
            "systemAnnounceNoScrollWaitTime",
            "System Announcement - No Scroll Wait Time",
            True,
            float,
            'The number of seconds to display when it is a short sentence that does not require scrolling of the operation announcement',
        ),
        ParamFieldInfo(
            "systemAnnounceScrollCount",
            "System Announcement - Scroll Count",
            True,
            int,
            'Number of times to repeat when scrolling long sentences of management announcement',
        ),
        ParamFieldInfo(
            "reserved17[3]",
            "reserve",
            False,
            pad_field(3),
            '(dummy8)',
        ),
        ParamFieldInfo(
            "compassMemoDispDistance",
            "Compass Memo Display Distance",
            True,
            float,
            'Display distance [m] of the memo marker displayed on the compass. Anything closer than this distance will be displayed',
        ),
        ParamFieldInfo(
            "compassBonfireDispDistance",
            "Compass Bonfire Display Distance",
            True,
            float,
            'The display distance of the bonfire displayed on the compass [m]. Anything closer than this distance will be displayed',
        ),
        ParamFieldInfo(
            "markerGoalThreshold",
            "Destination Marrker Threshold",
            True,
            float,
            'Goal judgment distance [m] of the destination marker. The destination marker disappears when you get closer than this distance',
        ),
        ParamFieldInfo(
            "svSliderStep",
            "Saturation/Brightness Slider Step",
            True,
            float,
            'Amount of movement of the saturation / brightness slider of the color control [% / sec]. Maximum amount to move in 1 second when each value is 0% to 100%. Since it is operated with an analog stick, it becomes a ratio by the input value.',
        ),
        ParamFieldInfo(
            "preOpeningMovie_WaitSec",
            "Pre-opening Movie - Wait Time",
            True,
            float,
            'Wait time before playing the OP movie. > SEQ 15261',
        ),
        ParamFieldInfo(
            "kgIconScale",
            "Key Guide Icon - Scale",
            True,
            float,
            'The scale value of the key guide icon. 100% is the texture size as it is',
        ),
        ParamFieldInfo(
            "kgIconScale_forTable",
            "Key Guide Icon for Table - Scale",
            True,
            float,
            'Scale value of the key guide icon for the pad operation list. 100% is the texture size as it is',
        ),
        ParamFieldInfo(
            "kgIconVspace_forTable",
            "Key Guide Icon for Table - Vertical Position",
            True,
            int,
            'Vertical position of the key guide icon for the pad operation list (+: top,-: bottom)',
        ),
        ParamFieldInfo(
            "kgIconScale_forConfig",
            "Key Guide Icon for Key Config - Scale",
            True,
            float,
            'The scale value of the key guide icon for the key config. 100% is the texture size as it is',
        ),
        ParamFieldInfo(
            "kgIconVspace_forConfig",
            "Key Guide Icon for Key Config - Vertical Position",
            True,
            int,
            'Vertical position of key guide icon for key config (+: top,-: bottom)',
        ),
        ParamFieldInfo(
            "worldMap_SearchRadius",
            "World Map Search Radius",
            True,
            float,
            'Range [m] (radius) that makes unsearched masks searched. It is assumed that the circle centered on the player has been searched.',
        ),
        ParamFieldInfo(
            "tutorialDisplayTime",
            "Tutorial Display Time",
            True,
            float,
            'Tutorial (toast notification) display time [sec]. It will be closed automatically after this time has passed',
        ),
        ParamFieldInfo(
            "compassFriendHostInnerDistance",
            "Compass Friendly Phantom Display Distance",
            True,
            float,
            'Display distance [m] of other players (friendly hosts) to be displayed on the compass. If you are more than this distance, it will be displayed on the compass.',
        ),
        ParamFieldInfo(
            "compassEnemyHostInnerDistance",
            "Compass Hostile Phantom Display Distance",
            True,
            float,
            'Display distance [m] of other players (enemy hosts) displayed on the compass. If you are more than this distance, it will be displayed on the compass.',
        ),
        ParamFieldInfo(
            "compassFriendGuestInnerDistance",
            "Compass Guest Phantom Display Distance",
            True,
            float,
            'Display distance [m] of other players (friendly guests) to be displayed on the compass. If you are more than this distance, it will be displayed on the compass.',
        ),
        ParamFieldInfo(
            "cutsceneKeyGuideAliveTime",
            "Cutscene Key Guide - Display Time",
            True,
            float,
            'The amount of time that the key guide will continue to be displayed after the cutscene skip has been pre-entered. Since skip input is accepted only while the key guide is displayed, it can be said that it is the skip input acceptance time.',
        ),
        ParamFieldInfo(
            "autoHideHpThresholdRatio",
            "Auto HUD: HP Ratio to display HUD",
            True,
            float,
            '[HUD: Auto setting] HP ratio. If the HP ratio is below this value, the HP gauge will always be displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "autoHideHpThresholdValue",
            "Auto HUD: Display HUD when below X HP",
            True,
            int,
            '[HUD: Auto setting] HP current value. If the current HP value is less than or equal to this value, the HP gauge will always be displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "autoHideMpThresholdRatio",
            "Auto HUD: FP Ratio to display HUD",
            True,
            float,
            '[HUD: Auto setting] MP ratio. If the MP ratio is below this value, the MP gauge is always displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "autoHideMpThresholdValue",
            "Auto HUD: Display HUD when below X FP",
            True,
            int,
            '[HUD: Auto setting] MP current value. If the current MP value is less than or equal to this value, the MP gauge is always displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "autoHideSpThresholdRatio",
            "Auto HUD: Stamina Ratio to display HUD",
            True,
            float,
            '[HUD: Auto setting] SP ratio. If the SP ratio is less than or equal to this value, the SP gauge is always displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "autoHideSpThresholdValue",
            "Auto HUD: Display HUD when below X Stamina",
            True,
            int,
            '[HUD: Auto setting] SP current value. If the current SP value is less than or equal to this value, the SP gauge is always displayed. Percentage and current value are OR conditions (displayed if either is satisfied)',
        ),
        ParamFieldInfo(
            "worldMapZoomAnimationTime",
            "World Map Zoom Animation Time",
            True,
            float,
            'World map: Time to zoom animation [seconds]',
        ),
        ParamFieldInfo(
            "worldMapIconScaleMin",
            "World Map Icon Minimum Scale",
            True,
            float,
            'World map: Display magnification of the map point icon at zoom step 0 (0.0 to 1.0). 1x (1.0) at zoom step 2. From there, the icon magnification is also interpolated according to the enlargement ratio.',
        ),
        ParamFieldInfo(
            "worldMap_TravelMargin_Point",
            "World Map - Travel Margin Point",
            True,
            float,
            'World map: Additional ban distance [m] when the ban is lifted in map point units. When the ban on map points such as the distant view stand is lifted, the ban on the traversal range will be lifted. Distance to be additionally extended in 4 directions around the map point',
        ),
        ParamFieldInfo(
            "enemyTagSafeLeft",
            "Enemy HP Guage - Max Left Justification",
            True,
            int,
            'How far can the center coordinates of the enemy HP gauge go to the left end? Since it is the center coordinate, the size of the gauge body is included.',
        ),
        ParamFieldInfo(
            "enemyTagSafeRight",
            "Enemy HP Guage - Max Right Justification",
            True,
            int,
            'How far can the center coordinates of the enemy HP gauge go to the right end? Since it is the center coordinate, the size of the gauge body is included.',
        ),
        ParamFieldInfo(
            "enemyTagSafeTop",
            "Enemy HP Guage - Max Top Justification",
            True,
            int,
            'How far can the center coordinates of the enemy HP gauge go to the upper end? Since it is the center coordinate, the size of the gauge body is included.',
        ),
        ParamFieldInfo(
            "enemyTagSafeBottom",
            "Enemy HP Guage - Max Bottom Justification",
            True,
            int,
            'How far can the center coordinates of the enemy HP gauge go to the lower end? Since it is the center coordinate, the size of the gauge body is included.',
        ),
        ParamFieldInfo(
            "pcHorseHpRecoverDispThreshold",
            "HP Threshold to display Horse HP",
            True,
            int,
            'Threshold for displaying the PC horse HP gauge at the time of recovery. "Constant value" of "Display HP bar when it increases more than a certain value at a time"',
        ),
        ParamFieldInfo(
            "reserved33[32]",
            "reserve",
            False,
            pad_field(32),
            '(dummy8)',
        ),
    ],
}
