from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


MODEL_SFX_PARAM_ST = {
    "param_type": "MODEL_SFX_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "sfxId_0",
            "SFX ID [0]",
            True,
            int,
            '0: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_0",
            "SFX Dummy Poly ID [0]",
            True,
            int,
            '0: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_0[8]",
            "0: Reservation",
            False,
            pad_field(8),
            '0: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_1",
            "SFX ID [1]",
            True,
            int,
            '1: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_1",
            "SFX Dummy Poly ID [1]",
            True,
            int,
            '1: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_1[8]",
            "1: Reservation",
            False,
            pad_field(8),
            '1: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_2",
            "SFX ID [2]",
            True,
            int,
            '2: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_2",
            "SFX Dummy Poly ID [2]",
            True,
            int,
            '2: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_2[8]",
            "2: Reservation",
            False,
            pad_field(8),
            '2: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_3",
            "SFX ID [3]",
            True,
            int,
            '3: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_3",
            "SFX Dummy Poly ID [3]",
            True,
            int,
            '3: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_3[8]",
            "3: Reservation",
            False,
            pad_field(8),
            '3: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_4",
            "SFX ID [4]",
            True,
            int,
            '4: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_4",
            "SFX Dummy Poly ID [4]",
            True,
            int,
            '4: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_4[8]",
            "4: Reservation",
            False,
            pad_field(8),
            '4: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_5",
            "SFX ID [5]",
            True,
            int,
            '5: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_5",
            "SFX Dummy Poly ID [5]",
            True,
            int,
            '5: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_5[8]",
            "5: Reservation",
            False,
            pad_field(8),
            '5: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_6",
            "SFX ID [6]",
            True,
            int,
            '6: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_6",
            "SFX Dummy Poly ID [6]",
            True,
            int,
            '6: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_6[8]",
            "6: Reservation",
            False,
            pad_field(8),
            '6: Reservation',
        ),
        ParamFieldInfo(
            "sfxId_7",
            "SFX ID [7]",
            True,
            int,
            '7: SfxID',
        ),
        ParamFieldInfo(
            "dmypolyId_7",
            "SFX Dummy Poly ID [7]",
            True,
            int,
            '7: Damipoli ID',
        ),
        ParamFieldInfo(
            "reserve_7[8]",
            "7: Reservation",
            False,
            pad_field(8),
            '7: Reservation',
        ),
    ],
}
