from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


MOVE_PARAM_ST = {
    "param_type": "MOVE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "stayId",
            "Stay ID",
            True,
            int,
            'stand-by',
        ),
        ParamFieldInfo(
            "walkF",
            "Walk - Forward",
            True,
            int,
            'Before walking',
        ),
        ParamFieldInfo(
            "walkB",
            "Walk - Backward",
            True,
            int,
            'After walking',
        ),
        ParamFieldInfo(
            "walkL",
            "Walk - Left",
            True,
            int,
            'Walking left',
        ),
        ParamFieldInfo(
            "walkR",
            "Walk - Right",
            True,
            int,
            'Walking right',
        ),
        ParamFieldInfo(
            "dashF",
            "Dash - Forward",
            True,
            int,
            'Before driving',
        ),
        ParamFieldInfo(
            "dashB",
            "Dash - Backward",
            True,
            int,
            'After running',
        ),
        ParamFieldInfo(
            "dashL",
            "Dash - Left",
            True,
            int,
            'Driving left',
        ),
        ParamFieldInfo(
            "dashR",
            "Dash - Right",
            True,
            int,
            'Driving right',
        ),
        ParamFieldInfo(
            "superDash",
            "Sprint Dash",
            True,
            int,
            'Dash move',
        ),
        ParamFieldInfo(
            "escapeF",
            "Evasion - Forward",
            True,
            int,
            'Before emergency avoidance',
        ),
        ParamFieldInfo(
            "escapeB",
            "Evasion - Backward",
            True,
            int,
            'After emergency avoidance',
        ),
        ParamFieldInfo(
            "escapeL",
            "Evasion - Left",
            True,
            int,
            'Emergency avoidance left',
        ),
        ParamFieldInfo(
            "escapeR",
            "Evasion - Right",
            True,
            int,
            'Emergency avoidance right',
        ),
        ParamFieldInfo(
            "turnL",
            "Turn - Left 90",
            True,
            int,
            '90 degree turn left',
        ),
        ParamFieldInfo(
            "trunR",
            "Turn - Right 90",
            True,
            int,
            '90 degree turn right',
        ),
        ParamFieldInfo(
            "largeTurnL",
            "Turn - Left 180",
            True,
            int,
            '180 degree turn left',
        ),
        ParamFieldInfo(
            "largeTurnR",
            "Turn - Right 180",
            True,
            int,
            '180 degree turn right',
        ),
        ParamFieldInfo(
            "stepMove",
            "Step Move",
            True,
            int,
            '180 degree turn right',
        ),
        ParamFieldInfo(
            "flyStay",
            "Fly Stay",
            True,
            int,
            'Flight standby',
        ),
        ParamFieldInfo(
            "flyWalkF",
            "Fly Walk - Forward",
            True,
            int,
            'Flight advance',
        ),
        ParamFieldInfo(
            "flyWalkFL",
            "Fly Walk - Forward Left",
            True,
            int,
            'Fly left forward. Low rotation',
        ),
        ParamFieldInfo(
            "flyWalkFR",
            "Fly Walk - Forward Right",
            True,
            int,
            'Fly right forward. Low rotation',
        ),
        ParamFieldInfo(
            "flyWalkFL2",
            "Fly Walk - Forward Left 2",
            True,
            int,
            'Flight left forward 2. High rotation',
        ),
        ParamFieldInfo(
            "flyWalkFR2",
            "Fly Walk - Forward Right 2",
            True,
            int,
            'Flight right forward 2. High rotation',
        ),
        ParamFieldInfo(
            "flyDashF",
            "Fly Dash - Forward",
            True,
            int,
            'High speed flight advance',
        ),
        ParamFieldInfo(
            "flyDashFL",
            "Fly Dash - Forward Left",
            True,
            int,
            'High-speed flight left forward. Low rotation',
        ),
        ParamFieldInfo(
            "flyDashFR",
            "Fly Dash - Forward Right",
            True,
            int,
            'High speed flight right forward. Low rotation',
        ),
        ParamFieldInfo(
            "flyDashFL2",
            "Fly Dash - Forward Left 2",
            True,
            int,
            'High speed flight left forward 2. High rotation',
        ),
        ParamFieldInfo(
            "flyDashFR2",
            "Fly Dash - Forward Right 2",
            True,
            int,
            'High speed flight right forward 2. High rotation',
        ),
        ParamFieldInfo(
            "dashEscapeF",
            "Fly Evasion - Forward",
            True,
            int,
            'Before dash emergency avoidance',
        ),
        ParamFieldInfo(
            "dashEscapeB",
            "Fly Evasion - Backward",
            True,
            int,
            'After dash emergency avoidance',
        ),
        ParamFieldInfo(
            "dashEscapeL",
            "Fly Evasion - Left",
            True,
            int,
            'Dash emergency avoidance left',
        ),
        ParamFieldInfo(
            "dashEscapeR",
            "Fly Evasion - Right",
            True,
            int,
            'Dash emergency avoidance right',
        ),
        ParamFieldInfo(
            "analogMoveParamId",
            "Analog Move Param ID",
            True,
            int,
            'Mobile animation parameter ID used in mobile animation blend',
        ),
        ParamFieldInfo(
            "turnNoAnimAngle",
            "No Anim Turn Angle",
            True,
            int,
            'If the turning angle is less than this value, the turning animation will not be played (only the enemy turning control is effective).',
        ),
        ParamFieldInfo(
            "turn45Angle",
            "45 Turn Angle",
            True,
            int,
            'If the turning angle is less than this value, the 45 degree turning animation will be played (only 2 bosses are valid).',
        ),
        ParamFieldInfo(
            "turn90Angle",
            "90 Turn Angle",
            True,
            int,
            'If the turning angle is less than this value, the 90 degree turning animation will be played (only the enemy turning control is effective).',
        ),
        ParamFieldInfo(
            "turnWaitNoAnimAngle",
            "Wait No Anim Turn Angle",
            True,
            int,
            'If the turning angle is less than this value, the turning animation will not be played [when stopped] (only valid for 2 boss legs)',
        ),
    ],
}
