from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


NETWORK_MSG_PARAM_ST = {
    "param_type": "NETWORK_MSG_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "priority",
            "Priority",
            True,
            int,
            'priority',
        ),
        ParamFieldInfo(
            "forcePlay",
            "Force Play",
            True,
            int,
            'Forced interrupt',
        ),
        ParamFieldInfo(
            "pad1[1]",
            "reserve",
            False,
            pad_field(1),
            'reserve',
        ),
        ParamFieldInfo(
            "normalWhite",
            "White Phantom - Normal",
            True,
            int,
            'White spirit (white sign)',
        ),
        ParamFieldInfo(
            "umbasaWhite",
            "White Phantom - Gold",
            True,
            int,
            'Sun spirit (white sign)',
        ),
        ParamFieldInfo(
            "berserkerWhite",
            "White Phantom - Berseker",
            True,
            int,
            'Berserker spirit (white sign)',
        ),
        ParamFieldInfo(
            "sinnerHeroWhite",
            "White Phantom - Sinner Hero",
            True,
            int,
            'Sinner Hero Spirit (white sign)',
        ),
        ParamFieldInfo(
            "normalBlack",
            "Black Phantom - Normal",
            True,
            int,
            'Dark spirit (red sign)',
        ),
        ParamFieldInfo(
            "umbasaBlack",
            "Black Phantom - Gold",
            True,
            int,
            'Sun spirit (red sign)',
        ),
        ParamFieldInfo(
            "berserkerBlack",
            "Black Phantom - Berserker",
            True,
            int,
            'Berserker spirit (red sign)',
        ),
        ParamFieldInfo(
            "forceJoinBlack",
            "Invasion - Black Phantom - Normal",
            True,
            int,
            'Intrusion_A',
        ),
        ParamFieldInfo(
            "forceJoinUmbasaBlack",
            "Invasion - Black Phantom - Gold",
            True,
            int,
            'Sun spirit (intrusion)',
        ),
        ParamFieldInfo(
            "forceJoinBerserkerBlack",
            "Invasion - Black Phantom - Berserker",
            True,
            int,
            'Berserker spirit (intrusion)',
        ),
        ParamFieldInfo(
            "sinnerHunterVisitor",
            "Sinner Hunter Visitor",
            True,
            int,
            'Sinner hunting spirit (visit)',
        ),
        ParamFieldInfo(
            "redHunterVisitor",
            "Red Hunter 1 Visitor",
            True,
            int,
            'Red Scare Spirit (Visit)',
        ),
        ParamFieldInfo(
            "guardianOfBossVisitor",
            "Boss Guardian Visitor",
            True,
            int,
            'Boss guardian spirit (visit)',
        ),
        ParamFieldInfo(
            "guardianOfForestMapVisitor",
            "Forest Hunter Visitor",
            True,
            int,
            'Map Guardian Spirit_Forest (Visit)',
        ),
        ParamFieldInfo(
            "guardianOfAnolisVisitor",
            "Darkmoon Blade Visitor",
            True,
            int,
            'Map Guardian_Anor (Visit)',
        ),
        ParamFieldInfo(
            "rosaliaBlack",
            "Black Phantom - Rosalia",
            True,
            int,
            'Rosalia spirit (red sign)',
        ),
        ParamFieldInfo(
            "forceJoinRosaliaBlack",
            "Invasion - Black Phantom - Rosalia",
            True,
            int,
            'Rosalia spirit (intrusion)',
        ),
        ParamFieldInfo(
            "redHunterVisitor2",
            "Red Hunter 2 Visitor",
            True,
            int,
            'Red Scare Spirit 2 (Visit)',
        ),
        ParamFieldInfo(
            "npc1",
            "NPC [1]",
            True,
            int,
            'NPC Pseudo Multi 1',
        ),
        ParamFieldInfo(
            "npc2",
            "NPC [2]",
            True,
            int,
            'NPC Pseudo Multi 2',
        ),
        ParamFieldInfo(
            "npc3",
            "NPC [3]",
            True,
            int,
            'NPC Pseudo Multi 3',
        ),
        ParamFieldInfo(
            "npc4",
            "NPC [4]",
            True,
            int,
            'NPC Pseudo Multi 4',
        ),
        ParamFieldInfo(
            "battleRoyal",
            "Arena",
            True,
            int,
            'Battle royale',
        ),
        ParamFieldInfo(
            "npc5",
            "NPC [5]",
            True,
            int,
            'NPC Pseudo Multi 5',
        ),
        ParamFieldInfo(
            "npc6",
            "NPC [6]",
            True,
            int,
            'NPC Pseudo Multi 6',
        ),
        ParamFieldInfo(
            "npc7",
            "NPC [7]",
            True,
            int,
            'NPC Pseudo Multi 7',
        ),
        ParamFieldInfo(
            "npc8",
            "NPC [8]",
            True,
            int,
            'NPC Pseudo Multi 8',
        ),
        ParamFieldInfo(
            "npc9",
            "NPC [9]",
            True,
            int,
            'NPC Pseudo Multi 9',
        ),
        ParamFieldInfo(
            "npc10",
            "NPC [10]",
            True,
            int,
            'NPC Pseudo Multi 10',
        ),
        ParamFieldInfo(
            "npc11",
            "NPC [11]",
            True,
            int,
            'NPC Pseudo Multi 11',
        ),
        ParamFieldInfo(
            "npc12",
            "NPC [12]",
            True,
            int,
            'NPC Pseudo Multi 12',
        ),
        ParamFieldInfo(
            "npc13",
            "NPC [13]",
            True,
            int,
            'NPC Pseudo Multi 13',
        ),
        ParamFieldInfo(
            "npc14",
            "NPC [14]",
            True,
            int,
            'NPC Pseudo Multi 14',
        ),
        ParamFieldInfo(
            "npc15",
            "NPC [15]",
            True,
            int,
            'NPC Pseudo Multi 15',
        ),
        ParamFieldInfo(
            "npc16",
            "NPC [16]",
            True,
            int,
            'NPC Pseudo Multi 16',
        ),
        ParamFieldInfo(
            "forceJoinBlack_B",
            "Invasion - Black Phantom - B",
            True,
            int,
            'Intrusion_B',
        ),
        ParamFieldInfo(
            "normalWhite_Npc",
            "NPC - White Phantom",
            True,
            int,
            'White spirit (white sign) for NPCs',
        ),
        ParamFieldInfo(
            "forceJoinBlack_Npc",
            "NPC - Black Phantom - Invasion",
            True,
            int,
            'For intrusion_A_NPCs',
        ),
        ParamFieldInfo(
            "forceJoinBlack_B_Npc",
            "NPC - Black Phantom B - Invasion",
            True,
            int,
            'For intrusion_B_NPCs',
        ),
        ParamFieldInfo(
            "forceJoinBlack_C_Npc",
            "NPC - Black Phantom C - Invasion",
            True,
            int,
            'For intrusion_C_NPCs',
        ),
        ParamFieldInfo(
            "pad2[28]",
            "reserve",
            False,
            pad_field(28),
            'reserve',
        ),
    ],
}
