from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


NPC_AI_BEHAVIOR_PROBABILITY_PARAM_ST = {
    "param_type": "NPC_AI_BEHAVIOR_PROBABILITY_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "param000",
            "Right-hand - R1 Combo",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param001",
            "Right-hand - R2 Combo",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param002",
            "Right-hand - Dash Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param003",
            "Right-hand - Forward Roll Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param004",
            "Right-hand - Side Roll Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param005",
            "Right-hand - Backward Roll Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param006",
            "Right-hand - Backstep Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param007",
            "Right-hand - Jump Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param008",
            "Right-hand - Dash Jump Attack",
            True,
            int,
            'Right-handed proximity behavior',
        ),
        ParamFieldInfo(
            "param009",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param010",
            "Right-hand - R1 Shoot (Bow)",
            True,
            int,
            'Right-handed long-range weapon action',
        ),
        ParamFieldInfo(
            "param011",
            "Right-hand - R2 Shoot (Bow)",
            True,
            int,
            'Right-handed long-range weapon action',
        ),
        ParamFieldInfo(
            "param012",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param013",
            "Right-hand - Forward Move (Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param014",
            "Right-hand - Backward Move (Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param015",
            "Right-hand - Side Move (Bow)",
            True,
            int,
            'Interrupt approached while holding a bow',
        ),
        ParamFieldInfo(
            "param016",
            "Right-hand - Side Roll (Bow)",
            True,
            int,
            'Interrupt approached while holding a bow',
        ),
        ParamFieldInfo(
            "param017",
            "Right-hand - No Interrupt (Bow)",
            True,
            int,
            'Interrupt approached while holding a bow',
        ),
        ParamFieldInfo(
            "param018",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param019",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param020",
            "Right-hand - Side Move (Melee Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param021",
            "Right-hand - Side Move (Medium Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param022",
            "Right-hand - Side Move (Long Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param023",
            "Right-hand - HP Recovery (Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param024",
            "Right-hand - Buff (Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param025",
            "Right-hand - Forward Move (Melee Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param026",
            "Right-hand - Backward Move (Melee Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param027",
            "Right-hand - Forward Move (Medium Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param028",
            "Right-hand - Backward Move (Medium Magic)",
            True,
            int,
            'Right hand magic action',
        ),
        ParamFieldInfo(
            "param029",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param030",
            "Right-hand - R1 Attack (Shield)",
            True,
            int,
            'Right hand shield action',
        ),
        ParamFieldInfo(
            "param031",
            "Right-hand - R2 Attack (Shield)",
            True,
            int,
            'Right hand shield action',
        ),
        ParamFieldInfo(
            "param032",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param033",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param034",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param035",
            "Right-hand - Backstep (Guard Succcess)",
            True,
            int,
            'Guard success interrupt',
        ),
        ParamFieldInfo(
            "param036",
            "Right-hand - No Interrupt (Guard Succcess)",
            True,
            int,
            'Guard success interrupt',
        ),
        ParamFieldInfo(
            "param037",
            "Right-hand - Guard Counter (Guard Succcess)",
            True,
            int,
            'Guard success interrupt',
        ),
        ParamFieldInfo(
            "param038",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param039",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param040",
            "Left-hand - R1 Combo (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param041",
            "Left-hand - R2 Combo (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param042",
            "Left-hand - L1 Combo (1H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param043",
            "Left-hand - Dash Attack (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param044",
            "Left-hand - Forward Roll (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param045",
            "Left-hand - Side Roll (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param046",
            "Left-hand - Backward Roll (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param047",
            "Left-hand - Backstep Attack (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param048",
            "Left-hand - Jump Attack (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param049",
            "Left-hand - Dash Jump Attack (2H Only)",
            True,
            int,
            'Left hand proximity behavior',
        ),
        ParamFieldInfo(
            "param050",
            "Left-hand - R1 Shoot (Bow)",
            True,
            int,
            'Left-handed long-range weapon action',
        ),
        ParamFieldInfo(
            "param051",
            "Left-hand - R2 Shoot (Bow)",
            True,
            int,
            'Left-handed long-range weapon action',
        ),
        ParamFieldInfo(
            "param052",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param053",
            "Left-hand - Forward Move (Long Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param054",
            "Left-hand - Backward Move (Long Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param055",
            "Left-hand - Parry Attack (Parry Success)",
            True,
            int,
            'Parry Success Interrupt',
        ),
        ParamFieldInfo(
            "param056",
            "Left-hand - No Interrupt (Parry Success)",
            True,
            int,
            'Parry Success Interrupt',
        ),
        ParamFieldInfo(
            "param057",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param058",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param059",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param060",
            "Left-hand - Side Move (Melee Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param061",
            "Left-hand - Side Move (Medium Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param062",
            "Left-hand - Side Move (Long Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param063",
            "Left-hand - HP Recovery (Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param064",
            "Left-hand - Buff (Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param065",
            "Left-hand - Forward Move (Melee Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param066",
            "Left-hand - Backward Move (Melee Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param067",
            "Left-hand - Forward Move (Medium Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param068",
            "Left-hand - Backward Move (Medium Magic)",
            True,
            int,
            'Left hand magic action',
        ),
        ParamFieldInfo(
            "param069",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param070",
            "Backstep",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param071",
            "Forward Roll",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param072",
            "Side Roll",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param073",
            "Backward Roll",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param074",
            "Side Move",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param075",
            "Common - Back",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param076",
            "Common - Backstep",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param077",
            "Common - Standby",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param078",
            "Common - 2H Right Switch",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param079",
            "Common - 2H Left Switch",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param080",
            "Common - 1H Switch",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param081",
            "Common - Approach Battle Distance",
            True,
            int,
            'Common behavior',
        ),
        ParamFieldInfo(
            "param082",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param083",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param084",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param085",
            "Guard Break - Deadly Attack",
            True,
            int,
            'Guard break interrupt',
        ),
        ParamFieldInfo(
            "param086",
            "Guard Break - Dash Attack",
            True,
            int,
            'Guard break interrupt',
        ),
        ParamFieldInfo(
            "param087",
            "Guard Break - Melee Magic",
            True,
            int,
            'Guard break interrupt',
        ),
        ParamFieldInfo(
            "param088",
            "Guard Break - No Interrupt",
            True,
            int,
            'Guard break interrupt',
        ),
        ParamFieldInfo(
            "param089",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param090",
            "Special - Shield Bash",
            True,
            int,
            'Special behavior',
        ),
        ParamFieldInfo(
            "param091",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param092",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param093",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param094",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param095",
            "Flask Interrupt - Dash Attack",
            True,
            int,
            'Interrupt who drank Est',
        ),
        ParamFieldInfo(
            "param096",
            "Flask Interrupt - Throwable Item",
            True,
            int,
            'Interrupt who drank Est',
        ),
        ParamFieldInfo(
            "param097",
            "Flask Interrupt - No Interrupt",
            True,
            int,
            'Interrupt who drank Est',
        ),
        ParamFieldInfo(
            "param098",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param099",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param100",
            "Parry Interrupt - Parry",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param101",
            "Parry Interrupt - Forward Roll",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param102",
            "Parry Interrupt - Side Roll",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param103",
            "Parry Interrupt - Backward Roll",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param104",
            "Parry Interrupt - Backstep Attack",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param105",
            "Parry Interrupt - Stationary Guard",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param106",
            "Parry Interrupt - No Interrupt",
            True,
            int,
            'Parry Timing Interrupt',
        ),
        ParamFieldInfo(
            "param107",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param108",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param109",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param110",
            "Damaged Interrupt - Backward Roll",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param111",
            "Damaged Interrupt - Side Roll",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param112",
            "Damaged Interrupt - Backward Guard Move",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param113",
            "Damaged Interrupt - Side Move",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param114",
            "Damaged Interrupt - No Interrupt",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param115",
            "Damaged Interrupt - R1 Combo",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param116",
            "Damaged Interrupt - Forward Roll",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param117",
            "Damaged Interrupt - Backstep",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param118",
            "Damaged Interrupt - Forward Guard Move",
            True,
            int,
            'Damaged interrupt',
        ),
        ParamFieldInfo(
            "param119",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param120",
            "Bullet Interrupt - Forward Roll",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param121",
            "Bullet Interrupt - Side Roll",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param122",
            "Bullet Interrupt - Forward Guard Move",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param123",
            "Bullet Interrupt - Side Move",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param124",
            "Bullet Interrupt - No Interrupt",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param125",
            "Bullet Interrupt - After Roll",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param126",
            "Bullet Interrupt - Dash Approach",
            True,
            int,
            'Projectile discovery interrupt',
        ),
        ParamFieldInfo(
            "param127",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param128",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param129",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param130",
            "Attack Interrupt - Backstep",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param131",
            "Attack Interrupt - Forward Roll",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param132",
            "Attack Interrupt - Side Roll",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param133",
            "Attack Interrupt - After Roll",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param134",
            "Attack Interrupt - Forward Guard Move",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param135",
            "Attack Interrupt - Side Guard Move",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param136",
            "Attack Interrupt - Stationary Guard",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param137",
            "Attack Interrupt - Shield Bash",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param138",
            "Attack Interrupt - No Interrupt",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param139",
            "Attack Interrupt - Avoidance Weapon Art",
            True,
            int,
            'Attack detection interrupt',
        ),
        ParamFieldInfo(
            "param140",
            "Misc - 2H R1 Combo",
            True,
            int,
            'Other probability corrections',
        ),
        ParamFieldInfo(
            "param141",
            "Misc - 2H R2 Combo",
            True,
            int,
            'Other probability corrections',
        ),
        ParamFieldInfo(
            "param142",
            "Misc - Guard during Move",
            True,
            int,
            'Other probability corrections',
        ),
        ParamFieldInfo(
            "param143",
            "Misc - Dual-wield R1 Attack",
            True,
            int,
            'Other probability corrections',
        ),
        ParamFieldInfo(
            "param144",
            "Misc - Replace Roll with Movement Art",
            True,
            int,
            'Other probability corrections',
        ),
        ParamFieldInfo(
            "param145",
            "Misc - Use Throwable Item",
            True,
            int,
            'Item usage system',
        ),
        ParamFieldInfo(
            "param146",
            "Misc - Use HP Recovery Item",
            True,
            int,
            'Item usage system',
        ),
        ParamFieldInfo(
            "param147",
            "Misc - Use Buff Item",
            True,
            int,
            'Item usage system',
        ),
        ParamFieldInfo(
            "param148",
            "Misc - Use Buff Combo Attack",
            True,
            int,
            'Item usage system',
        ),
        ParamFieldInfo(
            "param149",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param150",
            "Weapon Art - Short Range Attack",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param151",
            "Weapon Art - Medium Range Attack",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param152",
            "Weapon Art - Ranged Attack",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param153",
            "Weapon Art - Recovery",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param154",
            "Weapon Art - Buff",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param155",
            "Unused",
            True,
            int,
            'Arts behavior system',
        ),
        ParamFieldInfo(
            "param156",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param157",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param158",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param159",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param160",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param161",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param162",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param163",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param164",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param165",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param166",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param167",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param168",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param169",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param170",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param171",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param172",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param173",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param174",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param175",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param176",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param177",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param178",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param179",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param180",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param181",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param182",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param183",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param184",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param185",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param186",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param187",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param188",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param189",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param190",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param191",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param192",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param193",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param194",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param195",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param196",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param197",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param198",
            "Unused",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "param199",
            "Unused",
            True,
            int,
            '',
        ),
    ],
}
