from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


OBJECT_MATERIAL_SFX_PARAM_ST = {
    "param_type": "OBJECT_MATERIAL_SFX_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "sfxId_00",
            "Hit VFX [00]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_01",
            "Hit VFX [01]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_02",
            "Hit VFX [02]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_03",
            "Hit VFX [03]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_04",
            "Hit VFX [04]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_05",
            "Hit VFX [05]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_06",
            "Hit VFX [06]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_07",
            "Hit VFX [07]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_08",
            "Hit VFX [08]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_09",
            "Hit VFX [09]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_10",
            "Hit VFX [10]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_11",
            "Hit VFX [11]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_12",
            "Hit VFX [12]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_13",
            "Hit VFX [13]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_14",
            "Hit VFX [14]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_15",
            "Hit VFX [15]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_16",
            "Hit VFX [16]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_17",
            "Hit VFX [17]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_18",
            "Hit VFX [18]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_19",
            "Hit VFX [19]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_20",
            "Hit VFX [20]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_21",
            "Hit VFX [21]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_22",
            "Hit VFX [22]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_23",
            "Hit VFX [23]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_24",
            "Hit VFX [24]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_25",
            "Hit VFX [25]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_26",
            "Hit VFX [26]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_27",
            "Hit VFX [27]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_28",
            "Hit VFX [28]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_29",
            "Hit VFX [29]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_30",
            "Hit VFX [30]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
        ParamFieldInfo(
            "sfxId_31",
            "Hit VFX [31]",
            True,
            int,
            'SFX identifier corresponding to the object parameter "SFX identifier after destruction"',
        ),
    ],
}
