from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


PARTS_DRAW_PARAM_ST = {
    "param_type": "PARTS_DRAW_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "lv01_BorderDist",
            "LOD 0-1 Boundry Distance",
            True,
            float,
            'Switching center',
        ),
        ParamFieldInfo(
            "lv01_PlayDist",
            "LOD 0-1 Play Distance",
            True,
            float,
            '�} play at the center of the boundary',
        ),
        ParamFieldInfo(
            "lv12_BorderDist",
            "LOD 1-2 Boundry Distance",
            True,
            float,
            'Switching center',
        ),
        ParamFieldInfo(
            "lv12_PlayDist",
            "LOD 1-2 Play Distance",
            True,
            float,
            '�} play at the center of the boundary',
        ),
        ParamFieldInfo(
            "lv23_BorderDist",
            "LOD 2-3 Boundry Distance",
            True,
            float,
            'Switching center',
        ),
        ParamFieldInfo(
            "lv23_PlayDist",
            "LOD 2-3 Play Distance",
            True,
            float,
            '�} play at the center of the boundary',
        ),
        ParamFieldInfo(
            "lv34_BorderDist",
            "LOD 3-4 Boundry Distance",
            True,
            float,
            'Switching center',
        ),
        ParamFieldInfo(
            "lv34_PlayDist",
            "LOD 3-4 Play Distance",
            True,
            float,
            '�} play at the center of the boundary',
        ),
        ParamFieldInfo(
            "lv45_BorderDist",
            "LOD 4-5 Boundry Distance",
            True,
            float,
            'Switching center',
        ),
        ParamFieldInfo(
            "lv45_PlayDist",
            "LOD 4-5 Play Distance",
            True,
            float,
            '�} play at the center of the boundary',
        ),
        ParamFieldInfo(
            "tex_lv01_BorderDist",
            "Texture Switch - LOD 0-1 Boundry Distance",
            True,
            float,
            'Texture switching center (Texure LOD disabled at 0)',
        ),
        ParamFieldInfo(
            "tex_lv01_PlayDist",
            "Texture Switch - LOD 0-1 Play Distance",
            True,
            float,
            'Texture Play around the boundary',
        ),
        ParamFieldInfo(
            "enableCrossFade:1",
            "Enable Crossfade",
            True,
            int,
            'Is crossfade enabled (0: disabled, 1: enabled)?',
        ),
        ParamFieldInfo(
            "drawDist",
            "Draw - Max Distance",
            True,
            float,
            'Maximum drawing distance. In the open, it will be used for the activation distance',
        ),
        ParamFieldInfo(
            "drawFadeRange",
            "Draw - Fade Range",
            True,
            float,
            'Fade distance from the maximum drawing distance to the actual disappearance',
        ),
        ParamFieldInfo(
            "shadowDrawDist",
            "Shadow Draw - Max Distance",
            True,
            float,
            'Maximum shadow drawing distance',
        ),
        ParamFieldInfo(
            "shadowFadeRange",
            "Shadow Draw - Fade Range",
            True,
            float,
            'Fade distance from the maximum shadow drawing distance to the actual disappearance',
        ),
        ParamFieldInfo(
            "motionBlur_BorderDist",
            "Motion Blur - Max Distance",
            True,
            float,
            'Distance at which motion blur is enabled',
        ),
        ParamFieldInfo(
            "isPointLightShadowSrc",
            "Is Point Light Shadow Source",
            True,
            int,
            'Cast the shadow of a point light source',
        ),
        ParamFieldInfo(
            "isDirLightShadowSrc",
            "Is Directional Light Shadow Source",
            True,
            int,
            'Cast the shadow of a parallel light source',
        ),
        ParamFieldInfo(
            "isShadowDst",
            "Is Shadow Destination",
            True,
            int,
            'Receive a shadow',
        ),
        ParamFieldInfo(
            "isShadowOnly",
            "Is Shadow Only",
            True,
            int,
            'Shadow drawing only',
        ),
        ParamFieldInfo(
            "drawByReflectCam",
            "Drawn by Reflection Camera",
            True,
            int,
            'Reflected',
        ),
        ParamFieldInfo(
            "drawOnlyReflectCam",
            "Drawn only by Reflection Camera",
            True,
            int,
            'Reflection drawing only',
        ),
        ParamFieldInfo(
            "IncludeLodMapLv",
            "Include LOD Map Level",
            True,
            int,
            'What level of LodMap to include',
        ),
        ParamFieldInfo(
            "isNoFarClipDraw",
            "Disable Far Clip Draw",
            True,
            int,
            'Disable fur clips and always draw at the innermost depth of the clip space. Mainly for celestial sphere',
        ),
        ParamFieldInfo(
            "lodType",
            "LOD Type",
            True,
            int,
            'Type and size of LOD target',
        ),
        ParamFieldInfo(
            "shadowDrawLodOffset",
            "Shadow Draw LOD Offset",
            True,
            int,
            'LOD level offset value when drawing shadows',
        ),
        ParamFieldInfo(
            "isTraceCameraXZ",
            "Follow Camera on XZ Plane",
            True,
            int,
            'Follow the camera on the XZ plane (GR SEQ09242)',
        ),
        ParamFieldInfo(
            "isSkydomeDrawPhase",
            "Is Celestial Sphere Draw Phase",
            True,
            int,
            'Set the drawing phase to the celestial sphere (GR SEQ09242)',
        ),
        ParamFieldInfo(
            "DistantViewModel_BorderDist",
            "Distant LOD - Boundry Distance",
            True,
            float,
            'Distance switching distance [m]',
        ),
        ParamFieldInfo(
            "DistantViewModel_PlayDist",
            "Distant LOD - Play Distance",
            True,
            float,
            'Distant view switching play distance [m]',
        ),
        ParamFieldInfo(
            "LimtedActivate_BorderDist_forGrid",
            "Open-world - Minimum Boundry Distance",
            True,
            float,
            'Construction limit distance for open [m]. If the distance to the camera is less than this distance in the open, it will not be built. This is a function for distant view assets. -1: Function disabled (default)',
        ),
        ParamFieldInfo(
            "LimtedActivate_PlayDist_forGrid",
            "Open-world - Minimum Play Distance",
            True,
            float,
            'Open construction limit play distance [m]',
        ),
        ParamFieldInfo(
            "zSortOffsetForNoFarClipDraw",
            "Z Sort Offset for No Far Clip Draw",
            True,
            float,
            'If the distance from the camera is the same in the same drawing phase, the smaller translucent system is drawn in the foreground, and the opaque system is drawn in the larger value. The base point of the offset is the origin in the celestial sphere drawing phase. Other than that, it is mainly Model AABB. (GR SEQ09242)',
        ),
        ParamFieldInfo(
            "shadowDrawAlphaTestDist",
            "Shadow Draw Alpha Test Distance",
            True,
            float,
            'Distance to perform alpha test when drawing shadow [m]',
        ),
        ParamFieldInfo(
            "fowardDrawEnvmapBlendType",
            "Forward Draw Envmap Blend Type",
            True,
            int,
            'Forward Drawing environment map Blend type',
        ),
        ParamFieldInfo(
            "LBDrawDistScaleParamID",
            "Load Balancer - Draw Distance Scale Param ID",
            True,
            int,
            'Load balancer drawing distance scale parameter ID',
        ),
        ParamFieldInfo(
            "resereve[34]",
            "reserve",
            False,
            pad_field(34),
            'reserve',
        ),
    ],
}
