from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


PHANTOM_PARAM_ST = {
    "param_type": "PHANTOM_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "edgeColorA",
            "Edge Color: Alpha",
            True,
            float,
            'Edge color A.',
        ),
        ParamFieldInfo(
            "frontColorA",
            "Front Color: Alpha",
            True,
            float,
            'The front color is A.',
        ),
        ParamFieldInfo(
            "diffMulColorA",
            "Diffuse Color: Alpha",
            True,
            float,
            'Diffuse multiplication color A.',
        ),
        ParamFieldInfo(
            "specMulColorA",
            "Specular Color: Alpha",
            True,
            float,
            'Specular multiplication color A.',
        ),
        ParamFieldInfo(
            "lightColorA",
            "Light Color: Alpha",
            True,
            float,
            'Light color A.',
        ),
        ParamFieldInfo(
            "edgeColorR",
            "Edge Color: R",
            True,
            int,
            'Edge color R.',
        ),
        ParamFieldInfo(
            "edgeColorG",
            "Edge Color: G",
            True,
            int,
            'Edge color G.',
        ),
        ParamFieldInfo(
            "edgeColorB",
            "Edge Color: B",
            True,
            int,
            'Edge color B.',
        ),
        ParamFieldInfo(
            "frontColorR",
            "Front Color: R",
            True,
            int,
            'The front color is R.',
        ),
        ParamFieldInfo(
            "frontColorG",
            "Front Color: G",
            True,
            int,
            'The front color is G.',
        ),
        ParamFieldInfo(
            "frontColorB",
            "Front Color: B",
            True,
            int,
            'Front color B.',
        ),
        ParamFieldInfo(
            "diffMulColorR",
            "Diffuse Color: R",
            True,
            int,
            'Diffuse multiplication color R.',
        ),
        ParamFieldInfo(
            "diffMulColorG",
            "Diffuse Color: G",
            True,
            int,
            'Diffuse multiplication color G.',
        ),
        ParamFieldInfo(
            "diffMulColorB",
            "Diffuse Color: B",
            True,
            int,
            'Diffuse multiplication color B.',
        ),
        ParamFieldInfo(
            "specMulColorR",
            "Specular Color: R",
            True,
            int,
            'Specular multiplication color R.',
        ),
        ParamFieldInfo(
            "specMulColorG",
            "Specular Color: G",
            True,
            int,
            'Specular multiplication color G.',
        ),
        ParamFieldInfo(
            "specMulColorB",
            "Specular Color: B",
            True,
            int,
            'Specular multiplication color B.',
        ),
        ParamFieldInfo(
            "lightColorR",
            "Light Color: R",
            True,
            int,
            'Light color R.',
        ),
        ParamFieldInfo(
            "lightColorG",
            "Light Color: G",
            True,
            int,
            'Light color G.',
        ),
        ParamFieldInfo(
            "lightColorB",
            "Light Color: B",
            True,
            int,
            'Light color B.',
        ),
        ParamFieldInfo(
            "reserve[1]",
            "Reserve",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "alpha",
            "Overall Alpha",
            True,
            float,
            'The overall transparency.',
        ),
        ParamFieldInfo(
            "blendRate",
            "Blend Rate",
            True,
            float,
            'The blend ratio.',
        ),
        ParamFieldInfo(
            "blendType",
            "Blend Type",
            True,
            int,
            'The type of alpha blend.',
        ),
        ParamFieldInfo(
            "isEdgeSubtract",
            "Perform Edge Color Subtraction",
            True,
            int,
            'Whether to perform edge color subtraction.',
        ),
        ParamFieldInfo(
            "isFrontSubtract",
            "Perform Front Color Subtraction",
            True,
            int,
            'Is it front color subtraction?',
        ),
        ParamFieldInfo(
            "isNo2Pass",
            "Is 1 Pass Only",
            True,
            int,
            'Do you not do 2pass?',
        ),
        ParamFieldInfo(
            "edgePower",
            "Edge Width",
            True,
            float,
            'Edge width',
        ),
        ParamFieldInfo(
            "glowScale",
            "Glow Strength",
            True,
            float,
            'Glow strength',
        ),
    ],
}
