from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


POSTURE_CONTROL_PARAM_GENDER_ST = {
    "param_type": "POSTURE_CONTROL_PARAM_GENDER_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "a000_rightElbowIO",
            "[a000] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a000_leftElbowIO",
            "[a000] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a000_bothLegsIO",
            "[a000] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a002_rightElbowIO",
            "[a002] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a002_leftElbowIO",
            "[a002] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a002_bothLegsIO",
            "[a002] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a003_rightElbowIO",
            "[a003] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a003_leftElbowIO",
            "[a003] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a003_bothLegsIO",
            "[a003] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a010_rightElbowIO",
            "[a010] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a010_leftElbowIO",
            "[a010] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a010_bothLegsIO",
            "[a010] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a012_rightElbowIO",
            "[a012] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a012_leftElbowIO",
            "[a012] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a012_bothLegsIO",
            "[a012] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a013_rightElbowIO",
            "[a013] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a013_leftElbowIO",
            "[a013] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a013_bothLegsIO",
            "[a013] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a014_rightElbowIO",
            "[a014] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a014_leftElbowIO",
            "[a014] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a014_bothLegsIO",
            "[a014] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a015_rightElbowIO",
            "[a015] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a015_leftElbowIO",
            "[a015] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a015_bothLegsIO",
            "[a015] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "a016_rightElbowIO",
            "[a016] Right Elbow - Inside/Outside",
            True,
            int,
            'Right elbow _ inside and outside',
        ),
        ParamFieldInfo(
            "a016_leftElbowIO",
            "[a016] Left Elbow - Inside/Outside",
            True,
            int,
            'Left elbow_inside and outside',
        ),
        ParamFieldInfo(
            "a016_bothLegsIO",
            "[a016] Both Legs - Inside/Outside",
            True,
            int,
            'Both feet _ inside and outside',
        ),
        ParamFieldInfo(
            "pad[10]",
            "pad",
            False,
            pad_field(10),
            '',
        ),
    ],
}
