from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


POSTURE_CONTROL_PARAM_WEP_RIGHT_ST = {
    "param_type": "POSTURE_CONTROL_PARAM_WEP_RIGHT_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "a000_rightArmFB",
            "[a000] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a000_rightWristFB",
            "[a000] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a000_rightWristIO",
            "[a000] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a000_leftArmFB",
            "[a000] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a000_leftWristFB",
            "[a000] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a000_leftWristIO",
            "[a000] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a002_rightArmFB",
            "[a002] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a002_rightWristFB",
            "[a002] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a002_rightWristIO",
            "[a002] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a002_leftArmFB",
            "[a002] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a002_leftWristFB",
            "[a002] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a002_leftWristIO",
            "[a002] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a003_rightArmFB",
            "[a003] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a003_rightWristFB",
            "[a003] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a003_rightWristIO",
            "[a003] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a003_leftArmFB",
            "[a003] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a003_leftWristFB",
            "[a003] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a003_leftWristIO",
            "[a003] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a010_rightArmFB",
            "[a010] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a010_rightWristFB",
            "[a010] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a010_rightWristIO",
            "[a010] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a010_leftArmFB",
            "[a010] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a010_leftWristFB",
            "[a010] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a010_leftWristIO",
            "[a010] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a012_rightArmFB",
            "[a012] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a012_rightWristFB",
            "[a012] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a012_rightWristIO",
            "[a012] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a012_leftArmFB",
            "[a012] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a012_leftWristFB",
            "[a012] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a012_leftWristIO",
            "[a012] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a013_rightArmFB",
            "[a013] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a013_rightWristFB",
            "[a013] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a013_rightWristIO",
            "[a013] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a013_leftArmFB",
            "[a013] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a013_leftWristFB",
            "[a013] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a013_leftWristIO",
            "[a013] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a014_rightArmFB",
            "[a014] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a014_rightWristFB",
            "[a014] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a014_rightWristIO",
            "[a014] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a014_leftArmFB",
            "[a014] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a014_leftWristFB",
            "[a014] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a014_leftWristIO",
            "[a014] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a015_rightArmFB",
            "[a015] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a015_rightWristFB",
            "[a015] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a015_rightWristIO",
            "[a015] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a015_leftArmFB",
            "[a015] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a015_leftWristFB",
            "[a015] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a015_leftWristIO",
            "[a015] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a016_rightArmFB",
            "[a016] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a016_rightWristFB",
            "[a016] Right Wrist - Front/Back",
            True,
            int,
            'Right wrist_front and back',
        ),
        ParamFieldInfo(
            "a016_rightWristIO",
            "[a016] Right Wrist - Inside/Outside",
            True,
            int,
            'Right wrist_inside and outside',
        ),
        ParamFieldInfo(
            "a016_leftArmFB",
            "[a016] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a016_leftWristFB",
            "[a016] Left Wrist - Front/Back",
            True,
            int,
            'Left wrist_front and back',
        ),
        ParamFieldInfo(
            "a016_leftWristIO",
            "[a016] Left Wrist - Inside/Outside",
            True,
            int,
            'Left wrist_inside and outside',
        ),
        ParamFieldInfo(
            "pad[4]",
            "pad",
            False,
            pad_field(4),
            '',
        ),
    ],
}
