from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


POSTURE_CONTROL_PARAM_PRO_ST = {
    "param_type": "POSTURE_CONTROL_PARAM_PRO_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "a000_rightArmIO",
            "[a000] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a000_rightArmFB",
            "[a000] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a000_leftArmIO",
            "[a000] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a000_leftArmFB",
            "[a000] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a002_rightArmIO",
            "[a002] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a002_rightArmFB",
            "[a002] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a002_leftArmIO",
            "[a002] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a002_leftArmFB",
            "[a002] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a003_rightArmIO",
            "[a003] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a003_rightArmFB",
            "[a003] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a003_leftArmIO",
            "[a003] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a003_leftArmFB",
            "[a003] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a010_rightArmIO",
            "[a010] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a010_rightArmFB",
            "[a010] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a010_leftArmIO",
            "[a010] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a010_leftArmFB",
            "[a010] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a012_rightArmIO",
            "[a012] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a012_rightArmFB",
            "[a012] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a012_leftArmIO",
            "[a012] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a012_leftArmFB",
            "[a012] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a013_rightArmIO",
            "[a013] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a013_rightArmFB",
            "[a013] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a013_leftArmIO",
            "[a013] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a013_leftArmFB",
            "[a013] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a014_rightArmIO",
            "[a014] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a014_rightArmFB",
            "[a014] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a014_leftArmIO",
            "[a014] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a014_leftArmFB",
            "[a014] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a015_rightArmIO",
            "[a015] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a015_rightArmFB",
            "[a015] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a015_leftArmIO",
            "[a015] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a015_leftArmFB",
            "[a015] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "a016_rightArmIO",
            "[a016] Right Arm - Inside/Outside",
            True,
            int,
            'Right arm_inside and outside',
        ),
        ParamFieldInfo(
            "a016_rightArmFB",
            "[a016] Right Arm - Front/Back",
            True,
            int,
            'Right arm_front and back',
        ),
        ParamFieldInfo(
            "a016_leftArmIO",
            "[a016] Left Arm - Inside/Outside",
            True,
            int,
            'Left arm_inside and outside',
        ),
        ParamFieldInfo(
            "a016_leftArmFB",
            "[a016] Left Arm - Front/Back",
            True,
            int,
            'Left arm_front and back',
        ),
        ParamFieldInfo(
            "pad[8]",
            "pad",
            False,
            pad_field(8),
            '',
        ),
    ],
}
