from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


RANDOM_APPEAR_PARAM_ST = {
    "param_type": "RANDOM_APPEAR_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "slot0:1",
            "Random Slot [0]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot1:1",
            "Random Slot [1]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot2:1",
            "Random Slot [2]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot3:1",
            "Random Slot [3]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot4:1",
            "Random Slot [4]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot5:1",
            "Random Slot [5]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot6:1",
            "Random Slot [6]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot7:1",
            "Random Slot [7]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot8:1",
            "Random Slot [8]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot9:1",
            "Random Slot [9]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot10:1",
            "Random Slot [10]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot11:1",
            "Random Slot [11]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot12:1",
            "Random Slot [12]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot13:1",
            "Random Slot [13]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot14:1",
            "Random Slot [14]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot15:1",
            "Random Slot [15]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot16:1",
            "Random Slot [16]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot17:1",
            "Random Slot [17]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot18:1",
            "Random Slot [18]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot19:1",
            "Random Slot [19]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot20:1",
            "Random Slot [20]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot21:1",
            "Random Slot [21]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot22:1",
            "Random Slot [22]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot23:1",
            "Random Slot [23]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot24:1",
            "Random Slot [24]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot25:1",
            "Random Slot [25]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot26:1",
            "Random Slot [26]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot27:1",
            "Random Slot [27]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot28:1",
            "Random Slot [28]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot29:1",
            "Random Slot [29]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot30:1",
            "Random Slot [30]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot31:1",
            "Random Slot [31]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot32:1",
            "Random Slot [32]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot33:1",
            "Random Slot [33]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot34:1",
            "Random Slot [34]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot35:1",
            "Random Slot [35]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot36:1",
            "Random Slot [36]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot37:1",
            "Random Slot [37]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot38:1",
            "Random Slot [38]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot39:1",
            "Random Slot [39]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot40:1",
            "Random Slot [40]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot41:1",
            "Random Slot [41]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot42:1",
            "Random Slot [42]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot43:1",
            "Random Slot [43]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot44:1",
            "Random Slot [44]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot45:1",
            "Random Slot [45]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot46:1",
            "Random Slot [46]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot47:1",
            "Random Slot [47]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot48:1",
            "Random Slot [48]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot49:1",
            "Random Slot [49]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot50:1",
            "Random Slot [50]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot51:1",
            "Random Slot [51]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot52:1",
            "Random Slot [52]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot53:1",
            "Random Slot [53]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot54:1",
            "Random Slot [54]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot55:1",
            "Random Slot [55]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot56:1",
            "Random Slot [56]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot57:1",
            "Random Slot [57]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot58:1",
            "Random Slot [58]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot59:1",
            "Random Slot [59]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot60:1",
            "Random Slot [60]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot61:1",
            "Random Slot [61]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot62:1",
            "Random Slot [62]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot63:1",
            "Random Slot [63]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot64:1",
            "Random Slot [64]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot65:1",
            "Random Slot [65]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot66:1",
            "Random Slot [66]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot67:1",
            "Random Slot [67]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot68:1",
            "Random Slot [68]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot69:1",
            "Random Slot [69]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot70:1",
            "Random Slot [70]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot71:1",
            "Random Slot [71]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot72:1",
            "Random Slot [72]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot73:1",
            "Random Slot [73]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot74:1",
            "Random Slot [74]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot75:1",
            "Random Slot [75]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot76:1",
            "Random Slot [76]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot77:1",
            "Random Slot [77]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot78:1",
            "Random Slot [78]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot79:1",
            "Random Slot [79]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot80:1",
            "Random Slot [80]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot81:1",
            "Random Slot [81]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot82:1",
            "Random Slot [82]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot83:1",
            "Random Slot [83]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot84:1",
            "Random Slot [84]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot85:1",
            "Random Slot [85]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot86:1",
            "Random Slot [86]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot87:1",
            "Random Slot [87]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot88:1",
            "Random Slot [88]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot89:1",
            "Random Slot [89]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot90:1",
            "Random Slot [90]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot91:1",
            "Random Slot [91]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot92:1",
            "Random Slot [92]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot93:1",
            "Random Slot [93]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot94:1",
            "Random Slot [94]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot95:1",
            "Random Slot [95]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot96:1",
            "Random Slot [96]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot97:1",
            "Random Slot [97]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot98:1",
            "Random Slot [98]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "slot99:1",
            "Random Slot [99]",
            True,
            int,
            'Will it appear if the slot is won?',
        ),
        ParamFieldInfo(
            "pad:4",
            "pad]",
            False,
            bit_pad_field(4),
            '',
        ),
    ],
}
