from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


REINFORCE_PARAM_WEAPON_ST = {
    "param_type": "REINFORCE_PARAM_WEAPON_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "physicsAtkRate",
            "Damage %: Physical",
            True,
            float,
            'Physical attack power correction value',
        ),
        ParamFieldInfo(
            "magicAtkRate",
            "Damage %: Magic",
            True,
            float,
            'Magic attack power correction value',
        ),
        ParamFieldInfo(
            "fireAtkRate",
            "Damage %: Fire",
            True,
            float,
            'Fire attack power correction value',
        ),
        ParamFieldInfo(
            "thunderAtkRate",
            "Damage %: Lightning",
            True,
            float,
            'Correction value of electric shock attack power',
        ),
        ParamFieldInfo(
            "staminaAtkRate",
            "Damage %: Stamina",
            True,
            float,
            'Stamina attack power correction value',
        ),
        ParamFieldInfo(
            "saWeaponAtkRate",
            "Damage %: Poise",
            True,
            float,
            'Super Armor Weapon Attack Color Correction Value',
        ),
        ParamFieldInfo(
            "saDurabilityRate",
            "Poise Durability",
            True,
            float,
            'SA endurance correction value',
        ),
        ParamFieldInfo(
            "correctStrengthRate",
            "Correction %: STR",
            True,
            float,
            'Correction value of muscle strength correction',
        ),
        ParamFieldInfo(
            "correctAgilityRate",
            "Correction %: DEX",
            True,
            float,
            'Correction value of agility correction',
        ),
        ParamFieldInfo(
            "correctMagicRate",
            "Correction %: INT",
            True,
            float,
            'Correction value of magic power correction',
        ),
        ParamFieldInfo(
            "correctFaithRate",
            "Correction %: FTH",
            True,
            float,
            'Correction value of faith correction',
        ),
        ParamFieldInfo(
            "physicsGuardCutRate",
            "Guard Absorption %: Physical",
            True,
            float,
            'Correction value of physical attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "magicGuardCutRate",
            "Guard Absorption %: Magic",
            True,
            float,
            'Correction value of magic attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "fireGuardCutRate",
            "Guard Absorption %: Fire",
            True,
            float,
            'Correction value of flame attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "thunderGuardCutRate",
            "Guard Absorption %: Lightning",
            True,
            float,
            'Correction value of electric shock attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "poisonGuardResistRate",
            "Guard Absorption %: Poison",
            True,
            float,
            'Correction value of poison attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "diseaseGuardResistRate",
            "Guard Absorption %: Scarlet Rot",
            True,
            float,
            'Correction value of plague attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "bloodGuardResistRate",
            "Guard Absorption %: Hemorrhage",
            True,
            float,
            'Correction value for bleeding attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "curseGuardResistRate",
            "Guard Absorption %: Blight",
            True,
            float,
            'Correction value of curse attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "staminaGuardDefRate",
            "Guard Absorption %: Stability",
            True,
            float,
            'Correction value of stamina defense power when guarding',
        ),
        ParamFieldInfo(
            "spEffectId1",
            "Behavior SpEffect [1] Offset",
            True,
            int,
            'Addition correction value for special effect ID1',
        ),
        ParamFieldInfo(
            "spEffectId2",
            "Behavior SpEffect [2] Offset",
            True,
            int,
            'Addition correction value for special effect ID2',
        ),
        ParamFieldInfo(
            "spEffectId3",
            "Behavior SpEffect [3] Offset",
            True,
            int,
            'Addition correction value for special effect ID3',
        ),
        ParamFieldInfo(
            "residentSpEffectId1",
            "Passive SpEffect [1] Offset",
            True,
            int,
            'Addition correction value for resident special effect ID1',
        ),
        ParamFieldInfo(
            "residentSpEffectId2",
            "Passive SpEffect [2] Offset",
            True,
            int,
            'Addition correction value for resident special effect ID2',
        ),
        ParamFieldInfo(
            "residentSpEffectId3",
            "Passive SpEffect [3] Offset",
            True,
            int,
            'Addition correction value for resident special effect ID3',
        ),
        ParamFieldInfo(
            "materialSetId",
            "Reinforcement Material Set Offset",
            True,
            int,
            'Addition correction value of material parameter ID',
        ),
        ParamFieldInfo(
            "maxReinforceLevel",
            "Max Reinforcement Level",
            True,
            int,
            'Level value for maximum enhanced weapon level',
        ),
        ParamFieldInfo(
            "darkAtkRate",
            "Damage %: Holy",
            True,
            float,
            'Dark attack power correction value',
        ),
        ParamFieldInfo(
            "darkGuardCutRate",
            "Guard Absorption %: Holy",
            True,
            float,
            'Correction value of darkness attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "correctLuckRate",
            "Correction %: ARC",
            True,
            float,
            'Correction value of luck correction',
        ),
        ParamFieldInfo(
            "freezeGuardDefRate",
            "Guard Absorption %: Frostbite",
            True,
            float,
            'Correction value of cold air attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "reinforcePriceRate",
            "Reinforce Price Rate",
            True,
            float,
            'Correction value to multiply the enhancement price of the weapon parameter',
        ),
        ParamFieldInfo(
            "baseChangePriceRate",
            "Base Change Price Rate",
            True,
            float,
            'Correction value to multiply the evolution price of the weapon parameter',
        ),
        ParamFieldInfo(
            "enableGemRank",
            "Ash of War Rank",
            True,
            int,
            'Mountable magic stone rank',
        ),
        ParamFieldInfo(
            "pad2[3]",
            "pad",
            False,
            pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "sleepGuardDefRate",
            "Guard Absorption %: Sleep",
            True,
            float,
            'Correction value of sleep attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "madnessGuardDefRate",
            "Guard Absorption %: Madness",
            True,
            float,
            'Correction value of mad attack cut rate when guarding',
        ),
        ParamFieldInfo(
            "baseAtkRate",
            "Base Damage %: Overall",
            True,
            float,
            'Additional attack power multiplier',
        ),
    ],
}
