from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


ROLE_PARAM_ST = {
    "param_type": "ROLE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "teamType",
            "Team Type",
            True,
            int,
            'Team type',
        ),
        ParamFieldInfo(
            "pad10[3]",
            "pad10",
            False,
            pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "phantomParamId",
            "Phantom Param ID - Vow [0]",
            True,
            int,
            'Phantom parameter ID when pledge rank is 0',
        ),
        ParamFieldInfo(
            "spEffectID0",
            "SpEffect ID [0]",
            True,
            int,
            'Resident special effect 0',
        ),
        ParamFieldInfo(
            "spEffectID1",
            "SpEffect ID [1]",
            True,
            int,
            'Resident special effect 1',
        ),
        ParamFieldInfo(
            "spEffectID2",
            "SpEffect ID [2]",
            True,
            int,
            'Resident special effect 2',
        ),
        ParamFieldInfo(
            "spEffectID3",
            "SpEffect ID [3]",
            True,
            int,
            'Resident special effect 3',
        ),
        ParamFieldInfo(
            "spEffectID4",
            "SpEffect ID [4]",
            True,
            int,
            'Resident special effect 4',
        ),
        ParamFieldInfo(
            "spEffectID5",
            "SpEffect ID [5]",
            True,
            int,
            'Resident special effect 5',
        ),
        ParamFieldInfo(
            "spEffectID6",
            "SpEffect ID [6]",
            True,
            int,
            'Resident special effect 6',
        ),
        ParamFieldInfo(
            "spEffectID7",
            "SpEffect ID [7]",
            True,
            int,
            'Resident special effect 7',
        ),
        ParamFieldInfo(
            "spEffectID8",
            "SpEffect ID [8]",
            True,
            int,
            'Resident special effect 8',
        ),
        ParamFieldInfo(
            "spEffectID9",
            "SpEffect ID [9]",
            True,
            int,
            'Resident special effect 9',
        ),
        ParamFieldInfo(
            "sosSignSfxId",
            "Summon Sign - SFX ID",
            True,
            int,
            'SOS sign SFX ID issued by another person',
        ),
        ParamFieldInfo(
            "mySosSignSfxId",
            "Personal Summon Sign - SFX ID",
            True,
            int,
            'SOS sign SFX ID issued by me',
        ),
        ParamFieldInfo(
            "summonStartAnimId",
            "Player Summon Start - Animation ID",
            True,
            int,
            'Anime ID to play when the player is summoned and the game starts',
        ),
        ParamFieldInfo(
            "itemlotParamId",
            "Map Itemlot Param ID",
            True,
            int,
            'Acquisition reward item lottery parameter ID_for map (not -1)',
        ),
        ParamFieldInfo(
            "voiceChatGroup",
            "Voice Chat Group",
            True,
            int,
            'Voice chat group',
        ),
        ParamFieldInfo(
            "roleNameColor",
            "Role Name Color",
            True,
            int,
            'The color of the role name text displayed on the FE of the network PC',
        ),
        ParamFieldInfo(
            "pad1[2]",
            "pad1",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "roleNameId",
            "Role Name - Text ID",
            True,
            int,
            'Text ID of the role name to be displayed on the FE of the network PC',
        ),
        ParamFieldInfo(
            "threatLv",
            "Threat Level",
            True,
            int,
            'Threat level',
        ),
        ParamFieldInfo(
            "phantomParamId_vowRank1",
            "Phantom Param ID - Vow Rank [1]",
            True,
            int,
            'Phantom parameter ID when pledge rank is 1',
        ),
        ParamFieldInfo(
            "phantomParamId_vowRank2",
            "Phantom Param ID - Vow Rank [2]",
            True,
            int,
            'Phantom parameter ID when pledge rank is 2',
        ),
        ParamFieldInfo(
            "phantomParamId_vowRank3",
            "Phantom Param ID - Vow Rank [3]",
            True,
            int,
            'Phantom parameter ID when pledge rank is 3',
        ),
        ParamFieldInfo(
            "spEffectID_vowRank0",
            "Phantom Param ID - Vow Rank [4]",
            True,
            int,
            'Special effect ID for SFX when pledge rank 0',
        ),
        ParamFieldInfo(
            "spEffectID_vowRank1",
            "Phantom Param ID - Vow Rank [5]",
            True,
            int,
            'Special effect ID for SFX when pledge rank 1',
        ),
        ParamFieldInfo(
            "spEffectID_vowRank2",
            "Phantom Param ID - Vow Rank [6]",
            True,
            int,
            'Special effect ID for SFX when pledge rank 2',
        ),
        ParamFieldInfo(
            "spEffectID_vowRank3",
            "Phantom Param ID - Vow Rank [7]",
            True,
            int,
            'Special effect ID for SFX when pledge rank 3',
        ),
        ParamFieldInfo(
            "signPhantomId",
            "Ghost Phantom ID",
            True,
            int,
            'Multiplayer pledge ghost body sign phantom ID designation for illusion',
        ),
        ParamFieldInfo(
            "nonPlayerSummonStartAnimId",
            "NPC Summon Start - Animation ID",
            True,
            int,
            'Anime ID to play when a player other than the player is summoned and the game starts',
        ),
        ParamFieldInfo(
            "pad2[16]",
            "pad2",
            False,
            pad_field(16),
            '',
        ),
    ],
}
