from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


ROLLING_OBJ_LOT_PARAM_ST = {
    "param_type": "ROLLING_OBJ_LOT_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "AssetId_0",
            "Asset ID [0]",
            True,
            int,
            'AssetId_0 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_1",
            "Asset ID [1]",
            True,
            int,
            'AssetId_1 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_2",
            "Asset ID [2]",
            True,
            int,
            'AssetId_2 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_3",
            "Asset ID [3]",
            True,
            int,
            'AssetId_3 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_4",
            "Asset ID [4]",
            True,
            int,
            'AssetId_4 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_5",
            "Asset ID [5]",
            True,
            int,
            'AssetId_5 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_6",
            "Asset ID [6]",
            True,
            int,
            'AssetId_6 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "AssetId_7",
            "Asset ID [7]",
            True,
            int,
            'AssetId_7 (-1: Ignore)',
        ),
        ParamFieldInfo(
            "CreateWeight_0",
            "Appearance Weight [0]",
            True,
            int,
            'Appearance ratio point (weight) _0: 0 is ignored',
        ),
        ParamFieldInfo(
            "CreateWeight_1",
            "Appearance Weight [1]",
            True,
            int,
            'Appearance ratio point (weight) _1',
        ),
        ParamFieldInfo(
            "CreateWeight_2",
            "Appearance Weight [2]",
            True,
            int,
            'Appearance ratio point (weight) _2',
        ),
        ParamFieldInfo(
            "CreateWeight_3",
            "Appearance Weight [3]",
            True,
            int,
            'Appearance ratio point (weight) _3',
        ),
        ParamFieldInfo(
            "CreateWeight_4",
            "Appearance Weight [4]",
            True,
            int,
            'Appearance ratio point (weight) _4',
        ),
        ParamFieldInfo(
            "CreateWeight_5",
            "Appearance Weight [5]",
            True,
            int,
            'Appearance ratio point (weight) _5',
        ),
        ParamFieldInfo(
            "CreateWeight_6",
            "Appearance Weight [6]",
            True,
            int,
            'Appearance ratio point (weight) _6',
        ),
        ParamFieldInfo(
            "CreateWeight_7",
            "Appearance Weight [7]",
            True,
            int,
            'Appearance ratio point (weight) _7',
        ),
        ParamFieldInfo(
            "Reserve_0[20]",
            "Reserve",
            False,
            pad_field(20),
            'Reserve',
        ),
    ],
}
