from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


SHOP_LINEUP_PARAM = {
    "param_type": "SHOP_LINEUP_PARAM",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "equipId",
            "Reference ID",
            True,
            int,
            'ID of the equipment for sale',
        ),
        ParamFieldInfo(
            "value",
            "Sell Price Overwrite",
            True,
            int,
            'Selling price to overwrite (-1: Do not overwrite)',
        ),
        ParamFieldInfo(
            "mtrlId",
            "Required Material ID",
            True,
            int,
            'Material ID required for purchase (-1: None)',
        ),
        ParamFieldInfo(
            "eventFlag_forStock",
            "Quantity - Event Flag ID",
            True,
            int,
            'Event flag value that holds the number',
        ),
        ParamFieldInfo(
            "eventFlag_forRelease",
            "Visibility - Event Flag ID",
            True,
            int,
            'Sales ban event flag',
        ),
        ParamFieldInfo(
            "sellQuantity",
            "Amount to Sell",
            True,
            int,
            'Number of units sold',
        ),
        ParamFieldInfo(
            "pad3[1]",
            "Padding",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "equipType",
            "Equipment Type",
            True,
            int,
            'Types of equipment for sale',
        ),
        ParamFieldInfo(
            "costType",
            "Currency Type",
            True,
            int,
            'Price type. Applies only when overwriting the selling price',
        ),
        ParamFieldInfo(
            "pad1[1]",
            "Padding",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "setNum",
            "Amount on Purchase",
            True,
            int,
            'Number of sets sold. Number of pieces you can get with one purchase (default: 1)',
        ),
        ParamFieldInfo(
            "value_Add",
            "Price Addition",
            True,
            int,
            'Correction (addition) to the selling price of equipment. Equipment para selling price x magnification + addition',
        ),
        ParamFieldInfo(
            "value_Magnification",
            "Price Multiplier",
            True,
            float,
            'Correction (magnification) to the selling price of equipment. Equipment para selling price x magnification + addition',
        ),
        ParamFieldInfo(
            "iconId",
            "Icon ID",
            True,
            int,
            'Menu display_icon ID (-1: do not overwrite)',
        ),
        ParamFieldInfo(
            "nameMsgId",
            "Name - Text ID",
            True,
            int,
            'Menu display_text ID (-1: do not overwrite)',
        ),
        ParamFieldInfo(
            "menuTitleMsgId",
            "Menu Title - Text ID",
            True,
            int,
            'Text ID of the shop menu title (-1: Do not overwrite). This value of the first para found in the para ID range passed when launching the shop is referenced',
        ),
        ParamFieldInfo(
            "menuIconId",
            "Menu Icon ID",
            True,
            int,
            'Shop menu icon ID (-1: Do not overwrite). This value of the first para found in the para ID range passed when launching the shop is referenced',
        ),
        ParamFieldInfo(
            "pad2[2]",
            "Padding",
            False,
            pad_field(2),
            '',
        ),
    ],
}
