from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


SP_EFFECT_PARAM_ST = {
    "param_type": "SP_EFFECT_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "iconId",
            "Icon ID",
            True,
            int,
            'Icon ID (When -1, no icon is required)',
        ),
        ParamFieldInfo(
            "conditionHp",
            "Trigger at HP Below %",
            True,
            float,
            'Set what percentage of maxHP the remaining HP will be activated',
        ),
        ParamFieldInfo(
            "effectEndurance",
            "Duration",
            True,
            float,
            'Change duration / -1 for permanent / 0 for one moment only',
        ),
        ParamFieldInfo(
            "motionInterval",
            "Trigger Interval",
            True,
            float,
            'Set how many seconds it occurs',
        ),
        ParamFieldInfo(
            "maxHpRate",
            "Max HP %",
            True,
            float,
            'Correct the maximum HP',
        ),
        ParamFieldInfo(
            "maxMpRate",
            "Max FP %",
            True,
            float,
            'Correct the maximum MP',
        ),
        ParamFieldInfo(
            "maxStaminaRate",
            "Max Stamina %",
            True,
            float,
            'Correct the maximum SP',
        ),
        ParamFieldInfo(
            "slashDamageCutRate",
            "Absorption %: Slash",
            True,
            float,
            'Slash damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "blowDamageCutRate",
            "Absorption %: Strike",
            True,
            float,
            'Batter damage ratio: The calculated damage is corrected by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "thrustDamageCutRate",
            "Absorption %: Thrust",
            True,
            float,
            'Puncture damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "neutralDamageCutRate",
            "Absorption %: Standard",
            True,
            float,
            'Non-attribute damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "magicDamageCutRate",
            "Absorption %: Magic",
            True,
            float,
            'Magic damage multiplier: The calculated damage is corrected by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "fireDamageCutRate",
            "Absorption %: Fire",
            True,
            float,
            'Flame damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "thunderDamageCutRate",
            "Absorption %: Lightning",
            True,
            float,
            'Electric shock damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "physicsAttackRate",
            "Attack %: Physical",
            True,
            float,
            'Physical damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "magicAttackRate",
            "Attack %: Magic",
            True,
            float,
            'Magic damage multiplier: The calculated damage is corrected by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "fireAttackRate",
            "Attack %: Fire",
            True,
            float,
            'Flame damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "thunderAttackRate",
            "Attack %: Lightning",
            True,
            float,
            'Electric shock damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "physicsAttackPowerRate",
            "Power %: Physical",
            True,
            float,
            'Multiply the physical attack power by the set value',
        ),
        ParamFieldInfo(
            "magicAttackPowerRate",
            "Power %: Magic",
            True,
            float,
            'Multiply the magic attack power by the set value',
        ),
        ParamFieldInfo(
            "fireAttackPowerRate",
            "Power %: Fire",
            True,
            float,
            'Multiply the fire attack power by the set value',
        ),
        ParamFieldInfo(
            "thunderAttackPowerRate",
            "Power %: Lightning",
            True,
            float,
            'Multiply the electric shock attack power by the set value',
        ),
        ParamFieldInfo(
            "physicsAttackPower",
            "Damage +: Physical",
            True,
            int,
            'Add or subtract the value set for physical attack power',
        ),
        ParamFieldInfo(
            "magicAttackPower",
            "Damage +: Magic",
            True,
            int,
            'Add or subtract the value set for the magic attack power',
        ),
        ParamFieldInfo(
            "fireAttackPower",
            "Damage +: Fire",
            True,
            int,
            'Add or subtract the value set for the flame attack power',
        ),
        ParamFieldInfo(
            "thunderAttackPower",
            "Damage +: Lighting",
            True,
            int,
            'Add or subtract the value set for the electric shock attack power',
        ),
        ParamFieldInfo(
            "physicsDiffenceRate",
            "Defence %: Physical",
            True,
            float,
            'Multiply the set value for physical defense',
        ),
        ParamFieldInfo(
            "magicDiffenceRate",
            "Defence %: Magic",
            True,
            float,
            'Multiply the value set for magic defense',
        ),
        ParamFieldInfo(
            "fireDiffenceRate",
            "Defence %: Fire",
            True,
            float,
            'Multiply the fire defense by the set value',
        ),
        ParamFieldInfo(
            "thunderDiffenceRate",
            "Defence %: Lightning",
            True,
            float,
            'Multiply the value set for the electric shock defense',
        ),
        ParamFieldInfo(
            "physicsDiffence",
            "Defence +: Physical",
            True,
            int,
            'Add or subtract the value set for physical defense',
        ),
        ParamFieldInfo(
            "magicDiffence",
            "Defence +: Magic",
            True,
            int,
            'Add or subtract the value set for magic defense',
        ),
        ParamFieldInfo(
            "fireDiffence",
            "Defence +: Fire",
            True,
            int,
            'Add or subtract the value set for the fire defense',
        ),
        ParamFieldInfo(
            "thunderDiffence",
            "Defence +: Lightning",
            True,
            int,
            'Add or subtract the value set for the electric shock defense',
        ),
        ParamFieldInfo(
            "NoGuardDamageRate",
            "No Guard Damage %",
            True,
            float,
            'Replace the damage ratio at the time of the gap with the set value (set on the damage side)',
        ),
        ParamFieldInfo(
            "vitalSpotChangeRate",
            "Vital Spot Change %",
            True,
            float,
            'Replaces the damage calculation of the sweet spot with the specified value (key point damage correction) -Invalid at 1.0',
        ),
        ParamFieldInfo(
            "normalSpotChangeRate",
            "Normal Hit Change %",
            True,
            float,
            'Replaces normal hit damage calculation with the specified number -Invalid at 1.0',
        ),
        ParamFieldInfo(
            "lookAtTargetPosOffset",
            "Look-At Target Position Offset",
            True,
            float,
            'Offset the target position when the enemy looks at. Set to crouch or mount on the side to be seen',
        ),
        ParamFieldInfo(
            "behaviorId",
            "Behavior ID",
            True,
            int,
            'Specified -1 when dealing damage using action ID from special effects\nNPC Behavior - Requires State Info 142\nPlayer Behavior - Requires State Info 275\nBullet Behavior - Requires State Info 33',
        ),
        ParamFieldInfo(
            "changeHpRate",
            "Current HP %",
            True,
            float,
            'Set what percentage of the maximum HP to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "changeHpPoint",
            "Current HP +",
            True,
            int,
            'Set how many points to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "changeMpRate",
            "Current FP %",
            True,
            float,
            'Set what percentage of the maximum MP to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "changeMpPoint",
            "Current FP +",
            True,
            int,
            'Set how many points to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "mpRecoverChangeSpeed",
            "FP Recovery Speed",
            True,
            int,
            'Change the recovery speed. Add or subtract to the standard recovery speed and initial recovery speed of the recovery formula.',
        ),
        ParamFieldInfo(
            "changeStaminaRate",
            "Current Stamina %",
            True,
            float,
            'Set what percentage of the maximum stamina to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "changeStaminaPoint",
            "Current Stamina +",
            True,
            int,
            'Set how many points to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "staminaRecoverChangeSpeed",
            "Stamina Recovery Speed",
            True,
            int,
            'Change the recovery speed. Add or subtract to the standard recovery speed and initial recovery speed of the recovery formula.',
        ),
        ParamFieldInfo(
            "magicEffectTimeChange",
            "Magic Effect Time Change",
            True,
            float,
            'Add / subtract the time set for the effect duration only for magic that has the effect duration set to 0.1 seconds or more.',
        ),
        ParamFieldInfo(
            "insideDurability",
            "Current Durability +",
            True,
            int,
            'Add or subtract the numerical value to the internal wear degree',
        ),
        ParamFieldInfo(
            "maxDurability",
            "Max Durability",
            True,
            int,
            'Add the set value to the maximum value of the internal wear degree of durability.',
        ),
        ParamFieldInfo(
            "staminaAttackRate",
            "Attack %: Stamina",
            True,
            float,
            'Multiply the stamina attack power by a factor (1.0 1 times 0.5 half)',
        ),
        ParamFieldInfo(
            "poizonAttackPower",
            "Aux Inflict +: Poison",
            True,
            int,
            "A value to be added to the target's [poison resistance value] when it hits\nRequires State Info 2",
        ),
        ParamFieldInfo(
            "diseaseAttackPower",
            "Aux Inflict +: Scarlet Rot",
            True,
            int,
            'Numerical value to be added to the target [Plague resistance value] when hit\nRequires State Info 5',
        ),
        ParamFieldInfo(
            "bloodAttackPower",
            "Aux Inflict +: Hemorrhage",
            True,
            int,
            "A value to be added to the target's [bleeding resistance value] when it hits\nRequires State Info 6",
        ),
        ParamFieldInfo(
            "curseAttackPower",
            "Aux Inflict +: Blight",
            True,
            int,
            'A number to be added to the target [curse resistance value] when hit\nRequires State Info 116',
        ),
        ParamFieldInfo(
            "fallDamageRate",
            "Fall Damage %",
            True,
            float,
            'Multiply the damage calculation when falling',
        ),
        ParamFieldInfo(
            "soulRate",
            "Rune Gain %",
            True,
            float,
            'The amount of soul acquired when defeating an enemy is added by the specified multiple.\nRequires State Info 76',
        ),
        ParamFieldInfo(
            "equipWeightChangeRate",
            "Max Equip Load %",
            True,
            float,
            'Multiply the maximum equipment weight by the set magnification',
        ),
        ParamFieldInfo(
            "allItemWeightChangeRate",
            "Item Weight %",
            True,
            float,
            'Multiply the maximum weight you have by the set magnification',
        ),
        ParamFieldInfo(
            "soul",
            "Rune Gain +",
            True,
            int,
            'Add the set value to the possessed soul',
        ),
        ParamFieldInfo(
            "animIdOffset",
            "Anim ID Offset",
            True,
            int,
            'Anime ID offset (invalid-1)',
        ),
        ParamFieldInfo(
            "haveSoulRate",
            "Rune Possession Amount %",
            True,
            float,
            'For enemy lap effect. It is applied when the soul goes out from the set character.',
        ),
        ParamFieldInfo(
            "targetPriority",
            "Target Priority",
            True,
            float,
            'During multiplayer, the enemy will give priority to being targeted as a target. Addition of priority. 0 is the default. It will be often targeted with a positive value. Minus is up to -1.',
        ),
        ParamFieldInfo(
            "sightSearchEnemyRate",
            "Enemy Vision Adjustment",
            True,
            float,
            'Correct the ease of finding by a magnification',
        ),
        ParamFieldInfo(
            "hearingSearchEnemyRate",
            "Enemy Listen Adjustment",
            True,
            float,
            'Correct the loudness of the AI sound emitted by the magnification',
        ),
        ParamFieldInfo(
            "grabityRate",
            "Gravity %",
            True,
            float,
            'Gravity rate',
        ),
        ParamFieldInfo(
            "registPoizonChangeRate",
            "Aux Resist %: Poison",
            True,
            float,
            'Multiply the poison resistance value by the set multiplier',
        ),
        ParamFieldInfo(
            "registDiseaseChangeRate",
            "Aux Resist %: Scarlet Rot",
            True,
            float,
            'Multiply the plague resistance value by the set magnification',
        ),
        ParamFieldInfo(
            "registBloodChangeRate",
            "Aux Resist %: Hemorrhage",
            True,
            float,
            'Multiply the bleeding resistance value by the set magnification',
        ),
        ParamFieldInfo(
            "registCurseChangeRate",
            "Aux Resist %: Blight",
            True,
            float,
            'Multiply the spell resistance value by the set multiplier',
        ),
        ParamFieldInfo(
            "soulStealRate",
            "Soul Steal %",
            True,
            float,
            'Defense against HP robbed by NPCs in Soul Steel',
        ),
        ParamFieldInfo(
            "lifeReductionRate",
            "Effect Duration %",
            True,
            float,
            '',
        ),
        ParamFieldInfo(
            "hpRecoverRate",
            "HP Recovery Effectiveness %",
            True,
            float,
            "It doesn't work when HP decreases.",
        ),
        ParamFieldInfo(
            "replaceSpEffectId",
            "Chain SpEffect ID",
            True,
            int,
            'Special effect ID added at the end of life (-1 is ignored)',
        ),
        ParamFieldInfo(
            "cycleOccurrenceSpEffectId",
            "Cycle SpEffect ID",
            True,
            int,
            'Special effect ID that occurs in each activation cycle (-1 is ignored)',
        ),
        ParamFieldInfo(
            "atkOccurrenceSpEffectId",
            "Attack SpEffect ID",
            True,
            int,
            'Special effect ID that occurs when hitting an attack (-1 is ignored)',
        ),
        ParamFieldInfo(
            "guardDefFlickPowerRate",
            "Guard Defense - Weapon Repel Power %",
            True,
            float,
            'Repellent defense correction value when guarding',
        ),
        ParamFieldInfo(
            "guardStaminaCutRate",
            "Guard Stability %",
            True,
            float,
            'Stamina cut rate correction value when guarding',
        ),
        ParamFieldInfo(
            "rayCastPassedTime",
            "Raycast Passed Time",
            True,
            int,
            'Passing the line of sight: Activation time [ms] (for evil eye)',
        ),
        ParamFieldInfo(
            "magicSubCategoryChange1",
            "Conditional Category [1]",
            True,
            int,
            'Vs to subcategory parameter change 1',
        ),
        ParamFieldInfo(
            "magicSubCategoryChange2",
            "Conditional Category [2]",
            True,
            int,
            'Vs to subcategory parameter change 2',
        ),
        ParamFieldInfo(
            "bowDistRate",
            "Bow Distance %",
            True,
            int,
            'Correction value added to the flight distance correction of the weapon',
        ),
        ParamFieldInfo(
            "spCategory",
            "Effect Category",
            True,
            int,
            'Categories that determine behavior such as overwriting special effects',
        ),
        ParamFieldInfo(
            "categoryPriority",
            "Category Priority",
            True,
            int,
            'Priority within the same category (lower one has priority)',
        ),
        ParamFieldInfo(
            "saveCategory",
            "Save Category",
            True,
            int,
            'Category to save special effects',
        ),
        ParamFieldInfo(
            "changeMagicSlot",
            "Magic Attunement Slot",
            True,
            int,
            'You can increase the specified number of magic registration slots',
        ),
        ParamFieldInfo(
            "changeMiracleSlot",
            "Miracle Attunement Slot",
            True,
            int,
            'You can increase the specified number of trajectory registration frames.',
        ),
        ParamFieldInfo(
            "heroPointDamage",
            "Humanity Damage",
            True,
            int,
            'Damage value given to human nature value',
        ),
        ParamFieldInfo(
            "defFlickPower",
            "Weapon Repel Defence +",
            True,
            int,
            'Set a value that overwrites the repelling defense',
        ),
        ParamFieldInfo(
            "flickDamageCutRate",
            "Weapon Repel Absorption %",
            True,
            int,
            'Set a value that overwrites the damage attenuation rate at the time of repelling',
        ),
        ParamFieldInfo(
            "bloodDamageRate",
            "Damage Correction %: Hemorrhage",
            True,
            int,
            'Point damage of state change type [bleeding], correction value used only when% damage',
        ),
        ParamFieldInfo(
            "dmgLv_None",
            "Damage Level: No Impact",
            True,
            int,
            'Specify the type to replace the damage Lv0',
        ),
        ParamFieldInfo(
            "dmgLv_S",
            "Damage Level: Small Impact",
            True,
            int,
            'Specify the type to replace the damage Lv1',
        ),
        ParamFieldInfo(
            "dmgLv_M",
            "Damage Level: Medium Impact",
            True,
            int,
            'Specify the type to replace the damage Lv2',
        ),
        ParamFieldInfo(
            "dmgLv_L",
            "Damage Level: Large Impact",
            True,
            int,
            'Specify the type to replace the damage Lv3',
        ),
        ParamFieldInfo(
            "dmgLv_BlowM",
            "Damage Level: Medium Blow",
            True,
            int,
            'Specify the type to replace the damage Lv4',
        ),
        ParamFieldInfo(
            "dmgLv_Push",
            "Damage Level: Push",
            True,
            int,
            'Specify the type to replace the damage Lv5',
        ),
        ParamFieldInfo(
            "dmgLv_Strike",
            "Damage Level: Strike",
            True,
            int,
            'Specify the type to replace the damage Lv6',
        ),
        ParamFieldInfo(
            "dmgLv_BlowS",
            "Damage Level: Small Blow",
            True,
            int,
            'Specify the type to replace the damage Lv7',
        ),
        ParamFieldInfo(
            "dmgLv_Min",
            "Damage Level: Minimal",
            True,
            int,
            'Specify the type to replace the damage Lv8',
        ),
        ParamFieldInfo(
            "dmgLv_Uppercut",
            "Damage Level: Uppercut",
            True,
            int,
            'Specify the type to replace the damage Lv9',
        ),
        ParamFieldInfo(
            "dmgLv_BlowLL",
            "Damage Level: Blow Backward",
            True,
            int,
            'Specify the type to replace the damage Lv10',
        ),
        ParamFieldInfo(
            "dmgLv_Breath",
            "Damage Level: Breath",
            True,
            int,
            'Specify the type to replace the damage Lv11',
        ),
        ParamFieldInfo(
            "atkAttribute",
            "Attack Attribute",
            True,
            int,
            'Physical attributes to set for special effects',
        ),
        ParamFieldInfo(
            "spAttribute",
            "SpEffect Attribute",
            True,
            int,
            'Special attributes to set for special effects',
        ),
        ParamFieldInfo(
            "stateInfo",
            "State Info",
            True,
            int,
            'State change judgment flag',
        ),
        ParamFieldInfo(
            "wepParamChange",
            "Weapon Parameter Change",
            True,
            int,
            'Specify which weapon is effective. If there is no limit, all attacks and defenses including enemies are targeted',
        ),
        ParamFieldInfo(
            "moveType",
            "Move Type",
            True,
            int,
            'Movement type. Change the movement speed.',
        ),
        ParamFieldInfo(
            "lifeReductionType",
            "Effect Duration Multiplier - State Info",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "throwCondition",
            "Throw Trigger",
            True,
            int,
            'Throwing conditions. Affects the throwing mask.',
        ),
        ParamFieldInfo(
            "addBehaviorJudgeId_condition",
            "Add Behavior Judge ID - Trigger",
            True,
            int,
            'Condition value to add a value to the action judgment ID (Def: -1)',
        ),
        ParamFieldInfo(
            "freezeDamageRate",
            "Damage Correction %: Frostbite",
            True,
            int,
            'Correction value used only for point damage and% damage of state change type [cold air]',
        ),
        ParamFieldInfo(
            "effectTargetSelf:1",
            "Target Self",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetFriend:1",
            "Target Friend",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetEnemy:1",
            "Target Enemy",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetPlayer:1",
            "Target Player",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetAI:1",
            "Target AI",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetLive:1",
            "Target Live",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetGhost:1",
            "Target Ghost",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "disableSleep:1",
            "Disable Sleep",
            True,
            int,
            'If this effect is applied, you will not sleep',
        ),
        ParamFieldInfo(
            "disableMadness:1",
            "Disable Madness",
            True,
            int,
            "With this effect, you won't go mad",
        ),
        ParamFieldInfo(
            "effectTargetAttacker:1",
            "Target Attacker",
            True,
            int,
            'Apply special effects to attackers after damage (cannot enter defenders)',
        ),
        ParamFieldInfo(
            "dispIconNonactive:1",
            "Display Icon when Inactive",
            True,
            int,
            'The icon is displayed even in the state of waiting for activation.',
        ),
        ParamFieldInfo(
            "regainGaugeDamage:1",
            "Generate Regain Gauge",
            True,
            int,
            'Whether to generate a regain gauge',
        ),
        ParamFieldInfo(
            "bAdjustMagicAblity:1",
            "Use Intelligence Correction",
            True,
            int,
            'Do you want to correct the magic power?',
        ),
        ParamFieldInfo(
            "bAdjustFaithAblity:1",
            "Use Faith Correction",
            True,
            int,
            'Do you correct your faith?',
        ),
        ParamFieldInfo(
            "bGameClearBonus:1",
            "Enable for Game Clear",
            True,
            int,
            'Whether it is for the game clear lap bonus.',
        ),
        ParamFieldInfo(
            "magParamChange:1",
            "Affects Sorcery",
            True,
            int,
            'Set whether or not it is effective against magic',
        ),
        ParamFieldInfo(
            "miracleParamChange:1",
            "Affects Incantation",
            True,
            int,
            'Set whether or not it is effective against miracles',
        ),
        ParamFieldInfo(
            "clearSoul:1",
            "Clear Held Runes",
            True,
            int,
            'Possession soul becomes 0.',
        ),
        ParamFieldInfo(
            "requestSOS:1",
            "Request: Friendly Phantom Summon",
            True,
            int,
            'If checked, issue an SOS sign request when activated',
        ),
        ParamFieldInfo(
            "requestBlackSOS:1",
            "Request: Hostile Phantom Summon",
            True,
            int,
            'If checked, issue a black SOS sign request when activated',
        ),
        ParamFieldInfo(
            "requestForceJoinBlackSOS:1",
            "Request: Invasion",
            True,
            int,
            'If checked, issue an intrusion_A request when activated',
        ),
        ParamFieldInfo(
            "requestKickSession:1",
            "Request: Kick",
            True,
            int,
            'If checked, a kick request will be issued at the time of activation.',
        ),
        ParamFieldInfo(
            "requestLeaveSession:1",
            "Request: Return to Own World",
            True,
            int,
            'If checked, an exit request will be issued at the time of activation.',
        ),
        ParamFieldInfo(
            "requestNpcInveda:1",
            "Request: NPC Invasion",
            True,
            int,
            'If checked, an intrusion request to the NPC will be issued at the time of activation.',
        ),
        ParamFieldInfo(
            "noDead:1",
            "Is No Dead",
            True,
            int,
            'Whether you can be corpse. With this check, you will not be dead',
        ),
        ParamFieldInfo(
            "bCurrHPIndependeMaxHP:1",
            "Current HP independent Max HP",
            True,
            int,
            'Does HP now affect even if the maximum HP increases or decreases?',
        ),
        ParamFieldInfo(
            "corrosionIgnore:1",
            "Ignore Durability Loss",
            True,
            int,
            '[State change type] ignores [Durability] decrease due to [Corrosion]',
        ),
        ParamFieldInfo(
            "sightSearchCutIgnore:1",
            "Ignore Vision Reductions",
            True,
            int,
            'Ignore visual search invalidity',
        ),
        ParamFieldInfo(
            "hearingSearchCutIgnore:1",
            "Ignore Listen Reductions",
            True,
            int,
            'Ignore auditory search invalidity',
        ),
        ParamFieldInfo(
            "antiMagicIgnore:1",
            "Ignore Anti-Magic Effect",
            True,
            int,
            'You can use magic even in the anti-magic range',
        ),
        ParamFieldInfo(
            "fakeTargetIgnore:1",
            "Ignore Fake Targets",
            True,
            int,
            "Don't get caught in the fake target that occurred",
        ),
        ParamFieldInfo(
            "fakeTargetIgnoreUndead:1",
            "Ignore Fake Human Targets",
            True,
            int,
            'You will not be caught by the fake target of the human system that occurred',
        ),
        ParamFieldInfo(
            "fakeTargetIgnoreAnimal:1",
            "Ignore Fake Animal Targets",
            True,
            int,
            'You will not be caught by the fake target of the beast system that occurred',
        ),
        ParamFieldInfo(
            "grabityIgnore:1",
            "Ignore Gravity Change",
            True,
            int,
            'Gravity effect disabled',
        ),
        ParamFieldInfo(
            "disablePoison:1",
            "Disable Poison",
            True,
            int,
            'If this effect is applied, it will not be poisoned.',
        ),
        ParamFieldInfo(
            "disableDisease:1",
            "Disable Scarlet Rot",
            True,
            int,
            'If this effect is applied, you will not get plague',
        ),
        ParamFieldInfo(
            "disableBlood:1",
            "Disable Hemorrhage",
            True,
            int,
            "With this effect, you won't get bleeding",
        ),
        ParamFieldInfo(
            "disableCurse:1",
            "Disable Blight",
            True,
            int,
            "With this effect, you won't be cursed",
        ),
        ParamFieldInfo(
            "enableCharm:1",
            "Enable Charm",
            True,
            int,
            'If this effect is applied, you will be fascinated.',
        ),
        ParamFieldInfo(
            "enableLifeTime:1",
            "Enable Lifetime",
            True,
            int,
            'Will the life be extended when the flag is set by TAE?',
        ),
        ParamFieldInfo(
            "bAdjustStrengthAblity:1",
            "Use Strength Correction",
            True,
            int,
            'Do you want to correct your strength?',
        ),
        ParamFieldInfo(
            "bAdjustAgilityAblity:1",
            "Use Dexterity Correction",
            True,
            int,
            'Do you want to correct your workmanship?',
        ),
        ParamFieldInfo(
            "eraseOnBonfireRecover:1",
            "Erase on Bonfire Rest",
            True,
            int,
            'Will it be extinguished by bonfire recovery?',
        ),
        ParamFieldInfo(
            "throwAttackParamChange:1",
            "Throw Attack Param Change",
            True,
            int,
            'Set whether or not it is effective against throwing attacks',
        ),
        ParamFieldInfo(
            "requestLeaveColiseumSession:1",
            "Request: Leave Arena",
            True,
            int,
            'If checked, a request to leave the arena will be issued at the time of activation.',
        ),
        ParamFieldInfo(
            "isExtendSpEffectLife:1",
            "Has Effect Duration Adjustment Applied",
            True,
            int,
            'Whether to be eligible for extension when the life extension effect is applied',
        ),
        ParamFieldInfo(
            "hasTarget:1",
            "Has Target",
            True,
            int,
            'Do you know the enemy? : [Activation condition] (for evil eye users)',
        ),
        ParamFieldInfo(
            "replanningOnFire:1",
            "Cancel on Fire Damage",
            True,
            int,
            'Whether to replan at the time of activation',
        ),
        ParamFieldInfo(
            "vowType0:1",
            "Trigger for Vow Type [0]",
            True,
            int,
            'Pledge 0',
        ),
        ParamFieldInfo(
            "vowType1:1",
            "Trigger for Vow Type [1]",
            True,
            int,
            'Pledge 1',
        ),
        ParamFieldInfo(
            "vowType2:1",
            "Trigger for Vow Type [2]",
            True,
            int,
            'Pledge 2',
        ),
        ParamFieldInfo(
            "vowType3:1",
            "Trigger for Vow Type [3]",
            True,
            int,
            'Pledge 3',
        ),
        ParamFieldInfo(
            "vowType4:1",
            "Trigger for Vow Type [4]",
            True,
            int,
            'Pledge 4',
        ),
        ParamFieldInfo(
            "vowType5:1",
            "Trigger for Vow Type [5]",
            True,
            int,
            'Pledge 5',
        ),
        ParamFieldInfo(
            "vowType6:1",
            "Trigger for Vow Type [6]",
            True,
            int,
            'Pledge 6',
        ),
        ParamFieldInfo(
            "vowType7:1",
            "Trigger for Vow Type [7]",
            True,
            int,
            'Pledge 7',
        ),
        ParamFieldInfo(
            "vowType8:1",
            "Trigger for Vow Type [8]",
            True,
            int,
            'Pledge 8',
        ),
        ParamFieldInfo(
            "vowType9:1",
            "Trigger for Vow Type [9]",
            True,
            int,
            'Pledge 9',
        ),
        ParamFieldInfo(
            "vowType10:1",
            "Trigger for Vow Type [10]",
            True,
            int,
            'Pledge 10',
        ),
        ParamFieldInfo(
            "vowType11:1",
            "Trigger for Vow Type [11]",
            True,
            int,
            'Pledge 11',
        ),
        ParamFieldInfo(
            "vowType12:1",
            "Trigger for Vow Type [12]",
            True,
            int,
            'Pledge 12',
        ),
        ParamFieldInfo(
            "vowType13:1",
            "Trigger for Vow Type [13]",
            True,
            int,
            'Pledge 13',
        ),
        ParamFieldInfo(
            "vowType14:1",
            "Trigger for Vow Type [14]",
            True,
            int,
            'Pledge 14',
        ),
        ParamFieldInfo(
            "vowType15:1",
            "Trigger for Vow Type [15]",
            True,
            int,
            'Pledge 15',
        ),
        ParamFieldInfo(
            "repAtkDmgLv",
            "Change Attacker Damage Level",
            True,
            int,
            'The damage level of the attacking side changes to this value',
        ),
        ParamFieldInfo(
            "sightSearchRate",
            "AI Vision Correction",
            True,
            float,
            'Correct the ease of finding with a magnification\nRequires State Info 267',
        ),
        ParamFieldInfo(
            "effectTargetOpposeTarget:1",
            "Trigger for Opponent",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetFriendlyTarget:1",
            "Trigger for Friendly",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetSelfTarget:1",
            "Trigger for Self",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetPcHorse:1",
            "Trigger for Horse",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "effectTargetPcDeceased:1",
            "Trigger for Dead Player",
            True,
            int,
            'Only the target for which this judgment is checked is effective, the default is �~',
        ),
        ParamFieldInfo(
            "isContractSpEffectLife:1",
            "Can Duration be Reduced",
            True,
            int,
            'Whether it will be shortened when the life shortening effect is applied',
        ),
        ParamFieldInfo(
            "isWaitModeDelete:1",
            "Delete in Wait Mode",
            True,
            int,
            'Do you want to delete it the moment you are in a waiting state?',
        ),
        ParamFieldInfo(
            "isIgnoreNoDamage:1",
            "Apply through No Damage",
            True,
            int,
            'Whether to apply the damage from this special effect even in the invincible state only when the state change type "Apply the activation function even when invincible" is applied.',
        ),
        ParamFieldInfo(
            "changeTeamType",
            "Team Type",
            True,
            int,
            'Overwrites the specified team type\nRequires State Info 132',
        ),
        ParamFieldInfo(
            "dmypolyId",
            "Bullet Behavior ID - DmyPoly ID",
            True,
            int,
            'Damipoli ID. Damipoli ID range is 0 to 999.1000, 10000 is the category number.',
        ),
        ParamFieldInfo(
            "vfxId",
            "Effect VFX [0]",
            True,
            int,
            'Special effect VfxId (-1 disabled)',
        ),
        ParamFieldInfo(
            "accumuOverFireId",
            "Accumulator - Over Value - SpEffect ID",
            True,
            int,
            'Special effect Id activated at the upper limit of the spirit ball',
        ),
        ParamFieldInfo(
            "accumuOverVal",
            "Accumulator - Over Value",
            True,
            int,
            'Genkitama upper limit',
        ),
        ParamFieldInfo(
            "accumuUnderFireId",
            "Accumulator - Under Value - SpEffect ID",
            True,
            int,
            'Special effect Id activated at the lower limit of the spirit ball',
        ),
        ParamFieldInfo(
            "accumuUnderVal",
            "Accumulator - Under Value",
            True,
            int,
            'Genkitama lower limit',
        ),
        ParamFieldInfo(
            "accumuVal",
            "Accumulator - Increment Value",
            True,
            int,
            'Genkitama accumulation value',
        ),
        ParamFieldInfo(
            "eye_angX",
            "Vision - Overwrite Height Angle",
            True,
            int,
            'Override the findability angle x',
        ),
        ParamFieldInfo(
            "eye_angY",
            "Vision - Overwrite Width Angle",
            True,
            int,
            'Override the findability angle y',
        ),
        ParamFieldInfo(
            "addDeceasedLv",
            "Add Deceased Level",
            True,
            int,
            'Add this value to the degree of death',
        ),
        ParamFieldInfo(
            "vfxId1",
            "Effect VFX [1]",
            True,
            int,
            'Special effect VfxId1 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId2",
            "Effect VFX [2]",
            True,
            int,
            'Special effect VfxId2 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId3",
            "Effect VFX [3]",
            True,
            int,
            'Special effect VfxId3 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId4",
            "Effect VFX [4]",
            True,
            int,
            'Special effect VfxId4 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId5",
            "Effect VFX [5]",
            True,
            int,
            'Special effect VfxId5 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId6",
            "Effect VFX [6]",
            True,
            int,
            'Special effect VfxId6 (-1 invalid)',
        ),
        ParamFieldInfo(
            "vfxId7",
            "Effect VFX [7]",
            True,
            int,
            'Special effect VfxId7 (-1 invalid)',
        ),
        ParamFieldInfo(
            "freezeAttackPower",
            "Aux Inflict +: Frostbite",
            True,
            int,
            'Numerical value to be added to the target [Cold air resistance value] when hit\nRequires State Info 260',
        ),
        ParamFieldInfo(
            "AppearAiSoundId",
            "Generated AI Sound ID",
            True,
            int,
            'Generates AI sound parameters with set values',
        ),
        ParamFieldInfo(
            "addFootEffectSfxId",
            "Automatic Foot Effect - SFX ID Offset",
            True,
            int,
            'The identifier of the foot effect that is additionally generated during special effects. XYYZZZ ZZZ',
        ),
        ParamFieldInfo(
            "dexterityCancelSystemOnlyAddDexterity",
            "Cast Speed +",
            True,
            int,
            'Add this value when calculating the end timing of the TAE flag of "Skill Cancel".',
        ),
        ParamFieldInfo(
            "teamOffenseEffectivity",
            "Team Attack Effectivity",
            True,
            int,
            'Overwrite and change the target [Team Attack Influence] value. Do not change the default value (-1).',
        ),
        ParamFieldInfo(
            "toughnessDamageCutRate",
            "Toughness Absorption %",
            True,
            float,
            'Toughness version cut rate',
        ),
        ParamFieldInfo(
            "weakDmgRateA",
            "Damage Multiplier %: Type A",
            True,
            float,
            'Special Attack A Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "weakDmgRateB",
            "Damage Multiplier %: Type B",
            True,
            float,
            'Special attack B Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "weakDmgRateC",
            "Damage Multiplier %: Type C",
            True,
            float,
            'Special attack C Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "weakDmgRateD",
            "Damage Multiplier %: Type D",
            True,
            float,
            'Special attack D Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "weakDmgRateE",
            "Damage Multiplier %: Type E",
            True,
            float,
            'Special attack E Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "weakDmgRateF",
            "Damage Multiplier %: Type F",
            True,
            float,
            'Special attack F Damage multiplier is corrected. 1 is normal.',
        ),
        ParamFieldInfo(
            "darkDamageCutRate",
            "Absorption %: Holy",
            True,
            float,
            'Dark damage multiplier: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "darkDiffenceRate",
            "Defence %: Holy",
            True,
            float,
            'Multiply the darkness defense by the set value',
        ),
        ParamFieldInfo(
            "darkDiffence",
            "Defence +: Holy",
            True,
            int,
            'Add or subtract the value set for darkness defense',
        ),
        ParamFieldInfo(
            "darkAttackRate",
            "Attack %: Holy",
            True,
            float,
            'Dark damage multiplier: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "darkAttackPowerRate",
            "Power %: Holy",
            True,
            float,
            'Multiply the dark attack power by the set value',
        ),
        ParamFieldInfo(
            "darkAttackPower",
            "Damage +: Holy",
            True,
            int,
            'Add or subtract the value set for the dark attack power',
        ),
        ParamFieldInfo(
            "antiDarkSightRadius",
            "Full View in Darkness - Radius",
            True,
            float,
            'Radius of full view of darkness [m]. If you are within this distance, you will be able to see at normal distance even in the dark.',
        ),
        ParamFieldInfo(
            "antiDarkSightDmypolyId",
            "Full View in Darkness - Dummy Poly ID",
            True,
            int,
            'Damipoli ID (-1: Master) with full view of darkness. Create a full view area around this Damipoli',
        ),
        ParamFieldInfo(
            "conditionHpRate",
            "Trigger on HP Above %",
            True,
            float,
            'Activates only when you have HP above the specified value',
        ),
        ParamFieldInfo(
            "consumeStaminaRate",
            "Weapon Stamina Consumption %",
            True,
            float,
            'Multiply by multiplying the consumption stamina value of the behavior parameter',
        ),
        ParamFieldInfo(
            "itemDropRate",
            "Item Discovery %",
            True,
            float,
            'The set value is added to [Item Drop Correction]\nRequires State Info 66',
        ),
        ParamFieldInfo(
            "changePoisonResistPoint",
            "Aux Resist +: Poison",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "changeDiseaseResistPoint",
            "Aux Resist +: Scarlet Rot",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "changeBloodResistPoint",
            "Aux Resist +: Hemorrhage",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "changeCurseResistPoint",
            "Aux Resist +: Blight",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "changeFreezeResistPoint",
            "Aux Resist +: Frostbite",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "slashAttackRate",
            "Attack %: Slash",
            True,
            float,
            'Slash damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "blowAttackRate",
            "Attack %: Strike",
            True,
            float,
            'Batter damage ratio: The calculated damage is corrected by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "thrustAttackRate",
            "Attack %: Thrust",
            True,
            float,
            'Puncture damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "neutralAttackRate",
            "Attack %: Standard",
            True,
            float,
            'Non-attribute damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "slashAttackPowerRate",
            "Power %: Slash",
            True,
            float,
            'Multiply the slashing attack power by the set value',
        ),
        ParamFieldInfo(
            "blowAttackPowerRate",
            "Power %: Strike",
            True,
            float,
            'Multiply the hit attack power by the set value',
        ),
        ParamFieldInfo(
            "thrustAttackPowerRate",
            "Power %: Thrust",
            True,
            float,
            'Multiply the piercing attack power by the set value',
        ),
        ParamFieldInfo(
            "neutralAttackPowerRate",
            "Power %: Standard",
            True,
            float,
            'Multiply the non-attribute attack power by the set value',
        ),
        ParamFieldInfo(
            "slashAttackPower",
            "Damage +: Slash",
            True,
            int,
            'Add or subtract the value set for the slashing attack power',
        ),
        ParamFieldInfo(
            "blowAttackPower",
            "Damage +: Strike",
            True,
            int,
            'Add or subtract the value set for the batter attack power',
        ),
        ParamFieldInfo(
            "thrustAttackPower",
            "Damage +: Thrust",
            True,
            int,
            'Add or subtract the value set for the piercing attack power',
        ),
        ParamFieldInfo(
            "neutralAttackPower",
            "Damage +: Standard",
            True,
            int,
            'Add or subtract the value set for non-attribute attack power',
        ),
        ParamFieldInfo(
            "changeStrengthPoint",
            "Correction +: STR",
            True,
            int,
            'Add or subtract the correction value of the weapon',
        ),
        ParamFieldInfo(
            "changeAgilityPoint",
            "Correction +: DEX",
            True,
            int,
            'Add or subtract the correction value of the weapon',
        ),
        ParamFieldInfo(
            "changeMagicPoint",
            "Correction +: INT",
            True,
            int,
            'Add or subtract the correction value of the weapon',
        ),
        ParamFieldInfo(
            "changeFaithPoint",
            "Correction +: FTH",
            True,
            int,
            'Add or subtract the correction value of the weapon',
        ),
        ParamFieldInfo(
            "changeLuckPoint",
            "Correction +: ARC",
            True,
            int,
            'Add or subtract the correction value of the weapon',
        ),
        ParamFieldInfo(
            "recoverArtsPoint_Str",
            "Weapon Art Restore: STR",
            True,
            int,
            'Arts Point Restores strength',
        ),
        ParamFieldInfo(
            "recoverArtsPoint_Dex",
            "Weapon Art Restore: DEX",
            True,
            int,
            'Restores arts point workmanship',
        ),
        ParamFieldInfo(
            "recoverArtsPoint_Magic",
            "Weapon Art Restore: INT",
            True,
            int,
            'Restores arts point magic',
        ),
        ParamFieldInfo(
            "recoverArtsPoint_Miracle",
            "Weapon Art Restore: FTH",
            True,
            int,
            'Recover arts point miracles',
        ),
        ParamFieldInfo(
            "madnessDamageRate",
            "Damage Correction %: Madness",
            True,
            int,
            'Correction value used only for point damage and% damage of state change type [madness]',
        ),
        ParamFieldInfo(
            "isUseStatusAilmentAtkPowerCorrect:1",
            "Use Status Ailment Attack Power Correction",
            True,
            int,
            'If ��, the abnormal state attack power multiplier correction of the attack para is applied.',
        ),
        ParamFieldInfo(
            "isUseAtkParamAtkPowerCorrect:1",
            "Use AtkParam Attack Power Correction",
            True,
            int,
            'If ��, the attack power multiplier correction of the attack para is applied.',
        ),
        ParamFieldInfo(
            "dontDeleteOnDead:1",
            "Don't Delete on Dead",
            True,
            int,
            'If it is ��, it will not be deleted even if the character dies. Mainly used for death effects.',
        ),
        ParamFieldInfo(
            "disableFreeze:1",
            "Disable Frostbite",
            True,
            int,
            'When this effect is applied, it will not be cold',
        ),
        ParamFieldInfo(
            "isDisableNetSync:1",
            "Do not Sync in Multiplayer",
            True,
            int,
            'Do not synchronize with the net. It does not mean that you will be able to call it locally, but simply do not send it online. For example, a remote character does not activate locally, so nothing happens in that case.',
        ),
        ParamFieldInfo(
            "shamanParamChange:1",
            "Affects Pyromancy",
            True,
            int,
            'Set whether or not it is effective against spells',
        ),
        ParamFieldInfo(
            "isStopSearchedNotify:1",
            "Stop Platoon Notifications",
            True,
            int,
            'Whether to stop notifications targeting your army (used by EventMaker decisions and buddy platoons)',
        ),
        ParamFieldInfo(
            "isCheckAboveShadowTest:1",
            "Apply outside of Rain Shield",
            True,
            int,
            'If it is ��, it will not be applied when it is judged to be shielded (�~ is always applied)',
        ),
        ParamFieldInfo(
            "addBehaviorJudgeId_add",
            "Add Behavior Judgment ID - Addition Value",
            True,
            int,
            'If the addition value of the action judgment ID is 0, the action is not switched and the action is stopped.',
        ),
        ParamFieldInfo(
            "saReceiveDamageRate",
            "Absorption %: Poise Damage",
            True,
            float,
            'Multiplier for SA damage',
        ),
        ParamFieldInfo(
            "defPlayerDmgCorrectRate_Physics",
            "PVP Absorption %: Physical",
            True,
            float,
            'Damage correction for the damage value received from the player.',
        ),
        ParamFieldInfo(
            "defPlayerDmgCorrectRate_Magic",
            "PVP Absorption %: Magic",
            True,
            float,
            'Damage correction for the damage value received from the player.',
        ),
        ParamFieldInfo(
            "defPlayerDmgCorrectRate_Fire",
            "PVP Absorption %: Fire",
            True,
            float,
            'Damage correction for the damage value received from the player.',
        ),
        ParamFieldInfo(
            "defPlayerDmgCorrectRate_Thunder",
            "PVP Absorption %: Lightning",
            True,
            float,
            'Damage correction for the damage value received from the player.',
        ),
        ParamFieldInfo(
            "defPlayerDmgCorrectRate_Dark",
            "PVP Absorption %: Holy",
            True,
            float,
            'Damage correction for the damage value received from the player.',
        ),
        ParamFieldInfo(
            "defEnemyDmgCorrectRate_Physics",
            "Absorption %: Physical",
            True,
            float,
            'Damage correction for the damage value received from the enemy.',
        ),
        ParamFieldInfo(
            "defEnemyDmgCorrectRate_Magic",
            "Absorption %: Magic",
            True,
            float,
            'Damage correction for the damage value received from the enemy.',
        ),
        ParamFieldInfo(
            "defEnemyDmgCorrectRate_Fire",
            "Absorption %: Fire",
            True,
            float,
            'Damage correction for the damage value received from the enemy.',
        ),
        ParamFieldInfo(
            "defEnemyDmgCorrectRate_Thunder",
            "Absorption %: Lightning",
            True,
            float,
            'Damage correction for the damage value received from the enemy.',
        ),
        ParamFieldInfo(
            "defEnemyDmgCorrectRate_Dark",
            "Absorption %: Holy",
            True,
            float,
            'Damage correction for the damage value received from the enemy.',
        ),
        ParamFieldInfo(
            "defObjDmgCorrectRate",
            "Absorption %: Object",
            True,
            float,
            'Damage correction for the damage value received from OBJ.',
        ),
        ParamFieldInfo(
            "atkPlayerDmgCorrectRate_Physics",
            "PVP Damage %: Physical",
            True,
            float,
            'Damage correction for the damage value given to the player.',
        ),
        ParamFieldInfo(
            "atkPlayerDmgCorrectRate_Magic",
            "PVP Damage %: Magic",
            True,
            float,
            'Damage correction for the damage value given to the player.',
        ),
        ParamFieldInfo(
            "atkPlayerDmgCorrectRate_Fire",
            "PVP Damage %: Fire",
            True,
            float,
            'Damage correction for the damage value given to the player.',
        ),
        ParamFieldInfo(
            "atkPlayerDmgCorrectRate_Thunder",
            "PVP Damage %: Lightning",
            True,
            float,
            'Damage correction for the damage value given to the player.',
        ),
        ParamFieldInfo(
            "atkPlayerDmgCorrectRate_Dark",
            "PVP Damage %: Holy",
            True,
            float,
            'Damage correction for the damage value given to the player.',
        ),
        ParamFieldInfo(
            "atkEnemyDmgCorrectRate_Physics",
            "Damage %: Physical",
            True,
            float,
            'Damage correction for the damage value given to the enemy.',
        ),
        ParamFieldInfo(
            "atkEnemyDmgCorrectRate_Magic",
            "Damage %: Magic",
            True,
            float,
            'Damage correction for the damage value given to the enemy.',
        ),
        ParamFieldInfo(
            "atkEnemyDmgCorrectRate_Fire",
            "Damage %: Fire",
            True,
            float,
            'Damage correction for the damage value given to the enemy.',
        ),
        ParamFieldInfo(
            "atkEnemyDmgCorrectRate_Thunder",
            "Damage %: Lightning",
            True,
            float,
            'Damage correction for the damage value given to the enemy.',
        ),
        ParamFieldInfo(
            "atkEnemyDmgCorrectRate_Dark",
            "Damage %: Holy",
            True,
            float,
            'Damage correction for the damage value given to the enemy.',
        ),
        ParamFieldInfo(
            "registFreezeChangeRate",
            "Aux Resist %: Frostbite",
            True,
            float,
            'Multiply the cold resistance value by the set magnification',
        ),
        ParamFieldInfo(
            "invocationConditionsStateChange1",
            "Trigger on State Info [1]",
            True,
            int,
            'Trigger condition state change type 1',
        ),
        ParamFieldInfo(
            "invocationConditionsStateChange2",
            "Trigger on State Info [2]",
            True,
            int,
            'Trigger condition state change type 2',
        ),
        ParamFieldInfo(
            "invocationConditionsStateChange3",
            "Trigger on State Info [3]",
            True,
            int,
            'Trigger condition state change type 3',
        ),
        ParamFieldInfo(
            "hearingAiSoundLevel",
            "Listen - AI Sound Level",
            True,
            int,
            'Overwrite how good your ears are',
        ),
        ParamFieldInfo(
            "chrProxyHeightRate",
            "Proxy Height Capsule %",
            True,
            float,
            'Magnification over the height of the character capsule',
        ),
        ParamFieldInfo(
            "addAwarePointCorrectValue_forMe",
            "Search Awareness - Addition Correction - Self",
            True,
            float,
            'Search side addition correction_viewer',
        ),
        ParamFieldInfo(
            "addAwarePointCorrectValue_forTarget",
            "Search Awareness - Addition Correction - Target",
            True,
            float,
            'Searching degree addition correction _ side to be seen',
        ),
        ParamFieldInfo(
            "sightSearchEnemyAdd",
            "Vision Search - Enemy Addition",
            True,
            float,
            'Correct the ease of finding with a real number',
        ),
        ParamFieldInfo(
            "sightSearchAdd",
            "Vision Search Addition",
            True,
            float,
            'Correct the ease of finding with a real number',
        ),
        ParamFieldInfo(
            "hearingSearchAdd",
            "Listen Search Addition",
            True,
            float,
            'Correct the hearing of AI sounds with real numbers',
        ),
        ParamFieldInfo(
            "hearingSearchRate",
            "Listen Search Correction",
            True,
            float,
            'Correct the audibility of AI sound by magnification',
        ),
        ParamFieldInfo(
            "hearingSearchEnemyAdd",
            "Listen Search - Enemy Addition",
            True,
            float,
            'Correct the loudness of the emitted AI sound with a real number',
        ),
        ParamFieldInfo(
            "value_Magnification",
            "Sale Price Correction %",
            True,
            float,
            'Sales price correction: Magnification',
        ),
        ParamFieldInfo(
            "artsConsumptionRate",
            "Skill FP Consumption %",
            True,
            float,
            'Arts MP consumption multiplier [%]',
        ),
        ParamFieldInfo(
            "magicConsumptionRate",
            "Sorcery FP Consumption %",
            True,
            float,
            'Magic consumption MP multiplier [%]',
        ),
        ParamFieldInfo(
            "shamanConsumptionRate",
            "Pyromancy FP Consumption %",
            True,
            float,
            'Magic consumption MP multiplier [%]',
        ),
        ParamFieldInfo(
            "miracleConsumptionRate",
            "Incantation FP Consumption %",
            True,
            float,
            'Miracle consumption MP magnification [%]',
        ),
        ParamFieldInfo(
            "changeHpEstusFlaskRate",
            "HP Flask - HP Restore %",
            True,
            int,
            'Set what percentage of the maximum HP to add (or subtract) with one activation',
        ),
        ParamFieldInfo(
            "changeHpEstusFlaskPoint",
            "HP Flask - HP Restore +",
            True,
            int,
            'Set how many points to add (or subtract) with one activation',
        ),
        ParamFieldInfo(
            "changeMpEstusFlaskRate",
            "FP Flask - FP Restore %",
            True,
            int,
            'Set what percentage of the maximum MP to add (or subtract) with one activation',
        ),
        ParamFieldInfo(
            "changeMpEstusFlaskPoint",
            "FP Flask - FP Restore +",
            True,
            int,
            'Set how many points to add (or subtract) with one activation',
        ),
        ParamFieldInfo(
            "changeHpEstusFlaskCorrectRate",
            "HP Flask - HP Restore Correction",
            True,
            float,
            'Correct the damage amount of the HP Est bottle',
        ),
        ParamFieldInfo(
            "changeMpEstusFlaskCorrectRate",
            "FP Flask - HP Restore Correction",
            True,
            float,
            'Correct the damage amount of MP Est Bottle',
        ),
        ParamFieldInfo(
            "applyIdOnGetSoul",
            "Kill SpEffect ID",
            True,
            int,
            'When the special effect of the state change type "HP drain" is enabled, when the enemy is defeated, the special effect ID set in the "HP drain activation special effect" of the same special effect is called (0: ignore).',
        ),
        ParamFieldInfo(
            "extendLifeRate",
            "Extend SpEffect Duration %",
            True,
            float,
            'Extension coefficient of state change type "life extension"',
        ),
        ParamFieldInfo(
            "contractLifeRate",
            "Contract SpEffect Duration %",
            True,
            float,
            'Shortening coefficient of state change type "life shortening"',
        ),
        ParamFieldInfo(
            "defObjectAttackPowerRate",
            "Object Damage %",
            True,
            float,
            'Corrects the attack power against the damage received from OBJ. (Not damage compensation)',
        ),
        ParamFieldInfo(
            "effectEndDeleteDecalGroupId",
            "Decal Deletion Group ID",
            True,
            int,
            'When the special effect disappears (lifetime / overwritten / erased ... etc.), the paint decal is deleted if the special effect of the same group ID is not applied.',
        ),
        ParamFieldInfo(
            "addLifeForceStatus",
            "Vigor",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addWillpowerStatus",
            "Mind",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addEndureStatus",
            "Endurance",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addVitalityStatus",
            "Vitality",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addStrengthStatus",
            "Strength",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addDexterityStatus",
            "Dexterity",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addMagicStatus",
            "Intelligence",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addFaithStatus",
            "Faith",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "addLuckStatus",
            "Arcane",
            True,
            int,
            'Add value to growth status',
        ),
        ParamFieldInfo(
            "deleteCriteriaDamage",
            "Delete Criteria Damage",
            True,
            int,
            'Reason for damage under the condition to remove special effects',
        ),
        ParamFieldInfo(
            "magicSubCategoryChange3",
            "Conditional Category [3]",
            True,
            int,
            'Vs to subcategory parameter change 3',
        ),
        ParamFieldInfo(
            "spAttributeVariationValue",
            "SpEffect Attribute Variation Value",
            True,
            int,
            'This value is used to give variation to abnormal state SFX, SE, etc. in combination with the special attribute set for the special effect. SEQ16473',
        ),
        ParamFieldInfo(
            "atkFlickPower",
            "Weapon Repel Power +",
            True,
            int,
            'Set a value that overwrites the repelling attack power',
        ),
        ParamFieldInfo(
            "wetConditionDepth",
            "Wet Condition Depth",
            True,
            int,
            'TimeAct Determines whether special effects are applied in combination with "at what water level you get wet"',
        ),
        ParamFieldInfo(
            "changeSaRecoveryVelocity",
            "Poise Recovery Time %",
            True,
            float,
            'Change the recovery speed of SA durability',
        ),
        ParamFieldInfo(
            "regainRate",
            "Regain Correction %",
            True,
            float,
            'Regain magnification',
        ),
        ParamFieldInfo(
            "saAttackPowerRate",
            "Poise Damage %",
            True,
            float,
            'SA attack power multiplier',
        ),
        ParamFieldInfo(
            "sleepAttackPower",
            "Aux Inflict +: Sleep",
            True,
            int,
            "Numerical value to be added to the target's [Sleep tolerance] when hit",
        ),
        ParamFieldInfo(
            "madnessAttackPower",
            "Aux Inflict +: Madness",
            True,
            int,
            "A number to be added to the target's [madness resistance value] when it hits",
        ),
        ParamFieldInfo(
            "registSleepChangeRate",
            "Aux Resist %: Sleep",
            True,
            float,
            'Multiply the sleep tolerance value by the set magnification',
        ),
        ParamFieldInfo(
            "registMadnessChangeRate",
            "Aux Resist %: Madness",
            True,
            float,
            'Multiply the madness resistance value by the set multiplier',
        ),
        ParamFieldInfo(
            "changeSleepResistPoint",
            "Aux Resist +: Sleep",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "changeMadnessResistPoint",
            "Aux Resist +: Madness",
            True,
            int,
            'Increase or decrease the state resistance value',
        ),
        ParamFieldInfo(
            "sleepDamageRate",
            "Damage Correction %: Sleep",
            True,
            int,
            'Point damage of state change type [Sleep], correction value used only when% damage',
        ),
        ParamFieldInfo(
            "applyPartsGroup",
            "Apply Parts Group",
            True,
            int,
            'The effect is limited by the part where the attack hits. Only defensive items in damage calculation are subject to restriction',
        ),
        ParamFieldInfo(
            "clearTarget:1",
            "Clear Target",
            True,
            int,
            'Does not recognize the target while the special effect is applied (excluding the riding target)',
        ),
        ParamFieldInfo(
            "fakeTargetIgnoreAjin:1",
            "Ignore Fake Target - Human",
            True,
            int,
            'You will not be caught by the fake target of the subhuman system that occurred',
        ),
        ParamFieldInfo(
            "fakeTargetIgnoreMirageArts:1",
            "Ignore Fake Target - Phantom",
            True,
            int,
            'You will not be caught by the fake target of the phantom arts system that occurred',
        ),
        ParamFieldInfo(
            "requestForceJoinBlackSOS_B:1",
            "Force Invasion",
            True,
            int,
            'If checked, issue an intrusion_B request when activated',
        ),
        ParamFieldInfo(
            "unk353_4:1",
            "Blank",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "pad2[1]",
            "pad",
            False,
            pad_field(1),
            '',
        ),
        ParamFieldInfo(
            "changeSuperArmorPoint",
            "Poise +",
            True,
            float,
            'Value to add to the super armor value',
        ),
        ParamFieldInfo(
            "changeSaPoint",
            "Apply Poise Damage +",
            True,
            float,
            'Set how many points to subtract (or add) with one activation',
        ),
        ParamFieldInfo(
            "hugeEnemyPickupHeightOverwrite",
            "Giant Enemy Height Overwrite",
            True,
            float,
            'Giant enemy lift height overwrite [m]',
        ),
        ParamFieldInfo(
            "poisonDefDamageRate",
            "Aux Damage Correction %: Poison",
            True,
            float,
            'Poison resistance damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "diseaseDefDamageRate",
            "Aux Damage Correction %: Scarlet Rot",
            True,
            float,
            'Epidemic resistance damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "bloodDefDamageRate",
            "Aux Damage Correction %: Hemorrhage",
            True,
            float,
            'Bleeding resistance damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "curseDefDamageRate",
            "Aux Damage Correction %: Blight",
            True,
            float,
            'Curse resistance damage multiplier: Corrects the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "freezeDefDamageRate",
            "Aux Damage Correction %: Frostbite",
            True,
            float,
            'Cold resistance damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "sleepDefDamageRate",
            "Aux Damage Correction %: Sleep",
            True,
            float,
            'Sleep resistance damage ratio: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "madnessDefDamageRate",
            "Aux Damage Correction %: Madness",
            True,
            float,
            'Madness resistance damage multiplier: Correct the calculated damage by XX times. 1 is normal.',
        ),
        ParamFieldInfo(
            "overwrite_maxBackhomeDist",
            "Override - Max Back Home Distance",
            True,
            int,
            'Distance to go home no matter what [m] _ overwrite',
        ),
        ParamFieldInfo(
            "overwrite_backhomeDist",
            "Override - Back Home Distance",
            True,
            int,
            'Distance to return home while fighting [m] _ Overwrite',
        ),
        ParamFieldInfo(
            "overwrite_backhomeBattleDist",
            "Override - Back Home Battle Distance",
            True,
            int,
            'Distance to give up and fight to return to the nest [m] _ overwrite',
        ),
        ParamFieldInfo(
            "overwrite_BackHome_LookTargetDist",
            "Override - Look Target Distance",
            True,
            int,
            'When returning home: Distance to see the target [m] _ Overwrite',
        ),
        ParamFieldInfo(
            "goodsConsumptionRate",
            "Item FP Consumption %",
            True,
            float,
            'Item consumption MP multiplier',
        ),
        ParamFieldInfo(
            "pad3[8]",
            "pad",
            False,
            pad_field(8),
            '',
        ),
    ],
}
