from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


THROW_DIRECTION_SFX_PARAM_ST = {
    "param_type": "THROW_DIRECTION_SFX_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "sfxId_00",
            "SFX ID [0]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_01",
            "SFX ID [1]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_02",
            "SFX ID [2]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_03",
            "SFX ID [3]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_04",
            "SFX ID [4]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_05",
            "SFX ID [5]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_06",
            "SFX ID [6]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_07",
            "SFX ID [7]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_08",
            "SFX ID [8]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_09",
            "SFX ID [9]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_10",
            "SFX ID [10]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_11",
            "SFX ID [11]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_12",
            "SFX ID [12]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_13",
            "SFX ID [13]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_14",
            "SFX ID [14]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_15",
            "SFX ID [15]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_16",
            "SFX ID [16]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_17",
            "SFX ID [17]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_18",
            "SFX ID [18]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_19",
            "SFX ID [19]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_20",
            "SFX ID [20]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_21",
            "SFX ID [21]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_22",
            "SFX ID [22]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_23",
            "SFX ID [23]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_24",
            "SFX ID [24]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_25",
            "SFX ID [25]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_26",
            "SFX ID [26]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_27",
            "SFX ID [27]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_28",
            "SFX ID [28]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_29",
            "SFX ID [29]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "sfxId_30",
            "SFX ID [30]",
            True,
            int,
            'ID of SFX to use',
        ),
        ParamFieldInfo(
            "pad1[20]",
            "SFX ID [pad]",
            False,
            pad_field(20),
            'pad',
        ),
    ],
}
