from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


WEATHER_ASSET_REPLACE_PARAM_ST = {
    "param_type": "WEATHER_ASSET_REPLACE_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "mapId",
            "Map ID",
            True,
            int,
            'Specify the map number in 8 digits. Only open and legacy celestial sphere placement maps can be specified',
        ),
        ParamFieldInfo(
            "TransitionSrcWeather",
            "Transition Source Weather",
            True,
            int,
            'Specifies the assets that will be valid in this weather.',
        ),
        ParamFieldInfo(
            "padding0[2]",
            "reserved0",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "isFireAsh",
            "Is Burning Ash",
            True,
            int,
            'Specifies whether or not to adapt to the "fire ash" state of the map.',
        ),
        ParamFieldInfo(
            "padding1[3]",
            "padding0",
            False,
            pad_field(3),
            '',
        ),
        ParamFieldInfo(
            "reserved2",
            "reserved2",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "AssetId0",
            "Asset ID [0]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId1",
            "Asset ID [1]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId2",
            "Asset ID [2]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId3",
            "Asset ID [3]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId4",
            "Asset ID [4]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId5",
            "Asset ID [5]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId6",
            "Asset ID [6]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "AssetId7",
            "Asset ID [7]",
            True,
            int,
            '-1: Invalid Specify the asset ID to generate. AEG999_999-> 999999',
        ),
        ParamFieldInfo(
            "reserved0[8]",
            "reserved0",
            False,
            pad_field(8),
            '',
        ),
        ParamFieldInfo(
            "CreateAssetLimitId0",
            "Create Asset Limit ID [0]",
            True,
            int,
            'ID for production restriction. -1: Unlimited. Generation is allowed only if it matches the generation limit ID in "Map default parameter .xlsm" (SEQ08921).',
        ),
        ParamFieldInfo(
            "CreateAssetLimitId1",
            "Create Asset Limit ID [1]",
            True,
            int,
            'ID for production restriction. -1: Unlimited. Generation is allowed only if it matches the generation limit ID in "Map default parameter .xlsm" (SEQ08921).',
        ),
        ParamFieldInfo(
            "CreateAssetLimitId2",
            "Create Asset Limit ID [2]",
            True,
            int,
            'ID for production restriction. -1: Unlimited. Generation is allowed only if it matches the generation limit ID in "Map default parameter .xlsm" (SEQ08921).',
        ),
        ParamFieldInfo(
            "CreateAssetLimitId3",
            "Create Asset Limit ID [3]",
            True,
            int,
            'ID for production restriction. -1: Unlimited. Generation is allowed only if it matches the generation limit ID in "Map default parameter .xlsm" (SEQ08921).',
        ),
        ParamFieldInfo(
            "reserved1[4]",
            "reserved1",
            False,
            pad_field(4),
            '',
        ),
    ],
}
