from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


WEP_ABSORP_POS_PARAM_ST = {
    "param_type": "WEP_ABSORP_POS_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "hangPosType",
            "Sheath Position Type",
            True,
            int,
            'The animation at the time of sword delivery changes depending on this value',
        ),
        ParamFieldInfo(
            "isSkeletonBind",
            "Is Skeleton Bind",
            True,
            int,
            'Do you want to combine skeletons?',
        ),
        ParamFieldInfo(
            "pad0[2]",
            "Padding",
            False,
            pad_field(2),
            '',
        ),
        ParamFieldInfo(
            "right_0",
            "Right Hand - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "left_0",
            "Left Hand - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "both_0",
            "Both Hand - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding a right-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftHang_0",
            "Left Sheath - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding a weapon in the left hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "rightHang_0",
            "Right Sheath - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding a weapon in the right hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "right_1",
            "Right Hand - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "left_1",
            "Left Hand - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "both_1",
            "Both Hand - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding a right-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftHang_1",
            "Left Sheath - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding a weapon in the left hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "rightHang_1",
            "Right Sheath - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding a weapon in the right hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "right_2",
            "Right Hand - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "left_2",
            "Left Hand - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "both_2",
            "Both Hand - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding a right-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftHang_2",
            "Left Sheath - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding a weapon in the left hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "rightHang_2",
            "Right Sheath - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding a weapon in the right hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "right_3",
            "Right Hand - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "left_3",
            "Left Hand - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 adsorption Damipoli when holding the weapon in one hand.',
        ),
        ParamFieldInfo(
            "both_3",
            "Both Hand - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 adsorption Damipoli when holding a right-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftHang_3",
            "Left Sheath - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 Adsorption Damipoli when holding a weapon in the left hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "rightHang_3",
            "Right Sheath - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 Adsorption Damipoli when holding a weapon in his right hand and delivering the weapon.',
        ),
        ParamFieldInfo(
            "wepInvisibleType_0",
            "Hidden Type - Model [0]",
            True,
            int,
            'Hidden type of model 0. When hiding a weapon with TAE, erase the one that matches this',
        ),
        ParamFieldInfo(
            "wepInvisibleType_1",
            "Hidden Type - Model [1]",
            True,
            int,
            'Hidden type of model 1. When hiding a weapon with TAE, erase the one that matches this',
        ),
        ParamFieldInfo(
            "wepInvisibleType_2",
            "Hidden Type - Model [2]",
            True,
            int,
            'Hidden type of model 2. When hiding a weapon with TAE, erase the one that matches this',
        ),
        ParamFieldInfo(
            "wepInvisibleType_3",
            "Hidden Type - Model [3]",
            True,
            int,
            'Model 3 hidden type. When hiding a weapon with TAE, erase the one that matches this',
        ),
        ParamFieldInfo(
            "leftBoth_0",
            "Left Both-Hand - Dummy Poly - Model [0]",
            True,
            int,
            'Model 0 adsorption Damipoli when holding a left-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftBoth_1",
            "Left Both-Hand - Dummy Poly - Model [1]",
            True,
            int,
            'Model 1 adsorption Damipoli when holding a left-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftBoth_2",
            "Left Both-Hand - Dummy Poly - Model [2]",
            True,
            int,
            'Model 2 adsorption Damipoli when holding a left-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "leftBoth_3",
            "Left Both-Hand - Dummy Poly - Model [3]",
            True,
            int,
            'Model 3 adsorption Damipoli when holding a left-handed weapon with both hands.',
        ),
        ParamFieldInfo(
            "dispPosType_right_0",
            "Display Position - Right Hand - Model [0]",
            True,
            int,
            'Model 0_ Right-hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_left_0",
            "Display Position - Left Hand - Model [0]",
            True,
            int,
            'Model 0_Left hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightBoth_0",
            "Display Position - Right Both-hand - Model [0]",
            True,
            int,
            'Model 0_Right-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftBoth_0",
            "Display Position - Left Both-Hand - Model [0]",
            True,
            int,
            'Model 0_ Left-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightHang_0",
            "Display Position - Right Sheath - Model [0]",
            True,
            int,
            'Model 0_ Right-handed sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftHang_0",
            "Display Position - Left Sheath - Model [0]",
            True,
            int,
            'Model 0_ Left hand sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_right_1",
            "Display Position - Right Hand - Model [1]",
            True,
            int,
            'Model 1_ Right-hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_left_1",
            "Display Position - Left Hand - Model [1]",
            True,
            int,
            'Model 1_Left hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightBoth_1",
            "Display Position - Right Both-hand - Model [1]",
            True,
            int,
            'Model 1_Right-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftBoth_1",
            "Display Position - Left Both-Hand - Model [1]",
            True,
            int,
            'Model 1_ Left-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightHang_1",
            "Display Position - Right Sheath - Model [1]",
            True,
            int,
            'Model 1_ Right-handed sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftHang_1",
            "Display Position - Left Sheath - Model [1]",
            True,
            int,
            'Model 1_ Left hand sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_right_2",
            "Display Position - Right Hand - Model [2]",
            True,
            int,
            'Model 2_ Right-hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_left_2",
            "Display Position - Left Hand - Model [2]",
            True,
            int,
            'Model 2_Left hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightBoth_2",
            "Display Position - Right Both-hand - Model [2]",
            True,
            int,
            'Model 2_Right-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftBoth_2",
            "Display Position - Left Both-Hand - Model [2]",
            True,
            int,
            'Model 2_ Left-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightHang_2",
            "Display Position - Right Sheath - Model [2]",
            True,
            int,
            'Model 2_Right-handed sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftHang_2",
            "Display Position - Left Sheath - Model [2]",
            True,
            int,
            'Model 2_ Left hand sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_right_3",
            "Display Position - Right Hand - Model [3]",
            True,
            int,
            'Model 3_ Right-hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_left_3",
            "Display Position - Left Hand - Model [3]",
            True,
            int,
            'Model 3_Left hand display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightBoth_3",
            "Display Position - Right Both-hand - Model [3]",
            True,
            int,
            'Model 3_Right-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftBoth_3",
            "Display Position - Left Both-Hand - Model [3]",
            True,
            int,
            'Model 3_ Left-handed two-handed display position (used to specify hidden position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_rightHang_3",
            "Display Position - Right Sheath - Model [3]",
            True,
            int,
            'Model 3_Right-handed sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "dispPosType_leftHang_3",
            "Display Position - Left Sheath - Model [3]",
            True,
            int,
            'Model 3_ Left hand sword display position (used to specify the non-display position from TAE)',
        ),
        ParamFieldInfo(
            "reserve[12]",
            "Reserved area",
            False,
            pad_field(12),
            '',
        ),
    ],
}
