from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


WORLD_MAP_POINT_PARAM_ST = {
    "param_type": "WORLD_MAP_POINT_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "eventFlagId",
            "Open - Event Flag ID",
            True,
            int,
            'Event flag ID of open condition',
        ),
        ParamFieldInfo(
            "distViewEventFlagId",
            "Distant View - Event Flag ID",
            True,
            int,
            'Event flag ID to be set when found on the distant view',
        ),
        ParamFieldInfo(
            "iconId",
            "Icon ID",
            True,
            int,
            'Icon ID',
        ),
        ParamFieldInfo(
            "bgmPlaceType",
            "BGM Location Type",
            True,
            int,
            'Bgm location type',
        ),
        ParamFieldInfo(
            "isAreaIcon:1",
            "Is Area Icon",
            True,
            int,
            'Is it an icon that represents a range? Same size as the map',
        ),
        ParamFieldInfo(
            "isOverrideDistViewMarkPos:1",
            "Overwrite Coordinates when Distant View Marker",
            True,
            int,
            'Whether to overwrite the coordinates when using it as a distant view marker',
        ),
        ParamFieldInfo(
            "isEnableNoText:1",
            "Enable with No Text",
            True,
            int,
            'Do you want to display it even when there is no text? Basically, points are not displayed without text. Display without text when this flag is enabled',
        ),
        ParamFieldInfo(
            "pad3:5",
            "Pad 3",
            False,
            bit_pad_field(5),
            '',
        ),
        ParamFieldInfo(
            "areaNo_forDistViewMark",
            "Distant View Marker - Map Area",
            True,
            int,
            'AA part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "gridXNo_forDistViewMark",
            "Distant View Marker - Map Block",
            True,
            int,
            'BB part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "gridZNo_forDistViewMark",
            "Distant View Marker - Map Region",
            True,
            int,
            'CC part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "clearedEventFlagId",
            "Cleared - Event Flag ID",
            True,
            int,
            'Cleared event flag ID (0: always treated as cleared)',
        ),
        ParamFieldInfo(
            "dispMask00:1",
            "Display Mask M00",
            True,
            int,
            'Whether to display with M00',
        ),
        ParamFieldInfo(
            "dispMask01:1",
            "Display Mask M01",
            True,
            int,
            'Whether to display with M01',
        ),
        ParamFieldInfo(
            "pad2_0:6",
            "pad",
            False,
            bit_pad_field(6),
            'pad2_0',
        ),
        ParamFieldInfo(
            "pad2[1]",
            "pad",
            False,
            pad_field(1),
            'pad2',
        ),
        ParamFieldInfo(
            "distViewIconId",
            "Distant View - Icon ID",
            True,
            int,
            'Icon ID when distant view is found',
        ),
        ParamFieldInfo(
            "angle",
            "Display Icon Angle",
            True,
            float,
            'Display icon rotation angle [deg]',
        ),
        ParamFieldInfo(
            "areaNo",
            "Map Area",
            True,
            int,
            'AA part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "gridXNo",
            "Map Block",
            True,
            int,
            'BB part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "gridZNo",
            "Map Region",
            True,
            int,
            'CC part of mAA_BB_CC_DD',
        ),
        ParamFieldInfo(
            "pad[1]",
            "Padding",
            False,
            pad_field(1),
            'Padding',
        ),
        ParamFieldInfo(
            "posX",
            "Map Coordinate: X",
            True,
            float,
            'X coordinate',
        ),
        ParamFieldInfo(
            "posY",
            "Map Coordinate: Y",
            True,
            float,
            'Y coordinate (not used)',
        ),
        ParamFieldInfo(
            "posZ",
            "Map Coordinate: Z",
            True,
            float,
            'Z coordinate',
        ),
        ParamFieldInfo(
            "textId1",
            "Text ID [1]",
            True,
            int,
            'The text ID to display. If the value is invalid (-1), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId1",
            "Text Enable Flag [1]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (0) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId1",
            "Text Disable Flag [1]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (0) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId2",
            "Text ID [2]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-2), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId2",
            "Text Enable Flag [2]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (1) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId2",
            "Text Disable Flag [2]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (1) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId3",
            "Text ID [3]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-3), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId3",
            "Text Enable Flag [3]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (2) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId3",
            "Text Disable Flag [3]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (2) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId4",
            "Text ID [4]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-4), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId4",
            "Text Enable Flag [4]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (3) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId4",
            "Text Disable Flag [4]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (3) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId5",
            "Text ID [5]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-5), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId5",
            "Text Enable Flag [5]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (4) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId5",
            "Text Disable Flag [5]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (4) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId6",
            "Text ID [6]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-6), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId6",
            "Text Enable Flag [6]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (5) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId6",
            "Text Disable Flag [6]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (5) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId7",
            "Text ID [7]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-7), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId7",
            "Text Enable Flag [7]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (6) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId7",
            "Text Disable Flag [7]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (6) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textId8",
            "Text ID [8]",
            True,
            int,
            'The text ID to display. If it is an invalid value (-8), nothing is displayed.',
        ),
        ParamFieldInfo(
            "textEnableFlagId8",
            "Text Enable Flag [8]",
            True,
            int,
            'Display text Event flag ID. Display if the event flag is On. If the event flag ID (7) is invalid, it will be treated as On.',
        ),
        ParamFieldInfo(
            "textDisableFlagId8",
            "Text Disable Flag [8]",
            True,
            int,
            'Hidden event flag ID of the text. If the event flag is On, it will not be displayed. It takes precedence over the display event flag ID. If the event flag ID (7) is invalid, it will be treated as Off.',
        ),
        ParamFieldInfo(
            "textType1",
            "Text Type [1]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType2",
            "Text Type [2]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType3",
            "Text Type [3]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType4",
            "Text Type [4]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType5",
            "Text Type [5]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType6",
            "Text Type [6]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType7",
            "Text Type [7]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "textType8",
            "Text Type [8]",
            True,
            int,
            'Text type (place name, NPC name, ...)',
        ),
        ParamFieldInfo(
            "distViewId",
            "Distant View ID [0]",
            True,
            int,
            'Distance stand ID',
        ),
        ParamFieldInfo(
            "posX_forDistViewMark",
            "Distant View Marker - Coordinate: X",
            True,
            float,
            'X coordinate',
        ),
        ParamFieldInfo(
            "posY_forDistViewMark",
            "Distant View Marker - Coordinate: Y",
            True,
            float,
            'Y coordinate',
        ),
        ParamFieldInfo(
            "posZ_forDistViewMark",
            "Distant View Marker - Coordinate: Z",
            True,
            float,
            'Z coordinate',
        ),
        ParamFieldInfo(
            "distViewId1",
            "Distant View ID [1]",
            True,
            int,
            'Distance stand ID',
        ),
        ParamFieldInfo(
            "distViewId2",
            "Distant View ID [2]",
            True,
            int,
            'Distance stand ID',
        ),
        ParamFieldInfo(
            "distViewId3",
            "Distant View ID [3]",
            True,
            int,
            'Distance stand ID',
        ),
        ParamFieldInfo(
            "dispMinZoomStep",
            "Display - Min Zoom Step",
            True,
            int,
            "TODO",
        ),
        ParamFieldInfo(
            "selectMinZoomStep",
            "Selection - Min Zoom Step",
            True,
            int,
            "TODO",
        ),
        ParamFieldInfo(
            "entryFEType",
            "Entry FE Type",
            True,
            int,
            'Admission display format. Map points to be displayed at the time of admission Types of admission FE',
        ),
        ParamFieldInfo(
            "pad4[9]",
            "pad",
            False,
            pad_field(9),
            'pad3',
        ),
        ParamFieldInfo(
            "unkC0",
            "unkC0",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkC4",
            "unkC4",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkC8",
            "unkC8",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkCC",
            "unkCC",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkD0",
            "unkD0",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkD4",
            "unkD4",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkD8",
            "unkD8",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkDC",
            "unkDC",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkE0",
            "unkE0",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkE4",
            "unkE4",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkE8",
            "unkE8",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkEC",
            "unkEC",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkF0",
            "unkF0",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkF4",
            "unkF4",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkF8",
            "unkF8",
            True,
            int,
            '',
        ),
        ParamFieldInfo(
            "unkFC",
            "unkFC",
            True,
            int,
            '',
        ),
    ],
}
