from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field


WORLD_MAP_LEGACY_CONV_PARAM_ST = {
    "param_type": "WORLD_MAP_LEGACY_CONV_PARAM_ST",
    "file_name": "",  # TODO
    "nickname": "",  # TODO
    "fields": [
        ParamFieldInfo(
            "disableParam_NT:1",
            "Disable Param - Network Test",
            True,
            int,
            'Parameters marked with �� are excluded in the NT version package.',
        ),
        ParamFieldInfo(
            "disableParamReserve1:7",
            "Reserve for package output 1",
            False,
            bit_pad_field(7),
            'Reserve for package output 1',
        ),
        ParamFieldInfo(
            "disableParamReserve2[3]",
            "Reserve for package output 2",
            False,
            pad_field(3),
            'Reserve for package output 2',
        ),
        ParamFieldInfo(
            "srcAreaNo",
            "Source Map Area",
            True,
            int,
            'Conversion source map ID: Area number',
        ),
        ParamFieldInfo(
            "srcGridXNo",
            "Source Map Block",
            True,
            int,
            'Source map ID: Grid X',
        ),
        ParamFieldInfo(
            "srcGridZNo",
            "Source Map Region",
            True,
            int,
            'Source map ID: Grid Z',
        ),
        ParamFieldInfo(
            "pad1[1]",
            "Padding 1",
            False,
            pad_field(1),
            'Padding 1',
        ),
        ParamFieldInfo(
            "srcPosX",
            "Source Map Coordinate: X",
            True,
            float,
            'Source map reference coordinates X',
        ),
        ParamFieldInfo(
            "srcPosY",
            "Source Map Coordinate: Y",
            True,
            float,
            'Source map reference coordinates Y',
        ),
        ParamFieldInfo(
            "srcPosZ",
            "Source Map Coordinate: Z",
            True,
            float,
            'Source map reference coordinates Z',
        ),
        ParamFieldInfo(
            "dstAreaNo",
            "Destination Map Area",
            True,
            int,
            'Conversion destination map ID: Area number',
        ),
        ParamFieldInfo(
            "dstGridXNo",
            "Destination Map Block",
            True,
            int,
            'Destination map ID: Grid X',
        ),
        ParamFieldInfo(
            "dstGridZNo",
            "Destination Map Region",
            True,
            int,
            'Destination map ID: Grid Z',
        ),
        ParamFieldInfo(
            "pad2[1]",
            "Padding 2",
            False,
            pad_field(1),
            'Padding 2',
        ),
        ParamFieldInfo(
            "dstPosX",
            "Destination Map Coordinate: X",
            True,
            float,
            'Destination map reference coordinates X',
        ),
        ParamFieldInfo(
            "dstPosY",
            "Destination Map Coordinate: Y",
            True,
            float,
            'Destination map reference coordinates Y',
        ),
        ParamFieldInfo(
            "dstPosZ",
            "Destination Map Coordinate: Z",
            True,
            float,
            'Destination map reference coordinates Z',
        ),
        ParamFieldInfo(
            "isBasePoint:1",
            "Is Reference Connection Point",
            True,
            int,
            'Is it a reference connection point? One reference connection point is always set for one conversion source map ID.',
        ),
        ParamFieldInfo(
            "pad3:7",
            "Padding 3",
            False,
            bit_pad_field(7),
            'Padding 3',
        ),
        ParamFieldInfo(
            "pad4[11]",
            "Padding 4",
            False,
            pad_field(11),
            'Padding 4',
        ),
    ],
}
