__all__ = ["MSGDirectory"]

from soulstruct.text.base.msg_directory import MSGDirectory as _BaseMSGDirectory
from soulstruct.utilities.core import BiDict

from .fmg import FMG


class MSGDirectory(_BaseMSGDirectory):
    FMG_CLASS = FMG

    _MSGBND_INDEX_NAMES = BiDict(
        (1, "Subtitles"),
        (2, "SoapstoneMessages"),
        (3, "OpeningSubtitles"),
        (4, "CausesOfDeath"),
        (10, "GoodNames"),
        (11, "WeaponNames"),
        (12, "ArmorNames"),
        (13, "RingNames"),
        (14, "SpellNames"),
        (18, "NPCNames"),
        (19, "PlaceNames"),
        (20, "GoodSummaries"),
        (21, "WeaponSummaries"),
        (22, "ArmorSummaries"),
        (23, "RingSummaries"),
        (24, "GoodDescriptions"),
        (25, "WeaponDescriptions"),
        (26, "ArmorDescriptions"),
        (27, "RingDescriptions"),
        (28, "SpellSummaries"),
        (29, "SpellDescriptions"),
        (30, "EventText"),
        (31, "BloodGemNames"),
        (32, "BloodGemSummaries"),
        (33, "BloodGemDescriptions"),
        (34, "BloodGemPrefixes"),
        (35, "BloodGemEffects"),
        (70, "IngameMenus"),
        (76, "MenuText_Common"),
        (77, "MenuText_Other"),
        (78, "MenuDialogs"),
        (79, "KeyGuide"),
        (80, "MenuHelpSnippets"),
        (90, "TextTagPlaceholders"),
        (91, "DebugTags_Win64"),
        (92, "SystemMessages_Win64"),
        # Old playtest categories.
        (200, "MenuText_SP"),
        (201, "MenuHelpSnippets_SP"),
        (202, "KeyGuide_SP"),
        (203, "SystemMessages_Win64_SP"),
        (204, "MenuDialogs_SP"),
        # NOTE: No Patch categories.
    )

    MAIN_CATEGORIES = (
        "NPCNames",
        "PlaceNames",
        "EventText",
        "SoapstoneMessages",
        "WeaponNames",
        "WeaponSummaries",
        "WeaponDescriptions",
        "ArmorNames",
        "ArmorSummaries",
        "ArmorDescriptions",
        "RingNames",
        "RingSummaries",
        "RingDescriptions",
        "GoodNames",
        "GoodSummaries",
        "GoodDescriptions",
        "SpellNames",
        "SpellSummaries",
        "SpellDescriptions",
        "BloodGemNames",
        "BloodGemSummaries",
        "BloodGemDescriptions",
        "BloodGemEffects",
        "Subtitles",
    )

    INTERNAL_CATEGORIES = (
        "BloodGemPrefixes",
        "CausesOfDeath",
        "ContextualHelp",
        "DebugTags_Win64",
        "FeatureNames",
        "FeatureSummaries",
        "FeatureDescriptions",
        "IngameMenus",
        "KeyGuide",
        "KeyGuide_SP",
        "MenuDialogs",
        "MenuDialogs_SP",
        "MenuHelpSnippets",
        "MenuHelpSnippets_SP",
        "MenuText_Common",
        "MenuText_Other",
        "MenuText_SP",
        "OpeningSubtitles",
        "SystemMessages_Win64",
        "SystemMessages_Win64_SP",
        "TextTagPlaceholders",
    )


# Unused; using BND index instead.
_DSR_TO_SS = {
    # item.msgbnd
    "Accessory_long_desc_.fmg": "RingDescriptions",
    "Accessory_name_.fmg": "RingNames",
    "Accessory_description_.fmg": "RingSummaries",
    "Armor_long_desc_.fmg": "ArmorDescriptions",
    "Armor_name_.fmg": "ArmorNames",
    "Armor_description_.fmg": "ArmorSummaries",
    "Feature_long_desc_.fmg": "FeatureDescriptions",
    "Feature_name_.fmg": "FeatureNames",
    "Feature_description_.fmg": "FeatureSummaries",
    "Item_long_desc_.fmg": "GoodDescriptions",
    "Item_name_.fmg": "GoodNames",
    "Item_description_.fmg": "GoodSummaries",
    "Magic_long_desc_.fmg": "SpellDescriptions",
    "Magic_name_.fmg": "SpellNames",
    "Magic_description_.fmg": "SpellSummaries",
    "NPC_name_.fmg": "NPCNames",
    "Place_name_.fmg": "PlaceNames",
    "Weapon_long_desc_.fmg": "WeaponDescriptions",
    "Weapon_name_.fmg": "WeaponNames",
    "Weapon_description_.fmg": "WeaponSummaries",
    # menu.msgbnd
    "Blood_writing_.fmg": "SoapstoneMessages",
    "Conversation_.fmg": "Subtitles",
    "Dialogue_.fmg": "MenuDialogs",
    "Event_text_.fmg": "EventText",
    "Ingame_menu.fmg": "IngameMenus",
    "Item_help_.fmg": "ContextualHelp",
    "Key_guide_.fmg": "KeyGuide",
    "Menu_general_text_.fmg": "MenuText_Common",
    "Menu_others_.fmg": "MenuText_Other",
    "Movie_subtitles_.fmg": "OpeningSubtitles",
    "Single_line_help_.fmg": "MenuHelpSnippets",
    "System_message_win32_.fmg": "SystemMessages_Win32",
    "System_specific_tags_win32_.fmg": "DebugTags_Win32",
    "Text_display_tag_list_.fmg": "TextTagPlaceholders",
}

# Unused; using BND index instead.
_PTDE_TO_SS = {
    # item.msgbnd (including patch)
    "防具うんちく.fmg": "ArmorDescriptions",
    "防具うんちくパッチ.fmg": "ArmorDescriptionsPatch",
    "防具名.fmg": "ArmorNames",
    "防具名パッチ.fmg": "ArmorNamesPatch",
    "防具説明.fmg": "ArmorSummaries",
    "防具説明パッチ.fmg": "ArmorSummariesPatch",
    "特徴うんちく.fmg": "FeatureDescriptions",
    "特徴名.fmg": "FeatureNames",
    "特徴説明.fmg": "FeatureSummaries",
    "アイテムうんちく.fmg": "GoodDescriptions",
    "アイテムうんちくパッチ.fmg": "GoodDescriptionsPatch",
    "アイテム名.fmg": "GoodNames",
    "アイテム名パッチ.fmg": "GoodNamesPatch",
    "アイテム説明.fmg": "GoodSummaries",
    "アイテム説明パッチ.fmg": "GoodSummariesPatch",
    "NPC名.fmg": "NPCNames",
    "NPC名パッチ.fmg": "NPCNamesPatch",
    "地名.fmg": "PlaceNames",
    "地名パッチ.fmg": "PlaceNamesPatch",
    "アクセサリうんちく.fmg": "RingDescriptions",
    "アクセサリうんちくパッチ.fmg": "RingDescriptionsPatch",
    "アクセサリ名.fmg": "RingNames",
    "アクセサリ名パッチ.fmg": "RingNamesPatch",
    "アクセサリ説明.fmg": "RingSummaries",
    "アクセサリ説明パッチ.fmg": "RingSummariesPatch",
    "魔法うんちく.fmg": "SpellDescriptions",
    "魔法うんちくパッチ.fmg": "SpellDescriptionsPatch",
    "魔法名.fmg": "SpellNames",
    "魔法名パッチ.fmg": "SpellNamesPatch",
    "魔法説明.fmg": "SpellSummaries",
    "武器うんちく.fmg": "WeaponDescriptions",
    "武器うんちくパッチ.fmg": "WeaponDescriptionsPatch",
    "武器名.fmg": "WeaponNames",
    "武器名パッチ.fmg": "WeaponNamesPatch",
    "武器説明.fmg": "WeaponSummaries",
    "武器説明パッチ.fmg": "WeaponSummariesPatch",
    # menu.msgbnd
    "項目ヘルプ.fmg": "ContextualHelp",
    "会話.fmg": "Subtitles",
    "会話パッチ.fmg": "SubtitlesPatch",
    "機種別タグ_win32.fmg": "DebugTags_Win32",
    "イベントテキスト.fmg": "EventText",
    "イベントテキストパッチ.fmg": "EventTextPatch",
    "インゲームメニュー.fmg": "IngameMenus",
    "キーガイド.fmg": "KeyGuide",
    "キーガイドパッチ.fmg": "KeyGuidePatch",
    "ダイアログ.fmg": "MenuDialogs",
    "ダイアログパッチ.fmg": "MenuDialogsPatch",
    "一行ヘルプ.fmg": "MenuHelpSnippets",
    "一行ヘルプパッチ.fmg": "MenuHelpSnippetsPatch",
    "メニュー共通テキスト.fmg": "MenuText_Common",
    "メニュー共通テキストパッチ.fmg": "MenuText_CommonPatch",
    "メニューその他.fmg": "MenuText_Other",
    "メニューその他パッチ.fmg": "MenuText_OtherPatch",
    "ムービー字幕.fmg": "OpeningSubtitles",
    "血文字.fmg": "SoapstoneMessages",
    "血文字パッチ.fmg": "SoapstoneMessagesPatch",
    "システムメッセージ_win32.fmg": "SystemMessages_Win32",
    "システムメッセージ_win32パッチ.fmg": "SystemMessages_Win32Patch",
    "テキスト表示用タグ一覧.fmg": "TextTagPlaceholders",
}
