__all__ = [
    "DUNGEON_FEATURE_PARAM_ST",
    "DUNGEON_SUB_FEAT_LOT_PARAM",
    "HOLYGRAIL_EX_PARAM_ST",
    "RITUAL_REQUIRED_MAT_PARAM",
]

from soulstruct.base.params.utils import ParamFieldInfo, pad_field
from soulstruct.bloodborne.game_types import *


DUNGEON_FEATURE_PARAM_ST = {
    "param_type": "DUNGEON_FEATURE_PARAM_ST",
    "file_name": "DungeonFeatureParam",
    "nickname": "DungeonFeatures",
    "fields": [
        ParamFieldInfo("featureNameId", "FeatureNameID", True, int, ""),
        ParamFieldInfo("subFeatureGroupId", "SubFeatureGroupID", True, int, ""),
        ParamFieldInfo("eventflagId", "EventFlagID", True, int, ""),
        ParamFieldInfo("dungeonNamePriority", "DungeonNamePriority", True, int, ""),
        ParamFieldInfo("releaseFlagIdOffset", "ReleaseFlagIDOffset", True, int, ""),
        ParamFieldInfo("npcParamIdOffset", "CharacterParamOffset", True, int, ""),
        ParamFieldInfo("itemLotParamIdOffset", "ItemLotParamOffset", True, int, ""),
        ParamFieldInfo("eneSpeffectId", "EnemySpecialEffectID", True, int, ""),
        ParamFieldInfo("gemDropCorrectParamId", "GemDropCorrectionParamID", True, int, ""),
        ParamFieldInfo("gemGenParamIdOffset", "GemGeneratorParamIDOffset", True, int, ""),
        ParamFieldInfo("dungeonNameModifierId", "DungeonNameModifierID", True, int, ""),
        ParamFieldInfo("dungeonShortNameId", "DungeonShortNameID", True, int, ""),
    ],
}


DUNGEON_SUB_FEAT_LOT_PARAM = {
    "param_type": "DUNGEON_SUB_FEAT_LOT_PARAM",
    "file_name": "DungeonSubFeatLotParam",
    "nickname": "DungeonSubFeatureLots",
    "fields": [
        ParamFieldInfo("subFeatureNameId", "SubFeatureNameID", True, int, ""),
        ParamFieldInfo("requiredMaterialId", "RequiredMaterialID", True, int, ""),
        ParamFieldInfo("subFeatureId_1", "SubFeatureID1", True, int, ""),
        ParamFieldInfo("subFeatureId_2", "SubFeatureID2", True, int, ""),
        ParamFieldInfo("subFeatureId_3", "SubFeatureID3", True, int, ""),
        ParamFieldInfo("subFeatureId_4", "SubFeatureID4", True, int, ""),
        ParamFieldInfo("subFeatureId_5", "SubFeatureID5", True, int, ""),
        ParamFieldInfo("subFeatureId_6", "SubFeatureID6", True, int, ""),
        ParamFieldInfo("subFeatureId_7", "SubFeatureID7", True, int, ""),
        ParamFieldInfo("subFeatureId_8", "SubFeatureID8", True, int, ""),
        ParamFieldInfo("subFeatureId_9", "SubFeatureID9", True, int, ""),
        ParamFieldInfo("subFeatureId_10", "SubFeatureID10", True, int, ""),
        ParamFieldInfo("pad_0[2]", "Pad", False, pad_field(2), ""),
        ParamFieldInfo("rate_1", "Rate1", True, float, ""),
        ParamFieldInfo("rate_2", "Rate2", True, float, ""),
        ParamFieldInfo("rate_3", "Rate3", True, float, ""),
        ParamFieldInfo("rate_4", "Rate4", True, float, ""),
        ParamFieldInfo("rate_5", "Rate5", True, float, ""),
        ParamFieldInfo("rate_6", "Rate6", True, float, ""),
        ParamFieldInfo("rate_7", "Rate7", True, float, ""),
        ParamFieldInfo("rate_8", "Rate8", True, float, ""),
        ParamFieldInfo("rate_9", "Rate9", True, float, ""),
        ParamFieldInfo("rate_10", "Rate10", True, float, ""),
    ]
}


HOLYGRAIL_EX_PARAM_ST = {
    "param_type": "HOLYGRAIL_EX_PARAM_ST",
    "file_name": "HolygrailExParam",
    "nickname": "RitualChalices",
    "fields": [
        ParamFieldInfo("ritualLv", "RitualLevel", True, int, ""),
        ParamFieldInfo("attributeId", "AttributeID", True, int, ""),
        ParamFieldInfo("mapBaseId", "MapBaseID", True, int, ""),
        ParamFieldInfo("holygrailTypeId", "ChaliceTypeID", True, int, ""),
        ParamFieldInfo("variationNum", "Variation", True, int, ""),
        ParamFieldInfo("mainFeature_1", "MainFeature1", True, int, ""),
        ParamFieldInfo("pad_0", "Pad", False, pad_field(1), ""),
        ParamFieldInfo("dungeonNameBaseId", "DungeonNameBaseID", True, int, ""),
        ParamFieldInfo("uniqueBaseFlagId", "UniqueBaseFlagID", True, int, ""),
        ParamFieldInfo("uniqueItem00_head", "UniqueItem0Head", True, int, ""),
        ParamFieldInfo("uniqueItem00_tail", "UniqueItem0Tail", True, int, ""),
        ParamFieldInfo("uniqueItem01_head", "UniqueItem1Head", True, int, ""),
        ParamFieldInfo("uniqueItem01_tail", "UniqueItem1Tail", True, int, ""),
        ParamFieldInfo("uniqueItem02_head", "UniqueItem2Head", True, int, ""),
        ParamFieldInfo("uniqueItem02_tail", "UniqueItem2Tail", True, int, ""),
        ParamFieldInfo("uniqueItem03_head", "UniqueItem3Head", True, int, ""),
        ParamFieldInfo("uniqueItem03_tail", "UniqueItem3Tail", True, int, ""),
        ParamFieldInfo("directMapUid", "DirectMapUID", True, int, ""),
        ParamFieldInfo("requiredMaterialId", "RequiredMaterialID", True, int, ""),
        ParamFieldInfo("groupFrameNameId", "GroupFrameNameID", True, int, ""),
        ParamFieldInfo("uniqueItem04_head", "UniqueItem4Head", True, int, ""),
        ParamFieldInfo("uniqueItem04_tail", "UniqueItem4Tail", True, int, ""),
        ParamFieldInfo("uniqueItem05_head", "UniqueItem5Head", True, int, ""),
        ParamFieldInfo("uniqueItem05_tail", "UniqueItem5Tail", True, int, ""),
        ParamFieldInfo("uniqueItem06_head", "UniqueItem6Head", True, int, ""),
        ParamFieldInfo("uniqueItem06_tail", "UniqueItem6Tail", True, int, ""),
        ParamFieldInfo("uniqueItem07_head", "UniqueItem7Head", True, int, ""),
        ParamFieldInfo("uniqueItem07_tail", "UniqueItem7Tail", True, int, ""),
        ParamFieldInfo("uniqueItem08_head", "UniqueItem8Head", True, int, ""),
        ParamFieldInfo("uniqueItem08_tail", "UniqueItem8Tail", True, int, ""),
        ParamFieldInfo("uniqueItem09_head", "UniqueItem9Head", True, int, ""),
        ParamFieldInfo("uniqueItem09_tail", "UniqueItem9Tail", True, int, ""),
        ParamFieldInfo("uniqueItem10_head", "UniqueItem10Head", True, int, ""),
        ParamFieldInfo("uniqueItem10_tail", "UniqueItem10Tail", True, int, ""),
        ParamFieldInfo("uniqueItem11_head", "UniqueItem11Head", True, int, ""),
        ParamFieldInfo("uniqueItem11_tail", "UniqueItem11Tail", True, int, ""),
        ParamFieldInfo("uniqueItem12_head", "UniqueItem12Head", True, int, ""),
        ParamFieldInfo("uniqueItem12_tail", "UniqueItem12Tail", True, int, ""),
        ParamFieldInfo("uniqueItem13_head", "UniqueItem13Head", True, int, ""),
        ParamFieldInfo("uniqueItem13_tail", "UniqueItem13Tail", True, int, ""),
        # TODO: Add SubFeatureParam to Soulstruct types.
        ParamFieldInfo("fixedSf_1_subFeatureLotId", "FixedSubFeatureLotID1", True, int, ""),
        ParamFieldInfo("fixedSf_2_subFeatureLotId", "FixedSubFeatureLotID2", True, int, ""),
        ParamFieldInfo("fixedSf_3_subFeatureLotId", "FixedSubFeatureLotID3", True, int, ""),
        ParamFieldInfo("fixedSf_4_subFeatureLotId", "FixedSubFeatureLotID4", True, int, ""),
        ParamFieldInfo("fixedSf_5_subFeatureLotId", "FixedSubFeatureLotID5", True, int, ""),
        ParamFieldInfo("freeSf_1_subFeatureLotId", "FreeSubFeatureLotID1", True, int, ""),
        ParamFieldInfo("freeSf_2_subFeatureLotId", "FreeSubFeatureLotID2", True, int, ""),
        ParamFieldInfo("freeSf_3_subFeatureLotId", "FreeSubFeatureLotID3", True, int, ""),
        ParamFieldInfo("uniqueItem14_head", "UniqueItem14Head", True, int, ""),
        ParamFieldInfo("uniqueItem14_tail", "UniqueItem14Tail", True, int, ""),
        ParamFieldInfo("isGenericHolygrail", "IsGenericChalice", True, int, ""),
        ParamFieldInfo("releaseFlagIdOffset", "ReleaseFlagIDOffset", True, int, ""),
        ParamFieldInfo("pad_3[24]", "Pad", False, pad_field(24), ""),
        ParamFieldInfo("groupSf_1_subFeatureLotId", "GroupSubFeatureLotID1", True, int, ""),
        ParamFieldInfo("groupSf_2_subFeatureLotId", "GroupSubFeatureLotID2", True, int, ""),
        ParamFieldInfo("groupSf_3_subFeatureLotId", "GroupSubFeatureLotID3", True, int, ""),
        ParamFieldInfo("groupSf_4_subFeatureLotId", "GroupSubFeatureLotID4", True, int, ""),
        ParamFieldInfo("groupSf_5_subFeatureLotId", "GroupSubFeatureLotID5", True, int, ""),
    ],
}


RITUAL_REQUIRED_MAT_PARAM = {
    "param_type": "RITUAL_REQUIRED_MAT_PARAM",
    "file_name": "RitualRequiredMatParam",
    "nickname": "RitualMaterials",
    "fields": [
        ParamFieldInfo("useSoul", "UseSoul", True, int, ""),
        ParamFieldInfo("materialItemId_1", "MaterialItemID1", True, GoodParam, ""),
        ParamFieldInfo("materialItemId_2", "MaterialItemID2", True, GoodParam, ""),
        ParamFieldInfo("materialItemId_3", "MaterialItemID3", True, GoodParam, ""),
        ParamFieldInfo("materialItemId_4", "MaterialItemID4", True, GoodParam, ""),
        ParamFieldInfo("materialItemId_5", "MaterialItemID5", True, GoodParam, ""),
        ParamFieldInfo("num_1", "MaterialCount1", True, int, ""),
        ParamFieldInfo("num_2", "MaterialCount2", True, int, ""),
        ParamFieldInfo("num_3", "MaterialCount3", True, int, ""),
        ParamFieldInfo("num_4", "MaterialCount4", True, int, ""),
        ParamFieldInfo("num_5", "MaterialCount5", True, int, ""),
    ],
}
