__all__ = [
    "DUNGEON_FEATURE_PARAM_ST",
    "DUNGEON_SUB_FEAT_LOT_PARAM",
    "HOLYGRAIL_EX_PARAM_ST",
    "RITUAL_REQUIRED_MAT_PARAM",
]

from soulstruct.base.params.utils import FieldDisplayInfo, pad_field
from soulstruct.game_types import *


DUNGEON_FEATURE_PARAM_ST = {
    "paramdef_name": "DUNGEON_FEATURE_PARAM_ST",
    "file_name": "DungeonFeatureParam",
    "nickname": "DungeonFeatures",
    "fields": [
        FieldDisplayInfo("featureNameId", "FeatureNameID", True, int, ""),
        FieldDisplayInfo("subFeatureGroupId", "SubFeatureGroupID", True, int, ""),
        FieldDisplayInfo("eventflagId", "EventFlagID", True, int, ""),
        FieldDisplayInfo("dungeonNamePriority", "DungeonNamePriority", True, int, ""),
        FieldDisplayInfo("releaseFlagIdOffset", "ReleaseFlagIDOffset", True, int, ""),
        FieldDisplayInfo("npcParamIdOffset", "CharacterParamOffset", True, int, ""),
        FieldDisplayInfo("itemLotParamIdOffset", "ItemLotParamOffset", True, int, ""),
        FieldDisplayInfo("eneSpeffectId", "EnemySpecialEffectID", True, int, ""),
        FieldDisplayInfo("gemDropCorrectParamId", "GemDropCorrectionParamID", True, int, ""),
        FieldDisplayInfo("gemGenParamIdOffset", "GemGeneratorParamIDOffset", True, int, ""),
        FieldDisplayInfo("dungeonNameModifierId", "DungeonNameModifierID", True, int, ""),
        FieldDisplayInfo("dungeonShortNameId", "DungeonShortNameID", True, int, ""),
    ],
}


DUNGEON_SUB_FEAT_LOT_PARAM = {
    "paramdef_name": "DUNGEON_SUB_FEAT_LOT_PARAM",
    "file_name": "DungeonSubFeatLotParam",
    "nickname": "DungeonSubFeatureLots",
    "fields": [
        FieldDisplayInfo("subFeatureNameId", "SubFeatureNameID", True, int, ""),
        FieldDisplayInfo("requiredMaterialId", "RequiredMaterialID", True, int, ""),
        FieldDisplayInfo("subFeatureId_1", "SubFeatureID1", True, int, ""),
        FieldDisplayInfo("subFeatureId_2", "SubFeatureID2", True, int, ""),
        FieldDisplayInfo("subFeatureId_3", "SubFeatureID3", True, int, ""),
        FieldDisplayInfo("subFeatureId_4", "SubFeatureID4", True, int, ""),
        FieldDisplayInfo("subFeatureId_5", "SubFeatureID5", True, int, ""),
        FieldDisplayInfo("subFeatureId_6", "SubFeatureID6", True, int, ""),
        FieldDisplayInfo("subFeatureId_7", "SubFeatureID7", True, int, ""),
        FieldDisplayInfo("subFeatureId_8", "SubFeatureID8", True, int, ""),
        FieldDisplayInfo("subFeatureId_9", "SubFeatureID9", True, int, ""),
        FieldDisplayInfo("subFeatureId_10", "SubFeatureID10", True, int, ""),
        FieldDisplayInfo("pad_0[2]", "Pad", False, pad_field(2), ""),
        FieldDisplayInfo("rate_1", "Rate1", True, float, ""),
        FieldDisplayInfo("rate_2", "Rate2", True, float, ""),
        FieldDisplayInfo("rate_3", "Rate3", True, float, ""),
        FieldDisplayInfo("rate_4", "Rate4", True, float, ""),
        FieldDisplayInfo("rate_5", "Rate5", True, float, ""),
        FieldDisplayInfo("rate_6", "Rate6", True, float, ""),
        FieldDisplayInfo("rate_7", "Rate7", True, float, ""),
        FieldDisplayInfo("rate_8", "Rate8", True, float, ""),
        FieldDisplayInfo("rate_9", "Rate9", True, float, ""),
        FieldDisplayInfo("rate_10", "Rate10", True, float, ""),
    ]
}


HOLYGRAIL_EX_PARAM_ST = {
    "paramdef_name": "HOLYGRAIL_EX_PARAM_ST",
    "file_name": "HolygrailExParam",
    "nickname": "RitualChalices",
    "fields": [
        FieldDisplayInfo("ritualLv", "RitualLevel", True, int, ""),
        FieldDisplayInfo("attributeId", "AttributeID", True, int, ""),
        FieldDisplayInfo("mapBaseId", "MapBaseID", True, int, ""),
        FieldDisplayInfo("holygrailTypeId", "ChaliceTypeID", True, int, ""),
        FieldDisplayInfo("variationNum", "Variation", True, int, ""),
        FieldDisplayInfo("mainFeature_1", "MainFeature1", True, int, ""),
        FieldDisplayInfo("pad_0", "Pad", False, pad_field(1), ""),
        FieldDisplayInfo("dungeonNameBaseId", "DungeonNameBaseID", True, int, ""),
        FieldDisplayInfo("uniqueBaseFlagId", "UniqueBaseFlagID", True, int, ""),
        FieldDisplayInfo("uniqueItem00_head", "UniqueItem0Head", True, int, ""),
        FieldDisplayInfo("uniqueItem00_tail", "UniqueItem0Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem01_head", "UniqueItem1Head", True, int, ""),
        FieldDisplayInfo("uniqueItem01_tail", "UniqueItem1Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem02_head", "UniqueItem2Head", True, int, ""),
        FieldDisplayInfo("uniqueItem02_tail", "UniqueItem2Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem03_head", "UniqueItem3Head", True, int, ""),
        FieldDisplayInfo("uniqueItem03_tail", "UniqueItem3Tail", True, int, ""),
        FieldDisplayInfo("directMapUid", "DirectMapUID", True, int, ""),
        FieldDisplayInfo("requiredMaterialId", "RequiredMaterialID", True, int, ""),
        FieldDisplayInfo("groupFrameNameId", "GroupFrameNameID", True, int, ""),
        FieldDisplayInfo("uniqueItem04_head", "UniqueItem4Head", True, int, ""),
        FieldDisplayInfo("uniqueItem04_tail", "UniqueItem4Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem05_head", "UniqueItem5Head", True, int, ""),
        FieldDisplayInfo("uniqueItem05_tail", "UniqueItem5Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem06_head", "UniqueItem6Head", True, int, ""),
        FieldDisplayInfo("uniqueItem06_tail", "UniqueItem6Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem07_head", "UniqueItem7Head", True, int, ""),
        FieldDisplayInfo("uniqueItem07_tail", "UniqueItem7Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem08_head", "UniqueItem8Head", True, int, ""),
        FieldDisplayInfo("uniqueItem08_tail", "UniqueItem8Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem09_head", "UniqueItem9Head", True, int, ""),
        FieldDisplayInfo("uniqueItem09_tail", "UniqueItem9Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem10_head", "UniqueItem10Head", True, int, ""),
        FieldDisplayInfo("uniqueItem10_tail", "UniqueItem10Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem11_head", "UniqueItem11Head", True, int, ""),
        FieldDisplayInfo("uniqueItem11_tail", "UniqueItem11Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem12_head", "UniqueItem12Head", True, int, ""),
        FieldDisplayInfo("uniqueItem12_tail", "UniqueItem12Tail", True, int, ""),
        FieldDisplayInfo("uniqueItem13_head", "UniqueItem13Head", True, int, ""),
        FieldDisplayInfo("uniqueItem13_tail", "UniqueItem13Tail", True, int, ""),
        # TODO: Add SubFeatureParam to Soulstruct types.
        FieldDisplayInfo("fixedSf_1_subFeatureLotId", "FixedSubFeatureLotID1", True, int, ""),
        FieldDisplayInfo("fixedSf_2_subFeatureLotId", "FixedSubFeatureLotID2", True, int, ""),
        FieldDisplayInfo("fixedSf_3_subFeatureLotId", "FixedSubFeatureLotID3", True, int, ""),
        FieldDisplayInfo("fixedSf_4_subFeatureLotId", "FixedSubFeatureLotID4", True, int, ""),
        FieldDisplayInfo("fixedSf_5_subFeatureLotId", "FixedSubFeatureLotID5", True, int, ""),
        FieldDisplayInfo("freeSf_1_subFeatureLotId", "FreeSubFeatureLotID1", True, int, ""),
        FieldDisplayInfo("freeSf_2_subFeatureLotId", "FreeSubFeatureLotID2", True, int, ""),
        FieldDisplayInfo("freeSf_3_subFeatureLotId", "FreeSubFeatureLotID3", True, int, ""),
        FieldDisplayInfo("uniqueItem14_head", "UniqueItem14Head", True, int, ""),
        FieldDisplayInfo("uniqueItem14_tail", "UniqueItem14Tail", True, int, ""),
        FieldDisplayInfo("isGenericHolygrail", "IsGenericChalice", True, int, ""),
        FieldDisplayInfo("releaseFlagIdOffset", "ReleaseFlagIDOffset", True, int, ""),
        FieldDisplayInfo("pad_3[24]", "Pad", False, pad_field(24), ""),
        FieldDisplayInfo("groupSf_1_subFeatureLotId", "GroupSubFeatureLotID1", True, int, ""),
        FieldDisplayInfo("groupSf_2_subFeatureLotId", "GroupSubFeatureLotID2", True, int, ""),
        FieldDisplayInfo("groupSf_3_subFeatureLotId", "GroupSubFeatureLotID3", True, int, ""),
        FieldDisplayInfo("groupSf_4_subFeatureLotId", "GroupSubFeatureLotID4", True, int, ""),
        FieldDisplayInfo("groupSf_5_subFeatureLotId", "GroupSubFeatureLotID5", True, int, ""),
    ],
}


RITUAL_REQUIRED_MAT_PARAM = {
    "paramdef_name": "RITUAL_REQUIRED_MAT_PARAM",
    "file_name": "RitualRequiredMatParam",
    "nickname": "RitualMaterials",
    "fields": [
        FieldDisplayInfo("useSoul", "UseSoul", True, int, ""),
        FieldDisplayInfo("materialItemId_1", "MaterialItemID1", True, GoodParam, ""),
        FieldDisplayInfo("materialItemId_2", "MaterialItemID2", True, GoodParam, ""),
        FieldDisplayInfo("materialItemId_3", "MaterialItemID3", True, GoodParam, ""),
        FieldDisplayInfo("materialItemId_4", "MaterialItemID4", True, GoodParam, ""),
        FieldDisplayInfo("materialItemId_5", "MaterialItemID5", True, GoodParam, ""),
        FieldDisplayInfo("num_1", "MaterialCount1", True, int, ""),
        FieldDisplayInfo("num_2", "MaterialCount2", True, int, ""),
        FieldDisplayInfo("num_3", "MaterialCount3", True, int, ""),
        FieldDisplayInfo("num_4", "MaterialCount4", True, int, ""),
        FieldDisplayInfo("num_5", "MaterialCount5", True, int, ""),
    ],
}
