__all__ = [
    "GEM_CATEGORY_PARAM_ST",
    "GEM_DROP_DOPING_PARAM_ST",
    "GEM_DROP_MODIFY_PARAM_ST",
    "GEM_GEN_PARAM_ST",
    "GEMEFFECT_PARAM_ST",
]

from soulstruct.base.params.utils import FieldDisplayInfo, pad_field
from soulstruct.bloodborne.params.enums import *
from soulstruct.game_types import *


EQUIP_GEN_PARAM_BOOL32 = bool  # override u32


GEM_CATEGORY_PARAM_ST = {
    "paramdef_name": "GEM_CATEGORY_PARAM_ST",
    "file_name": "GemCategoryParam",
    "nickname": "GemCategories",
    "fields": [
        FieldDisplayInfo("sortNo", "SortID", True, int, ""),
        FieldDisplayInfo("manifestRate", "ManifestRate", True, float, ""),
        FieldDisplayInfo("directionalId", "DirectionalID", True, int, ""),
        FieldDisplayInfo("cateGroupId", "CategoryGroupID", True, int, ""),
        FieldDisplayInfo("excludeGroupId", "ExcludeGroupID", True, int, ""),
        FieldDisplayInfo("isNegative:1", "IsNegative", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeA:1", "EnableSlotTypeA", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeB:1", "EnableSlotTypeB", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeC:1", "EnableSlotTypeC", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeD:1", "EnableSlotTypeD", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeE:1", "EnableSlotTypeE", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("enableSlotTypeF:1", "EnableSlotTypeF", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("holygrailTypeGroup:7", "ChaliceTypeGroup", True, int, ""),
        FieldDisplayInfo("affinityCateId_0", "AffinityCategoryID0", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_0", "AffinityModifyRate0", True, float, ""),
        FieldDisplayInfo("affinityCateId_1", "AffinityCategoryID1", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_1", "AffinityModifyRate1", True, float, ""),
        FieldDisplayInfo("affinityCateId_2", "AffinityCategoryID2", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_2", "AffinityModifyRate2", True, float, ""),
        FieldDisplayInfo("affinityCateId_3", "AffinityCategoryID3", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_3", "AffinityModifyRate3", True, float, ""),
    ],
}


GEM_DROP_DOPING_PARAM_ST = {
    "paramdef_name": "GEM_DROP_DOPING_PARAM_ST",
    "file_name": "GemDropDopingParam",
    "nickname": "GemDropDoping",
    "fields": [
        FieldDisplayInfo("rankMin", "MinimumRank", True, int, ""),
        FieldDisplayInfo("rankMax", "MaximumRank", True, int, ""),
        FieldDisplayInfo("normalDistributionAve", "NormalDistributionMean", True, int, ""),
        FieldDisplayInfo("normalDistributionSigma", "NormalDistributionSigma", True, int, ""),
        FieldDisplayInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        FieldDisplayInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        FieldDisplayInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        FieldDisplayInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        FieldDisplayInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        FieldDisplayInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        FieldDisplayInfo("directionalIdRate_0", "DirectionalIDRate0", True, float, ""),
        FieldDisplayInfo("directionalIdRate_1", "DirectionalIDRate1", True, float, ""),
        FieldDisplayInfo("directionalIdRate_2", "DirectionalIDRate2", True, float, ""),
        FieldDisplayInfo("directionalIdRate_3", "DirectionalIDRate3", True, float, ""),
        FieldDisplayInfo("directionalIdRate_4", "DirectionalIDRate4", True, float, ""),
        FieldDisplayInfo("directionalIdRate_5", "DirectionalIDRate5", True, float, ""),
        FieldDisplayInfo("directionalIdRate_6", "DirectionalIDRate6", True, float, ""),
        FieldDisplayInfo("directionalIdRate_7", "DirectionalIDRate7", True, float, ""),
    ],
}


GEM_DROP_MODIFY_PARAM_ST = {
    "paramdef_name": "GEM_DROP_MODIFY_PARAM_ST",
    "file_name": "GemDropModifyParam",
    "nickname": "GemDropModifications",
    "fields": [
        FieldDisplayInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        FieldDisplayInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        FieldDisplayInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        FieldDisplayInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        FieldDisplayInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        FieldDisplayInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        FieldDisplayInfo("directionalIdRate_0", "DirectionalIDRate0", True, float, ""),
        FieldDisplayInfo("directionalIdRate_1", "DirectionalIDRate1", True, float, ""),
        FieldDisplayInfo("directionalIdRate_2", "DirectionalIDRate2", True, float, ""),
        FieldDisplayInfo("directionalIdRate_3", "DirectionalIDRate3", True, float, ""),
        FieldDisplayInfo("directionalIdRate_4", "DirectionalIDRate4", True, float, ""),
        FieldDisplayInfo("directionalIdRate_5", "DirectionalIDRate5", True, float, ""),
        FieldDisplayInfo("directionalIdRate_6", "DirectionalIDRate6", True, float, ""),
        FieldDisplayInfo("directionalIdRate_7", "DirectionalIDRate7", True, float, ""),
        FieldDisplayInfo("affinityCateId_0", "AffinityCategoryID0", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_0", "AffinityModifyRate0", True, float, ""),
        FieldDisplayInfo("affinityCateId_1", "AffinityCategoryID1", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_1", "AffinityModifyRate1", True, float, ""),
        FieldDisplayInfo("affinityCateId_2", "AffinityCategoryID2", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_2", "AffinityModifyRate2", True, float, ""),
        FieldDisplayInfo("affinityCateId_3", "AffinityCategoryID3", True, int, ""),
        FieldDisplayInfo("affinityModifyRate_3", "AffinityModifyRate3", True, float, ""),
        FieldDisplayInfo("manifestRate_0", "ManifestRate0", True, float, ""),
        FieldDisplayInfo("manifestRate_1", "ManifestRate1", True, float, ""),
        FieldDisplayInfo("manifestRate_2", "ManifestRate2", True, float, ""),
        FieldDisplayInfo("manifestRate_3", "ManifestRate3", True, float, ""),
        FieldDisplayInfo("manifestRate_4", "ManifestRate4", True, float, ""),
        FieldDisplayInfo("manifestRate_5", "ManifestRate5", True, float, ""),
        FieldDisplayInfo("negativizeRate_0", "NegativizeRate0", True, float, ""),
        FieldDisplayInfo("normalDistributionAve", "NormalDistributionMean", True, int, ""),
        FieldDisplayInfo("normalDistributionSigma", "NormalDistributionSigma", True, int, ""),
    ],
}


GEMEFFECT_PARAM_ST = {
    "paramdef_name": "GEMEFFECT_PARAM_ST",
    "file_name": "GemeffectParam",
    "nickname": "GemEffects",
    "fields": [
        FieldDisplayInfo("speffectId", "SpecialEffectID", True, SpecialEffectParam, ""),
        FieldDisplayInfo("categoryId", "CategoryID", True, int, ""),
        FieldDisplayInfo("effectRank", "EffectRank", True, int, ""),
        FieldDisplayInfo("rankMin", "MinimumRank", True, int, ""),
        FieldDisplayInfo("rankMax", "MaximumRank", True, int, ""),
        FieldDisplayInfo("disposalPrice", "DisposalPrice", True, int, ""),
        FieldDisplayInfo("gemIconIdOffset", "GemIconIDOffset", True, int, ""),
        FieldDisplayInfo("sortId:14", "SortID", True, int, ""),
        FieldDisplayInfo("sortCategory:2", "SortCategory", True, int, ""),
        FieldDisplayInfo("gemNameIdOffset", "GemNameIDOffset", True, int, ""),
        FieldDisplayInfo("speffectId_forAtk", "AttackSpecialEffectID", True, SpecialEffectParam, ""),
    ],
}


GEM_GEN_PARAM_ST = {
    "paramdef_name": "GEM_GEN_PARAM_ST",
    "file_name": "GemGenParam",
    "nickname": "GemGenerators",
    "fields": [
        FieldDisplayInfo("isUnique:1", "IsUnique", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("pad_0[4]", "Pad", False, pad_field(4), ""),
        FieldDisplayInfo("gemNameIdOffset", "GemNameIDOffset", True, int, ""),
        FieldDisplayInfo("disableSlotRateModify:1", "DisableSlotModifyRate", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        FieldDisplayInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        FieldDisplayInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        FieldDisplayInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        FieldDisplayInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        FieldDisplayInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        FieldDisplayInfo("gemRankDoping", "GemRankDoping", True, int, ""),
        FieldDisplayInfo("pad_1[3]", "Pad", False, pad_field(3), ""),
        FieldDisplayInfo("gemeffectGenParamType_0", "GemEffectGenParamType0", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_0", "GemEffectGenParam0", True, int, ""),
        FieldDisplayInfo("manifestRate_0", "ManifestRate0", True, float, ""),
        FieldDisplayInfo("negativizeRate_0", "NegativizeRate0", True, float, ""),
        FieldDisplayInfo("gemeffectGenParamType_1", "GemEffectGenParamType1", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_1", "GemEffectGenParam1", True, int, ""),
        FieldDisplayInfo("manifestRate_1", "ManifestRate1", True, float, ""),
        FieldDisplayInfo("negativizeRate_1", "NegativizeRate1", True, float, ""),
        FieldDisplayInfo("gemeffectGenParamType_2", "GemEffectGenParamType2", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_2", "GemEffectGenParam2", True, int, ""),
        FieldDisplayInfo("manifestRate_2", "ManifestRate2", True, float, ""),
        FieldDisplayInfo("negativizeRate_2", "NegativizeRate2", True, float, ""),
        FieldDisplayInfo("gemeffectGenParamType_3", "GemEffectGenParamType3", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_3", "GemEffectGenParam3", True, int, ""),
        FieldDisplayInfo("manifestRate_3", "ManifestRate3", True, float, ""),
        FieldDisplayInfo("negativizeRate_3", "NegativizeRate3", True, float, ""),
        FieldDisplayInfo("gemeffectGenParamType_4", "GemEffectGenParamType4", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_4", "GemEffectGenParam4", True, int, ""),
        FieldDisplayInfo("manifestRate_4", "ManifestRate4", True, float, ""),
        FieldDisplayInfo("negativizeRate_4", "NegativizeRate4", True, float, ""),
        FieldDisplayInfo("gemeffectGenParamType_5", "GemEffectGenParamType5", True, GEMEFFECT_GEN_PT, ""),
        FieldDisplayInfo("gemeffectGenParam_5", "GemEffectGenParam5", True, int, ""),
        FieldDisplayInfo("manifestRate_5", "ManifestRate5", True, float, ""),
        FieldDisplayInfo("negativizeRate_5", "NegativizeRate5", True, float, ""),
        FieldDisplayInfo("equipableSegmentBody:1", "IsRune", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("equipableSegmentWeapon:1", "IsBloodGem", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("unremovable:1", "CannotRemove", True, EQUIP_GEN_PARAM_BOOL32, ""),
        FieldDisplayInfo("isGuestDrop:1", "CanDropToSummons", True, EQUIP_GEN_PARAM_BOOL32, ""),
    ],
}
