__all__ = [
    "GEM_CATEGORY_PARAM_ST",
    "GEM_DROP_DOPING_PARAM_ST",
    "GEM_DROP_MODIFY_PARAM_ST",
    "GEM_GEN_PARAM_ST",
    "GEMEFFECT_PARAM_ST",
]

from soulstruct.base.params.utils import ParamFieldInfo, pad_field
from soulstruct.bloodborne.params.enums import *
from soulstruct.bloodborne.game_types import *


EQUIP_GEN_PARAM_BOOL32 = bool  # override u32


GEM_CATEGORY_PARAM_ST = {
    "param_type": "GEM_CATEGORY_PARAM_ST",
    "file_name": "GemCategoryParam",
    "nickname": "GemCategories",
    "fields": [
        ParamFieldInfo("sortNo", "SortID", True, int, ""),
        ParamFieldInfo("manifestRate", "ManifestRate", True, float, ""),
        ParamFieldInfo("directionalId", "DirectionalID", True, int, ""),
        ParamFieldInfo("cateGroupId", "CategoryGroupID", True, int, ""),
        ParamFieldInfo("excludeGroupId", "ExcludeGroupID", True, int, ""),
        ParamFieldInfo("isNegative:1", "IsNegative", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeA:1", "EnableSlotTypeA", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeB:1", "EnableSlotTypeB", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeC:1", "EnableSlotTypeC", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeD:1", "EnableSlotTypeD", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeE:1", "EnableSlotTypeE", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("enableSlotTypeF:1", "EnableSlotTypeF", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("holygrailTypeGroup:7", "ChaliceTypeGroup", True, int, ""),
        ParamFieldInfo("affinityCateId_0", "AffinityCategoryID0", True, int, ""),
        ParamFieldInfo("affinityModifyRate_0", "AffinityModifyRate0", True, float, ""),
        ParamFieldInfo("affinityCateId_1", "AffinityCategoryID1", True, int, ""),
        ParamFieldInfo("affinityModifyRate_1", "AffinityModifyRate1", True, float, ""),
        ParamFieldInfo("affinityCateId_2", "AffinityCategoryID2", True, int, ""),
        ParamFieldInfo("affinityModifyRate_2", "AffinityModifyRate2", True, float, ""),
        ParamFieldInfo("affinityCateId_3", "AffinityCategoryID3", True, int, ""),
        ParamFieldInfo("affinityModifyRate_3", "AffinityModifyRate3", True, float, ""),
    ],
}


GEM_DROP_DOPING_PARAM_ST = {
    "param_type": "GEM_DROP_DOPING_PARAM_ST",
    "file_name": "GemDropDopingParam",
    "nickname": "GemDropDoping",
    "fields": [
        ParamFieldInfo("rankMin", "MinimumRank", True, int, ""),
        ParamFieldInfo("rankMax", "MaximumRank", True, int, ""),
        ParamFieldInfo("normalDistributionAve", "NormalDistributionMean", True, int, ""),
        ParamFieldInfo("normalDistributionSigma", "NormalDistributionSigma", True, int, ""),
        ParamFieldInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        ParamFieldInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        ParamFieldInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        ParamFieldInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        ParamFieldInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        ParamFieldInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        ParamFieldInfo("directionalIdRate_0", "DirectionalIDRate0", True, float, ""),
        ParamFieldInfo("directionalIdRate_1", "DirectionalIDRate1", True, float, ""),
        ParamFieldInfo("directionalIdRate_2", "DirectionalIDRate2", True, float, ""),
        ParamFieldInfo("directionalIdRate_3", "DirectionalIDRate3", True, float, ""),
        ParamFieldInfo("directionalIdRate_4", "DirectionalIDRate4", True, float, ""),
        ParamFieldInfo("directionalIdRate_5", "DirectionalIDRate5", True, float, ""),
        ParamFieldInfo("directionalIdRate_6", "DirectionalIDRate6", True, float, ""),
        ParamFieldInfo("directionalIdRate_7", "DirectionalIDRate7", True, float, ""),
    ],
}


GEM_DROP_MODIFY_PARAM_ST = {
    "param_type": "GEM_DROP_MODIFY_PARAM_ST",
    "file_name": "GemDropModifyParam",
    "nickname": "GemDropModifications",
    "fields": [
        ParamFieldInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        ParamFieldInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        ParamFieldInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        ParamFieldInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        ParamFieldInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        ParamFieldInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        ParamFieldInfo("directionalIdRate_0", "DirectionalIDRate0", True, float, ""),
        ParamFieldInfo("directionalIdRate_1", "DirectionalIDRate1", True, float, ""),
        ParamFieldInfo("directionalIdRate_2", "DirectionalIDRate2", True, float, ""),
        ParamFieldInfo("directionalIdRate_3", "DirectionalIDRate3", True, float, ""),
        ParamFieldInfo("directionalIdRate_4", "DirectionalIDRate4", True, float, ""),
        ParamFieldInfo("directionalIdRate_5", "DirectionalIDRate5", True, float, ""),
        ParamFieldInfo("directionalIdRate_6", "DirectionalIDRate6", True, float, ""),
        ParamFieldInfo("directionalIdRate_7", "DirectionalIDRate7", True, float, ""),
        ParamFieldInfo("affinityCateId_0", "AffinityCategoryID0", True, int, ""),
        ParamFieldInfo("affinityModifyRate_0", "AffinityModifyRate0", True, float, ""),
        ParamFieldInfo("affinityCateId_1", "AffinityCategoryID1", True, int, ""),
        ParamFieldInfo("affinityModifyRate_1", "AffinityModifyRate1", True, float, ""),
        ParamFieldInfo("affinityCateId_2", "AffinityCategoryID2", True, int, ""),
        ParamFieldInfo("affinityModifyRate_2", "AffinityModifyRate2", True, float, ""),
        ParamFieldInfo("affinityCateId_3", "AffinityCategoryID3", True, int, ""),
        ParamFieldInfo("affinityModifyRate_3", "AffinityModifyRate3", True, float, ""),
        ParamFieldInfo("manifestRate_0", "ManifestRate0", True, float, ""),
        ParamFieldInfo("manifestRate_1", "ManifestRate1", True, float, ""),
        ParamFieldInfo("manifestRate_2", "ManifestRate2", True, float, ""),
        ParamFieldInfo("manifestRate_3", "ManifestRate3", True, float, ""),
        ParamFieldInfo("manifestRate_4", "ManifestRate4", True, float, ""),
        ParamFieldInfo("manifestRate_5", "ManifestRate5", True, float, ""),
        ParamFieldInfo("negativizeRate_0", "NegativizeRate0", True, float, ""),
        ParamFieldInfo("normalDistributionAve", "NormalDistributionMean", True, int, ""),
        ParamFieldInfo("normalDistributionSigma", "NormalDistributionSigma", True, int, ""),
    ],
}


GEMEFFECT_PARAM_ST = {
    "param_type": "GEMEFFECT_PARAM_ST",
    "file_name": "GemeffectParam",
    "nickname": "GemEffects",
    "fields": [
        ParamFieldInfo("speffectId", "SpecialEffectID", True, SpecialEffectParam, ""),
        ParamFieldInfo("categoryId", "CategoryID", True, int, ""),
        ParamFieldInfo("effectRank", "EffectRank", True, int, ""),
        ParamFieldInfo("rankMin", "MinimumRank", True, int, ""),
        ParamFieldInfo("rankMax", "MaximumRank", True, int, ""),
        ParamFieldInfo("disposalPrice", "DisposalPrice", True, int, ""),
        ParamFieldInfo("gemIconIdOffset", "GemIconIDOffset", True, int, ""),
        ParamFieldInfo("sortId:14", "SortID", True, int, ""),
        ParamFieldInfo("sortCategory:2", "SortCategory", True, int, ""),
        ParamFieldInfo("gemNameIdOffset", "GemNameIDOffset", True, int, ""),
        ParamFieldInfo("speffectId_forAtk", "AttackSpecialEffectID", True, SpecialEffectParam, ""),
    ],
}


GEM_GEN_PARAM_ST = {
    "param_type": "GEM_GEN_PARAM_ST",
    "file_name": "GemGenParam",
    "nickname": "GemGenerators",
    "fields": [
        ParamFieldInfo("isUnique:1", "IsUnique", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("pad_0[4]", "Pad", False, pad_field(4), ""),
        ParamFieldInfo("gemNameIdOffset", "GemNameIDOffset", True, int, ""),
        ParamFieldInfo("disableSlotRateModify:1", "DisableSlotModifyRate", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("slotTypeRateA", "SlotTypeRateA", True, float, ""),
        ParamFieldInfo("slotTypeRateB", "SlotTypeRateB", True, float, ""),
        ParamFieldInfo("slotTypeRateC", "SlotTypeRateC", True, float, ""),
        ParamFieldInfo("slotTypeRateD", "SlotTypeRateD", True, float, ""),
        ParamFieldInfo("slotTypeRateE", "SlotTypeRateE", True, float, ""),
        ParamFieldInfo("slotTypeRateF", "SlotTypeRateF", True, float, ""),
        ParamFieldInfo("gemRankDoping", "GemRankDoping", True, int, ""),
        ParamFieldInfo("pad_1[3]", "Pad", False, pad_field(3), ""),
        ParamFieldInfo("gemeffectGenParamType_0", "GemEffectGenParamType0", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_0", "GemEffectGenParam0", True, int, ""),
        ParamFieldInfo("manifestRate_0", "ManifestRate0", True, float, ""),
        ParamFieldInfo("negativizeRate_0", "NegativizeRate0", True, float, ""),
        ParamFieldInfo("gemeffectGenParamType_1", "GemEffectGenParamType1", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_1", "GemEffectGenParam1", True, int, ""),
        ParamFieldInfo("manifestRate_1", "ManifestRate1", True, float, ""),
        ParamFieldInfo("negativizeRate_1", "NegativizeRate1", True, float, ""),
        ParamFieldInfo("gemeffectGenParamType_2", "GemEffectGenParamType2", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_2", "GemEffectGenParam2", True, int, ""),
        ParamFieldInfo("manifestRate_2", "ManifestRate2", True, float, ""),
        ParamFieldInfo("negativizeRate_2", "NegativizeRate2", True, float, ""),
        ParamFieldInfo("gemeffectGenParamType_3", "GemEffectGenParamType3", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_3", "GemEffectGenParam3", True, int, ""),
        ParamFieldInfo("manifestRate_3", "ManifestRate3", True, float, ""),
        ParamFieldInfo("negativizeRate_3", "NegativizeRate3", True, float, ""),
        ParamFieldInfo("gemeffectGenParamType_4", "GemEffectGenParamType4", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_4", "GemEffectGenParam4", True, int, ""),
        ParamFieldInfo("manifestRate_4", "ManifestRate4", True, float, ""),
        ParamFieldInfo("negativizeRate_4", "NegativizeRate4", True, float, ""),
        ParamFieldInfo("gemeffectGenParamType_5", "GemEffectGenParamType5", True, GEMEFFECT_GEN_PT, ""),
        ParamFieldInfo("gemeffectGenParam_5", "GemEffectGenParam5", True, int, ""),
        ParamFieldInfo("manifestRate_5", "ManifestRate5", True, float, ""),
        ParamFieldInfo("negativizeRate_5", "NegativizeRate5", True, float, ""),
        ParamFieldInfo("equipableSegmentBody:1", "IsRune", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("equipableSegmentWeapon:1", "IsBloodGem", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("unremovable:1", "CannotRemove", True, EQUIP_GEN_PARAM_BOOL32, ""),
        ParamFieldInfo("isGuestDrop:1", "CanDropToSummons", True, EQUIP_GEN_PARAM_BOOL32, ""),
    ],
}
