from __future__ import annotations

__all__ = ["CHARACTER_INIT_PARAM"]

from soulstruct.base.params.utils import ParamFieldInfo, pad_field, bit_pad_field
from soulstruct.darksouls1ptde.game_types import *
from ..enums import *


CHARACTER_INIT_PARAM = {
    "param_type": "CHARACTER_INIT_PARAM",
    "file_name": "CharaInitParam",
    "nickname": "Players",
    "fields": [
        ParamFieldInfo("baseRec_mp", "BaseRecMP", False, float, "Unknown."),
        ParamFieldInfo("baseRec_sp", "BaseRecSP", False, float, "Unknown."),
        ParamFieldInfo("red_Falldam", "RedFallDamage", False, float, "Unknown."),
        ParamFieldInfo("soul", "SoulCount", True, int, "Starting soul count of character."),
        ParamFieldInfo(
            "equip_Wep_Right",
            "RightHandWeapon1",
            True,
            WeaponParam,
            "First (default) weapon/shield equipped in right hand.",
        ),
        ParamFieldInfo(
            "equip_Subwep_Right",
            "RightHandWeapon2",
            True,
            WeaponParam,
            "Second weapon/shield equipped in right hand.",
        ),
        ParamFieldInfo(
            "equip_Wep_Left",
            "LeftHandWeapon1",
            True,
            WeaponParam,
            "First (default) weapon/shield equipped in left hand.",
        ),
        ParamFieldInfo(
            "equip_Subwep_Left",
            "LeftHandWeapon2",
            True,
            WeaponParam,
            "Second weapon/shield equipped in left hand.",
        ),
        ParamFieldInfo("equip_Helm", "HeadArmor", True, ArmorParam, "Armor equipped to head."),
        ParamFieldInfo("equip_Armer", "BodyArmor", True, ArmorParam, "Armor equipped to body."),
        ParamFieldInfo("equip_Gaunt", "HandsArmor", True, ArmorParam, "Armor equipped to hands."),
        ParamFieldInfo("equip_Leg", "LegsArmor", True, ArmorParam, "Armor equipped to legs."),
        ParamFieldInfo("equip_Arrow", "ArrowSlot1", True, WeaponParam, "Arrows equipped in slot 1."),
        ParamFieldInfo("equip_Bolt", "BoltSlot1", True, WeaponParam, "Bolts equipped in slot 1."),
        ParamFieldInfo("equip_SubArrow", "ArrowSlot2", True, WeaponParam, "Arrows equipped in slot 2."),
        ParamFieldInfo("equip_SubBolt", "BoltSlot2", True, WeaponParam, "Bolts equipped in slot 2."),
        ParamFieldInfo(
            "equip_Accessory01",
            "RingSlot1",
            True,
            AccessoryParam,
            "First ring equipped. Note that up to five rings can be equipped to human NPCs.",
        ),
        ParamFieldInfo(
            "equip_Accessory02",
            "RingSlot2",
            True,
            AccessoryParam,
            "Second ring equipped. Note that up to five rings can be equipped to human NPCs.",
        ),
        ParamFieldInfo(
            "equip_Accessory03",
            "RingSlot3",
            True,
            AccessoryParam,
            "Third ring equipped. Note that up to five rings can be equipped to human NPCs.",
        ),
        ParamFieldInfo(
            "equip_Accessory04",
            "RingSlot4",
            True,
            AccessoryParam,
            "Fourth ring equipped. Note that up to five rings can be equipped to human NPCs.",
        ),
        ParamFieldInfo(
            "equip_Accessory05",
            "RingSlot5",
            True,
            AccessoryParam,
            "Fifth ring equipped. Note that up to five rings can be equipped to human NPCs.",
        ),
        ParamFieldInfo("equip_Skill_01", "SkillSlot1", False, int, ""),
        ParamFieldInfo("equip_Skill_02", "SkillSlot2", False, int, ""),
        ParamFieldInfo("equip_Skill_03", "SkillSlot3", False, int, ""),
        ParamFieldInfo("equip_Spell_01", "SpellSlot1", True, SpellParam, "First spell equipped."),
        ParamFieldInfo("equip_Spell_02", "SpellSlot2", True, SpellParam, "Second spell equipped."),
        ParamFieldInfo("equip_Spell_03", "SpellSlot3", True, SpellParam, "Third spell equipped."),
        ParamFieldInfo("equip_Spell_04", "SpellSlot4", True, SpellParam, "Fourth spell equipped."),
        ParamFieldInfo("equip_Spell_05", "SpellSlot5", True, SpellParam, "Fifth spell equipped."),
        ParamFieldInfo("equip_Spell_06", "SpellSlot6", True, SpellParam, "Sixth spell equipped."),
        ParamFieldInfo("equip_Spell_07", "SpellSlot7", True, SpellParam, "Seventh spell equipped."),
        ParamFieldInfo("item_01", "GoodSlot1", True, GoodParam, "Good (item) equipped in slot 1."),
        ParamFieldInfo("item_02", "GoodSlot2", True, GoodParam, "Good (item) equipped in slot 2."),
        ParamFieldInfo("item_03", "GoodSlot3", True, GoodParam, "Good (item) equipped in slot 3."),
        ParamFieldInfo("item_04", "GoodSlot4", True, GoodParam, "Good (item) equipped in slot 4."),
        ParamFieldInfo("item_05", "GoodSlot5", True, GoodParam, "Good (item) equipped in slot 5."),
        ParamFieldInfo("item_06", "GoodSlot6", True, GoodParam, "Good (item) equipped in slot 6."),
        ParamFieldInfo("item_07", "GoodSlot7", True, GoodParam, "Good (item) equipped in slot 7."),
        ParamFieldInfo("item_08", "GoodSlot8", True, GoodParam, "Good (item) equipped in slot 8."),
        ParamFieldInfo("item_09", "GoodSlot9", True, GoodParam, "Good (item) equipped in slot 9."),
        ParamFieldInfo("item_10", "GoodSlot10", True, GoodParam, "Good (item) equipped in slot 10."),
        ParamFieldInfo("npcPlayerFaceGenId", "FaceID", True, FaceParam, "Face parameter ID (NPCs only)."),
        ParamFieldInfo("npcPlayerThinkId", "DefaultAI", True, AIParam, "Default AI (NPCs only)."),
        ParamFieldInfo("baseHp", "BaseMaxHP", True, int, "Base amount of maximum HP (excluding effects of vitality)."),
        ParamFieldInfo("baseMp", "BaseMaxMP", False, int, "Base amount of maximum MP (unused in Dark Souls)."),
        ParamFieldInfo("baseSp", "BaseMaxStamina", True, int, "Base maximum stamina (excluding effects of endurance)."),
        ParamFieldInfo("arrowNum", "ArrowSlot1Count", True, int, "Count of arrows equipped in slot 1."),
        ParamFieldInfo("boltNum", "BoltSlot1Count", True, int, "Count of arrows equipped in slot 2."),
        ParamFieldInfo("subArrowNum", "ArrowSlot2Count", True, int, "Count of bolts equipped in slot 1."),
        ParamFieldInfo("subBoltNum", "BoltSlot2Count", True, int, "Count of bolts equipped in slot 2."),
        ParamFieldInfo("QWC_sb", "QWC_SB", False, int, "Unknown. Likely to be unused world tendency effect."),
        ParamFieldInfo("QWC_mw", "QWC_MW", False, int, "Unknown. Likely to be unused world tendency effect."),
        ParamFieldInfo("QWC_cd", "QWC_CD", False, int, "Unknown. Likely to be unused world tendency effect."),
        ParamFieldInfo(
            "soulLv",
            "Level",
            True,
            int,
            "Soul level, independent of actual stats. Determines amount of souls rewarded by human NPCs.",
        ),
        ParamFieldInfo("baseVit", "Vitality", True, int, "Base vitality level. Determines maximum health."),
        ParamFieldInfo(
            "baseWil", "Attunement", True, int, "Base attunement level. Determines spell slots and casting speed."
        ),
        ParamFieldInfo(
            "baseEnd", "Endurance", True, int, "Base endurance level. Determines maximum stamina and equip load."
        ),
        ParamFieldInfo(
            "baseStr", "Strength", True, int, "Base strength level. Affects strength-based weapons and damage."
        ),
        ParamFieldInfo(
            "baseDex", "Dexterity", True, int, "Base dexterity level. Affects skill-based weapons and damage."
        ),
        ParamFieldInfo(
            "baseMag",
            "Intelligence",
            True,
            int,
            "Base intelligence level. Affects magic usability and effectiveness.",
        ),
        ParamFieldInfo("baseFai", "Faith", True, int, "Base faith level. Affects miracle usability and effectiveness."),
        ParamFieldInfo("baseLuc", "Luck", True, int, "Base luck level. Improves chances of rare item drops."),
        ParamFieldInfo("baseHeroPoint", "Humanity", True, int, "Base 'soft' humanity."),
        ParamFieldInfo(
            "baseDurability",
            "Resistance",
            True,
            int,
            "Base resistance level. Improves resistances to status ailments.",
        ),
        ParamFieldInfo("itemNum_01", "GoodSlot1Count", True, int, "Count of good equipped in slot 1."),
        ParamFieldInfo("itemNum_02", "GoodSlot2Count", True, int, "Count of good equipped in slot 2."),
        ParamFieldInfo("itemNum_03", "GoodSlot3Count", True, int, "Count of good equipped in slot 3."),
        ParamFieldInfo("itemNum_04", "GoodSlot4Count", True, int, "Count of good equipped in slot 4."),
        ParamFieldInfo("itemNum_05", "GoodSlot5Count", True, int, "Count of good equipped in slot 5."),
        ParamFieldInfo("itemNum_06", "GoodSlot6Count", True, int, "Count of good equipped in slot 6."),
        ParamFieldInfo("itemNum_07", "GoodSlot7Count", True, int, "Count of good equipped in slot 7."),
        ParamFieldInfo("itemNum_08", "GoodSlot8Count", True, int, "Count of good equipped in slot 8."),
        ParamFieldInfo("itemNum_09", "GoodSlot9Count", True, int, "Count of good equipped in slot 9."),
        ParamFieldInfo("itemNum_10", "GoodSlot10Count", True, int, "Count of good equipped in slot 10."),
        ParamFieldInfo("bodyScaleHead", "HeadScale", True, int, "Multiplier applied to head size."),
        ParamFieldInfo("bodyScaleBreast", "ChestScale", True, int, "Multiplier applied to chest size."),
        ParamFieldInfo("bodyScaleAbdomen", "AbdomenScale", True, int, "Multiplier applied to abdomen size."),
        ParamFieldInfo("bodyScaleArm", "ArmScale", True, int, "Multiplier applied to arm size."),
        ParamFieldInfo("bodyScaleLeg", "LegScale", True, int, "Multiplier applied to leg size."),
        ParamFieldInfo("gestureId0", "Gesture1", True, int, "First equipped gesture."),
        ParamFieldInfo("gestureId1", "Gesture2", True, int, "Second equipped gesture."),
        ParamFieldInfo("gestureId2", "Gesture3", True, int, "Third equipped gesture."),
        ParamFieldInfo("gestureId3", "Gesture4", True, int, "Fourth equipped gesture."),
        ParamFieldInfo("gestureId4", "Gesture5", True, int, "Fifth equipped gesture."),
        ParamFieldInfo("gestureId5", "Gesture6", True, int, "Sixth equipped gesture."),
        ParamFieldInfo("gestureId6", "Gesture7", True, int, "Seventh equipped gesture."),
        ParamFieldInfo("npcPlayerType", "CharacterType", True, NPC_TYPE, "Type of human NPC."),
        ParamFieldInfo("npcPlayerDrawType", "DrawType", True, NPC_DRAW_TYPE, "Draw type of human NPC."),
        ParamFieldInfo("npcPlayerSex", "Gender", True, CHARACTER_INIT_SEX, "Character gender."),
        ParamFieldInfo("vowType:4", "Covenant", True, CHRINIT_VOW_TYPE, "Character covenant."),
        ParamFieldInfo("pad:4", "Pad0", False, bit_pad_field(4), "Null padding."),
        ParamFieldInfo("pad0[10]", "Pad1", False, pad_field(10), "Null padding."),
    ],
}
