from __future__ import annotations

__all__ = ["FACE_PARAM_ST"]

from soulstruct.base.params.utils import ParamFieldInfo, pad_field
from ..enums import *

FACE_PARAM_ST = {
    "param_type": "FACE_PARAM_ST",
    "file_name": "FaceGenParam",
    "nickname": "Faces",
    "fields": [
        ParamFieldInfo("faceGeoData00", "GeometryData00", True, int, "Geometry data point 0."),
        ParamFieldInfo("faceGeoData01", "GeometryData01", True, int, "Geometry data point 1."),
        ParamFieldInfo("faceGeoData02", "GeometryData02", True, int, "Geometry data point 2."),
        ParamFieldInfo("faceGeoData03", "GeometryData03", True, int, "Geometry data point 3."),
        ParamFieldInfo("faceGeoData04", "GeometryData04", True, int, "Geometry data point 4."),
        ParamFieldInfo("faceGeoData05", "GeometryData05", True, int, "Geometry data point 5."),
        ParamFieldInfo("faceGeoData06", "GeometryData06", True, int, "Geometry data point 6."),
        ParamFieldInfo("faceGeoData07", "GeometryData07", True, int, "Geometry data point 7."),
        ParamFieldInfo("faceGeoData08", "GeometryData08", True, int, "Geometry data point 8."),
        ParamFieldInfo("faceGeoData09", "GeometryData09", True, int, "Geometry data point 9."),
        ParamFieldInfo("faceGeoData10", "GeometryData10", True, int, "Geometry data point 10."),
        ParamFieldInfo("faceGeoData11", "GeometryData11", True, int, "Geometry data point 11."),
        ParamFieldInfo("faceGeoData12", "GeometryData12", True, int, "Geometry data point 12."),
        ParamFieldInfo("faceGeoData13", "GeometryData13", True, int, "Geometry data point 13."),
        ParamFieldInfo("faceGeoData14", "GeometryData14", True, int, "Geometry data point 14."),
        ParamFieldInfo("faceGeoData15", "GeometryData15", True, int, "Geometry data point 15."),
        ParamFieldInfo("faceGeoData16", "GeometryData16", True, int, "Geometry data point 16."),
        ParamFieldInfo("faceGeoData17", "GeometryData17", True, int, "Geometry data point 17."),
        ParamFieldInfo("faceGeoData18", "GeometryData18", True, int, "Geometry data point 18."),
        ParamFieldInfo("faceGeoData19", "GeometryData19", True, int, "Geometry data point 19."),
        ParamFieldInfo("faceGeoData20", "GeometryData20", True, int, "Geometry data point 20."),
        ParamFieldInfo("faceGeoData21", "GeometryData21", True, int, "Geometry data point 21."),
        ParamFieldInfo("faceGeoData22", "GeometryData22", True, int, "Geometry data point 22."),
        ParamFieldInfo("faceGeoData23", "GeometryData23", True, int, "Geometry data point 23."),
        ParamFieldInfo("faceGeoData24", "GeometryData24", True, int, "Geometry data point 24."),
        ParamFieldInfo("faceGeoData25", "GeometryData25", True, int, "Geometry data point 25."),
        ParamFieldInfo("faceGeoData26", "GeometryData26", True, int, "Geometry data point 26."),
        ParamFieldInfo("faceGeoData27", "GeometryData27", True, int, "Geometry data point 27."),
        ParamFieldInfo("faceGeoData28", "GeometryData28", True, int, "Geometry data point 28."),
        ParamFieldInfo("faceGeoData29", "GeometryData29", True, int, "Geometry data point 29."),
        ParamFieldInfo("faceGeoData30", "GeometryData30", True, int, "Geometry data point 30."),
        ParamFieldInfo("faceGeoData31", "GeometryData31", True, int, "Geometry data point 31."),
        ParamFieldInfo("faceGeoData32", "GeometryData32", True, int, "Geometry data point 32."),
        ParamFieldInfo("faceGeoData33", "GeometryData33", True, int, "Geometry data point 33."),
        ParamFieldInfo("faceGeoData34", "GeometryData34", True, int, "Geometry data point 34."),
        ParamFieldInfo("faceGeoData35", "GeometryData35", True, int, "Geometry data point 35."),
        ParamFieldInfo("faceGeoData36", "GeometryData36", True, int, "Geometry data point 36."),
        ParamFieldInfo("faceGeoData37", "GeometryData37", True, int, "Geometry data point 37."),
        ParamFieldInfo("faceGeoData38", "GeometryData38", True, int, "Geometry data point 38."),
        ParamFieldInfo("faceGeoData39", "GeometryData39", True, int, "Geometry data point 39."),
        ParamFieldInfo("faceGeoData40", "GeometryData40", True, int, "Geometry data point 40."),
        ParamFieldInfo("faceGeoData41", "GeometryData41", True, int, "Geometry data point 41."),
        ParamFieldInfo("faceGeoData42", "GeometryData42", True, int, "Geometry data point 42."),
        ParamFieldInfo("faceGeoData43", "GeometryData43", True, int, "Geometry data point 43."),
        ParamFieldInfo("faceGeoData44", "GeometryData44", True, int, "Geometry data point 44."),
        ParamFieldInfo("faceGeoData45", "GeometryData45", True, int, "Geometry data point 45."),
        ParamFieldInfo("faceGeoData46", "GeometryData46", True, int, "Geometry data point 46."),
        ParamFieldInfo("faceGeoData47", "GeometryData47", True, int, "Geometry data point 47."),
        ParamFieldInfo("faceGeoData48", "GeometryData48", True, int, "Geometry data point 48."),
        ParamFieldInfo("faceGeoData49", "GeometryData49", True, int, "Geometry data point 49."),
        ParamFieldInfo("faceTexData00", "TextureData00", True, int, "Texture data point 0."),
        ParamFieldInfo("faceTexData01", "TextureData01", True, int, "Texture data point 1."),
        ParamFieldInfo("faceTexData02", "TextureData02", True, int, "Texture data point 2."),
        ParamFieldInfo("faceTexData03", "TextureData03", True, int, "Texture data point 3."),
        ParamFieldInfo("faceTexData04", "TextureData04", True, int, "Texture data point 4."),
        ParamFieldInfo("faceTexData05", "TextureData05", True, int, "Texture data point 5."),
        ParamFieldInfo("faceTexData06", "TextureData06", True, int, "Texture data point 6."),
        ParamFieldInfo("faceTexData07", "TextureData07", True, int, "Texture data point 7."),
        ParamFieldInfo("faceTexData08", "TextureData08", True, int, "Texture data point 8."),
        ParamFieldInfo("faceTexData09", "TextureData09", True, int, "Texture data point 9."),
        ParamFieldInfo("faceTexData10", "TextureData10", True, int, "Texture data point 10."),
        ParamFieldInfo("faceTexData11", "TextureData11", True, int, "Texture data point 11."),
        ParamFieldInfo("faceTexData12", "TextureData12", True, int, "Texture data point 12."),
        ParamFieldInfo("faceTexData13", "TextureData13", True, int, "Texture data point 13."),
        ParamFieldInfo("faceTexData14", "TextureData14", True, int, "Texture data point 14."),
        ParamFieldInfo("faceTexData15", "TextureData15", True, int, "Texture data point 15."),
        ParamFieldInfo("faceTexData16", "TextureData16", True, int, "Texture data point 16."),
        ParamFieldInfo("faceTexData17", "TextureData17", True, int, "Texture data point 17."),
        ParamFieldInfo("faceTexData18", "TextureData18", True, int, "Texture data point 18."),
        ParamFieldInfo("faceTexData19", "TextureData19", True, int, "Texture data point 19."),
        ParamFieldInfo("faceTexData20", "TextureData20", True, int, "Texture data point 20."),
        ParamFieldInfo("faceTexData21", "TextureData21", True, int, "Texture data point 21."),
        ParamFieldInfo("faceTexData22", "TextureData22", True, int, "Texture data point 22."),
        ParamFieldInfo("faceTexData23", "TextureData23", True, int, "Texture data point 23."),
        ParamFieldInfo("faceTexData24", "TextureData24", True, int, "Texture data point 24."),
        ParamFieldInfo("faceTexData25", "TextureData25", True, int, "Texture data point 25."),
        ParamFieldInfo("faceTexData26", "TextureData26", True, int, "Texture data point 26."),
        ParamFieldInfo("faceTexData27", "TextureData27", True, int, "Texture data point 27."),
        ParamFieldInfo("faceTexData28", "TextureData28", True, int, "Texture data point 28."),
        ParamFieldInfo("faceTexData29", "TextureData29", True, int, "Texture data point 29."),
        ParamFieldInfo("faceTexData30", "TextureData30", True, int, "Texture data point 30."),
        ParamFieldInfo("faceTexData31", "TextureData31", True, int, "Texture data point 31."),
        ParamFieldInfo("faceTexData32", "TextureData32", True, int, "Texture data point 32."),
        ParamFieldInfo("faceTexData33", "TextureData33", True, int, "Texture data point 33."),
        ParamFieldInfo("faceTexData34", "TextureData34", True, int, "Texture data point 34."),
        ParamFieldInfo("faceTexData35", "TextureData35", True, int, "Texture data point 35."),
        ParamFieldInfo("faceTexData36", "TextureData36", True, int, "Texture data point 36."),
        ParamFieldInfo("faceTexData37", "TextureData37", True, int, "Texture data point 37."),
        ParamFieldInfo("faceTexData38", "TextureData38", True, int, "Texture data point 38."),
        ParamFieldInfo("faceTexData39", "TextureData39", True, int, "Texture data point 39."),
        ParamFieldInfo("faceTexData40", "TextureData40", True, int, "Texture data point 40."),
        ParamFieldInfo("faceTexData41", "TextureData41", True, int, "Texture data point 41."),
        ParamFieldInfo("faceTexData42", "TextureData42", True, int, "Texture data point 42."),
        ParamFieldInfo("faceTexData43", "TextureData43", True, int, "Texture data point 43."),
        ParamFieldInfo("faceTexData44", "TextureData44", True, int, "Texture data point 44."),
        ParamFieldInfo("faceTexData45", "TextureData45", True, int, "Texture data point 45."),
        ParamFieldInfo("faceTexData46", "TextureData46", True, int, "Texture data point 46."),
        ParamFieldInfo("faceTexData47", "TextureData47", True, int, "Texture data point 47."),
        ParamFieldInfo("faceTexData48", "TextureData48", True, int, "Texture data point 48."),
        ParamFieldInfo("faceTexData49", "TextureData49", True, int, "Texture data point 49."),
        ParamFieldInfo("hairStyle", "HairStyle", True, FACE_PARAM_HAIRSTYLE_TYPE, "Hairstyle of face."),
        ParamFieldInfo("hairColor_Base ", "BaseHairColor", True, FACE_PARAM_HAIRCOLOR_TYPE, "Base hair color of face."),
        ParamFieldInfo("hairColor_R ", "HairColorRed", True, int, "Red channel of hair color (0 to 255)."),
        ParamFieldInfo("hairColor_G ", "HairColorGreen", True, int, "Greenchannel of hair color (0 to 255)."),
        ParamFieldInfo("hairColor_B ", "HairColorBlue", True, int, "Blue channel of hair color (0 to 255)."),
        ParamFieldInfo("eyeColor_R", "EyeColorRed", True, int, "Red channel of eye color (0 to 255)."),
        ParamFieldInfo("eyeColor_G", "EyeColorGreen", True, int, "Green channel of eye color (0 to 255)."),
        ParamFieldInfo("eyeColor_B", "EyeColorBlue", True, int, "Blue channel of eye color (0 to 255)."),
        ParamFieldInfo("pad[20]", "Pad1", False, pad_field(20), "Null padding."),
    ],
}
