__all__ = [
    "GAME_AREA_PARAM_ST",
    "GAME_MAP_PARAM_ST",
    "LOCK_CAM_PARAM_ST",
    "TALK_PARAM_ST",
    "FACE_GEN_PARAM_ST",
    "FACE_PARAM_ST",
    "FACE_RANGE_PARAM_ST",
    "MENU_PARAM_COLOR_TABLE_ST",
    "MENUPROPERTY_LAYOUT",
    "MENUPROPERTY_SPEC",
    "MENU_VALUE_TABLE_SPEC",
    "MOVE_PARAM_ST",
    "HIT_MTRL_PARAM_ST",
    "ACTIONBUTTON_PARAM_ST",
    "CHARMAKEMENU_LISTITEM_PARAM_ST",
    "CHARMAKEMENUTOP_PARAM_ST",
    "DECAL_PARAM_ST",
    "RETURN_POINT_PARAM_ST",
    "WIND_PARAM_ST",
]

from soulstruct.game_types import *
from soulstruct.params.bloodborne.enums import *
from soulstruct.params.core import FieldDisplayInfo, pad_field

GAME_AREA_PARAM_ST = {
    "paramdef_name": "GAME_AREA_PARAM_ST",
    "file_name": "GameAreaParam",
    "nickname": "Bosses",
    "fields": [
        FieldDisplayInfo(
            "bonusSoul_single",
            "SingleplayerSoulReward",
            True,
            int,
            "Souls awarded (after delay) when boss is defeated with no summons.",
        ),
        FieldDisplayInfo(
            "bonusSoul_multi",
            "MultiplayerSoulReward",
            True,
            int,
            "Souls awarded to each player (after delay) when boss is defeated with summons.",
        ),
        FieldDisplayInfo(
            "humanityPointCountFlagIdTop",
            "FirstHumanityFlag",
            True,
            Flag,
            "First flag for recording number of humanity drops awarded in boss's area.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint1",
            "HumanityDropPoint1",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for first Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint2",
            "HumanityDropPoint2",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for second Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint3",
            "HumanityDropPoint3",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for third Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint4",
            "HumanityDropPoint4",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for fourth Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint5",
            "HumanityDropPoint5",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for fifth Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint6",
            "HumanityDropPoint6",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for sixth Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint7",
            "HumanityDropPoint7",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for seventh Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint8",
            "HumanityDropPoint8",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for eighth Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint9",
            "HumanityDropPoint9",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for ninth Humanity.",
        ),
        FieldDisplayInfo(
            "humanityDropPoint10",
            "HumanityDropPoint10",
            True,
            int,
            "Number of 'points' needed from killing enemies in the boss area for final Humanity.",
        ),
    ],
}


GAME_MAP_PARAM_ST = {
    "paramdef_name": "GAME_MAP_PARAM_ST",
    "file_name": "GameMapParam",
    "nickname": "GameMaps",
    "fields": [
        FieldDisplayInfo("settingNo_timeSlotA", "TimeSlotA", True, int, ""),
        FieldDisplayInfo("settingNo_timeSlotB", "TimeSlotB", True, int, ""),
        FieldDisplayInfo("settingNo_timeSlotC", "TimeSlotC", True, int, ""),
        FieldDisplayInfo("settingNo_timeSlotD", "TimeSlotD", True, int, ""),
    ],
}


LOCK_CAM_PARAM_ST = {
    "paramdef_name": "LOCK_CAM_PARAM_ST",
    "file_name": "LockCamParam",
    "nickname": "Cameras",
    "fields": [
        FieldDisplayInfo(
            "camDistTarget",
            "CameraDistanceFromTarget",
            True,
            float,
            "Distance maintained from target by camera in meters. (Default value is 4.)",
        ),
        FieldDisplayInfo(
            "rotRangeMinX",
            "MinRotationElevation",
            True,
            float,
            "Minimum angle of elevation (X-axis rotation) permitted for camera.",
        ),
        FieldDisplayInfo(
            "lockRotXShiftRatio",
            "LockElevationShiftRatio",
            True,
            float,
            "'Lock X-rotation shift ratio (0.0 to 1.0).' Unclear effect. Default value is 0.6.",
        ),
        FieldDisplayInfo(
            "chrOrgOffset_Y",
            "CharacterVerticalOffset",
            True,
            float,
            "Vertical offset of camera target from character's base. Default value is 1.42.",
        ),
        FieldDisplayInfo(
            "chrLockRangeMaxRadius",
            "MaxDistanceFromCharacter",
            True,
            float,
            "Maximum distance ('radius') of camera from character in meters. Default value is 15; only other "
            "value used is 7.",
        ),
        FieldDisplayInfo(
            "camFovY",
            "VerticalFieldOfView",
            True,
            float,
            "Vertical field of view of camera in degrees. Default value is 43. Never goes above 48 (Lost Izalith).",
        ),
        FieldDisplayInfo("chrLockRangeMaxRadius_forD", "CharacterLockRangeMaxRadiusD", True, float, ""),
        FieldDisplayInfo("chrLockRangeMaxRadius_forPD", "CharacterLockRangeMaxRadiusPD", True, float, ""),
    ],
}

TALK_PARAM_ST = {
    "paramdef_name": "TALK_PARAM_ST",
    "file_name": "TalkParam",
    "nickname": "Dialogue",
    "fields": [
        FieldDisplayInfo("msgId", "SubtitleText", True, Subtitle, "Text ID for dialogue subtitle."),
        FieldDisplayInfo("voiceId", "VoiceSound", True, VoiceSound, "Sound ID (voice) for dialogue."),
        FieldDisplayInfo("spEffectId0", "SpecialEffectID0", True, int, ""),
        FieldDisplayInfo("motionId0", "AnimationID0", True, int, ""),
        FieldDisplayInfo("spEffectId1", "SpecialEffectID1", True, int, ""),
        FieldDisplayInfo("motionId1", "AnimationID1", True, int, ""),
        FieldDisplayInfo("spEffectId2", "SpecialEffectID2", True, int, ""),
        FieldDisplayInfo("motionId2", "AnimationID2", True, int, ""),
        FieldDisplayInfo("spEffectId3", "SpecialEffectID3", True, int, ""),
        FieldDisplayInfo("motionId3", "AnimationID3", True, int, ""),
        FieldDisplayInfo("spEffectId4", "SpecialEffectID4", True, int, ""),
        FieldDisplayInfo("motionId4", "AnimationID4", True, int, ""),
        FieldDisplayInfo("spEffectId5", "SpecialEffectID5", True, int, ""),
        FieldDisplayInfo("motionId5", "AnimationID5", True, int, ""),
        FieldDisplayInfo(
            "returnPos",
            "ReturnConversation",
            False,
            DialogueParam,
            "Conversation ID to use instead if the player has 'returned' to this conversation. Used exactly once "
            "for one line by the Crestfallen Warrior, so presumably works, but probably not useful.",
        ),
        FieldDisplayInfo(
            "reactionId",
            "ReactionConversation",
            False,
            DialogueParam,
            "Conversation ID to use as 'reaction'. Always -1.",
        ),
        FieldDisplayInfo(
            "eventId",
            "EventFlag",
            False,
            Flag,
            "Flag that is enabled when conversation plays (I assume). Used exactly once, for the same Crestfallen "
            "Warrior line that uses the ReturnConversation field.",
        ),
    ],
}

FACE_GEN_PARAM_ST = {
    "paramdef_name": "FACE_GEN_PARAM_ST",
    "file_name": "FaceGenParam",
    "nickname": "FaceGeneratos",
    "fields": [
        FieldDisplayInfo("faceGeoData00", "GeometryData00", True, int, "Geometry data point 0."),
        FieldDisplayInfo("faceGeoData01", "GeometryData01", True, int, "Geometry data point 1."),
        FieldDisplayInfo("faceGeoData02", "GeometryData02", True, int, "Geometry data point 2."),
        FieldDisplayInfo("faceGeoData03", "GeometryData03", True, int, "Geometry data point 3."),
        FieldDisplayInfo("faceGeoData04", "GeometryData04", True, int, "Geometry data point 4."),
        FieldDisplayInfo("faceGeoData05", "GeometryData05", True, int, "Geometry data point 5."),
        FieldDisplayInfo("faceGeoData06", "GeometryData06", True, int, "Geometry data point 6."),
        FieldDisplayInfo("faceGeoData07", "GeometryData07", True, int, "Geometry data point 7."),
        FieldDisplayInfo("faceGeoData08", "GeometryData08", True, int, "Geometry data point 8."),
        FieldDisplayInfo("faceGeoData09", "GeometryData09", True, int, "Geometry data point 9."),
        FieldDisplayInfo("faceGeoData10", "GeometryData10", True, int, "Geometry data point 10."),
        FieldDisplayInfo("faceGeoData11", "GeometryData11", True, int, "Geometry data point 11."),
        FieldDisplayInfo("faceGeoData12", "GeometryData12", True, int, "Geometry data point 12."),
        FieldDisplayInfo("faceGeoData13", "GeometryData13", True, int, "Geometry data point 13."),
        FieldDisplayInfo("faceGeoData14", "GeometryData14", True, int, "Geometry data point 14."),
        FieldDisplayInfo("faceGeoData15", "GeometryData15", True, int, "Geometry data point 15."),
        FieldDisplayInfo("faceGeoData16", "GeometryData16", True, int, "Geometry data point 16."),
        FieldDisplayInfo("faceGeoData17", "GeometryData17", True, int, "Geometry data point 17."),
        FieldDisplayInfo("faceGeoData18", "GeometryData18", True, int, "Geometry data point 18."),
        FieldDisplayInfo("faceGeoData19", "GeometryData19", True, int, "Geometry data point 19."),
        FieldDisplayInfo("faceGeoData20", "GeometryData20", True, int, "Geometry data point 20."),
        FieldDisplayInfo("faceGeoData21", "GeometryData21", True, int, "Geometry data point 21."),
        FieldDisplayInfo("faceGeoData22", "GeometryData22", True, int, "Geometry data point 22."),
        FieldDisplayInfo("faceGeoData23", "GeometryData23", True, int, "Geometry data point 23."),
        FieldDisplayInfo("faceGeoData24", "GeometryData24", True, int, "Geometry data point 24."),
        FieldDisplayInfo("faceGeoData25", "GeometryData25", True, int, "Geometry data point 25."),
        FieldDisplayInfo("faceGeoData26", "GeometryData26", True, int, "Geometry data point 26."),
        FieldDisplayInfo("faceGeoData27", "GeometryData27", True, int, "Geometry data point 27."),
        FieldDisplayInfo("faceGeoData28", "GeometryData28", True, int, "Geometry data point 28."),
        FieldDisplayInfo("faceGeoData29", "GeometryData29", True, int, "Geometry data point 29."),
        FieldDisplayInfo("faceGeoData30", "GeometryData30", True, int, "Geometry data point 30."),
        FieldDisplayInfo("faceGeoData31", "GeometryData31", True, int, "Geometry data point 31."),
        FieldDisplayInfo("faceGeoData32", "GeometryData32", True, int, "Geometry data point 32."),
        FieldDisplayInfo("faceGeoData33", "GeometryData33", True, int, "Geometry data point 33."),
        FieldDisplayInfo("faceGeoData34", "GeometryData34", True, int, "Geometry data point 34."),
        FieldDisplayInfo("faceGeoData35", "GeometryData35", True, int, "Geometry data point 35."),
        FieldDisplayInfo("faceGeoData36", "GeometryData36", True, int, "Geometry data point 36."),
        FieldDisplayInfo("faceGeoData37", "GeometryData37", True, int, "Geometry data point 37."),
        FieldDisplayInfo("faceGeoData38", "GeometryData38", True, int, "Geometry data point 38."),
        FieldDisplayInfo("faceGeoData39", "GeometryData39", True, int, "Geometry data point 39."),
        FieldDisplayInfo("faceGeoData40", "GeometryData40", True, int, "Geometry data point 40."),
        FieldDisplayInfo("faceGeoData41", "GeometryData41", True, int, "Geometry data point 41."),
        FieldDisplayInfo("faceGeoData42", "GeometryData42", True, int, "Geometry data point 42."),
        FieldDisplayInfo("faceGeoData43", "GeometryData43", True, int, "Geometry data point 43."),
        FieldDisplayInfo("faceGeoData44", "GeometryData44", True, int, "Geometry data point 44."),
        FieldDisplayInfo("faceGeoData45", "GeometryData45", True, int, "Geometry data point 45."),
        FieldDisplayInfo("faceGeoData46", "GeometryData46", True, int, "Geometry data point 46."),
        FieldDisplayInfo("faceGeoData47", "GeometryData47", True, int, "Geometry data point 47."),
        FieldDisplayInfo("faceGeoData48", "GeometryData48", True, int, "Geometry data point 48."),
        FieldDisplayInfo("faceGeoData49", "GeometryData49", True, int, "Geometry data point 49."),
        FieldDisplayInfo("faceTexData00", "TextureData00", True, int, "Texture data point 0."),
        FieldDisplayInfo("faceTexData01", "TextureData01", True, int, "Texture data point 1."),
        FieldDisplayInfo("faceTexData02", "TextureData02", True, int, "Texture data point 2."),
        FieldDisplayInfo("faceTexData03", "TextureData03", True, int, "Texture data point 3."),
        FieldDisplayInfo("faceTexData04", "TextureData04", True, int, "Texture data point 4."),
        FieldDisplayInfo("faceTexData05", "TextureData05", True, int, "Texture data point 5."),
        FieldDisplayInfo("faceTexData06", "TextureData06", True, int, "Texture data point 6."),
        FieldDisplayInfo("faceTexData07", "TextureData07", True, int, "Texture data point 7."),
        FieldDisplayInfo("faceTexData08", "TextureData08", True, int, "Texture data point 8."),
        FieldDisplayInfo("faceTexData09", "TextureData09", True, int, "Texture data point 9."),
        FieldDisplayInfo("faceTexData10", "TextureData10", True, int, "Texture data point 10."),
        FieldDisplayInfo("faceTexData11", "TextureData11", True, int, "Texture data point 11."),
        FieldDisplayInfo("faceTexData12", "TextureData12", True, int, "Texture data point 12."),
        FieldDisplayInfo("faceTexData13", "TextureData13", True, int, "Texture data point 13."),
        FieldDisplayInfo("faceTexData14", "TextureData14", True, int, "Texture data point 14."),
        FieldDisplayInfo("faceTexData15", "TextureData15", True, int, "Texture data point 15."),
        FieldDisplayInfo("faceTexData16", "TextureData16", True, int, "Texture data point 16."),
        FieldDisplayInfo("faceTexData17", "TextureData17", True, int, "Texture data point 17."),
        FieldDisplayInfo("faceTexData18", "TextureData18", True, int, "Texture data point 18."),
        FieldDisplayInfo("faceTexData19", "TextureData19", True, int, "Texture data point 19."),
        FieldDisplayInfo("faceTexData20", "TextureData20", True, int, "Texture data point 20."),
        FieldDisplayInfo("faceTexData21", "TextureData21", True, int, "Texture data point 21."),
        FieldDisplayInfo("faceTexData22", "TextureData22", True, int, "Texture data point 22."),
        FieldDisplayInfo("faceTexData23", "TextureData23", True, int, "Texture data point 23."),
        FieldDisplayInfo("faceTexData24", "TextureData24", True, int, "Texture data point 24."),
        FieldDisplayInfo("faceTexData25", "TextureData25", True, int, "Texture data point 25."),
        FieldDisplayInfo("faceTexData26", "TextureData26", True, int, "Texture data point 26."),
        FieldDisplayInfo("faceTexData27", "TextureData27", True, int, "Texture data point 27."),
        FieldDisplayInfo("faceTexData28", "TextureData28", True, int, "Texture data point 28."),
        FieldDisplayInfo("faceTexData29", "TextureData29", True, int, "Texture data point 29."),
        FieldDisplayInfo("faceTexData30", "TextureData30", True, int, "Texture data point 30."),
        FieldDisplayInfo("faceTexData31", "TextureData31", True, int, "Texture data point 31."),
        FieldDisplayInfo("faceTexData32", "TextureData32", True, int, "Texture data point 32."),
        FieldDisplayInfo("faceTexData33", "TextureData33", True, int, "Texture data point 33."),
        FieldDisplayInfo("faceTexData34", "TextureData34", True, int, "Texture data point 34."),
        FieldDisplayInfo("faceTexData35", "TextureData35", True, int, "Texture data point 35."),
        FieldDisplayInfo("faceTexData36", "TextureData36", True, int, "Texture data point 36."),
        FieldDisplayInfo("faceTexData37", "TextureData37", True, int, "Texture data point 37."),
        FieldDisplayInfo("faceTexData38", "TextureData38", True, int, "Texture data point 38."),
        FieldDisplayInfo("faceTexData39", "TextureData39", True, int, "Texture data point 39."),
        FieldDisplayInfo("faceTexData40", "TextureData40", True, int, "Texture data point 40."),
        FieldDisplayInfo("faceTexData41", "TextureData41", True, int, "Texture data point 41."),
        FieldDisplayInfo("faceTexData42", "TextureData42", True, int, "Texture data point 42."),
        FieldDisplayInfo("faceTexData43", "TextureData43", True, int, "Texture data point 43."),
        FieldDisplayInfo("faceTexData44", "TextureData44", True, int, "Texture data point 44."),
        FieldDisplayInfo("faceTexData45", "TextureData45", True, int, "Texture data point 45."),
        FieldDisplayInfo("faceTexData46", "TextureData46", True, int, "Texture data point 46."),
        FieldDisplayInfo("faceTexData47", "TextureData47", True, int, "Texture data point 47."),
        FieldDisplayInfo("faceTexData48", "TextureData48", True, int, "Texture data point 48."),
        FieldDisplayInfo("faceTexData49", "TextureData49", True, int, "Texture data point 49."),
        FieldDisplayInfo("facePartsId", "FacePartsID", True, int, ""),
        FieldDisplayInfo("skinColor_R ", "SkinColorRed", True, int, ""),
        FieldDisplayInfo("skinColor_G ", "SkinColorGreen", True, int, ""),
        FieldDisplayInfo("skinColor_B ", "SkinColorBlue", True, int, ""),
        FieldDisplayInfo("hairPartsId", "HairPartsID", True, int, ""),
        FieldDisplayInfo("hairColor_R ", "HairColorRed", True, int, ""),
        FieldDisplayInfo("hairColor_G ", "HairColorGreen", True, int, ""),
        FieldDisplayInfo("hairColor_B ", "HairColorBlue", True, int, ""),
        FieldDisplayInfo("eyeLPartsId", "LeftEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeLColor_R", "LeftEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeLColor_G", "LeftEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeLColor_B", "LeftEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyeRPartsId", "RightEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeRColor_R", "RightEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeRColor_G", "RightEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeRColor_B", "RightEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyebrowPartsId", "EyebrowsPartsID", True, int, ""),
        FieldDisplayInfo("eyebrowColor_R ", "EyebrowsColorRed", True, int, ""),
        FieldDisplayInfo("eyebrowColor_G ", "EyebrowsColorGreen", True, int, ""),
        FieldDisplayInfo("eyebrowColor_B ", "EyebrowsColorBlue", True, int, ""),
        FieldDisplayInfo("beardPartsId", "BeardPartsID", True, int, ""),
        FieldDisplayInfo("beardColor_R ", "BeardColorRed", True, int, ""),
        FieldDisplayInfo("beardColor_G ", "BeardColorGreen", True, int, ""),
        FieldDisplayInfo("beardColor_B ", "BeardColorBlue", True, int, ""),
        FieldDisplayInfo("accessoriesPartsId", "AccessoriesPartsID", True, int, ""),
        FieldDisplayInfo("accessoriesColor_R ", "AccessoriesColorRed", True, int, ""),
        FieldDisplayInfo("accessoriesColor_G ", "AccessoriesColorGreen", True, int, ""),
        FieldDisplayInfo("accessoriesColor_B ", "AccessoriesColorBlue", True, int, ""),
        FieldDisplayInfo("decalPartsId", "DecalPartsID", True, int, ""),
        FieldDisplayInfo("decalColor_R ", "DecalColorRed", True, int, ""),
        FieldDisplayInfo("decalColor_G ", "DecalColorGreen", True, int, ""),
        FieldDisplayInfo("decalColor_B ", "DecalColorBlue", True, int, ""),
        FieldDisplayInfo("decalPosX", "DecalPositionX", True, int, ""),
        FieldDisplayInfo("decalPosY", "DecalPositionY", True, int, ""),
        FieldDisplayInfo("decalAngle", "DecalAngle", True, int, ""),
        FieldDisplayInfo("decalScale", "DecalScale", True, int, ""),
    ],
}


FACE_PARAM_ST = {
    "paramdef_name": "FACE_PARAM_ST",
    "file_name": "FaceParam",
    "nickname": "Faces",
    "fields": [
        FieldDisplayInfo("facePartsId", "FacePartsID", True, int, ""),
        FieldDisplayInfo("skinColor_R ", "SkinColorRed", True, int, ""),
        FieldDisplayInfo("skinColor_G ", "SkinColorGreen", True, int, ""),
        FieldDisplayInfo("skinColor_B ", "SkinColorBlue", True, int, ""),
        FieldDisplayInfo("hairPartsId", "", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("hairPartsId", "HairPartsID", True, int, ""),
        FieldDisplayInfo("hairColor_R ", "HairColorRed", True, int, ""),
        FieldDisplayInfo("hairColor_G ", "HairColorGreen", True, int, ""),
        FieldDisplayInfo("hairColor_B ", "HairColorBlue", True, int, ""),
        FieldDisplayInfo("eyeLPartsId", "LeftEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeLColor_R", "LeftEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeLColor_G", "LeftEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeLColor_B", "LeftEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyeRPartsId", "RightEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeRColor_R", "RightEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeRColor_G", "RightEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeRColor_B", "RightEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyebrowPartsId", "EyebrowsPartsID", True, int, ""),
        FieldDisplayInfo("eyebrowColor_R ", "EyebrowsColorRed", True, int, ""),
        FieldDisplayInfo("eyebrowColor_G ", "EyebrowsColorGreen", True, int, ""),
        FieldDisplayInfo("eyebrowColor_B ", "EyebrowsColorBlue", True, int, ""),
        FieldDisplayInfo("eyelashPartsId", "EyelashesPartsID", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_R ", "EyelashesColorRed", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_G ", "EyelashesColorGreen", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_B ", "EyelashesColorBlue", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("beardPartsId", "BeardPartsID", True, int, ""),
        FieldDisplayInfo("beardColor_R ", "BeardColorRed", True, int, ""),
        FieldDisplayInfo("beardColor_G ", "BeardColorGreen", True, int, ""),
        FieldDisplayInfo("beardColor_B ", "BeardColorBlue", True, int, ""),
        FieldDisplayInfo("accessoriesPartsId", "AccessoriesPartsID", True, int, ""),
        FieldDisplayInfo("accessoriesColor_R ", "AccessoriesColorRed", True, int, ""),
        FieldDisplayInfo("accessoriesColor_G ", "AccessoriesColorGreen", True, int, ""),
        FieldDisplayInfo("accessoriesColor_B ", "AccessoriesColorBlue", True, int, ""),
        FieldDisplayInfo("decalPartsId", "DecalPartsID", True, int, ""),
        FieldDisplayInfo("decalColor_R ", "DecalColorRed", True, int, ""),
        FieldDisplayInfo("decalColor_G ", "DecalColorGreen", True, int, ""),
        FieldDisplayInfo("decalColor_B ", "DecalColorBlue", True, int, ""),
        FieldDisplayInfo("decalPosX", "DecalPositionX", True, int, ""),
        FieldDisplayInfo("decalPosY", "DecalPositionY", True, int, ""),
        FieldDisplayInfo("decalAngle", "DecalAngle", True, int, ""),
        FieldDisplayInfo("decalScale", "DecalScale", True, int, ""),
        FieldDisplayInfo("chrBodyScaleHead", "HeadScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleBreast", "BreastScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleAbdomen", "AbdomenScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleArm", "ArmScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleLeg", "LegScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("age", "Age", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("gender", "Gender", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("caricatureGeometry", "CaricatureGeometry", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("caricatureTexture", "CaricatureTexture", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("faceGeoData00", "GeometryData00", True, int, "Geometry data point 0."),
        FieldDisplayInfo("faceGeoData01", "GeometryData01", True, int, "Geometry data point 1."),
        FieldDisplayInfo("faceGeoData02", "GeometryData02", True, int, "Geometry data point 2."),
        FieldDisplayInfo("faceGeoData03", "GeometryData03", True, int, "Geometry data point 3."),
        FieldDisplayInfo("faceGeoData04", "GeometryData04", True, int, "Geometry data point 4."),
        FieldDisplayInfo("faceGeoData05", "GeometryData05", True, int, "Geometry data point 5."),
        FieldDisplayInfo("faceGeoData06", "GeometryData06", True, int, "Geometry data point 6."),
        FieldDisplayInfo("faceGeoData07", "GeometryData07", True, int, "Geometry data point 7."),
        FieldDisplayInfo("faceGeoData08", "GeometryData08", True, int, "Geometry data point 8."),
        FieldDisplayInfo("faceGeoData09", "GeometryData09", True, int, "Geometry data point 9."),
        FieldDisplayInfo("faceGeoData10", "GeometryData10", True, int, "Geometry data point 10."),
        FieldDisplayInfo("faceGeoData11", "GeometryData11", True, int, "Geometry data point 11."),
        FieldDisplayInfo("faceGeoData12", "GeometryData12", True, int, "Geometry data point 12."),
        FieldDisplayInfo("faceGeoData13", "GeometryData13", True, int, "Geometry data point 13."),
        FieldDisplayInfo("faceGeoData14", "GeometryData14", True, int, "Geometry data point 14."),
        FieldDisplayInfo("faceGeoData15", "GeometryData15", True, int, "Geometry data point 15."),
        FieldDisplayInfo("faceGeoData16", "GeometryData16", True, int, "Geometry data point 16."),
        FieldDisplayInfo("faceGeoData17", "GeometryData17", True, int, "Geometry data point 17."),
        FieldDisplayInfo("faceGeoData18", "GeometryData18", True, int, "Geometry data point 18."),
        FieldDisplayInfo("faceGeoData19", "GeometryData19", True, int, "Geometry data point 19."),
        FieldDisplayInfo("faceGeoData20", "GeometryData20", True, int, "Geometry data point 20."),
        FieldDisplayInfo("faceGeoData21", "GeometryData21", True, int, "Geometry data point 21."),
        FieldDisplayInfo("faceGeoData22", "GeometryData22", True, int, "Geometry data point 22."),
        FieldDisplayInfo("faceGeoData23", "GeometryData23", True, int, "Geometry data point 23."),
        FieldDisplayInfo("faceGeoData24", "GeometryData24", True, int, "Geometry data point 24."),
        FieldDisplayInfo("faceGeoData25", "GeometryData25", True, int, "Geometry data point 25."),
        FieldDisplayInfo("faceGeoData26", "GeometryData26", True, int, "Geometry data point 26."),
        FieldDisplayInfo("faceGeoData27", "GeometryData27", True, int, "Geometry data point 27."),
        FieldDisplayInfo("faceGeoData28", "GeometryData28", True, int, "Geometry data point 28."),
        FieldDisplayInfo("faceGeoData29", "GeometryData29", True, int, "Geometry data point 29."),
        FieldDisplayInfo("faceGeoData30", "GeometryData30", True, int, "Geometry data point 30."),
        FieldDisplayInfo("faceGeoData31", "GeometryData31", True, int, "Geometry data point 31."),
        FieldDisplayInfo("faceGeoData32", "GeometryData32", True, int, "Geometry data point 32."),
        FieldDisplayInfo("faceGeoData33", "GeometryData33", True, int, "Geometry data point 33."),
        FieldDisplayInfo("faceGeoData34", "GeometryData34", True, int, "Geometry data point 34."),
        FieldDisplayInfo("faceGeoData35", "GeometryData35", True, int, "Geometry data point 35."),
        FieldDisplayInfo("faceGeoData36", "GeometryData36", True, int, "Geometry data point 36."),
        FieldDisplayInfo("faceGeoData37", "GeometryData37", True, int, "Geometry data point 37."),
        FieldDisplayInfo("faceGeoData38", "GeometryData38", True, int, "Geometry data point 38."),
        FieldDisplayInfo("faceGeoData39", "GeometryData39", True, int, "Geometry data point 39."),
        FieldDisplayInfo("faceGeoData40", "GeometryData40", True, int, "Geometry data point 40."),
        FieldDisplayInfo("faceGeoData41", "GeometryData41", True, int, "Geometry data point 41."),
        FieldDisplayInfo("faceGeoData42", "GeometryData42", True, int, "Geometry data point 42."),
        FieldDisplayInfo("faceGeoData43", "GeometryData43", True, int, "Geometry data point 43."),
        FieldDisplayInfo("faceGeoData44", "GeometryData44", True, int, "Geometry data point 44."),
        FieldDisplayInfo("faceGeoData45", "GeometryData45", True, int, "Geometry data point 45."),
        FieldDisplayInfo("faceGeoData46", "GeometryData46", True, int, "Geometry data point 46."),
        FieldDisplayInfo("faceGeoData47", "GeometryData47", True, int, "Geometry data point 47."),
        FieldDisplayInfo("faceGeoData48", "GeometryData48", True, int, "Geometry data point 48."),
        FieldDisplayInfo("faceGeoData49", "GeometryData49", True, int, "Geometry data point 49."),
        FieldDisplayInfo("faceGeoData50", "GeometryData50", True, int, "Geometry data point 50."),
        FieldDisplayInfo("faceGeoData51", "GeometryData51", True, int, "Geometry data point 51."),
        FieldDisplayInfo("faceGeoData52", "GeometryData52", True, int, "Geometry data point 52."),
        FieldDisplayInfo("faceGeoData53", "GeometryData53", True, int, "Geometry data point 53."),
        FieldDisplayInfo("faceGeoData54", "GeometryData54", True, int, "Geometry data point 54."),
        FieldDisplayInfo("faceGeoData55", "GeometryData55", True, int, "Geometry data point 55."),
        FieldDisplayInfo("faceGeoData56", "GeometryData56", True, int, "Geometry data point 56."),
        FieldDisplayInfo("faceGeoData57", "GeometryData57", True, int, "Geometry data point 57."),
        FieldDisplayInfo("faceGeoData58", "GeometryData58", True, int, "Geometry data point 58."),
        FieldDisplayInfo("faceGeoData59", "GeometryData59", True, int, "Geometry data point 59."),
        FieldDisplayInfo("faceGeoData60", "GeometryData60", True, int, "Geometry data point 60."),
        FieldDisplayInfo("faceTexData00", "TextureData00", True, int, "Texture data point 0."),
        FieldDisplayInfo("faceTexData01", "TextureData01", True, int, "Texture data point 1."),
        FieldDisplayInfo("faceTexData02", "TextureData02", True, int, "Texture data point 2."),
        FieldDisplayInfo("faceTexData03", "TextureData03", True, int, "Texture data point 3."),
        FieldDisplayInfo("faceTexData04", "TextureData04", True, int, "Texture data point 4."),
        FieldDisplayInfo("faceTexData05", "TextureData05", True, int, "Texture data point 5."),
        FieldDisplayInfo("faceTexData06", "TextureData06", True, int, "Texture data point 6."),
        FieldDisplayInfo("faceTexData07", "TextureData07", True, int, "Texture data point 7."),
        FieldDisplayInfo("faceTexData08", "TextureData08", True, int, "Texture data point 8."),
        FieldDisplayInfo("faceTexData09", "TextureData09", True, int, "Texture data point 9."),
        FieldDisplayInfo("faceTexData10", "TextureData10", True, int, "Texture data point 10."),
        FieldDisplayInfo("faceTexData11", "TextureData11", True, int, "Texture data point 11."),
        FieldDisplayInfo("faceTexData12", "TextureData12", True, int, "Texture data point 12."),
        FieldDisplayInfo("faceTexData13", "TextureData13", True, int, "Texture data point 13."),
        FieldDisplayInfo("faceTexData14", "TextureData14", True, int, "Texture data point 14."),
        FieldDisplayInfo("faceTexData15", "TextureData15", True, int, "Texture data point 15."),
        FieldDisplayInfo("faceTexData16", "TextureData16", True, int, "Texture data point 16."),
        FieldDisplayInfo("faceTexData17", "TextureData17", True, int, "Texture data point 17."),
        FieldDisplayInfo("faceTexData18", "TextureData18", True, int, "Texture data point 18."),
        FieldDisplayInfo("faceTexData19", "TextureData19", True, int, "Texture data point 19."),
        FieldDisplayInfo("faceTexData20", "TextureData20", True, int, "Texture data point 20."),
        FieldDisplayInfo("faceTexData21", "TextureData21", True, int, "Texture data point 21."),
        FieldDisplayInfo("faceTexData22", "TextureData22", True, int, "Texture data point 22."),
        FieldDisplayInfo("faceTexData23", "TextureData23", True, int, "Texture data point 23."),
        FieldDisplayInfo("faceTexData24", "TextureData24", True, int, "Texture data point 24."),
        FieldDisplayInfo("faceTexData25", "TextureData25", True, int, "Texture data point 25."),
        FieldDisplayInfo("faceTexData26", "TextureData26", True, int, "Texture data point 26."),
        FieldDisplayInfo("faceTexData27", "TextureData27", True, int, "Texture data point 27."),
        FieldDisplayInfo("faceTexData28", "TextureData28", True, int, "Texture data point 28."),
        FieldDisplayInfo("faceTexData29", "TextureData29", True, int, "Texture data point 29."),
        FieldDisplayInfo("faceTexData30", "TextureData30", True, int, "Texture data point 30."),
        FieldDisplayInfo("faceTexData31", "TextureData31", True, int, "Texture data point 31."),
        FieldDisplayInfo("faceTexData32", "TextureData32", True, int, "Texture data point 32."),
        FieldDisplayInfo("faceTexData33", "TextureData33", True, int, "Texture data point 33."),
        FieldDisplayInfo("faceTexData34", "TextureData34", True, int, "Texture data point 34."),
        FieldDisplayInfo("faceTexData35", "TextureData35", True, int, "Texture data point 35."),
        FieldDisplayInfo("faceGeoAsymData00", "GeoAsymData00", True, int, "Geometry asym data point 0."),
        FieldDisplayInfo("faceGeoAsymData01", "GeoAsymData01", True, int, "Geometry asym data point 1."),
        FieldDisplayInfo("faceGeoAsymData02", "GeoAsymData02", True, int, "Geometry asym data point 2."),
        FieldDisplayInfo("faceGeoAsymData03", "GeoAsymData03", True, int, "Geometry asym data point 3."),
        FieldDisplayInfo("faceGeoAsymData04", "GeoAsymData04", True, int, "Geometry asym data point 4."),
        FieldDisplayInfo("faceGeoAsymData05", "GeoAsymData05", True, int, "Geometry asym data point 5."),
        FieldDisplayInfo("faceGeoAsymData06", "GeoAsymData06", True, int, "Geometry asym data point 6."),
        FieldDisplayInfo("faceGeoAsymData07", "GeoAsymData07", True, int, "Geometry asym data point 7."),
        FieldDisplayInfo("faceGeoAsymData08", "GeoAsymData08", True, int, "Geometry asym data point 8."),
        FieldDisplayInfo("faceGeoAsymData09", "GeoAsymData09", True, int, "Geometry asym data point 9."),
        FieldDisplayInfo("faceGeoAsymData10", "GeoAsymData10", True, int, "Geometry asym data point 10."),
        FieldDisplayInfo("faceGeoAsymData11", "GeoAsymData11", True, int, "Geometry asym data point 11."),
        FieldDisplayInfo("faceGeoAsymData12", "GeoAsymData12", True, int, "Geometry asym data point 12."),
        FieldDisplayInfo("faceGeoAsymData13", "GeoAsymData13", True, int, "Geometry asym data point 13."),
        FieldDisplayInfo("faceGeoAsymData14", "GeoAsymData14", True, int, "Geometry asym data point 14."),
        FieldDisplayInfo("faceGeoAsymData15", "GeoAsymData15", True, int, "Geometry asym data point 15."),
        FieldDisplayInfo("faceGeoAsymData16", "GeoAsymData16", True, int, "Geometry asym data point 16."),
        FieldDisplayInfo("faceGeoAsymData17", "GeoAsymData17", True, int, "Geometry asym data point 17."),
        FieldDisplayInfo("faceGeoAsymData18", "GeoAsymData18", True, int, "Geometry asym data point 18."),
        FieldDisplayInfo("faceGeoAsymData19", "GeoAsymData19", True, int, "Geometry asym data point 19."),
        FieldDisplayInfo("faceGeoAsymData20", "GeoAsymData20", True, int, "Geometry asym data point 20."),
        FieldDisplayInfo("faceGeoAsymData21", "GeoAsymData21", True, int, "Geometry asym data point 21."),
        FieldDisplayInfo("faceGeoAsymData22", "GeoAsymData22", True, int, "Geometry asym data point 22."),
        FieldDisplayInfo("faceGeoAsymData23", "GeoAsymData23", True, int, "Geometry asym data point 23."),
        FieldDisplayInfo("faceGeoAsymData24", "GeoAsymData24", True, int, "Geometry asym data point 24."),
        FieldDisplayInfo("faceGeoAsymData25", "GeoAsymData25", True, int, "Geometry asym data point 25."),
    ],
}


FACE_RANGE_PARAM_ST = {
    "paramdef_name": "FACE_RANGE_PARAM_ST",
    "file_name": "FaceRangeParam",
    "nickname": "FaceRanges",
    "fields": [
        FieldDisplayInfo("facePartsId", "FacePartsID", True, int, ""),
        FieldDisplayInfo("skinColor_R ", "SkinColorRed", True, int, ""),
        FieldDisplayInfo("skinColor_G ", "SkinColorGreen", True, int, ""),
        FieldDisplayInfo("skinColor_B ", "SkinColorBlue", True, int, ""),
        FieldDisplayInfo("hairPartsId", "", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("hairPartsId", "HairPartsID", True, int, ""),
        FieldDisplayInfo("hairColor_R ", "HairColorRed", True, int, ""),
        FieldDisplayInfo("hairColor_G ", "HairColorGreen", True, int, ""),
        FieldDisplayInfo("hairColor_B ", "HairColorBlue", True, int, ""),
        FieldDisplayInfo("eyeLPartsId", "LeftEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeLColor_R", "LeftEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeLColor_G", "LeftEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeLColor_B", "LeftEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyeRPartsId", "RightEyePartsID", True, int, ""),
        FieldDisplayInfo("eyeRColor_R", "RightEyeColorRed", True, int, ""),
        FieldDisplayInfo("eyeRColor_G", "RightEyeColorGreen", True, int, ""),
        FieldDisplayInfo("eyeRColor_B", "RightEyeColorBlue", True, int, ""),
        FieldDisplayInfo("eyebrowPartsId", "EyebrowsPartsID", True, int, ""),
        FieldDisplayInfo("eyebrowColor_R ", "EyebrowsColorRed", True, int, ""),
        FieldDisplayInfo("eyebrowColor_G ", "EyebrowsColorGreen", True, int, ""),
        FieldDisplayInfo("eyebrowColor_B ", "EyebrowsColorBlue", True, int, ""),
        FieldDisplayInfo("eyelashPartsId", "EyelashesPartsID", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_R ", "EyelashesColorRed", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_G ", "EyelashesColorGreen", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("eyelashColor_B ", "EyelashesColorBlue", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("beardPartsId", "BeardPartsID", True, int, ""),
        FieldDisplayInfo("beardColor_R ", "BeardColorRed", True, int, ""),
        FieldDisplayInfo("beardColor_G ", "BeardColorGreen", True, int, ""),
        FieldDisplayInfo("beardColor_B ", "BeardColorBlue", True, int, ""),
        FieldDisplayInfo("accessoriesPartsId", "AccessoriesPartsID", True, int, ""),
        FieldDisplayInfo("accessoriesColor_R ", "AccessoriesColorRed", True, int, ""),
        FieldDisplayInfo("accessoriesColor_G ", "AccessoriesColorGreen", True, int, ""),
        FieldDisplayInfo("accessoriesColor_B ", "AccessoriesColorBlue", True, int, ""),
        FieldDisplayInfo("decalPartsId", "DecalPartsID", True, int, ""),
        FieldDisplayInfo("decalColor_R ", "DecalColorRed", True, int, ""),
        FieldDisplayInfo("decalColor_G ", "DecalColorGreen", True, int, ""),
        FieldDisplayInfo("decalColor_B ", "DecalColorBlue", True, int, ""),
        FieldDisplayInfo("decalPosX", "DecalPositionX", True, int, ""),
        FieldDisplayInfo("decalPosY", "DecalPositionY", True, int, ""),
        FieldDisplayInfo("decalAngle", "DecalAngle", True, int, ""),
        FieldDisplayInfo("decalScale", "DecalScale", True, int, ""),
        FieldDisplayInfo("chrBodyScaleHead", "HeadScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleBreast", "BreastScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleAbdomen", "AbdomenScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleArm", "ArmScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("chrBodyScaleLeg", "LegScale", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("age", "Age", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("gender", "Gender", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("caricatureGeometry", "CaricatureGeometry", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("caricatureTexture", "CaricatureTexture", True, int, ""),  # u8 (u8)
        FieldDisplayInfo("faceGeoData00", "GeometryData00", True, int, "Geometry data point 0."),
        FieldDisplayInfo("faceGeoData01", "GeometryData01", True, int, "Geometry data point 1."),
        FieldDisplayInfo("faceGeoData02", "GeometryData02", True, int, "Geometry data point 2."),
        FieldDisplayInfo("faceGeoData03", "GeometryData03", True, int, "Geometry data point 3."),
        FieldDisplayInfo("faceGeoData04", "GeometryData04", True, int, "Geometry data point 4."),
        FieldDisplayInfo("faceGeoData05", "GeometryData05", True, int, "Geometry data point 5."),
        FieldDisplayInfo("faceGeoData06", "GeometryData06", True, int, "Geometry data point 6."),
        FieldDisplayInfo("faceGeoData07", "GeometryData07", True, int, "Geometry data point 7."),
        FieldDisplayInfo("faceGeoData08", "GeometryData08", True, int, "Geometry data point 8."),
        FieldDisplayInfo("faceGeoData09", "GeometryData09", True, int, "Geometry data point 9."),
        FieldDisplayInfo("faceGeoData10", "GeometryData10", True, int, "Geometry data point 10."),
        FieldDisplayInfo("faceGeoData11", "GeometryData11", True, int, "Geometry data point 11."),
        FieldDisplayInfo("faceGeoData12", "GeometryData12", True, int, "Geometry data point 12."),
        FieldDisplayInfo("faceGeoData13", "GeometryData13", True, int, "Geometry data point 13."),
        FieldDisplayInfo("faceGeoData14", "GeometryData14", True, int, "Geometry data point 14."),
        FieldDisplayInfo("faceGeoData15", "GeometryData15", True, int, "Geometry data point 15."),
        FieldDisplayInfo("faceGeoData16", "GeometryData16", True, int, "Geometry data point 16."),
        FieldDisplayInfo("faceGeoData17", "GeometryData17", True, int, "Geometry data point 17."),
        FieldDisplayInfo("faceGeoData18", "GeometryData18", True, int, "Geometry data point 18."),
        FieldDisplayInfo("faceGeoData19", "GeometryData19", True, int, "Geometry data point 19."),
        FieldDisplayInfo("faceGeoData20", "GeometryData20", True, int, "Geometry data point 20."),
        FieldDisplayInfo("faceGeoData21", "GeometryData21", True, int, "Geometry data point 21."),
        FieldDisplayInfo("faceGeoData22", "GeometryData22", True, int, "Geometry data point 22."),
        FieldDisplayInfo("faceGeoData23", "GeometryData23", True, int, "Geometry data point 23."),
        FieldDisplayInfo("faceGeoData24", "GeometryData24", True, int, "Geometry data point 24."),
        FieldDisplayInfo("faceGeoData25", "GeometryData25", True, int, "Geometry data point 25."),
        FieldDisplayInfo("faceGeoData26", "GeometryData26", True, int, "Geometry data point 26."),
        FieldDisplayInfo("faceGeoData27", "GeometryData27", True, int, "Geometry data point 27."),
        FieldDisplayInfo("faceGeoData28", "GeometryData28", True, int, "Geometry data point 28."),
        FieldDisplayInfo("faceGeoData29", "GeometryData29", True, int, "Geometry data point 29."),
        FieldDisplayInfo("faceGeoData30", "GeometryData30", True, int, "Geometry data point 30."),
        FieldDisplayInfo("faceGeoData31", "GeometryData31", True, int, "Geometry data point 31."),
        FieldDisplayInfo("faceGeoData32", "GeometryData32", True, int, "Geometry data point 32."),
        FieldDisplayInfo("faceGeoData33", "GeometryData33", True, int, "Geometry data point 33."),
        FieldDisplayInfo("faceGeoData34", "GeometryData34", True, int, "Geometry data point 34."),
        FieldDisplayInfo("faceGeoData35", "GeometryData35", True, int, "Geometry data point 35."),
        FieldDisplayInfo("faceGeoData36", "GeometryData36", True, int, "Geometry data point 36."),
        FieldDisplayInfo("faceGeoData37", "GeometryData37", True, int, "Geometry data point 37."),
        FieldDisplayInfo("faceGeoData38", "GeometryData38", True, int, "Geometry data point 38."),
        FieldDisplayInfo("faceGeoData39", "GeometryData39", True, int, "Geometry data point 39."),
        FieldDisplayInfo("faceGeoData40", "GeometryData40", True, int, "Geometry data point 40."),
        FieldDisplayInfo("faceGeoData41", "GeometryData41", True, int, "Geometry data point 41."),
        FieldDisplayInfo("faceGeoData42", "GeometryData42", True, int, "Geometry data point 42."),
        FieldDisplayInfo("faceGeoData43", "GeometryData43", True, int, "Geometry data point 43."),
        FieldDisplayInfo("faceGeoData44", "GeometryData44", True, int, "Geometry data point 44."),
        FieldDisplayInfo("faceGeoData45", "GeometryData45", True, int, "Geometry data point 45."),
        FieldDisplayInfo("faceGeoData46", "GeometryData46", True, int, "Geometry data point 46."),
        FieldDisplayInfo("faceGeoData47", "GeometryData47", True, int, "Geometry data point 47."),
        FieldDisplayInfo("faceGeoData48", "GeometryData48", True, int, "Geometry data point 48."),
        FieldDisplayInfo("faceGeoData49", "GeometryData49", True, int, "Geometry data point 49."),
        FieldDisplayInfo("faceGeoData50", "GeometryData50", True, int, "Geometry data point 50."),
        FieldDisplayInfo("faceGeoData51", "GeometryData51", True, int, "Geometry data point 51."),
        FieldDisplayInfo("faceGeoData52", "GeometryData52", True, int, "Geometry data point 52."),
        FieldDisplayInfo("faceGeoData53", "GeometryData53", True, int, "Geometry data point 53."),
        FieldDisplayInfo("faceGeoData54", "GeometryData54", True, int, "Geometry data point 54."),
        FieldDisplayInfo("faceGeoData55", "GeometryData55", True, int, "Geometry data point 55."),
        FieldDisplayInfo("faceGeoData56", "GeometryData56", True, int, "Geometry data point 56."),
        FieldDisplayInfo("faceGeoData57", "GeometryData57", True, int, "Geometry data point 57."),
        FieldDisplayInfo("faceGeoData58", "GeometryData58", True, int, "Geometry data point 58."),
        FieldDisplayInfo("faceGeoData59", "GeometryData59", True, int, "Geometry data point 59."),
        FieldDisplayInfo("faceGeoData60", "GeometryData60", True, int, "Geometry data point 60."),
        FieldDisplayInfo("faceTexData00", "TextureData00", True, int, "Texture data point 0."),
        FieldDisplayInfo("faceTexData01", "TextureData01", True, int, "Texture data point 1."),
        FieldDisplayInfo("faceTexData02", "TextureData02", True, int, "Texture data point 2."),
        FieldDisplayInfo("faceTexData03", "TextureData03", True, int, "Texture data point 3."),
        FieldDisplayInfo("faceTexData04", "TextureData04", True, int, "Texture data point 4."),
        FieldDisplayInfo("faceTexData05", "TextureData05", True, int, "Texture data point 5."),
        FieldDisplayInfo("faceTexData06", "TextureData06", True, int, "Texture data point 6."),
        FieldDisplayInfo("faceTexData07", "TextureData07", True, int, "Texture data point 7."),
        FieldDisplayInfo("faceTexData08", "TextureData08", True, int, "Texture data point 8."),
        FieldDisplayInfo("faceTexData09", "TextureData09", True, int, "Texture data point 9."),
        FieldDisplayInfo("faceTexData10", "TextureData10", True, int, "Texture data point 10."),
        FieldDisplayInfo("faceTexData11", "TextureData11", True, int, "Texture data point 11."),
        FieldDisplayInfo("faceTexData12", "TextureData12", True, int, "Texture data point 12."),
        FieldDisplayInfo("faceTexData13", "TextureData13", True, int, "Texture data point 13."),
        FieldDisplayInfo("faceTexData14", "TextureData14", True, int, "Texture data point 14."),
        FieldDisplayInfo("faceTexData15", "TextureData15", True, int, "Texture data point 15."),
        FieldDisplayInfo("faceTexData16", "TextureData16", True, int, "Texture data point 16."),
        FieldDisplayInfo("faceTexData17", "TextureData17", True, int, "Texture data point 17."),
        FieldDisplayInfo("faceTexData18", "TextureData18", True, int, "Texture data point 18."),
        FieldDisplayInfo("faceTexData19", "TextureData19", True, int, "Texture data point 19."),
        FieldDisplayInfo("faceTexData20", "TextureData20", True, int, "Texture data point 20."),
        FieldDisplayInfo("faceTexData21", "TextureData21", True, int, "Texture data point 21."),
        FieldDisplayInfo("faceTexData22", "TextureData22", True, int, "Texture data point 22."),
        FieldDisplayInfo("faceTexData23", "TextureData23", True, int, "Texture data point 23."),
        FieldDisplayInfo("faceTexData24", "TextureData24", True, int, "Texture data point 24."),
        FieldDisplayInfo("faceTexData25", "TextureData25", True, int, "Texture data point 25."),
        FieldDisplayInfo("faceTexData26", "TextureData26", True, int, "Texture data point 26."),
        FieldDisplayInfo("faceTexData27", "TextureData27", True, int, "Texture data point 27."),
        FieldDisplayInfo("faceTexData28", "TextureData28", True, int, "Texture data point 28."),
        FieldDisplayInfo("faceTexData29", "TextureData29", True, int, "Texture data point 29."),
        FieldDisplayInfo("faceTexData30", "TextureData30", True, int, "Texture data point 30."),
        FieldDisplayInfo("faceTexData31", "TextureData31", True, int, "Texture data point 31."),
        FieldDisplayInfo("faceTexData32", "TextureData32", True, int, "Texture data point 32."),
        FieldDisplayInfo("faceTexData33", "TextureData33", True, int, "Texture data point 33."),
        FieldDisplayInfo("faceTexData34", "TextureData34", True, int, "Texture data point 34."),
        FieldDisplayInfo("faceTexData35", "TextureData35", True, int, "Texture data point 35."),
    ],
}


HIT_MTRL_PARAM_ST = {
    "paramdef_name": "HIT_MTRL_PARAM_ST",
    "file_name": "HitMtrlParam",
    "nickname": "Terrains",
    "fields": [
        FieldDisplayInfo(
            "aiVolumeRate",
            "SoundRadiusMultiplier",
            True,
            float,
            "Multiplier for foot sound effect radius on this terrain.",
        ),
        FieldDisplayInfo(
            "spEffectIdOnHit0",
            "SpecialEffect1",
            True,
            SpecialEffectParam,
            "Special effect applied to character walking on terrain (first of two).",
        ),
        FieldDisplayInfo(
            "spEffectIdOnHit1",
            "SpecialEffect2",
            True,
            SpecialEffectParam,
            "Special effect applied to character walking on terrain (second of two).",
        ),
        FieldDisplayInfo(
            "footEffectHeightType:2",
            "FootEffectHeightType",
            True,
            HMP_FOOT_EFFECT_HEIGHT_TYPE,
            "Determines the height at which foot impact effects are generated.",
        ),
        FieldDisplayInfo(
            "footEffectDirType:2",
            "FootEffectDirectionType",
            True,
            HMP_FOOT_EFFECT_DIR_TYPE,
            "Determines the direction of foot impact effects.",
        ),
        FieldDisplayInfo(
            "floorHeightType:2",
            "TerrainHeightType",
            True,
            HMP_FLOOR_HEIGHT_TYPE,
            "Determines distance from floor collision at which effects are applied.",
        ),
        FieldDisplayInfo("pad0[3]", "Pad1", False, pad_field(3), "Null padding."),
    ],
}


MENU_PARAM_COLOR_TABLE_ST = {
    "paramdef_name": "MENU_PARAM_COLOR_TABLE_ST",
    "file_name": "MenuColorTableParam",
    "nickname": "MenuColors",
    "fields": [
        FieldDisplayInfo("r", "RedChannel", True, int, "Red value of RGBA color (0-255)."),
        FieldDisplayInfo("g", "GreenChannel", True, int, "Green value of RGBA color (0-255)."),
        FieldDisplayInfo("b", "BlueChannel", True, int, "Blue value of RGBA color (0-255)."),
        FieldDisplayInfo("a", "AlphaChannel", True, int, "Alpha value of RGBA color (0-255). Higher is more opaque."),
    ],
}


MENUPROPERTY_LAYOUT = {
    "paramdef_name": "MENUPROPERTY_LAYOUT",
    "file_name": "MenuPropertyLayoutParam",
    "nickname": "MenuPropertyLayouts",
    "fields": [
        FieldDisplayInfo("LayoutPath[16]", "LayoutPath", True, str, ""),  # TODO: handle str display type
        FieldDisplayInfo("PropertyID", "", True, MENU_PROPERTY_ID, ""),
        FieldDisplayInfo("CaptionTextID", "CaptionTextID", True, int, ""),
        FieldDisplayInfo("HelpTextID", "HelpTextID", True, int, ""),
        FieldDisplayInfo("reserved[4]", "Reserved", False, pad_field(4), ""),

    ],
}


MENUPROPERTY_SPEC = {
    "paramdef_name": "MENUPROPERTY_SPEC",
    "file_name": "MenuPropertySpecParam",
    "nickname": "MenuPropertySpecs",
    "fields": [
        FieldDisplayInfo("CaptionTextID", "CaptionTextID", True, int, ""),
        FieldDisplayInfo("IconID", "IconID", True, int, ""),
        FieldDisplayInfo("RequiredPropertyID", "RequiredPropertyID", True, MENU_PROPERTY_ID, ""),
        FieldDisplayInfo("CompareType", "CompareType", True, MENU_PROPERTY_CMP_TYPE, ""),
        FieldDisplayInfo("FormatType", "FormatType", True, MENU_PROPERTY_FORMAT_TYPE, ""),
        FieldDisplayInfo("AdhocCaption[9]", "AdhocCaption", True, str, ""),
    ],
}


MENU_VALUE_TABLE_SPEC = {
    "paramdef_name": "MENU_VALUE_TABLE_SPEC",
    "file_name": "MenuValueTableSpecParam",
    "nickname": "MenuValueTableSpecs",
    "fields": [
        FieldDisplayInfo("value", "Value", True, float, ""),
        FieldDisplayInfo("textId", "TextID", True, int, ""),
        FieldDisplayInfo("compareType", "CompareType", True, MENU_VALUE_TABLE_CMP_TYPE, ""),
        FieldDisplayInfo("padding[3]", "Pad", False, pad_field(3), ""),
    ],
}


MOVE_PARAM_ST = {
    "paramdef_name": "MOVE_PARAM_ST",
    "file_name": "MoveParam",
    "nickname": "Movement",
    "fields": [
        FieldDisplayInfo("stayId", "StillAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("walkF", "WalkForwardAnimatiom", True, Animation, "Animation ID."),
        FieldDisplayInfo("walkB", "WalkBackwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("walkL", "StrafeLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("walkR", "StrafeRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashF", "RunForwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashB", "RunBackwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashL", "StrafeRunLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashR", "StrafeRunRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("superDash", "SprintForwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("escapeF", "RollForwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("escapeB", "RollBackwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("escapeL", "RollLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("escapeR", "RollRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("turnL", "TurnLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("trunR", "TurnRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("largeTurnL", "LargeTurnLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("largeTurnR", "LargeTurnRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("stepMove", "BackstepAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyStay", "HoverAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyWalkF", "FlyForwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyWalkFL", "FlyForwardLeftAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyWalkFR", "FlyForwardRightAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyWalkFL2", "FlyForwardLeft2Animation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyWalkFR2", "FlyForwardRight2Animation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyDashF", "FlyForwardFastAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyDashFL", "FlyForwardLeftFastAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyDashFR", "FlyForwardRightFastAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyDashFL2", "FlyForwardLeftFast2Animation", True, Animation, "Animation ID."),
        FieldDisplayInfo("flyDashFR2", "FlyForwardRightFast2Animation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashEscapeF", "RunningRollForwardAnimation", True, Animation, "Animation ID."),
        FieldDisplayInfo("dashEscapeB", "RunningRollBackwardAnimation", True, Animation, "Animation ID. (Never used.)"),
        FieldDisplayInfo("dashEscapeL", "RunningRollLeftAnimation", True, Animation, "Animation ID. (Never used.)"),
        FieldDisplayInfo("dashEscapeR", "RunningRollRightAnimation", True, Animation, "Animation ID. (Never used.)"),
        FieldDisplayInfo(
            "analogMoveParamId",
            "AnalogMovement",
            True,
            int,
            "Movement settings for analog stick version of movement. (Unknown enum.)",
        ),
        FieldDisplayInfo("turnNoAnimAngle", "TurnNoAnimationAngle", True, int, ""),
        FieldDisplayInfo("turn45Angle", "Turn45DegreeAngle", True, int, ""),
        FieldDisplayInfo("turn90Angle", "Turn90DegreeAngle", True, int, ""),
        FieldDisplayInfo("turnWaitNoAnimAngle", "TurnWaitNoAnimationAngle", True, int, ""),
    ],
}


ACTIONBUTTON_PARAM_ST = {
    "paramdef_name": "ACTIONBUTTON_PARAM_ST",
    "file_name": "ActionButtonParam",
    "nickname": "ActionButtons",
    "fields": [
        FieldDisplayInfo("regionType", "", True, ACTION_BUTTON_REGION_TYPE, ""),
        FieldDisplayInfo("padding1[3]", "", False, pad_field(3), ""),
        FieldDisplayInfo("dummyPoly1", "", True, int, ""),
        FieldDisplayInfo("dummyPoly2", "", True, int, ""),
        FieldDisplayInfo("radius", "", True, float, ""),
        FieldDisplayInfo("angle", "", True, int, ""),
        FieldDisplayInfo("depth", "", True, float, ""),
        FieldDisplayInfo("width", "", True, float, ""),
        FieldDisplayInfo("height", "", True, float, ""),
        FieldDisplayInfo("baseHeightOffset", "", True, float, ""),
        FieldDisplayInfo("angleCheckType", "", True, int, ""),
        FieldDisplayInfo("padding2[3]", "", False, pad_field(3), ""),
        FieldDisplayInfo("allowAngle", "", True, int, ""),
        FieldDisplayInfo("textBoxType", "", True, int, ""),
        FieldDisplayInfo("padding3[3]", "", False, pad_field(3), ""),
        FieldDisplayInfo("textId", "", True, int, ""),
        FieldDisplayInfo("invalidFlag", "", True, int, ""),
        FieldDisplayInfo("grayoutFlag", "", True, int, ""),
        FieldDisplayInfo("priority", "", True, int, ""),
        FieldDisplayInfo("execInvalidTime", "", True, float, ""),
        FieldDisplayInfo("execButtonCircle", "", True, int, ""),
        FieldDisplayInfo("padding4[3]", "", False, pad_field(3), ""),
    ],
}


CHARMAKEMENU_LISTITEM_PARAM_ST = {
    "paramdef_name": "CHARMAKEMENU_LISTITEM_PARAM_ST",
    "file_name": "CharMakeMenuListItemParam",
    "nickname": "CharacterCreationMenuItems",
    "fields": [
        FieldDisplayInfo("Value", "Value", True, int, ""),
        FieldDisplayInfo("CaptionID", "CaptionID", True, int, ""),
        FieldDisplayInfo("IconID", "IconID", True, int, ""),
        FieldDisplayInfo("reserved[7]", "Reserved", False, pad_field(7), ""),
    ],
}


CHARMAKEMENUTOP_PARAM_ST = {
    "paramdef_name": "CHARMAKEMENUTOP_PARAM_ST",
    "file_name": "CharMakeMenuTopParam",
    "nickname": "CharacterCreationMenuTop",
    "fields": [
        FieldDisplayInfo("CommandID", "CommandID", True, CHARMAKEMENU_CMD_TYPE, ""),
        FieldDisplayInfo("CaptionID", "CaptionID", True, int, ""),
        FieldDisplayInfo("FaceParamID", "FaceParamID", True, FACE_PARAM, ""),
        FieldDisplayInfo("TableID", "TableID", True, int, ""),
        FieldDisplayInfo("ViewCondition", "ViewCondition", True, CHARMAKEMENU_VIEW_CONDITION, ""),
        FieldDisplayInfo("PreviewMode", "PreviewMode", True, CHARMAKEMENU_PREVIEW_MODE, ""),
        FieldDisplayInfo("reserved[11]", "", False, pad_field(11), ""),
    ],
}


DECAL_PARAM_ST = {
    "paramdef_name": "DECAL_PARAM_ST",
    "file_name": "DecalParam",
    "nickname": "DecalsCharacterCreationMenuTop",
    "fields": [
        FieldDisplayInfo("textureId", "TextureID", True, int, ""),
        FieldDisplayInfo("dmypolyId", "ModelPoint", True, int, ""),
        FieldDisplayInfo("pitchAngle", "PitchAngle", True, float, ""),
        FieldDisplayInfo("yawAngle", "YawAngle", True, float, ""),
        FieldDisplayInfo("nearDistance", "NearDistance", True, float, ""),
        FieldDisplayInfo("farDistance", "FarDistance", True, float, ""),
        FieldDisplayInfo("nearSize", "NearSize", True, float, ""),
        FieldDisplayInfo("farSize", "FarSize", True, float, ""),
        FieldDisplayInfo("maskSpeffectId", "MaskSpecialEffectID", True, int, ""),
        FieldDisplayInfo("randomVariationNum:4", "RandomVariationCount", True, int, ""),
        FieldDisplayInfo("replaceTextureId_byMaterial:1", "ReplaceTextureIDWithMaterial", True, bool, ""),
        FieldDisplayInfo("dmypolyCategory:2", "ModelPointCategory", True, int, ""),
        FieldDisplayInfo("decalShapeType:4", "DecalShapeType", True, int, ""),
        FieldDisplayInfo("useDeferredDecal:1", "UseDeferredDecal", True, bool, ""),
        FieldDisplayInfo("usePaintDecal:1", "UsePaintDecal", True, bool, ""),
        FieldDisplayInfo("targetAttackChr:1", "TargetAttackingChr", True, bool, ""),
        FieldDisplayInfo("targetDamageChr:1", "TargetDamagedChr", True, bool, ""),
        FieldDisplayInfo("targetOtherChr:1", "TargetOtherChr", True, bool, ""),
        FieldDisplayInfo("targetMapObj:1", "TargetMapObject", True, bool, ""),
        FieldDisplayInfo("usePom:1", "UsePom", True, bool, ""),
        FieldDisplayInfo("randomSizeMin", "RandomSizeMin", True, int, ""),
        FieldDisplayInfo("randomSizeMax", "RandomSizeMax", True, int, ""),
        FieldDisplayInfo("randomRollMin", "RandomRollMin", True, float, ""),
        FieldDisplayInfo("randomRollMax", "RandomRollMax", True, float, ""),
        FieldDisplayInfo("randomPitchMin", "RandomPitchMin", True, float, ""),
        FieldDisplayInfo("randomPitchMax", "RandomPitchMax", True, float, ""),
        FieldDisplayInfo("randomYawMin", "RandomYawMin", True, float, ""),
        FieldDisplayInfo("randomYawMax", "RandomYawMax", True, float, ""),
        FieldDisplayInfo("pomHightScale", "PomHeightScale", True, float, ""),
        FieldDisplayInfo("pomSampleMin", "PomSampleMin", True, int, ""),
        FieldDisplayInfo("pomSampleMax", "PomSampleMax", True, int, ""),
        FieldDisplayInfo("pad_00[14]", "Pad", False, pad_field(14), ""),
    ],
}


RETURN_POINT_PARAM_ST = {
    "paramdef_name": "RETURN_POINT_PARAM_ST",
    "file_name": "ReturnPointParam",
    "nickname": "ReturnPoints",
    "fields": [
        FieldDisplayInfo("areaNo", "Area", True, int, ""),
        FieldDisplayInfo("blockNo", "Block", True, int, ""),
        FieldDisplayInfo("returnPointEntityId", "ReturnPointEntityID", True, int, ""),
        FieldDisplayInfo("returnAnimId", "ReturnAnimationID", True, int, ""),
        FieldDisplayInfo("isRegistDeadReturn", "IsRegistDeadReturn", True, RETURN_POINT_TYPE_YES_NO, ""),  # TODO: bool?
        FieldDisplayInfo("warpChairNo", "WarpChair", True, int, ""),
        FieldDisplayInfo("pad1[18]", "Pad", False, pad_field(18), ""),
    ],
}


WIND_PARAM_ST = {
    "paramdef_name": "WIND_PARAM_ST",
    "file_name": "WindParam",
    "nickname": "Wind",
    "fields": [
        FieldDisplayInfo("commonCapsuleBeginDmyId", "CommonCapsuleBeginModelPoint", True, int, ""),
        FieldDisplayInfo("commonCapsuleEndDmyId", "CommonCapsuleEndModelPoint", True, int, ""),
        FieldDisplayInfo("commonCapsuleRadius", "CommonCapsuleRadius", True, float, ""),
        FieldDisplayInfo("commonReserve[120]", "CommonReserve", False, pad_field(120), ""),
        FieldDisplayInfo("sfxWindEnable:1", "EnableWindVFX", True, bool, ""),
        FieldDisplayInfo("sfxIgnorePlayerSfx:1", "IgnorePlayerVFX", True, bool, ""),
        FieldDisplayInfo("sfxIsCollision:1", "EnableVFXCollision", True, bool, ""),
        FieldDisplayInfo("sfxPad_0[3]", "Pad", False, pad_field(3), ""),
        FieldDisplayInfo("sfxDirPitchMin", "VFXDirectionMinimumPitch", True, float, ""),
        FieldDisplayInfo("sfxDirPitchMax", "VFXDirectionMaximumPitch", True, float, ""),
        FieldDisplayInfo("sfxDirYawMin", "VFXDirectionMinimumYaw", True, float, ""),
        FieldDisplayInfo("sfxDirYawMax", "VFXDirectionMaximumYaw", True, float, ""),
        FieldDisplayInfo("sfxCycleMin", "VFXMinimumCycle", True, float, ""),
        FieldDisplayInfo("sfxCycleMax", "VFXMaximumCycle", True, float, ""),
        FieldDisplayInfo("sfxSpeedMin", "VFXMinimumSpeed", True, float, ""),
        FieldDisplayInfo("sfxSpeedMax", "VFXMaximumSpeed", True, float, ""),
        FieldDisplayInfo("sfxMaximumDrag", "VFXMaximumDrag", True, float, ""),
        FieldDisplayInfo("sfxReserve[88]", "VFXReserve", False, pad_field(88), ""),
        FieldDisplayInfo("clothWindEnable:1", "EnableClothWind", True, bool, ""),
        FieldDisplayInfo("clothVertexWind:1", "ClothVertexWind", True, bool, ""),
        FieldDisplayInfo("clothPad_0[3]", "ClothPad", False, pad_field(3), ""),
        FieldDisplayInfo("clothDirPitchMin", "ClothDirectionMinimumPitch", True, float, ""),
        FieldDisplayInfo("clothDirPitchMax", "ClothDirectionMaximumPitch", True, float, ""),
        FieldDisplayInfo("clothDirYawMin", "ClothDirectionMinimumYaw", True, float, ""),
        FieldDisplayInfo("clothDirYawMax", "ClothDirectionMaximumYaw", True, float, ""),
        FieldDisplayInfo("clothCycleMin", "ClothMinimumCycle", True, float, ""),
        FieldDisplayInfo("clothCycleMax", "ClothMaximumCycle", True, float, ""),
        FieldDisplayInfo("clothSpeedMin", "ClothMinimumSpeed", True, float, ""),
        FieldDisplayInfo("clothSpeedMax", "ClothMaximumSpeed", True, float, ""),
        FieldDisplayInfo("clothMaximumDrag", "ClothMaximumDrag", True, float, ""),
        FieldDisplayInfo("clothReserve[88]", "ClothReserve", False, pad_field(88), ""),
    ],
}
