import soulstruct.emevd.game_types as gt

class COMMON:
    file_name = 'common'

class COMMON_FUNC:
    file_name = 'common_func'


HIGH_WALL_OF_LOTHRIC = gt.Map(30, 0)
LOTHRIC_CASTLE = CONSUMED_KINGS_GARDEN = gt.Map(30, 1)
UNDEAD_SETTLEMENT = gt.Map(31, 0)
ARCHDRAGON_PEAK = gt.Map(32, 0)
ROAD_OF_SACRIFICES = FARRON_KEEP = gt.Map(33, 0)
GRAND_ARCHIVES = gt.Map(34, 1)
CATHEDRAL_OF_THE_DEEP = gt.Map(35, 0)
IRITHYLL = IRITHYLL_OF_THE_BOREAL_VALLEY = ANOR_LONDO = gt.Map(37, 0)
CATACOMBS_OF_CARTHUS = SMOULDERING_LAKE = DEMON_RUINS = gt.Map(38, 0)
IRITHYLL_DUNGEON = PROFANED_CAPITAL = gt.Map(39, 0)
CEMETERY_OF_ASH = FIRELINK_SHRINE = UNTENDED_GRAVES = gt.Map(40, 0)
KILN_OF_THE_FIRST_FLAME = gt.Map(41, 0)
PAINTED_WORLD_OF_ARIANDEL = gt.Map(45, 0)
ARENA_GRAND_ROOF = gt.Map(46, 0)
ARENA_KILN_OF_FLAME = gt.Map(47, 0)
DREG_HEAP = gt.Map(50, 0)
RINGED_CITY = gt.Map(51, 0)
ARENA_DRAGON_RUINS = gt.Map(53, 0)
ARENA_ROUND_PLAZA = gt.Map(54, 0)

ALL_MAPS = [COMMON, COMMON_FUNC, HIGH_WALL_OF_LOTHRIC, LOTHRIC_CASTLE, UNDEAD_SETTLEMENT, ARCHDRAGON_PEAK, FARRON_KEEP,
            GRAND_ARCHIVES, CATHEDRAL_OF_THE_DEEP, IRITHYLL, CATACOMBS_OF_CARTHUS, IRITHYLL_DUNGEON, FIRELINK_SHRINE,
            KILN_OF_THE_FIRST_FLAME, PAINTED_WORLD_OF_ARIANDEL, DREG_HEAP, RINGED_CITY, ARENA_GRAND_ROOF,
            ARENA_KILN_OF_FLAME, ARENA_DRAGON_RUINS, ARENA_ROUND_PLAZA]

MAP_NAMES = {
    (30, 0): "HIGH_WALL_OF_LOTHRIC",
    (30, 1): "LOTHRIC_CASTLE",
    (31, 0): "UNDEAD_SETTLEMENT",
    (32, 0): "ARCHDRAGON_PEAK",
    (33, 0): "FARRON_KEEP",
    (34, 1): "GRAND_ARCHIVES",
    (35, 0): "CATHEDRAL_OF_THE_DEEP",
    (37, 0): "IRITHYLL",
    (38, 0): "CATACOMBS_OF_CARTHUS",
    (39, 0): "IRITHYLL_DUNGEON",
    (40, 0): "FIRELINK_SHRINE",
    (41, 0): "KILN_OF_THE_FIRST_FLAME",
    (45, 0): "PAINTED_WORLD_OF_ARIANDEL",
    (50, 0): "DREG_HEAP",
    (51, 0): "RINGED_CITY",
    (46, 0): "ARENA_GRAND_ROOF",
    (47, 0): "ARENA_KILN_OF_FLAME",
    (53, 0): "ARENA_DRAGON_RUINS",
    (54, 0): "ARENA_ROUND_PLAZA",
}


class FLAG(gt.Flag):
    pass


class CHR(gt.Character):
    LorianWithoutLothric = 3410832
    LorianWithLothric = 3410830
    Lothric = 3410831


class TEXT(gt.Text):
    LorianName = 905250
    LothicName = 905251


class SOUND(gt.IntEnum):
    BossDeath = 777777777


EVENT_NAMES = {
    13415830: "StartTwinPrincesBossFight",
    13415841: "MoveLothricToLorian",
    13410832: "TwinPrincesDeath",
}