from typing import TYPE_CHECKING
from soulstruct.emevd.shared.tests import *
if TYPE_CHECKING:
    from soulstruct.emevd.game_types import *


# Boolean constants.
HOST = ...
CLIENT = ...
IN_OWN_WORLD = ...

def ActionButtonInRegion(action_button_id: int, region: RegionInt): ...
def IsAttackedWithDamageType(attacked_entity: CharacterInt, attacking_character: CharacterInt, damage_type): ...
def CharacterDrawGroupActive(character: CharacterInt): ...
def CharacterDrawGroupInactive(character: CharacterInt): ...
