
COMMANDS = {
    'chr': {
        1: {
            0: ['ChangeGeneralAnim', ('anim_id', 'layer_index', 'blend', 'is_loop')],
            1: ['ChangeUpperBodyAnim', ()],
            2: ['ChangeStayAnim', ()],
            3: ['ChangeGeneralAnimCategorized', ('anim_category', 'anim_id', 'layer_index', 'blend', 'is_loop')],
            4: ['ChangeUpperBodyAnimCategorized', ()],
            5: ['ChangeGeneralAnimAdditiveCategorized', ()],
            6: ['ChangeUpperBodyAnimAdditiveCategorized', ()],
            7: ['ChangeGeneralAnimCategorizedMatchPlaybackTime', ()],
            8: ['ChangeUpperBodyAnimCategorizedMatchPlaybackTime', ()],
            9: ['SetAnimIDOffset', ()],
            10: ['SetAdditiveBlendAnimation', ()],
            11: ['SetAdditiveBlendAnimationSlotted', ()],
            12: ['ChangeBlendAnimationCategorized', ()],
            13: ['ChangeUpperAndLowerBodySyncedAnimCategorized', ()],
            100: ['SwitchActiveActionState', ()],
            101: ['SwitchMotion', ()],
            102: ['SetThrowAttackTypePossible', ()],
            103: ['SetThrowDefenseTypePossible', ()],
            104: ['SwitchEquippedWeapon', ()],
            105: ['SetReadyForAtkFinish', ()],
            106: ['SetEquipmentChangeable', ()],
            107: ['SetUnableToDrop', ()],
            108: ['IssueMessageIDToEvents', ()],
            109: ['SetAttackType', ()],
            110: ['SetNoStaminaRecover', ()],
            112: ['SetAIBusyDoingAction', ()],
            113: ['BowTurn', ()],
            114: ['SetIsHoldingBow', ()],
            115: ['SwitchSpecificRangeMode', ()],
            116: ['SwitchSpecialMotion', ()],
            117: ['SetIsWeaponChanging', ()],
            118: ['SetIsItemInUse', ()],
            119: ['SetIsItemAnimPlaying', ()],
            120: ['RemoveBinoculars', ()],
            121: ['SetIsMagicInUse', ()],
            122: ['IsHeadTurnPossible', ()],
            123: ['ChangeHoveringState', ()],
            124: ['ChangeToSpecialStay', ()],
            125: ['OpenMenuWhenUsingItem', ()],
            126: ['OpenMenuWhenUsingMagic', ()],
            127: ['BlowDamageTurn', ()],
            128: ['SetDeathStay', ()],
            129: ['CloseMenuWhenUsingItem', ()],
            130: ['CloseMenuWhenUsingMagic', ()],
            131: ['AdditionNoTurning', ()],
            132: ['WhiffPossibility', ()],
            133: ['ChangeFlightStatus', ()],
            134: ['SetStatsNotMetAnimID', ()],
            135: ['ShowFixedYAxisDirectionDisplay', ()],
            136: ['SetLadderActionState', ()],
            137: ['ForceCancelThrowAnim', ()],
            138: ['SetThrowState', ()],
            139: ['LadderSlideStart', ()],
            140: ['SetIsEventActionPossible', ()],
            141: ['RequestThrowAnimInterrupt', ()],
            142: ['SetHandStateOfLadder', ()],
            143: ['SetDamageAnimType', ()],
            144: ['SlideTurn', ()],
            145: ['InterruptAttack', ()],
            146: ['MidairDeathWarp', ()],
            147: ['ClearSlopeInfo', ()],
            148: ['StateInputRecieve', ()],
            149: ['EquipmentChangeableFromMenu', ()],
            200: ['SetVariable', ()],
            151: ['AimAtSelfPosition', ()],
            152: ['StateIdentifier', ()],
            153: ['DoAIReplanningAtCancelTiming', ()],
            154: ['DenyEventAnimPlaybackDemand', ()],
            155: ['InvokeBackstab', ()],
            156: ['WeaponParamReferent', ()],
            157: ['AINotifyAttackType', ()],
            158: ['SetAutoTrapTarget', ()],
            159: ['ClearAutoTrapTarget', ()],
            1000: ['AddHP', ('amount',)],
            1001: ['AddStamina', ('amount',)],
            1100: ['SyncAtInit_Active', ()],
            1101: ['SyncAtInit_Passive', ()],
            2000: ['SetIsTurnAnimInProgress', ()],
            2001: ['CalculateTurnAnimCorrectionFactor', ()],
            2002: ['SetStealthState', ()],
            2003: ['SetMoveMult', ()],
            2004: ['SpEffectAccomodation', ()],
            2005: ['StealthyHighSpeedThrowEffective', ()],
            2006: ['SetTurnSpeed', ()],

            # These are likely only added in Dark Souls 3.
            2007: ['SetCeremonyState', ()],
            2008: ['SetDamageMotionBlendRatio', ()],
            2009: ['SetForceTurnTarget', ()],
            2010: ['InSpecialGuard', ()],
            2011: ['SetWeaponCancelType', ()],
            2012: ['IsPreciseShootingPossible', ()],
            2013: ['ChooseBowAndArrowSlot', ()],
            2014: ['Set4DirectionMovementThreshold', ()],
            2015: ['LockonSystemUnableToTurnAngle', ()],
            2016: ['ReserveArtsPointsUse', ()],
            2017: ['SetArtsPointFEDisplayState', ()],
            2018: ['LockonFixedAngleCancel', ()],

            2019: ['TurnToLockonTargetImmediately', ()],
            2020: ['SetSpecialInterpolation', ()],
            2021: ['LadderSlideDownCancel', ()],
            2022: ['DisableMagicIDSwitching', ()],
            2023: ['DisableToolIDSwitching', ()],

            9000: ['DebugLogOutput', ('text',)],

            # These are likely only added in Dark Souls 3.
            9001: ['Test_SpEffectDelete', ()],
            9002: ['Test_SpEffectTypeSpecifyDelete', ()],
            9100: ['AnimationCancel', ()],
            9101: ['RequestAIReprogramming', ()],
            9102: ['MarkOfGreedyPersonSlipDamageDisable', ()],
            9103: ['ResetInputQueue', ()],
            9104: ['SetIsEventAnim', ()],
            9105: ['AIAttackState', ()],
        },
    },
    'talk': {
        1: {
            0: ['DebugEvent', ('name',)],
            1: ['TalkToPlayer', ()],
            2: ['InvokeEvent', ()],
            3: ['StopAttacking', ()],
            4: ['Attack', ()],
            5: ['RemoveMyAggro', ()],
            6: ['DisplayOneLineHelp', ()],
            7: ['TurnToFacePlayer', ()],
            8: ['ForceEndTalk', ()],
            9: ['ClearTalkProgressData', ()],
            10: ['ShowShopMessage', ()],
            11: ['SetFlagState', ('flag', 'state')],
            12: ['CloseShopMessage', ()],
            13: ['OpenCampMenu', ()],
            14: ['CloseCampMenu', ()],
            15: ['ChangeTeamType', ()],
            16: ['SetDefaultTeamType', ()],
            17: ['OpenGenericDialog', ('unk1', 'text_id', 'unk2', 'unk3', 'display_distance')],
            18: ['ForceCloseGenericDialog', ()],
            19: ['AddTalkListData', ('menu_index', 'menu_text', 'required_flag')],
            20: ['ClearTalkListData', ()],
            21: ['RequestMoviePlayback', ()],
            22: ['OpenRegularShop', ()],
            23: ['OpenRepairShop', ()],
            24: ['OpenEnhanceShop', ()],
            25: ['OpenHumanityMenu', ()],
            26: ['OpenMagicShop', ()],
            27: ['OpenMiracleShop', ()],
            28: ['OpenMagicEquip', ()],
            29: ['OpenMiracleEquip', ()],
            30: ['OpenRepository', ()],
            31: ['OpenSoul', ()],
            32: ['CloseMenu', ()],
            33: ['SetEventFlagRange', ()],
            34: ['OpenDepository', ()],
            35: ['ClearTalkActionState', ()],
            36: ['ClearTalkDisabledState', ()],
            37: ['SetTalkDisableStateMaxDuration', ()],
            38: ['SetUpdateDistance', ('distance',)],
            39: ['ClearPlayerDamageInfo', ()],
            40: ['OfferHumanity', ()],
            41: ['StartWarpMenuInit', ()],
            42: ['StartBonfireAnimLoop', ()],
            43: ['EndBonfireKindleAnimLoop', ()],
            46: ['OpenSellShop', ()],
            47: ['ChangePlayerStats', ()],
            48: ['OpenEquipmentChangeOfPurposeShop', ()],
            49: ['CombineMenuFlagAndEventFlag', ()],
            50: ['RequestSave', ()],
            51: ['ChangeMotionOffsetID', ()],
            52: ['PlayerEquipmentQuantityChange', ()],
            53: ['RequestUnlockTrophy', ()],
            54: ['EnterBonfireEventRange', ()],
            55: ['SetAquittalCostMessageTag', ()],
            56: ['SubtractAcquittalCostFromPlayerSouls', ()],
            57: ['ShuffleRNGSeed', ()],
            58: ['SetRNGSeed', ()],
            59: ['ReplaceTool', ()],
            60: ['BreakCovenantPledge', ()],
            61: ['PlayerRespawn', ()],
            62: ['GiveSpEffectToPlayer', ('speffect',)],
            63: ['DisplayBanner', ('banner_type',)],
            64: ['AddIzalithRankingPoints', ()],
            65: ['OpenItemAcquisitionMenu', ()],
            66: ['AcquireGesture', ()],
            67: ['ForceCloseMenu', ()],
            68: ['SetTalkTime', ()],
            69: ['CollectJustPyromancyFlame', ()],
            70: ['OpenArenaRanking', ()],
            71: ['ReportConversationEndToHavokBehavior', ()],
            76: ['OpenConversationChoicesMenu', ()],
            80: ['StopEventAnimWithoutForcingConversationEnd', ()],
            81: ['OpenCharaMakeMenu', ()],
            82: ['OpenChooseQuantityDialog', ()],
            83: ['ClearQuantityValueOfChooseQuantityDialog', ()],
            100: ['SetWorkValue', ()],
            101: ['UpdatePlayerRespawnPoint', ()],
            102: ['SetMessageTagValue', ()],
            103: ['TurnCharacterToFaceEntity', ()],
            104: ['GetItemFromItemLot', ()],
            105: ['OpenEstusAllotMenu', ()],
            106: ['AddRankingPoints', ()],
            107: ['OpenHollowLevelUpMenu', ()],
        },
    },
}
COMMANDS_BANK_ID_BY_TYPE_NAME = {}
for esd_type, banks in COMMANDS.items():
    for bank, commands in banks.items():
        for f_id, command in commands.items():
            COMMANDS_BANK_ID_BY_TYPE_NAME[esd_type, command[0]] = [bank, f_id]


TEST_FUNCTIONS = {
    'chr': {
        0: ['IsGeneralAnimEnd', ()],
        1: ['IsAttackAnimEnd', ()],
        9: ['AnimIDOffset', ()],
        10: ['AdditiveBlendAnim', ()],
        11: ['AdditiveBlendAnimOfSlot', ()],
        100: ['IsAtkRequest', ('request_type',)],
        101: ['IsAtkReleaseRequest', ()],
        102: ['IsChainAtkRequest', ()],
        103: ['GetAtkDuration', ()],
        104: ['GetWeaponSwitchRequest', ()],
        105: ['GetCommandIDFromEvent', ()],
        106: ['GetAIActionType', ()],
        107: ['GetAIChainActionType', ()],
        108: ['GetChainEvadeRequest', ()],
        109: ['GetWeaponChangeRequest', ()],
        110: ['GetAnimIDFromMoveParam', ()],
        111: ['IsThereAnyAtkRequest', ()],
        112: ['IsThereAnyChainAtkRequest', ()],
        113: ['IsItemUseMenuOpening', ()],
        114: ['IsMagicUseMenuOpening', ()],
        115: ['IsItemUseMenuOpened', ()],
        116: ['IsMagicUseMenuOpened', ()],
        117: ['GetBlendAnimIDFromMoveParam', ()],
        118: ['GetAIChainStepType', ()],
        119: ['GetTransitionToSpecialStayAnimID', ()],
        120: ['GetAIAtkCancelType', ()],
        121: ['GetWeaponCancelType', ()],
        122: ['IsWeaponCancelPossible', ()],
        123: ['GetAIDefenseCancelType', ()],
        124: ['GetAIVersusBackstabCancelType', ()],
        200: ['IsFalling', ()],
        201: ['IsLanding', ()],
        202: ['GetReceivedDamageType', ()],
        203: ['IsActiveActionValid', ()],
        204: ['GetActionEventNumber', ()],
        205: ['IsNormalDmgPassThroughDuringThrow', ()],
        206: ['IsThrowing', ()],
        207: ['GetWeaponSwitchState', ()],
        209: ['IsEquipmentSwitchPossible', ()],
        210: ['IsAnimCancelPossibleInAtkRelease', ()],
        211: ['IsEmergencyStopAnimPlaying', ()],
        212: ['GetLockRangeState', ()],
        213: ['GetLockAngleState', ()],
        214: ['IsAnimCancelPossibleInDamageHit', ()],
        215: ['IsChangeToScrapeAtk', ()],
        216: ['IsChangeToDeflectAtk', ()],
        217: ['IsChangeToAfterParrySuccess', ()],
        218: ['IsChangeFromNormalToBigAtk', ()],
        219: ['GetMovementType', ()],
        220: ['IsLargeAtkComboPossible', ()],
        221: ['IsMapActionPossible', ()],
        222: ['GetReceivedDamageDirection', ()],
        223: ['GetMapActionID', ()],
        224: ['GetFallHeight', ()],
        225: ['GetEquipWeaponCategory', ()],
        226: ['IsHoldingBow', ()],
        227: ['GetMagicAnimType', ()],
        228: ['WasNotLargeAtk', ()],
        229: ['IsBackAtkPossible', ()],
        230: ['IsAfterParryAtkPossible', ()],
        231: ['GetItemAnimType', ()],
        232: ['IsMagicUseable', ()],
        233: ['IsItemUseable', ()],
        234: ['IsPrecisionShoot', ()],
        235: ['IsFireDamaged', ()],
        236: ['GetDamageLevel', ()],
        237: ['GetGuardLevelAction', ()],
        238: ['IsNewLeftHandAtkFromStay', ()],
        239: ['IsParryFromIdle', ()],
        240: ['IsGuardFromIdle', ()],
        241: ['IsNewLeftHandAtkFromAtkCancel', ()],
        242: ['IsParryFromAtkCancel', ()],
        243: ['IsGuardFromAtkCancel', ()],
        244: ['IsTiedUp', ()],
        245: ['IsOutOfAmmo', ()],
        246: ['IsUseCatLanding', ()],
        247: ['GetHoverMoveState', ()],
        248: ['IsTruelyLanding', ()],
        249: ['IsRightHandMagic', ()],
        250: ['IsChangeToSpecialStayAnim', ()],
        251: ['GetSpecialStayAnimID', ()],
        252: ['AcquireSpecialDamageAnimationID', ()],
        253: ['IsRunTurnAnimPlaying', ()],
        254: ['IsGenerateAction', ()],
        255: ['GetSpecialStayCancelAnimID', ()],
        256: ['HasReceivedAnyDamage', ()],
        257: ['GetMoveAnimParamID', ()],
        258: ['GetGuardLevel', ()],
        259: ['IsRequestTurnAnimStart', ()],
        260: ['IsTurningWithAnim', ()],
        261: ['IsFlying', ()],
        262: ['IsAbilityInsufficient', ()],
        263: ['GetEquipWeightRatioForFalling', ()],
        264: ['GetFlightMotionState', ()],
        265: ['GetIsWeakPoint', ()],
        266: ['GetMoveAnimBlendRatio', ()],
        267: ['GetLadderActionState', ()],
        268: ['IsInDisguise', ()],
        269: ['IsCoopWait', ()],
        270: ['IsCoop', ()],
        271: ['IsSpecialTransitionPossible', ()],
        272: ['GetLandingAnimBlendRatio', ()],
        273: ['GetThrowAnimID', ()],
        274: ['DidOpponentDieFromThrow', ()],
        275: ['HasThrowEnded', ()],
        276: ['IsThrowSelfDeath', ()],
        277: ['IsThrowSuccess', ()],
        278: ['GetGuardMotionCategory', ()],
        279: ['IsBeingThrown', ()],
        280: ['IsSelfThrow', ()],
        281: ['IsThrowDeathState', ()],
        282: ['GetNewLockState', ()],
        283: ['IsOnLadder', ()],
        284: ['GetPhysicalAttribute', ()],
        285: ['GetSpecialAttribute', ()],
        286: ['GetSpecialStayDeathAnimID', ()],
        287: ['HasReceivedAnyDamage_AnimEnd', ()],
        288: ['EggGrowth_IsHeadScratch', ()],
        289: ['EggGrowth_IsBecomeEggHead', ()],
        290: ['IsStop', ()],
        291: ['IsSomeoneOnLadder', ()],
        292: ['IsSomeoneUnderLadder', ()],
        293: ['GetLadderHandState', ()],
        294: ['DoesLadderHaveCharacters', ()],
        295: ['IsLadderRightHandStayState', ()],
        296: ['DescendingToFloor', ()],
        297: ['IsInputDirectionMatch', ()],
        298: ['IsSpecialTransition2Possible', ()],
        299: ['IsVersusDivineDamage', ()],
        300: ['IsGeneralAnimCancelPossible', ()],
        301: ['GetEventEzStateFlag', ()],
        302: ['IsLadderEventEnd', ()],
        303: ['IsReachBottomOfLadder', ()],
        304: ['IsReachTopOfLadder', ()],
        305: ['GetStateChangeType', ()],
        306: ['IsOnLastRungOfLadder', ()],
        311: ['GetWeaponDurability', ()],
        312: ['IsWeaponBroken', ()],
        313: ['IsAnimEndBySkillCancel', ()],
        314: ['EggGrowth_IsBecomeEgghead_SecondStage', ()],
        315: ['IsHamariFallDeath', ()],
        316: ['IsClient', ()],
        317: ['IsSlope', ()],
        318: ['IsSwitchState', ()],
        319: ['IsPressUpKey', ()],
        320: ['IsSpecialTurning', ()],
        321: ['GetIntValueForTest', ()],
        322: ['IsObjActInterpolatedMotion', ()],
        323: ['GetObjActTargetDirection', ()],
        324: ['GetObjActRemainingInterpolateTime', ()],
        325: ['IsGap', ()],
        326: ['GetWeaponID', ()],
        327: ['IsMovingLaterally', ()],
        328: ['IsNet', ()],
        329: ['HasBrokenSA', ()],
        330: ['IsEmergencyQuickTurnActivated', ()],
        331: ['IsDoubleChantPossible', ()],
        332: ['IsAnimOver', ()],
        333: ['ObtainedDT', ()],
        334: ['GetBehaviorID', ()],
        335: ['IsTwoHandPossible', ()],
        336: ['IsPartDamageAdditiveBlendInvalid', ()],
        337: ['IsThrowPosRealign', ()],
        338: ['GetBoltLoadingState', ()],
        339: ['IsAnimEnd', ()],
        340: ['IsTwinSwords', ()],

        # These are likely only added in Dark Souls 3.
        341: ['DS3GetTurnAngleForDelayedTurn', ()],
        342: ['DS3GetThrowDefenseCount', ()],
        343: ['DS3IsEmergencyEvasionPossible', ()],
        344: ['DS3HasEnoughArtsPoints', ()],
        345: ['DS3GetEquipWeaponSpecialCategoryNumber', ()],
        346: ['DS3CheckForEventAnimPlaybackRequest', ()],
        347: ['DS3IsFemale', ()],
        348: ['DS3GetDelayTurnAngleDifference', ()],
        349: ['DS3IsDamageMotionOff', ()],
        350: ['DS3HasReachedStatsNeededForWeapon', ()],
        351: ['DS3UpperArmControlOuterAngle', ()],
        352: ['DS3UpperArmControlTopAndBottomAngle', ()],
        353: ['DS3CompleteLadderSlideDown', ()],
        354: ['DS3GetLadderRungCount', ()],
        355: ['DS3GetNumberOfRungsBelowOnLadder', ()],
        356: ['DS3GetBowAndArrowSlot', ()],
        357: ['DS3GetWeaponStorageSpotType', ()],
        358: ['DS3GetStayAnimCategory', ()],
        359: ['DS3GetWeaponSwitchState', ()],
        360: ['DS3IsEquipmentMenuOpen', ()],
        361: ['DS3GetRemainingArrowCount', ()],

        1000: ['GetHP', ()],
        1001: ['GetStamina', ()],
        1002: ['IsGhost', ()],
        1003: ['GetRandomInt', ()],
        1004: ['GetRandomFloat', ()],
        1005: ['IsUnableToDie', ()],
        1006: ['IsResurrectionPossible', ()],
        1007: ['IsCOMPlayer', ()],
        1008: ['GetAITargetAwareState', ()],
        1009: ['IsAIChangeToAwareState', ()],
        1010: ['GetAITargetAwareStatePreviousFrame', ()],
        1100: ['GetTestDamageAnimID', ()],
        1101: ['IsInvincibleDebugMode', ()],
        1102: ['WasGameLaunchedInPGTestMode', ()],
        1103: ['IsTiltingStick', ()],
        1104: ['DS3GetGestureRequestNumber', ()],
        1105: ['DS3IsStayState', ()],
        1106: ['DS3ActionRequest', ()],
        1107: ['DS3ActionCancelRequest', ()],
        1108: ['DS3ActionDuration', ()],
        1109: ['DS3HasActionRequest', ()],
        1110: ['DS3MovementRequest', ()],
        1111: ['DS3MovementRequestDuration', ()],
        1112: ['DS3HasThrowRequest', ()],
        1113: ['DS3IsGuardCancelPossible', ()],
        1114: ['DS3DoesAnimExist', ()],
        1115: ['DS3GetAIMovementType', ()],
        1116: ['DS3GetSpecialEffectID', ()],
        1117: ['DS3IsConversationEnd', ()],
        1118: ['DS3IsLocked', ()],
        1119: ['DS3GetAtkDirection', ()],
        1120: ['DS3GetPartGroup', ()],
        1121: ['DS3GetKnockbackDistance', ()],
        2000: ['DS3IsMoveCancelPossible', ()],
        2002: ['DS3GetSpecialMovementType', ()],
        2003: ['DS3GetGeneralTAEFlag', ()],
        2004: ['DS3IsSwingHitTarget', ()],
        2005: ['DS3GetCeremonyState', ()],
        2006: ['DS3GetSuccessiveGuardCount', ()],
        2007: ['DS3GetMinLuck', ()],
        2008: ['DS3GetAccumulatedLuck', ()],
        2009: ['DS3GetMaxLuck', ()],
        2010: ['DS3GetMaxStamina', ()],
        2011: ['DS3GetGeneralMSBParameter', ()],
        2012: ['DS3IsHitWall', ()],
        2013: ['DS3GetSafetyDirection', ()],
        2014: ['DS3IsInCeremony', ()],
        2015: ['DS3IsDoingCorpseCarryKeyframe', ()],
        2016: ['DS3GetMP', ()],
        2017: ['DS3IsCeremonyComplete', ()],
        2018: ['DS3IsCeremonyInterrupt', ()],
    },
    'talk': {
        0: ['GetWhetherEnemiesAreNearby', ()],
        1: ['GetDistanceToPlayer', ()],
        2: ['HasTalkEnded', ()],
        3: ['CheckSelfDeath', ()],
        4: ['IsPlayerTalkingToMe', ()],
        5: ['IsAttackedBySomeone', ()],
        6: ['GetSelfHP', ()],
        7: ['GetDistanceFromEnemy', ()],
        8: ['GetRelativeAngleBetweenPlayerAndSelf', ()],
        9: ['IsPlayerAttacking', ()],
        10: ['GetRelativeAngleBetweenSelfAndPlayer', ()],
        11: ['IsTalkInProgress', ()],
        12: ['GetTalkInterruptReason', ()],
        13: ['GetShopCondition', ()],
        14: ['GetOneLineHelpStatus', ()],
        15: ['GetFlagState', ('flag',)],
        16: ['IsEquipmentIDObtained', ()],
        17: ['IsEquipmentIDEquipped', ()],
        18: ['IsFightingAlone', ()],
        19: ['IsClientPlayer', ()],
        20: ['IsCampMenuOpen', ()],
        21: ['IsGenericDialogOpen', ()],
        22: ['GetGenericDialogButtonResult', ()],
        23: ['GetTalkListEntryResult', ()],
        24: ['IsMoviePlaying', ()],
        25: ['IsMenuOpen', ('menu_index',)],
        26: ['IsCharacterDisabled', ()],
        27: ['IsPlayerDead', ()],
        28: ['DidYouDoSomethingInTheMenu', ()],
        29: ['GetStatus', ()],
        30: ['IsPlayerMovingACertainDistance', ()],
        31: ['IsTalkingToSomeoneElse', ()],
        32: ['HasDisableTalkPeriodElapsed', ()],
        33: ['HasPlayerBeenAttacked', ()],
        34: ['GetPlayerYDistance', ()],
        35: ['GetPlayerChrType', ()],
        36: ['CanIGoToNextTalkBlock', ()],
        37: ['CompareBonfireState', ()],
        38: ['CompareBonfireLevel', ()],
        39: ['CompareParentBonfire', ()],
        40: ['BonfireRegistration0', ()],
        41: ['BonfireRegistration1', ()],
        42: ['BonfireRegistration2', ()],
        43: ['BonfireRegistration3', ()],
        44: ['BonfireRegistration4', ()],
        45: ['ComparePlayerStatus', ()],
        46: ['RelativeAngleBetweenTwoPlayers_SpecifyAxis', ()],
        47: ['ComparePlayerInventoryNumber', ()],
        48: ['IsPlayerCurrentWeaponDamaged', ()],
        49: ['ComparePlayerAcquittalPrice', ()],
        50: ['CompareRNGValue', ()],
        51: ['WasWarpMenuDestinationSelected', ()],
        52: ['IsMultiplayerInProgress', ()],
        53: ['IsTalkExclusiveMenuOpen', ()],
        54: ['IsRankingMenuOpen', ()],
        55: ['GetPlayerRemainingHP', ()],
        56: ['CheckActionButtonArea', ()],
        57: ['CheckSpecificPersonTalkHasEnded', ()],
        58: ['CheckSpecificPersonGenericDialogIsOpen', ()],
        59: ['CheckSpecificPersonMenuIsOpen', ()],
        60: ['DoesSelfHaveSpEffect', ()],
        61: ['DoesPlayerHaveSpEffect', ()],
        62: ['GetValueFromNumberSelectDialog', ()],
        100: ['GetWorkValue', ()],
        101: ['GetEventFlagValue', ()],
        102: ['GetCurrentStateElapsedFrames', ()],
        103: ['GetCurrentStateElapsedTime', ()],
        104: ['GetPlayerStatus', ()],
        105: ['GetLevelUpSoulCost', ()],
        106: ['GetWhetherChrTurnAnimHasEnded', ()],
        107: ['GetWhetherChrEventAnimHasEnded', ()],
        108: ['GetItemHeldNumLimit', ()],
    },
}

TEST_FUNCTIONS_ID_BY_TYPE_NAME = {}
for esd_type, commands in TEST_FUNCTIONS.items():
    for f_id, command in commands.items():
        TEST_FUNCTIONS_ID_BY_TYPE_NAME[esd_type, command[0]] = f_id


ATTACK_REQUEST_TYPE = {
    0: 'R1',
    1: 'L1',
    2: 'Catalyst / Talisman / Pyromancy Flame R1',
    3: 'Catalyst / Talisman / Pyromancy Flame L1',
    10: 'Backstep',
    14: 'Use Goods',
    15: 'Roll Forward',
    16: 'Roll Backward',
    17: 'Roll Left',
    18: 'Roll Right',
    22: 'AttackArm_Gesture0 (Beckon)',
    23: 'AttackArm_Gesture1 (Point Forward)',
    24: 'AttackArm_Gesture2 (Hurrah!)',
    25: 'AttackArm_Gesture3 (Bow)',
    26: 'AttackArm_Gesture4 (Joy)',
    27: 'AttackArm_Gesture5 (Shrug)',
    28: 'AttackArm_Gesture6 (Wave)',
    29: 'AttackArm_Gesture7 (Praise the Sun)',
    30: 'AttackArm_Gesture8 (Point Up)',
    31: 'AttackArm_Gesture9 (Point Down)',
    32: 'AttackArm_Gesture10 (Look Skyward)',
    33: 'AttackArm_Gesture11 (Well! What is it!)',
    34: 'AttackArm_Gesture12 (Prostration)',
    35: 'AttackArm_Gesture13 (Proper Bow)',
    36: 'AttackArm_Gesture14 (Prayer)',
    37: 'AttackArm_Gesture15 (Unused)',  # Has Prayer animation as placeholder
    38: 'AttackArm_Gesture16 (Unused)',  # Has carving toss animation as placeholder
    39: 'AttackArm_Gesture17 (Unused)',  # Has lever pull animation as placeholder
    40: 'AttackArm_Gesture18 (Unused)',  # Has turn crank animation as placeholder
    41: 'AttackArm_Gesture19 (Unused)',  # Has turn rotunda animation as placeholder
    42: 'Jump',
    52: 'Left Hand Crossbow Ammo Swap',
}

ANIM_CATEGORY = {
    0: 'Based on Left Hand Motion Category',
    1: 'Based on Right Hand Motion Category',
    2: 'Based on current Move Param',
    3: 'Absolute Animation ID',
}


ANIM_LAYER_INDEX = {
    0: 'Wait',
    1: 'SpWait',
    2: 'WalkLR',
    3: 'WalkFB',
    4: 'Guard',
    5: 'Attack',
    6: 'SpecialAttack',
    7: 'Action',
    8: 'Damage S',
    9: 'Damage L',
    10: 'Event',
    11: 'ExtraAnim',
    12: 'TaeExtraAnim',
}
