from soulstruct.game_types import *

__all__ = [
    # Names processed directly by EVS parser
    "NeverRestart",
    "RestartOnRest",
    "UnknownRestart",
    "EVENTS",
    "Condition",
    "HeldCondition",
    "END",
    "RESTART",
    "Await",
    # Shared tests
    "THIS_FLAG",
    "THIS_SLOT_FLAG",
    "ONLINE",
    "OFFLINE",
    "DLC_OWNED",
    "SKULL_LANTERN_ACTIVE",
    "WHITE_WORLD_TENDENCY",
    "BLACK_WORLD_TENDENCY",
    "NEW_GAME_CYCLE",
    "PLAYER_LEVEL",
    "FlagEnabled",
    "FlagDisabled",
    "SecondsElapsed",
    "FramesElapsed",
    "CharacterInsideRegion",
    "CharacterOutsideRegion",
    "PlayerInsideRegion",
    "PlayerOutsideRegion",
    "AllPlayersInsideRegion",
    "AllPlayersOutsideRegion",
    "InsideMap",
    "OutsideMap",
    "EntityWithinDistance",
    "EntityBeyondDistance",
    "PlayerWithinDistance",
    "PlayerBeyondDistance",
    "HasItem",
    "HasWeapon",
    "HasArmor",
    "HasAccessory",
    "HasGood",
    "ActionButton",
    "MultiplayerEvent",
    "TrueFlagCount",
    "EventValue",
    "EventFlagValue",
    "AnyItemDroppedInRegion",
    "ItemDropped",
    "OwnsItem",
    "OwnsWeapon",
    "OwnsArmor",
    "OwnsAccessory",
    "OwnsGood",
    "Alive",
    "Dead",
    "Attacked",
    "HealthRatio",
    "HealthValue",
    "PartHealthValue",
    "IsCharacterType",
    "IsHollow",
    "IsHuman",
    "IsInvader",
    "IsBlackPhantom",
    "IsWhitePhantom",
    "HasSpecialEffect",
    "BackreadEnabled",
    "BackreadDisabled",
    "CharacterHasTAEEvent",
    "CharacterTargeting",
    "HasAIStatus",
    "HasNormalAIStatus",
    "HasRecognitionAIStatus",
    "HasAlertAIStatus",
    "HasBattleAIStatus",
    "PlayerIsClass",
    "PlayerInCovenant",
    "ObjectDamaged",
    "ObjectDestroyed",
    "ObjectActivated",
    "PlayerStandingOnCollision",
    "PlayerMovingOnCollision",
    "PlayerRunningOnCollision",
    # Dark Souls 3 tests
    "HOST",
    "CLIENT",
    "IN_OWN_WORLD",
    "ActionButtonParamActivated",
    "AttackedWithDamageType",
    "CharacterDrawGroupActive",
    "CharacterDrawGroupInactive",
]

from soulstruct.base.events.emevd.tests import *
from .enums import *

# Boolean constants.
HOST = ...
CLIENT = ...
IN_OWN_WORLD = ...

def ActionButtonParamActivated(action_button_id: int, entity: CoordEntityTyping): ...
def AttackedWithDamageType(attacked_entity: CharacterTyping, attacker: CharacterTyping, damage_type: DamageType): ...
def CharacterDrawGroupActive(character: CharacterTyping): ...
def CharacterDrawGroupInactive(character: CharacterTyping): ...
