from typing import Union, Callable, Optional
import soulstruct.game_types as gt
from soulstruct.enums.shared import *


# Restart decorators.
def NeverRestart(func: Callable): ...
def RestartOnRest(func: Callable): ...
def UnknownRestart(func: Callable): ...


# Dummy enum for accessing event flags defined by events.
class EVENTS(gt.Flag): ...
# Dummy class for creating conditions.
class Condition(object):
    def __init__(self, condition: bool, hold: bool = False): ...


# Terminators.
END = ...
RESTART = ...


# The Await function. Equivalent to using the 'await' built-in Python keyword.
def Await(condition): ...


# Boolean constants.
THIS_FLAG = ...
THIS_SLOT_FLAG = ...
ONLINE = ...
OFFLINE = ...
DLC_OWNED = ...
SKULL_LANTERN_ACTIVE = ...

# Compare these constants to numeric values.
WHITE_WORLD_TENDENCY = ...
BLACK_WORLD_TENDENCY = ...
NEW_GAME_CYCLE = ...
SOUL_LEVEL = ...

def FlagEnabled(flag: gt.FlagInt): ...
def FlagDisabled(flag: gt.FlagInt): ...

def SecondsElapsed(elapsed_seconds): ...
def FramesElapsed(elapsed_frames): ...

def EntityInsideRegion(entity: gt.CoordEntityInt, region: gt.RegionInt): ...
def EntityOutsideRegion(entity: gt.CoordEntityInt, region: gt.RegionInt): ...
def PlayerInsideRegion(region: gt.RegionInt): ...
def PlayerOutsideRegion(region: gt.RegionInt): ...
def AllPlayersInsideRegion(region: gt.RegionInt): ...
def AllPlayersOutsideRegion(region: gt.RegionInt): ...

def InsideMap(game_map: gt.MapOrSequence): ...
def OutsideMap(game_map: gt.MapOrSequence): ...

def EntityWithinDistance(first_entity: gt.CoordEntityInt, second_entity: gt.CoordEntityInt, max_distance): ...
def EntityBeyondDistance(first_entity: gt.CoordEntityInt, second_entity: gt.CoordEntityInt, min_distance): ...
def PlayerWithinDistance(entity: gt.CoordEntityInt, max_distance): ...
def PlayerBeyondDistance(entity: gt.CoordEntityInt, min_distance): ...

# These do NOT include the Bottomless Box.
def HasItem(item: gt.ItemInt): ...  # Can be used with any subclass of Item.
def HasWeapon(weapon: gt.WeaponInt): ...
def HasArmor(armor: gt.ArmorInt): ...
def HasRing(ring: gt.RingInt): ...
def HasGood(good: gt.GoodInt): ...

# These include the Bottomless Box. (Not sure if that include general storage in other games.)
def OwnsItem(item: gt.ItemInt): ...  # Can be used with any subclass of Item.
def OwnsWeapon(weapon: gt.WeaponInt): ...
def OwnsArmor(armor: gt.ArmorInt): ...
def OwnsRing(ring: gt.RingInt): ...
def OwnsGood(good: gt.GoodInt): ...

# This test creates a dialog prompt, and returns True when the prompt is activated (with A).
# Should only be used with Await().
def DialogPromptActivated(prompt_text: gt.EventTextInt, anchor_entity: gt.CoordEntityInt, facing_angle: float=None,
                          max_distance: float = None, model_point: int=None, human_or_hollow_only=True, button=0,
                          anchor_type=None, boss_version=False, line_intersects: Optional[gt.CoordEntityInt] = None): ...

def MultiplayerEvent(multiplayer_event): ...

def EventFlagValue(left_start_flag, left_bit_count, right_start_flag, right_bit_count): ...  # Compare two flags.

def AnyItemDroppedInRegion(region: gt.RegionInt): ...
def ItemDropped(item: gt.Item): ...

def IsAlive(character: gt.CharacterInt): ...
def IsDead(character: gt.CharacterInt): ...

def IsAttacked(attacked_entity: Union[gt.Object, gt.CharacterInt], attacking_character: gt.CharacterInt): ...

# The values returned by these should be compared with a number literal.
def TrueFlagCount(flag_range) -> int: ...
def EventValue(start_flag, bit_count) -> int: ...  # Use this to compare an event value to an arbitrary integer.
def HealthRatio(character: gt.CharacterInt) -> float: ...
def HealthValue(character: gt.CharacterInt) -> int: ...
def PartHealthValue(character: gt.CharacterInt, part_type) -> int: ...

# Character tests.
def IsCharacterType(character: gt.CharacterInt, character_type: CharacterType): ...
def IsHollow(character: gt.CharacterInt): ...
def IsHuman(character: gt.CharacterInt): ...
def IsInvader(character: gt.CharacterInt): ...
def IsBlackPhantom(character: gt.CharacterInt): ...
def IsWhitePhantom(character: gt.CharacterInt): ...

def PlayerIsClass(class_type: ClassType): ...
def PlayerInCovenant(covenant_type: Covenant): ...

def IsTargeting(targeting_chr: gt.CharacterInt, targeted_chr: gt.CharacterInt): ...
def HasAiStatus(character: gt.CharacterInt, ai_status): ...
def AiStatusIsNormal(character: gt.CharacterInt): ...
def AiStatusIsRecognition(character: gt.CharacterInt): ...
def AiStatusIsAlert(character: gt.CharacterInt): ...
def AiStatusIsBattle(character: gt.CharacterInt): ...

def HasTaeEvent(character: gt.CharacterInt, tae_event_id): ...
def HasSpecialEffect(character: gt.CharacterInt, special_effect): ...

def BackreadEnabled(character: gt.CharacterInt): ...
def BackreadDisabled(character: gt.CharacterInt): ...

# Objects
def IsDestroyed(obj: gt.ObjectInt): ...
def IsActivated(obj: gt.ObjectInt): ...

# Hitboxes
def PlayerStandingOnHitbox(hitbox: gt.HitboxInt): ...
def PlayerMovingOnHitbox(hitbox: gt.HitboxInt): ...
def PlayerRunningOnHitbox(hitbox: gt.HitboxInt): ...
