from .core import EMEVD, convert_events
import soulstruct.constants.darksouls1.maps as constants
from soulstruct.constants.darksouls1.maps import *
from . import instructions
from .instructions import *
from . import tests
from .tests import *
import soulstruct.enums.darksouls1 as enums
from soulstruct.enums.darksouls1 import *
from . import decompiler
name = 'darksouls1'

__all__ = [
    # EMEVD class
    "EMEVD",

    # Sub-packages / package attributes (contents of constants, instructions, and tests are also in this namespace)
    "constants", "instructions", "tests", "enums", "name", "decompiler",

    # Batch file conversion utility
    "convert_events",

    # Dark Souls 1 map constants
    "COMMON", "DEPTHS", "UNDEAD_BURG", "FIRELINK_SHRINE", "PAINTED_WORLD", "DARKROOT_GARDEN", "OOLACILE", "CATACOMBS",
    "TOMB_OF_THE_GIANTS", "ASH_LAKE", "BLIGHTTOWN", "LOST_IZALITH", "SENS_FORTRESS", "ANOR_LONDO", "NEW_LONDO_RUINS",
    "DUKES_ARCHIVES", "KILN_OF_THE_FIRST_FLAME", "UNDEAD_ASYLUM",

    # Shared instructions
    "RunEvent",
    "Wait", "WaitFrames", "WaitRandomSeconds", "WaitRandomFrames", "WaitForNetworkApproval",
    "SetCharacterState", "EnableCharacter", "DisableCharacter",
    "SetAIState", "EnableAI", "DisableAI", "SetTeamType",
    "Kill",
    "EzstateAIRequest",
    "CancelSpecialEffect",
    "ResetStandbyAnimationSettings", "SetStandbyAnimationSettings",
    "SetGravityState", "EnableGravity", "DisableGravity",
    "SetCharacterEventTarget",
    "SetImmortalityState", "EnableImmortality", "DisableImmortality",
    "SetNest",
    "SetInvincibilityState", "EnableInvincibility", "DisableInvincibility",
    "ClearTargetList", "AICommand", "SetEventPoint", "SetAIParamID", "ReplanAI",
    "CreateNPCPart", "SetNPCPartHealth", "SetNPCPartEffects", "SetNPCPartBulletDamageScaling",
    "SetDisplayMask", "SetCollisionMask",
    "SetNetworkUpdateAuthority", "SetBackreadState",
    "EnableBackread", "DisableBackread",
    "SetHealthBarState", "EnableHealthBar", "DisableHealthBar",
    "SetCharacterCollisionState", "EnableCharacterCollision", "DisableCharacterCollision",
    "AIEvent",
    "ReferDamageToEntity",
    "SetNetworkUpdateRate",
    "SetBackreadStateAlternate",
    "DropMandatoryTreasure",
    "SetTeamTypeAndExitStandbyAnimation",
    "HumanityRegistration",
    "ResetAnimation",
    "ActivateMultiplayerBuffs",
    "SetObjectState", "EnableObject", "DisableObject",
    "DestroyObject", "RestoreObject",
    "SetTreasureState", "EnableTreasure", "DisableTreasure",
    "ActivateObject", "SetObjectActivation", "SetObjectActivationWithIdx",
    "EnableObjectActivation", "DisableObjectActivation",
    "PostDestruction",
    "CreateHazard",
    "RegisterStatue",
    "RemoveObjectFlag",
    "SetObjectInvulnerability", "EnableObjectInvulnerability", "DisableObjectInvulnerability",
    "EnableTreasureCollection",
    "SetFlagState", "EnableFlag", "DisableFlag", "ToggleFlag",
    "SetRandomFlagInRange", "EnableRandomFlagInRange", "DisableRandomFlagInRange", "ToggleRandomFlagInRange",
    "SetFlagRangeState", "EnableFlagRange", "DisableFlagRange", "ChangeFlagRange",
    "IncrementEventValue", "ClearEventValue",
    "EnableThisFlag", "DisableThisFlag",
    "SetEventState", "StopEvent", "RestartEvent",
    "SetCollisionState", "EnableCollision", "DisableCollision",
    "SetCollisionBackreadMaskState", "EnableCollisionBackreadMask", "DisableCollisionBackreadMask",
    "AwardItemLot", "AwardItemLotToHostOnly",
    "RemoveItemFromPlayer", "RemoveWeaponFromPlayer", "RemoveArmorFromPlayer", "RemoveRingFromPlayer",
    "RemoveGoodFromPlayer",
    "SnugglyItemDrop", "SetNextSnugglyTrade",
    "RequestAnimation", "ForceAnimation",
    "SetAnimationsState", "EnableAnimations", "DisableAnimations", "EndOfAnimation",
    "CreateFX", "DeleteFX", "CreateTemporaryFX", "CreateObjectFX", "DeleteObjectFX",
    "SetBackgroundMusic",
    "PlaySoundEffect",
    "SetSoundEventState", "EnableSoundEvent", "DisableSoundEvent",
    "RegisterLadder", "RegisterBonfire",
    "SetMapPieceState", "DisableMapPiece", "EnableMapPiece",
    "PlaceSummonSign",
    "SetDeveloperMessageState", "EnableSoapstoneMessage", "DisableSoapstoneMessage",
    "DisplayDialog", "DisplayBanner", "DisplayStatus", "DisplayBattlefieldMessage",
    "PlayCutscene", "PlayCutsceneAndMovePlayer", "PlayCutsceneToPlayer", "PlayCutsceneAndMoveSpecificPlayer",
    "PlayCutsceneAndRotatePlayer",
    "SetNavmeshType", "EnableNavmeshType", "DisableNavmeshType", "ToggleNavmeshType",
    "SetNetworkSync", "EnableNetworkSync", "DisableNetworkSync",
    "ClearMainCondition",
    "IssuePrefetchRequest",
    "SaveRequest",
    "TriggerMultiplayerEvent",
    "SetVagrantSpawning", "EnableVagrantSpawning", "DisableVagrantSpawning",
    "IncrementPvPSin",
    "NotifyBossBattleStart",
    "SetSpawnerState", "EnableSpawner", "DisableSpawner",
    "ShootProjectile",
    "CreateProjectileOwner",
    "WarpToMap", "MoveRemains", "Move", "MoveToEntity", "MoveAndSetDrawParent", "ShortMove",
    "MoveAndCopyDrawParent", "MoveObjectToCharacter",
    "SetRespawnPoint",
    "KillBoss",
    "IncrementNewGameCycle",
    "AwardAchievement",
    "BetrayCurrentCovenant",
    "EqualRecovery",
    "ChangeCamera", "SetCameraVibration", "SetLockedCameraSlot",
    "HellkiteBreathControl",
    "SetMapDrawParamSlot",

    # Line-for-line control flow instructions (high-level Python blocks are recommended instead)
    "SkipLines", "Terminate", "End", "Restart",
    "IfValueComparison", "AwaitConditionState", "AwaitConditionTrue", "AwaitConditionFalse",
    "SkipLinesIfConditionState", "SkipLinesIfConditionTrue", "SkipLinesIfConditionFalse",
    "SkipLinesIfFinishedConditionState", "SkipLinesIfFinishedConditionTrue", "SkipLinesIfFinishedConditionFalse",
    "TerminateIfConditionState", "EndIfConditionTrue", "EndIfConditionFalse", "RestartIfConditionTrue",
    "RestartIfConditionFalse", "TerminateIfFinishedConditionState", "EndIfFinishedConditionTrue",
    "EndIfFinishedConditionFalse", "RestartIfFinishedConditionTrue", "RestartIfFinishedConditionFalse",
    "IfConditionState", "IfConditionTrue", "IfConditionFalse", "IfTimeElapsed", "IfFramesElapsed",
    "IfRandomTimeElapsed", "IfRandomFramesElapsed", "SkipLinesIfMapPresenceState", "SkipLinesIfInsideMap",
    "SkipLinesIfOutsideMap", "TerminateIfMapPresenceState", "EndIfInsideMap", "EndIfOutsideMap", "RestartIfInsideMap",
    "RestartIfOutsideMap", "IfMapPresenceState", "IfInsideMap", "IfOutsideMap", "IfMultiplayerEvent", "AwaitFlagState",
    "AwaitThisEventOn", "AwaitThisEventOff", "AwaitThisEventSlotOn", "AwaitThisEventSlotOff", "AwaitFlagOn",
    "AwaitFlagOff", "AwaitFlagChange", "SkipLinesIfFlagState", "SkipLinesIfThisEventOn", "SkipLinesIfThisEventOff",
    "SkipLinesIfThisEventSlotOn", "SkipLinesIfThisEventSlotOff", "SkipLinesIfFlagOn", "SkipLinesIfFlagOff",
    "TerminateIfFlagState", "EndIfThisEventOn", "EndIfThisEventOff", "EndIfThisEventSlotOn", "EndIfThisEventSlotOff",
    "EndIfFlagOn", "EndIfFlagOff", "RestartIfThisEventOn", "RestartIfThisEventOff", "RestartIfThisEventSlotOn",
    "RestartIfThisEventSlotOff", "RestartIfFlagOn", "RestartIfFlagOff", "IfFlagState", "IfThisEventOn",
    "IfThisEventOff", "IfThisEventSlotOn", "IfThisEventSlotOff", "IfFlagOn", "IfFlagOff", "IfFlagChange",
    "SkipLinesIfFlagRangeState", "SkipLinesIfFlagRangeAllOn", "SkipLinesIfFlagRangeAllOff", "SkipLinesIfFlagRangeAnyOn",
    "SkipLinesIfFlagRangeAnyOff", "TerminateIfFlagRangeState", "EndIfFlagRangeAllOn", "EndIfFlagRangeAllOff",
    "EndIfFlagRangeAnyOn", "EndIfFlagRangeAnyOff", "RestartIfFlagRangeAllOn", "RestartIfFlagRangeAllOff",
    "RestartIfFlagRangeAnyOn", "RestartIfFlagRangeAnyOff", "IfFlagRangeState", "IfFlagRangeAllOn", "IfFlagRangeAllOff",
    "IfFlagRangeAnyOn", "IfFlagRangeAnyOff", "IfTrueFlagCountComparison", "IfTrueFlagCountEqual",
    "IfTrueFlagCountNotEqual", "IfTrueFlagCountGreaterThan", "IfTrueFlagCountLessThan",
    "IfTrueFlagCountGreaterThanOrEqual", "IfTrueFlagCountLessThanOrEqual", "IfEventValueComparison",
    "IfEventValueEqual", "IfEventValueNotEqual", "IfEventValueGreaterThan", "IfEventValueLessThan",
    "IfEventValueGreaterThanOrEqual", "IfEventValueLessThanOrEqual", "IfEventsComparison",
    # "IfCharacterRegionState" and shortcut versions overridden in Dark Souls 1.
    "IfAllPlayersRegionState", "IfAllPlayersInsideRegion", "IfAllPlayersOutsideRegion", "IfEntityDistanceState",
    "IfEntityWithinDistance", "IfEntityBeyondDistance", "IfPlayerWithinDistance", "IfPlayerBeyondDistance",
    "IfPlayerItemStateNoBox", "IfPlayerItemStateBox", "IfPlayerItemState", "IfPlayerHasItem", "IfPlayerHasWeapon",
    "IfPlayerHasArmor", "IfPlayerHasRing", "IfPlayerHasGood", "IfPlayerDoesNotHaveItem", "IfPlayerDoesNotHaveWeapon",
    "IfPlayerDoesNotHaveArmor", "IfPlayerDoesNotHaveRing", "IfPlayerDoesNotHaveGood", "IfAnyItemDroppedInRegion",
    "IfItemDropped", "AwaitObjectDestructionState", "AwaitObjectDestroyed", "AwaitObjectNotDestroyed",
    "SkipLinesIfObjectDestructionState", "SkipLinesIfObjectDestroyed", "SkipLinesIfObjectNotDestroyed",
    "TerminateIfObjectDestructionState", "EndIfObjectDestroyed", "EndIfObjectNotDestroyed", "RestartIfObjectDestroyed",
    "RestartIfObjectNotDestroyed", "IfObjectDestructionState", "IfObjectDestroyed", "IfObjectNotDestroyed",
    "IfObjectDamagedBy", "IfObjectActivated", "IfObjectHealthValueComparison", "IfMovingOnCollision",
    "IfRunningOnCollision",
    "IfStandingOnCollision", "SkipLinesIfComparison", "SkipLinesIfEqual", "SkipLinesIfNotEqual",
    "SkipLinesIfGreaterThan",
    "SkipLinesIfLessThan", "SkipLinesIfGreaterThanOrEqual", "SkipLinesIfLessThanOrEqual", "TerminateIfComparison",
    "EndIfEqual", "EndIfNotEqual", "EndIfGreaterThan", "EndIfLessThan", "EndIfGreaterThanOrEqual",
    "EndIfLessThanOrEqual", "RestartIfEqual", "RestartIfNotEqual", "RestartIfGreaterThan", "RestartIfLessThan",
    "RestartIfGreaterThanOrEqual", "RestartIfLessThanOrEqual", "IfDialogPromptActivated", "IfWorldTendencyComparison",
    "IfWhiteWorldTendencyComparison", "IfBlackWorldTendencyComparison", "IfWhiteWorldTendencyGreaterThanOrEqual",
    "IfBlackWorldTendencyGreaterThanOrEqual", "IfNewGameCycleComparison", "IfNewGameCycleEqual",
    "IfNewGameCycleGreaterThanOrEqual", "IfDLCState", "IfDLCOwned", "IfDLCNotOwned", "IfOnlineState", "IfOnline",
    "IfOffline", "IfCharacterDeathState", "IfCharacterDead", "IfCharacterAlive", "IfAttacked", "IfHealthComparison",
    "IfHealthEqual", "IfHealthNotEqual", "IfHealthGreaterThan", "IfHealthLessThan", "IfHealthGreaterThanOrEqual",
    "IfHealthLessThanOrEqual", "IfCharacterType", "IfCharacterHollow", "IfCharacterHuman", "IfCharacterTargetingState",
    "IfCharacterTargeting", "IfCharacterNotTargeting", "IfCharacterSpecialEffectState", "IfCharacterHasSpecialEffect",
    "IfCharacterDoesNotHaveSpecialEffect", "IfCharacterPartHealthComparison", "IfCharacterPartHealthLessThanOrEqual",
    "IfCharacterBackreadState", "IfCharacterBackreadEnabled", "IfCharacterBackreadDisabled", "IfTAEEventState",
    "IfHasTAEEvent", "IfDoesNotHaveTAEEvent", "IfHasAIStatus", "IfSkullLanternState", "IfSkullLanternActive",
    "IfSkullLanternInactive", "IfPlayerClass", "IfPlayerCovenant", "IfPlayerSoulLevelComparison",
    "IfPlayerSoulLevelGreaterThanOrEqual", "IfPlayerSoulLevelLessThanOrEqual", "IfHealthValueComparison",
    "IfHealthValueEqual", "IfHealthValueNotEqual", "IfHealthValueGreaterThan", "IfHealthValueLessThan",
    "IfHealthValueGreaterThanOrEqual", "IfHealthValueLessThanOrEqual", "ArenaRankingRequest1v1",
    "ArenaRankingRequest2v2", "ArenaRankingRequestFFA", "ArenaExitRequest", "ArenaSetNametag1", "ArenaSetNametag2",
    "ArenaSetNametag3", "ArenaSetNametag4", "DisplayArenaDissolutionMessage", "ArenaSetNametag5", "ArenaSetNametag6",

    # Dark Souls 1 specific instructions
    "IfCharacterRegionState", "IfCharacterInsideRegion", "IfCharacterOutsideRegion",
    "IfPlayerInsideRegion", "IfPlayerOutsideRegion",
    "SkipLinesIfMultiplayerState", "SkipLinesIfHost", "SkipLinesIfClient",
    "SkipLinesIfMultiplayer", "SkipLinesIfSingleplayer",
    "TerminateIfMultiplayerState", "EndIfHost", "EndIfClient", "EndIfMultiplayer", "EndIfSingleplayer",
    "RestartIfHost", "RestartIfClient", "RestartIfMultiplayer", "RestartIfSingleplayer",
    "IfMultiplayerState", "IfHost", "IfClient", "IfMultiplayer", "IfSingleplayer",
    "SetBossHealthBarState", "EnableBossHealthBar", "DisableBossHealthBar",
    "ActivateKillplaneForModel",
    "AddSpecialEffect",
    "RotateToFaceEntity",

    # REMASTERED ONLY (mostly Arena events - no warning given if you try to use these in PTDE!)
    "SkipLinesIfUnknownPlayerType4", "SkipLinesIfUnknownPlayerType5",
    "RestartIfUnknownPlayerType4", "RestartIfUnknownPlayerType5",
    "EndIfUnknownPlayerType4", "EndIfUnknownPlayerType5",
    "IfUnknownPlayerType4", "IfUnknownPlayerType5",

    "RegisterHealingFountain",
    "Unknown_3_23",
    "IfMultiplayerCount",
    "Unknown_4_15",
    "Unknown_4_16",
    "IfArenaMatchmaking",
    "Unknown_2000_06",
    "PlayCutsceneAndRandomlyWarpPlayer_WithUnknownEffect1",
    "PlayCutsceneAndRandomlyWarpPlayer_WithUnknownEffect2",
    "CopyEventValue",
    "Unknown_2003_43",
    "ForceAnimation_WithUnknownEffect1",
    "ForceAnimation_WithUnknownEffect2",
    "Unknown_2003_47",
    "Unknown_2003_48",
    "EraseNPCSummonSign",
    "FadeOutCharacter",
    "FadeInCharacter",
    "Unknown_2004_50",
    "Unknown_2004_51",
    "Unknown_2004_52",
    "Unknown_2007_13",
    "Unknown_2008_4",

    # Names processed directly by EVS parser
    "NeverRestart", "RestartOnRest", "UnknownRestart", "EVENTS", "Condition", "END", "RESTART", "Await",

    # Shared tests
    "THIS_FLAG", "THIS_SLOT_FLAG",
    "ONLINE", "OFFLINE", "DLC_OWNED", "SKULL_LANTERN_ACTIVE",
    "WHITE_WORLD_TENDENCY", "BLACK_WORLD_TENDENCY", "NEW_GAME_CYCLE", "SOUL_LEVEL",
    "FlagEnabled", "FlagDisabled",
    "SecondsElapsed", "FramesElapsed",
    "CharacterInsideRegion", "CharacterOutsideRegion",
    "PlayerInsideRegion", "PlayerOutsideRegion", "AllPlayersInsideRegion", "AllPlayersOutsideRegion",
    "InsideMap", "OutsideMap",
    "EntityWithinDistance", "EntityBeyondDistance", "PlayerWithinDistance", "PlayerBeyondDistance",
    "HasItem", "HasWeapon", "HasArmor", "HasRing", "HasGood",
    "DialogPromptActivated",
    "MultiplayerEvent", "TrueFlagCount", "EventValue", "EventFlagValue",
    "AnyItemDroppedInRegion", "ItemDropped",
    "OwnsItem", "OwnsWeapon", "OwnsArmor", "OwnsRing", "OwnsGood",
    "IsAlive", "IsDead", "IsAttacked",
    "HealthRatio", "HealthValue", "PartHealthValue",
    "IsCharacterType", "IsHollow", "IsHuman", "IsInvader", "IsBlackPhantom", "IsWhitePhantom",
    "HasSpecialEffect",
    "BackreadEnabled", "BackreadDisabled",
    "HasTaeEvent",
    "IsTargeting", "HasAiStatus", "AiStatusIsNormal", "AiStatusIsRecognition", "AiStatusIsAlert", "AiStatusIsBattle",
    "PlayerIsClass", "PlayerInCovenant",
    "IsDamaged", "IsDestroyed", "IsActivated",
    "PlayerStandingOnCollision", "PlayerMovingOnCollision", "PlayerRunningOnCollision",

    # Dark Souls 1 specific tests
    "HOST", "CLIENT", "SINGLEPLAYER", "MULTIPLAYER",

    # Basic enums
    "RestartType",
    "uint", "short", "ushort", "char", "uchar",
    "PLAYER", "CLIENT_PLAYER_1", "CLIENT_PLAYER_2", "CLIENT_PLAYER_3", "CLIENT_PLAYER_4", "CLIENT_PLAYER_5",

    # Enums identical in all games
    "AIStatusType", "BitOperation", "ButtonType", "CharacterType", "CharacterUpdateRate", "ClassType",
    "ComparisonType", "CutsceneType", "DamageTargetType", "EventEndType", "FlagType", "InterpolationState",
    "ItemType", "RangeState", "CoordEntityType", "NavmeshType", "NumberButtons", "OnOffChange",
    "RestartType", "SoundType", "StatueType", "SummonSignType", "TriggerAttribute", "WorldTendencyType",
    "UpdateAuthority",

    # Enums for Dark Souls 1 (both PTD and DSR) only
    "CalculationType", "ConditionGroup", "Covenant", "TeamType", "BannerType", "MultiplayerState", "NPCPartType",
]
