"""TODO: Should be obsolete now with EMEDF."""

__all__ = ["INSTRUCTION_ARG_TYPES"]


INSTRUCTION_ARG_TYPES = {
    0: {0: "bBb", 1: "bbii", 2: "bbII"},
    1: {
        0: "bf",
        1: "bi",
        2: "bff",
        3: "bii",
        5: "bBBBBBB",  # TODO: New.
    },
    3: {
        0: "bBBI",
        1: "bBBII",
        2: "bBIIi",
        3: "bBIIfi",
        4: "bBiB",
        5: "biifhfiBi",
        6: "bb",
        7: "bBi",
        8: "bBBBBB",  # TODO: Changed (+4). IF Player In/Out Map. Probably accepts CC and DD in mAA_BB_CC_DD.
        9: "bI",
        10: "bBiibi",
        11: "bBBB",
        12: "biBBI",
        13: "biifhfiBi",
        14: "bi",
        15: "bii",
        16: "bBiB",
        17: "bBB",
        18: "biifhfiBii",
        19: "biifhfiBii",
        20: "biBBiB",
        21: "bB",
        22: "bB",
        23: "bIiB",
        24: "bii",
        25: "bBii",
        26: "bB",
        28: "bBBBH",
        29: "b",
        30: "bBBBB",  # TODO: +6. IF Player Gender
        31: "bbfi",  # TODO: +4. IF Ongoing Cutscene Finished
        32: "bB",
        33: "bIB",  # TODO: +10. ?
        34: "bbii",  # TODO: +4. IF Player Has Item Equipped
        35: "bB",
        37: "bii",  # TODO: New.
        38: "bB",
        39: "bBbi",
    },
    4: {
        0: "bIBbf",
        1: "bIi",
        2: "bIbfbf",
        3: "bIbbf",
        4: "bIiB",
        5: "bIiBbf",
        6: "bIiib",
        7: "bIBbf",
        8: "bIiBbf",
        9: "bIBbf",
        10: "bB",
        11: "bB",
        12: "bB",
        13: "bBI",
        14: "bIBibf",
        15: "bIBbf",
        26: "bBi",
        27: "bIBbf",
        28: "bIiB",
        31: "bIII",  # TODO: New
        34: "bIhbbf",
    },
    5: {0: "bBibf", 1: "bii", 2: "bi", 3: "bibi", 9: "biBBbf", 10: "biBbf", 11: "biBbf"},
    11: {0: "bi", 1: "bi", 2: "bi"},
    1000: {
        0: "Bb",
        1: "BBb",
        2: "BBb",
        3: "B",
        4: "B",
        5: "Bbii",
        6: "Bbii",
        7: "BBb",
        8: "BBb",
        9: "f",
        10: "BbII",  # TODO: New.
        11: "BbII",  # TODO: New.
        101: "BBb",
        103: "B",
        105: "Bbii",
        107: "BBb",
    },
    1001: {
        0: "f",
        1: "i",
        2: "ff",
        3: "ii",
        4: "BB",
        6: "I",
    },
    1003: {
        0: "BBI",
        1: "BBBI",
        2: "BBBI",
        3: "BBBII",
        4: "BBBII",
        5: "Bb",
        6: "Bb",
        7: "BBBB",
        8: "BBBB",
        9: "BBB",
        10: "BBB",
        12: "BB",
        13: "BB",
        14: "BB",
        101: "BBBI",
        103: "BBBII",
        105: "Bb",
        107: "BBBB",
        109: "BBB",
        200: "BBIIi",
        201: "BBIIi",
        202: "BBIIi",
        211: "BB",
    },
    1004: {
        0: "BIiBbi",  # TODO: New in Sekiro?
        1: "BIiBbi",  # TODO: New in Sekiro?
        2: "BIiBbi",  # TODO: New in Sekiro?

        5: "BII",
    },
    1005: {0: "Bi", 1: "BBibf", 2: "BBibf", 101: "BBibf"},
    1014: {
        0: "",
        1: "",
        2: "",
        3: "",
        4: "",
        5: "",
        6: "",
        7: "",
        8: "",
        9: "",
        10: "",
        11: "",
        12: "",
        13: "",
        14: "",
        15: "",
        16: "",
        17: "",
        18: "",
        19: "",
        20: "",
    },
    2000: {
        0: "iII",
        1: "iI",
        2: "B",
        3: "B",
        4: "I",
        5: "B",
        6: "II",
        7: "I",  # TODO: New.
        8: "I",  # TODO: New.
    },
    2001: {
        4: "BBBbbbiii",  # TODO: New.
        5: "b",  # TODO: New.
    },
    2002: {
        1: "iI",
        2: "iIiBB",
        3: "iIi",
        4: "iIiBBi",
        5: "iIffifi",
        6: "iIiBBiB",
        7: "iIiB",
        8: "iBB",
        9: "iIIiiBBi",
        10: "iIIbbfbbb",  # TODO: +4. Play Cutscene to Player and Change Current Map Ceremony
        11: "iIIIiIBBBB",  # TODO: Changed (Play Ongoing Cutscene and Warp Player). Six extra bytes.
        12: "iIiIIIBBBBfBB",  # TODO: +12. Play Cutscene and Warp Player + UNKNOWN 2002[12]
        13: "iIIIIII",  # TODO: New.
    },
    2003: {
        1: "iiBB",
        2: "iB",
        3: "iB",
        4: "i",
        5: "iiiiiii",
        6: "iB",
        7: "iB",
        8: "iiB",
        9: "i",
        10: "h",
        11: "bihi",
        12: "iI",  # TODO: +4.
        13: "iIB",
        14: "BBBBii",  # TODO: +4. Warp Player. Probably accepts map CC and DD.
        15: "i",
        16: "I",
        17: "IIB",
        18: "iiBBBBf",
        19: "hh",
        20: "i",
        21: "B",
        22: "iiB",
        23: "i",
        24: "iii",
        25: "iiiii",
        26: "iB",
        27: "B",
        28: "i",
        29: "Bb",
        30: "B",
        31: "iII",
        32: "iI",
        33: "i",
        34: "iiii",
        35: "ii",
        36: "i",
        37: "",
        38: "",
        39: "",
        40: "",
        41: "iIiiIb",
        42: "iiII",
        43: "iiII",
        44: "B",
        45: "ihhhB",
        46: "hB",
        47: "hhhB",
        48: "iBfi",
        49: "i",
        50: "i",
        51: "iiiii",
        52: "i",
        54: "i",
        57: "I",
        59: "IBI",
        61: "i",
        62: "iB",
        63: "IIB",
        64: "ii",
        65: "",
        66: "BIB",  # TODO: Changed (Crow Trade) (-8).
        67: "i",
        68: "ifi",  # TODO: New.
        69: "BIB",  # TODO: New.
        70: "B",
        71: "i",
        72: "iiB",
        73: "BB",
        74: "iB",
        75: "BB",
        76: "BIIII",  # TODO: New.
        77: "HHi",
        78: "i",
        79: "B",
        80: "I",  # TODO: Changed (Set Area Envmap).
        81: "I",  # TODO: -16. Set Lighting + UNKNOWN
    },
    2004: {
        1: "IB",
        2: "IB",
        3: "IBii",
        4: "IB",
        5: "IB",
        6: "IiB",
        7: "I",
        8: "Ii",
        9: "Iiiiii",
        10: "IB",
        11: "Ii",
        12: "IB",
        13: "Ii",
        14: "IiiB",
        15: "IB",
        16: "I",
        17: "IiB",
        18: "Iif",
        19: "Ii",
        20: "I",
        21: "Ii",
        22: "IhhiffBB",
        23: "IiiB",
        24: "Iiii",
        25: "Iif",
        26: "IBB",
        27: "IBB",
        28: "Ii",
        29: "IB",
        30: "IB",
        31: "IB",
        32: "IiBii",
        33: "Ii",
        34: "IBb",
        35: "IB",
        36: "Iii",
        37: "I",
        38: "B",
        39: "IB",
        40: "IBiii",
        41: "IBii",
        42: "IBiii",
        43: "IB",
        44: "IB",
        45: "Ii",
        46: "B",
        47: "",
        48: "IBB",
        49: "Ii",
        50: "IiB",
        51: "Iiiiii",
        52: "I",
        53: "I",
        54: "IB",
        55: "If",
        57: "I",
        58: "IB",
        59: "IB",
        60: "B",

        68: "III",  # TODO: New.
        73: "II",  # TODO: New.
        74: "IbIiIbb",  # TODO: New.
        75: "Ibi",  # TODO: New.
        76: "Ii",  # TODO: New.
        77: "ffbf",  # TODO: New.
    },
    2005: {
        1: "ib",
        2: "i",
        3: "iB",
        4: "iB",
        5: "iii",
        6: "iiB",
        7: "ii",
        8: "ib",
        9: "iiiiifff",
        10: "iBBB",
        11: "iih",
        12: "i",
        13: "iB",
        14: "iiiB",
        15: "i",
        16: "",
        17: "iIi",
        19: "i",
    },
    2006: {
        1: "IB",
        2: "I",
        3: "iIii",
        4: "Iii",
        5: "Ii",
        6: "I",  # TODO: New.
    },
    2007: {
        1: "ihhif",
        2: "B",
        3: "iB",
        4: "iB",
        5: "i",
        6: "i",
        7: "i",
        8: "i",
        9: "i",
        10: "ihhifiii",
        11: "i",
        12: "ihB",

        15: "iBB",  # TODO: New.
        16: "ii",  # TODO: New.
    },
    2008: {  # Camera
        1: "ii",
        2: "iiiiff",
        3: "BBH",
        4: "if",  # TODO: New.
    },
    2009: {0: "iii", 1: "iii", 2: "iii", 3: "iiffi", 4: "i", 5: "iiffii", 6: "B", 8: "i", 10: "i", 11: "i"},
    2010: {
        1: "BHiii",
        2: "iii",
        3: "iB",
        4: "iB",
        5: "iB",
        6: "iBf",
        7: "iii",  # TODO: +8. UNKNOWN 2010[07]
    },
    2011: {1: "iB", 2: "iB", 3: "iB", 4: "iB"},
    2012: {
        1: "iB",
        8: "B",
        12: "f",  # TODO
    },
    2013: {1: "s", 2: "IsB", 3: "I", 4: "BsB"},
}
