"""GameParam types that refer to entry IDs in a certain game parameter table."""

__all__ = [
    "BaseParam",
    "BaseGameParam",
    "BaseItemParam",
    "BaseDrawParam",

    "AIParam",
    "ArmorParam",
    "ArmorUpgradeParam",
    "AttackParam",
    "BehaviorParam",
    "BossParam",
    "BulletParam",
    "CameraParam",
    "CharacterParam",
    "DialogueParam",
    "FaceParam",
    "GoodParam",
    "GrowthCurveParam",
    "ItemLotParam",
    "KnockbackParam",
    "MenuColorsParam",
    "MovementParam",
    "ObjActParam",
    "ObjectParam",
    "PlayerParam",
    "AccessoryParam",
    "ShopParam",
    "SpecialEffectParam",
    "SpecialEffectVisualParam",
    "SpellParam",
    "TerrainParam",
    "ThrowParam",
    "UpgradeMaterialParam",
    "WeaponParam",
    "WeaponUpgradeParam",

    "FogParam",
    "AmbientLightParam",
    "ScatteredLightParam",
    "PointLightParam",
    "LensFlareParam",
    "LensFlareSourceParam",
    "DepthOfFieldParam",
    "ToneMappingParam",
    "ToneCorrectionParam",
    "ShadowParam",

    "AITyping",
    "ArmorTyping",
    "ArmorUpgradeTyping",
    "AttackTyping",
    "BehaviorTyping",
    "BulletTyping",
    "CameraTyping",
    "DialogueTyping",
    "FaceTyping",
    "GoodTyping",
    "ItemTyping",
    "ItemLotTyping",
    "KnockbackTyping",
    "AccessoryTyping",
    "SpecialEffectTyping",
    "SpellTyping",
    "TerrainTyping",
    "UpgradeMaterialTyping",
    "WeaponTyping",
    "WeaponUpgradeTyping",
]

from soulstruct.darksouls1ptde.game_types.param_types import *
