from typing import TYPE_CHECKING
from soulstruct.emevd.shared.tests import *
if TYPE_CHECKING:
    from soulstruct.emevd.game_types import *


# Boolean constants.
HOST = ...
CLIENT = ...
SINGLEPLAYER = ...
MULTIPLAYER = ...
